### ISSUE TITLE
is this fix?

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#1]
@cs6413110 ? is this the fix? what happened to the code? to the old ownership? huh??

**Comment by BreadSpam** [comment]
idk check ur notifications

**Comment by cs6413110** [comment]
I think it's fixed now.

**Comment by cs6413110** [comment]
I may need to consider getting a new github account though.

**Comment by LostKing73** [comment]
probably.

**Comment by LostKing73** [comment]
the server is still gone tho

**Comment by cs6413110** [comment]
Need to setup static pages

**Comment by DarkMemeGod411** [comment]
lets go. tysm aaron

**Comment by LostKing73** [comment]
yes, it is

**Comment by LostKing73** [comment]
no. its not. bcuz how could this be a fix, when we are in a regime.
