### ISSUE TITLE
New Item: E.M.P

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#100]
inspired by the actual tool used in tank combat.

the E.M.P causes a 3x3 electric explosion starting on your tank. which does 2 things:

1: does 50 damage with a 1 second 50% slow effect (could be removed if broken)

2: disables all currently active tank abilities (k lemme explain with examples)
ur boosting/warrior boosting? nah get emp'd
ur grippling? nah get emp'd
ur reflecting? nah get emp'd
ur being usb buffed? nah get emp'd
ur have a shield? nah get emp'd (damage does not overflow to hp)
ur invis? nah get emp'd
the only thing it doesn't undo is toolkitting bc that would be absolutley busted.

30 sec cd

don't have to add now, but like of we need more, then this is a gud option

**Comment by LostKing73** [comment]
what if u have an enemy usb on u, could it disable that? does it effect u and ur teammates? if it effects u then wouldn't that be bad?

**Comment by LostKing73** [comment]
u wasted 100 on this btw

**Comment by cs6413110** [comment]
Do we really have the time/space/sanity for new items?

**Comment by BreadSpammer** [comment]
idk lag bye
