### ISSUE TITLE
1st placed turret matches internet color?

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#102]
why? how? whut????
![Screenshot 2024-10-24 8 15 40 AM](https://github.com/user-attachments/assets/c9c254f0-1346-4039-a7d9-ce0bd9f43586)
![Screenshot 2024-10-24 8 15 16 AM](https://github.com/user-attachments/assets/785be64d-c29e-4f21-ac46-bc7e24917b53)

**Comment by LostKing73** [comment]
red turip

**Comment by 3foe** [comment]
its a feature

**Comment by LostKing73** [comment]
cann yall vote iin banners

**Comment by cs6413110** [comment]
Bread fixable by putting:
```javascript
GUI.draw.fillStyle = '#ffffff';
```
in the very front of Client.frame

**Comment by BreadSpammer** [comment]
but like its a feature :D

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/abfcf90c-5d8e-4319-9b98-95bba12bb0a9)

**Comment by LostKing73** [comment]
why isnt he spinning..??

**Comment by CelestialKnight7** [comment]
@BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer  IFXXXXXXXXXXFIXIFIFIXIFIFXIIFIXFIIXFIXFIFIXFIIFXIFIXFIFIXIFIXFIFXIFXIXFIIXFIXFIXFIFXIXFIXIFIFXIXFIFXIFXIIFXIXFIXFIXFIXFIXIFIFXIXFIXFIIXFIXFIXFIXFIFXIIXFIXFIXFIXFIXIFIIFXIXFIXFIFXIXFIFIXFIXFIIX

**Comment by 3foe** [comment]
bruh thats weak
you can do better

**Comment by 3foe** [comment]
@BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer  @BreadSpammer

**Comment by LostKing73** [comment]
dont 3foe

**Comment by LostKing73** [comment]
bruh

**Comment by 3foe** [comment]
:D

**Comment by LostKing73** [comment]
no one finds you funny

**Comment by BreadSpammer** [comment]
help. FINE ill fix

**Comment by BreadSpammer** [comment]
fixed

**Comment by CelestialKnight7** [comment]
ezzzzzz
