### ISSUE TITLE
not smoke bomb. now jonas cosmet issue

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#105]
its bad. and evan's idea of a rework is trash. spam here to fix.

**Comment by CelestialKnight7** [comment]
ur just mad that ur stun idea got downvoted to oblivion and ur desperately trying to remove an item so theres a vacancy so you can go say "oh well now we might as well use my idea since is a functioning item"

**Comment by LostKing73** [comment]
no. my stun idea is literally spam, idc abt it. it just made me notice how bad smoke is, and how bad ur "fix" is

**Comment by LostKing73** [comment]
idc abt stun thing. idc abt most things.

**Comment by cs6413110** [comment]
smoke bomb still cringe tho

**Comment by cs6413110** [comment]
It's as used as bomb.

**Comment by CelestialKnight7** [comment]
my fix will turn it from an aneurysm to an actual cloaking item

**Comment by LostKing73** [comment]
> my fix will turn it from an aneurysm to an actual cloaking item

ur fix is make it stop moving for while it exists, then animate when it goes aaway

**Comment by LostKing73** [comment]
why would that be good

**Comment by BreadSpammer** [comment]
where is evan's fix and ill prove u all wrong by using smoke bomb

**Comment by CelestialKnight7** [comment]
> > my fix will turn it from an aneurysm to an actual cloaking item
> 
> ur fix is make it stop moving for while it exists, then animate when it goes aaway

it would make  it so that its not constantly animated meaning that instead of bleeding your eyes it will hide stuff. its not a buff its a fix

**Comment by LostKing73** [comment]
> smoke bomb still cringe tho

^^^???

**Comment by LostKing73** [comment]
> > > my fix will turn it from an aneurysm to an actual cloaking item
> > 
> > 
> > ur fix is make it stop moving for while it exists, then animate when it goes aaway
> 
> it would make it so that its not constantly animated meaning that instead of bleeding your eyes it will hide stuff. its not a buff its a fix

that's so ugly tho????????

**Comment by LostKing73** [comment]
like, if a gif hurts ur eyes, making it not animate until its done doesn't fix anything

**Comment by CelestialKnight7** [comment]
my dude. my gamer in christ. my fellow american.
it gives you an anurism rn yes?
why?
cuz there are so many and they're all constantly animated
so if you dont animate them and have them be 5 single images that cover an area, it wont give you an anyurism while looking at it

**Comment by LostKing73** [comment]
> my dude. my gamer in christ. my fellow american. it gives you an anurism rn yes? why? cuz there are so many and they're all constantly animated so if you dont animate them and have them be 5 single images that cover an area, it wont give you an anyurism while looking at it

at that point, it would look like a pile of rocks. there comes a point where you must realise that you are trying to solve problems by adding more, but its the base that is bad. smoke bomb does not work as an item. ik ur in it. there's not point if I fire boost, warrior boost, fire f, just RUN, place a turret, and so on. we could have way cooler abilities, but we are locked to _smoke_??

**Comment by CelestialKnight7** [comment]
> > my dude. my gamer in christ. my fellow american. it gives you an anurism rn yes? why? cuz there are so many and they're all constantly animated so if you dont animate them and have them be 5 single images that cover an area, it wont give you an anyurism while looking at it
> 
> at that point, it would look like a pile of rocks.
false
>there comes a point where you must realise that you are trying to solve problems by adding more,
how does this add more problems, all it does is make it so that looking at is doesnt hurt your eyes, if anything this should have been done from the start
>but its the base that is bad. smoke bomb does not work as an item. ik ur in it. there's not point if I fire boost, warrior boost, fire f, just RUN, place a turret, and so on. 
the point of it is that they're harder to hit, or if they were stealth you wouldn't know where they went, they could have used the smoke as a diversion so you think they're in there. the point of smoke isn't to hide while running its to cause chaos in a fight to attempt to gain an advantage. 
>we could have way cooler abilities, but we are locked to _smoke_??
like what?

**Comment by LostKing73** [comment]
1. see attatched image. this doesnt just look like a bloated bolder or smth????
2. The problem is that smoke isn't being replaced. its a bad item that looks bad and doesn't help.
3. Smoke really only buffs stealth at that point, and stelth doesn't need that buff, bcuz they can GO THRU WALLS??? and adding chaos isn't helpful to you, if ur trying to also hit ur shots and then like boom fart cloud, that's not helpful.
4. smoke bad make smth cooler
![image](https://github.com/user-attachments/assets/21506b92-2d03-4aeb-8478-21d52175cae6)

**Comment by CelestialKnight7** [comment]
> 1. see attatched image. this doesnt just look like a bloated bolder or smth????

not really, i mean if you someone says this is a boulder id could believe it but if someone said this is smoke id also believe it

> 2. The problem is that smoke isn't being replaced. its a bad item that looks bad and doesn't help.

so how is that "more" problems?

> 3. Smoke really only buffs stealth at that point, and stelth doesn't need that buff, bcuz they can GO THRU WALLS??? and adding chaos isn't helpful to you, if ur trying to also hit ur shots and then like boom fart cloud, that's not helpful.

use with turret, use with fire, use with radar so you can see but they cant, use radar and tactical so you can see, they can't and then theyre dead, use with warrior cuz u dont need to see to hit it, u can use it offensively too. Or use with airstrike to hide it, use it with block to confuse your opponent.

> 4. smoke bad make smth cooler

what is the smth cooler????

**Comment by LostKing73** [comment]
not the whole image, just as large of a chunk as possible

**Comment by CelestialKnight7** [comment]
what image

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/776e9dfe-6c4d-4cf2-ac4a-533fbde0c735)

**Comment by LostKing73** [comment]
tryna do smth. thats the pixil art ver btw

**Comment by LostKing73** [comment]
wait sry wrong one. its this one and its 1000 by 719
![image](https://github.com/user-attachments/assets/f46286e4-26c1-495a-8d7c-50cd9cf4021b)

**Comment by LostKing73** [comment]
also like idk just make the smoke texture better and then sure whatev

**Comment by LostKing73** [comment]
also on a related note, how big is the limit for cosmetic size?

**Comment by CelestialKnight7** [comment]
no clue, also this is soo cooked

**Comment by CelestialKnight7** [comment]
no way you get that image in a tonk without crunching it to hell and back

**Comment by CelestialKnight7** [comment]
i tried
![pixil-frame-0 - 2024-10-25T081027 449](https://github.com/user-attachments/assets/db91299b-01f7-4c8d-bb43-d67ec8ddc7fc)

**Comment by LostKing73** [comment]
k hld on, thx

**Comment by LostKing73** [comment]
what did u delete?

**Comment by LostKing73** [comment]
k it looks rly good tho

**Comment by CelestialKnight7** [comment]
i jsut halved the size repeatedly until i could fit enough in for it to look good

**Comment by LostKing73** [comment]
but can we only do 40x45? or is there bigger

**Comment by CelestialKnight7** [comment]
you could prob make it bigger as long as it can be simplified down to 40x45 if u want more details

**Comment by LostKing73** [comment]
alr. i cant rly explain what im tryna make other than its my own creation

**Comment by CelestialKnight7** [comment]
idk what the cosmet size is but its standard across all of them, meaningyou probobly cant upright add what i posted cuz its not the right cosmet size

**Comment by LostKing73** [comment]
omg i just realized what oc stood for

**Comment by CelestialKnight7** [comment]
overclock

**Comment by LostKing73** [comment]
> idk what the cosmet size is but its standard across all of them, meaningyou probobly cant upright add what i posted cuz its not the right cosmet size

ye ik, I fixed that, but like I need @cs6413110 to tell me cuz the bigger/ more clear the better

**Comment by LostKing73** [comment]
thx btw

**Comment by CelestialKnight7** [comment]
anyways looks like were done with smoke?

**Comment by CelestialKnight7** [comment]
yipee

**Comment by LostKing73** [comment]
but leave open so we can have @cs6413110 HAAAAAAAAAAAALP me

**Comment by LostKing73** [comment]
i also need someone to add the new inv stuff to my texture pack

**Comment by LostKing73** [comment]
@cs6413110 , what is the max size for cosmets?

**Comment by CelestialKnight7** [comment]
40x 45

**Comment by CelestialKnight7** [comment]
they can be bigger but they have to simplify to that size

**Comment by LostKing73** [comment]
also evan bruh no one said add im not doen

**Comment by LostKing73** [comment]
> they can be bigger but they have to simplify to that size

what does that even mean

**Comment by LostKing73** [comment]
@CelestialKnight7

**Comment by cs6413110** [comment]
same aspect ratio

**Comment by CelestialKnight7** [comment]
> > they can be bigger but they have to simplify to that size
> 
> what does that even mean

means if u want more detail u can make it 80x90 cuz 80x90 can be halved to get back to 40x45. so it has to have a ratio of 8x9 which is 40x45 which is 80x90 which is 320x360

**Comment by LostKing73** [comment]
> same aspect ratio

so like can someone help me make that  image fit into that? like without bein super pixelated

**Comment by CelestialKnight7** [comment]
![pixil-frame-0 - 2024-10-25T115755 414](https://github.com/user-attachments/assets/892d447e-c145-4647-a8ef-46fc91a58f6c)
heres ur fat cosmet

**Comment by cs6413110** [comment]
MY EYEZ

**Comment by cs6413110** [comment]
LITERALLY GOT FLASHBNAGED

**Comment by CelestialKnight7** [comment]
690x920

**Comment by CelestialKnight7** [comment]
which is 23 times the 40x45

**Comment by LostKing73** [comment]
can u just make it please my brain hurts

**Comment by LostKing73** [comment]
as far as i understood(as in this is all I could do) this is the size of the image
![image](https://github.com/user-attachments/assets/e878486d-6ef4-4dd9-9040-a2b7751d3317)

**Comment by cs6413110** [comment]
He made it but Bradley deleted the comment

**Comment by LostKing73** [comment]
@CelestialKnight7

**Comment by BreadSpammer** [comment]
Evan made me. he wants money for it

**Comment by LostKing73** [comment]
:((((((( plssssssssssssssssssss

**Comment by cs6413110** [comment]
LOL SCAM

**Comment by LostKing73** [comment]
:(

**Comment by LostKing73** [comment]
gib cosmet >:|

**Comment by LostKing73** [comment]
@CelestialKnight7

**Comment by CelestialKnight7** [comment]
PROFIT
![pixil-frame-0 - 2024-10-25T115755 414](https://github.com/user-attachments/assets/cd69d614-5c08-4468-a513-31b057f1faec)

**Comment by LostKing73** [comment]
HOLY-

**Comment by LostKing73** [comment]
WOW

**Comment by LostKing73** [comment]
THX

**Comment by LostKing73** [comment]
ok, so if i just put this in as a cosmet, it SHOULD work, yes?

**Comment by CelestialKnight7** [comment]
no

**Comment by CelestialKnight7** [comment]
cuz tis friggin big rn and Aaron has to artificially resize it

**Comment by CelestialKnight7** [comment]
u "can" add it but if u equip it, it will be huge

**Comment by LostKing73** [comment]
bruh

**Comment by LostKing73** [comment]
can like game work please?

**Comment by LostKing73** [comment]
:((((((( @cs6413110 @BreadSpammer

**Comment by LostKing73** [comment]
can like my owner come back????

**Comment by LostKing73** [comment]
@cs6413110 at lunch, help me with resizing it and giving me that and one other cosmet.

**Comment by BreadSpammer** [comment]
nah

**Comment by BreadSpammer** [comment]
@LostKing73 celestial is dum. it should auto resize bc some cosmetics are 40x45 and others are 80x90 and they work in harmony. it might not work tho but like only 1 way to find out :D

**Comment by LostKing73** [comment]
ok, but i need twrite to test unless cs gives it to me...

**Comment by BreadSpammer** [comment]
just wait for crates to be fixed.

**Comment by LostKing73** [comment]
bro in like 4 years? no, @cs6413110 gib its

author_body 
and
author_hat

**Comment by BreadSpammer** [comment]
i would fix it, but its a problem with the crate menu itself, and that was broken like 4 months ago so like idk bye

**Comment by CelestialKnight7** [comment]
![pixil-frame-0 - 2024-10-28T114752 945](https://github.com/user-attachments/assets/c119c4ef-b410-42e9-9dd0-964a3f5445a2)
xifed but smoller
880x990 which can be simplified to 40 x45 unlike the original cuz I'm bad at math apparently

**Comment by LostKing73** [comment]
z

**Comment by LostKing73** [comment]
k thx

**Comment by LostKing73** [comment]
ok closed cuz transaction
