### ISSUE TITLE
First world problems

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#107]
mainly for me and aaron to keep track of what is fixed:

not ai:
- doing a 180 should not have your tank need to be turned around (to make it feel better)
- htmlify the inventory color thing
- death messages break chat
- can't change key binds or open crates

ai:
- stealth ai can go into void
- ai turrets have items too, and it breaks them
- ai don't use certain items
- ai dont have perks
- ai medic is outdated
- ai warrior died ig?'
- ai reflector is outdated. bullets that get reflected move slowlu
- ai sometimes just crash their code and become ghosts (maybe an item?)

**Comment by CelestialKnight7** [comment]
- balancing

**Comment by LostKing73** [comment]
ew, have vip be grren, yellow is ugy

**Comment by CelestialKnight7** [comment]
have vip be a2a415

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/6073a350-ba2d-4086-b0da-5fd301e7eeca)

**Comment by LostKing73** [comment]
bro y game no work T_T

**Comment by BreadSpammer** [comment]
HALP /gpt DIED!!!! how am I gonna cheat on my English homework :(((

**Comment by LostKing73** [comment]
> HALP /gpt DIED!!!! how am I gonna cheat on my English homework :(((

ye @cs6413110 figs

**Comment by LostKing73** [comment]
1: xif
2: vote on zones

**Comment by LostKing73** [comment]
> have vip be #a2a415

bro u downvoted the COLOR U SAID

**Comment by LostKing73** [comment]
still white

**Comment by CelestialKnight7** [comment]
its not, its vomit yellow

**Comment by CelestialKnight7** [comment]
put it in pixelart

**Comment by LostKing73** [comment]
ew, stop making it yellow. orange is good

**Comment by BreadSpammer** [comment]
its not yellow. its the color for "amber" in discord

**Comment by LostKing73** [comment]
🤢

**Comment by BreadSpammer** [comment]
its yellow+ orange deal with it

**Comment by BreadSpammer** [comment]
@cs6413110 make it so when ur tank bottom is turning, its based off of your speed (so when ur boosting, u turn rly fast, and when toolkitting, u turn slow.) for polishing purposes :)

**Comment by cs6413110** [comment]
aaaaaaaaa

**Comment by BreadSpammer** [comment]
🔫 fixed?

**Comment by LostKing73** [comment]
no :(

**Comment by CelestialKnight7** [comment]
![Screenshot 2024-11-14 9 08 52 AM](https://github.com/user-attachments/assets/6e608112-ea28-43d8-9614-27c9db9caa64)
@cs6413110

**Comment by cs6413110** [comment]
![Screenshot 2024-11-13 11 46 40 AM](https://github.com/user-attachments/assets/734163aa-9a1a-46ea-a8ff-792d39280444)
@CelestialKnight7

**Comment by cs6413110** [comment]
Menu buttons don't always update when needed.

**Comment by cs6413110** [comment]
![image](https://github.com/user-attachments/assets/745ee0c2-5013-42e6-b5a7-09c48f8a63c6)

**Comment by BreadSpammer** [comment]
make ai prioritize shooting shooting crates over anything, and make them go towards supply airstrikes

**Comment by BreadSpammer** [comment]
k, but make ai get crate buffs if they open one, and @everyone VOTE

should ai have perks? (they have everything else... items, classes, cosmetics, colors, etc. all they don't have is toolkit (why) and death effects (just don't die lol)

👍 = sure why not?
👎 = my name is Aaron Godfrey, and I am a confirmed downvote spammer

**Comment by cs6413110** [comment]
In other games enemies don't have certain  player-specific abilities and since we're triply-exceeding our workload limits, there's no reason we would even brainstorm something like this.

**Comment by BreadSpammer** [comment]
i WOULD conplain about improving ai braincells by making 6 different types based on class instead of 3, but then i would need to remake levels so nah

**Comment by BreadSpammer** [comment]
- turret maximum is 3 for everyone in a single player game, so if the ai place turrets, they will override your turrets
- ai can get hit by their own spikes
- game stops rendering for a frame when certain actions occur in single player
- when joining multiplayer, or at random, most of the game will not render
- levels never get locked, don't have rewards, or have requirements to unlock them
- certain types of ai will never move until freed, if they don't have a tile to move to in their range, and others will never stop moving, which is kind of weird (like imagine if in ur chicken pen in mc, all the chickens were running around in peril.
- turrets placed by ai are generated independently, so they have different cosmetics/color, and they don't die if the owner dies
- where'd the toolkit animation go?
- the default for spawning into a map if a spawn point is not present, is the first air block
