### ISSUE TITLE
someone broke admin, full auth, and vip

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#108]
whos the bread who broke it all

**Comment by LostKing73** [comment]
bread still has admin tho. i think its just full auth

**Comment by LostKing73** [comment]
@cs6413110

**Comment by CelestialKnight7** [comment]
if no one has full auth that means the game is fixed

**Comment by LostKing73** [comment]
ez. although cs doesnt have it either

**Comment by cs6413110** [comment]
game fixed then

**Comment by LostKing73** [comment]
i need my admin back at least aranb

**Comment by BreadSpammer** [comment]
ye resolved

**Comment by LostKing73** [comment]
no. not fixed until i get my admin back

**Comment by BreadSpammer** [comment]
lk talk in tanks

**Comment by LostKing73** [comment]
AHAHAHAHHAHAHA

**Comment by LostKing73** [comment]
ahem. fixed
