### ISSUE TITLE
@CS6413110 CANT DO THINGS

### ISSUE THREAD

**Issue by BreadSpam** [cs6413110/Pixel-Tanks#11]
can't assign, label, etc. plz save

**Comment by LostKing73** [comment]
what? how? whos got ownership then?

**Comment by LostKing73** [comment]
wait, neither can i??

**Comment by DarkMemeGod411** [comment]
no one has access rn

**Comment by LostKing73** [comment]
how?? is noone owner?

**Comment by DarkMemeGod411** [comment]
I think so

**Comment by LostKing73** [comment]
no, aaron is, but like its not working? he needs to make a new acc

**Comment by cs6413110** [comment]
Sorry, lemme fix contributor stuff.

**Comment by LostKing73** [comment]
huh?

**Comment by LostKing73** [comment]
danks
