### ISSUE TITLE
new map is tunnel hope u like I even made H O U S E

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#110]
R81X3R50X3R5XR8X3R40X3RX12RX3R40X3RX12RX3R41XR2X12R2XR41X3RX12RX3R40X20R40X3RX12RX3R47XR5XR53XR4X6R49XR4X6R13X5R31XR4X6R9X6R2XR31XR16X4R7X2R30XR14X3R11X2R27X7R9X2R14XR26X2R5X2R4X5R14X2R26XR7XRX4RX4R10X4R26X2R7X3R7X2R5X5RX2R26XR8XR10XR3X3R6XR26XR8XR10X2RX2R8XR26XR8XR11X3R4X6R26XR8XR12X2R4X5R23X5R8XR13XR4XR3XR22X2R3XR8XR13X2R3XR3XR22X2R3XR8XR12X11R22XR4XR8XR9X5R4X5R21XR5XR7X3R4X5R8XR3XR21XR5XR6X5R3XR3XR8XR3XR20X2R5X9SX6R3XR2X3R3X5R20XR6X2R5X5R7XRX4R3X5R20XR6XR7X3R8XRXRX2R3XR3XR20XR6XR8XR9X5R4XR3XR20X2R5XR8XR9XRXR6X5R21X5RX33R25X3R3XR4XR7XRXR8XR3X2R26XR3XR4XR7X3R8XR3X2R18X9R3XR4XR9XRX6RX6R18X5R3XR3XR4XR9XRXR4XRX6R18X7RXR3XR4XR6X11R6XR18X3R3XRX17R3XR3XRX8R18XR4X2RXR4XR3XR10X7R25X6R2XR4XR3XR42X2R6XR4X5R43X2R5XR53X7R644XRXRX3RXR2X2R47X3RX3RXR2X2R47XRXRXRXRX2RXR106
![Screenshot 2024-10-28 1 46 26 PM](https://github.com/user-attachments/assets/34e42445-1b46-4298-a812-57c1132f0cdc)

**Comment by LostKing73** [comment]
add

**Comment by 3foe** [comment]
promotes flatting and running but sure ig

**Comment by LostKing73** [comment]
that doesnt matter its tunnels >:)

**Comment by CelestialKnight7** [comment]
the pathway on the left doesn't connect...

**Comment by LostKing73** [comment]
sh

**Comment by CelestialKnight7** [comment]
*inhale* FIXIXIXIXIXIXIIFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXFFFIFIIFXXIFIXFIFXIXFIXFIFIFIFIFIFIXIXFIXFIXFIXFIXFIXFIFXIXFIIFIFIXFIFIIXIFXIFIXIFIXIIIFIIXIIFFIXFIXIFIXFIXFIFIXFIIFXIFIXFIIXF

**Comment by LostKing73** [comment]
fix urself the code is right there

**Comment by CelestialKnight7** [comment]
u so lazy

**Comment by LostKing73** [comment]
yes

**Comment by LostKing73** [comment]
nooooooooooooo but im working on backrooms :(

**Comment by LostKing73** [comment]
..fine but only bcuz i have no other way to procrastinate R81X3R50X3R5XR8X3R40X3RX12RX3R40X3RX12RX3R41XR2X12R2XR41X3RX12RX3R40X20R40X3RX12RX3R47XR5XR53XR4X6R49XR4X6R13X5R31XR4X6R9X6R2XR31XR16X4R7X2R30XR14X3R11X2R27X7R9X2R14XR26X2R5X2R4X5R14X2R26XR7XRX4RX4R10X4R26X2R7X3R7X2R5X5RX2R26XR8XR10XR3X3R6XR26XR8XR10X2RX2R8XR26XR8XR11X3R4X6R26XR8XR12X2R4X5R23X5R8XR13XR4XR3XR22X2R3XR8XR13X2R3XR3XR22X2R3XR8XR12X11R22XR4XR8XR9X5R4X5R21X2R4XR7X3R4X5R8XR3XR21XR5XR6X5R3XR3XR8XR3XR20X2R5X9SX6R3XR2X3R3X5R20XR6X2R5X5R7XRX4R3X5R20XR6XR7X3R8XRXRX2R3XR3XR20XR6XR8XR9X5R4XR3XR20X2R5XR8XR9XRXR6X5R21X5RX33R25X3R3XR4XR7XRXR8XR3X2R26XR3XR4XR7X3R8XR3X2R18X9R3XR4XR9XRX6RX6R18X5R3XR3XR4XR9XRXR4XRX6R18X7RXR3XR4XR6X11R6XR18X3R3XRX17R3XR3XRX8R18XR4X2RXR4XR3XR10X7R25X6R2XR4XR3XR42X2R6XR4X5R43X2R5XR53X7R644XRXRX3RXR2X2R47X3RX3RXR2X2R47XRXRXRXRX2RXR106

**Comment by 3foenation** [comment]
i think it would be fun to add and find runners
