### ISSUE TITLE
Discord server integration

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#111]
Basically link discord and FFA chat.

We can also do other stuff later ig, idk

**Comment by DarkMemeGod411** [comment]
How would that be possible?

**Comment by cs6413110** [comment]
Also you can run tanks commands from discord

**Comment by cs6413110** [comment]
https://www.npmjs.com/package/discord.js?activeTab=readme

**Comment by DarkMemeGod411** [comment]
how do i set it up

**Comment by cs6413110** [comment]
I would do it. I just need to know if we want to or not.

**Comment by LostKing73** [comment]
> how do i set it up

bruh, he's saying HE's coding it

**Comment by LostKing73** [comment]
> I would do it. I just need to know if we want to or not.

like yes obv

**Comment by BreadSpammer** [comment]
ye add. I'll link soon. @DarkMemeGod411 when i do, get everyone who plays tonks regulaury into the server

**Comment by BreadSpammer** [comment]
@cs6413110 can u make it so ur discord rank = ur tanks rank

**Comment by DarkMemeGod411** [comment]
> ye add. I'll link soon. @DarkMemeGod411 when i do, get everyone who plays tonks regulaury into the server
Will do

**Comment by cs6413110** [comment]
Can we clean up the discord server too? It's kinda messy and needs more channels

**Comment by BreadSpammer** [comment]
like after scoollol

**Comment by LostKing73** [comment]
i have owned a server in the past so I got u

**Comment by LostKing73** [comment]
k, so change co-owner to admin, and ill make dc look better, none of yall touch

**Comment by LostKing73** [comment]
> Can we clean up the discord server too? It's kinda messy and needs more channels

IM DOING IT NO ONE TOUCH AAAAAAAAAAAA

**Comment by cs6413110** [comment]
For ranking, it will be separate.

**Comment by cs6413110** [comment]
I'll have to /admin discord usernames

**Comment by LostKing73** [comment]
can you english pls

**Comment by cs6413110** [comment]
Discord roles won't mean anything for executing commands.

**Comment by LostKing73** [comment]
ok but they need to bcuz i don't want tony nukes

**Comment by cs6413110** [comment]
That won't be a problem.

**Comment by LostKing73** [comment]
wdym?

**Comment by LostKing73** [comment]
ohhhhhhhhhhhh

**Comment by BreadSpammer** [comment]
speakng of this, @cs6413110  make a issue template that just has u always assigned so I don't have to do it manually anymore

**Comment by LostKing73** [comment]
@BreadSpammer inv me back to the dc

**Comment by BreadSpammer** [comment]
after school lmao

**Comment by LostKing73** [comment]
aaaaaa

**Comment by LostKing73** [comment]
:(

**Comment by cs6413110** [comment]
But I cleared out general before I got banned. And I got the bot into the server, so I can start coding it on Monday.

**Comment by cs6413110** [comment]
Well, maybe today, but I don't think it would let me login.

**Comment by cs6413110** [comment]
Do we want death messages, bans, kicks, mutes, requesting unmutes, etc. to show up in chat?

**Comment by BreadSpammer** [comment]
sure

**Comment by DarkMemeGod411** [comment]
what would this do to me if i don't have discord. nothing?

**Comment by LostKing73** [comment]
yes. read.

**Comment by DarkMemeGod411** [comment]
game ded fix

**Comment by LostKing73** [comment]
we know.

**Comment by LostKing73** [comment]
so, @cs6413110 u coded, but like hows it gonna wor, is there gonna be a channel for it or just general? if its a choice I say leave general seperate

**Comment by cs6413110** [comment]
Should I alter /getlogs and /flushlogs to only log command usage since the discord bot will have all chat logs?

Should the discord bot include leave/join messages?

Should the discord bot include death messages?

Should the discord bot erase discord command usage?

*Commands will have to be recoded to allow for discord commands

**Comment by LostKing73** [comment]
yes
yes
no
wdym. translate to dum pls

**Comment by DarkMemeGod411** [comment]
1: yes
2: maybe?
3: no
4: yes.

**Comment by cs6413110** [comment]
Tried to code but got instaed for doing it on Sunday.

**Comment by LostKing73** [comment]
yes cuz like spamage
yes so ik if the person I'm talking to leaves
no cuz I don't need to know that idc
I need english, pls translate

**Comment by LostKing73** [comment]
done so closed
