### ISSUE TITLE
VIPs

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#114]
For context, VIPs can:
- filter words(but not allow)
- use /newmap
- mute
- unmute
- kick
- spectate
- switch teams in TDM
- start TDM early
- announce

Should we give more people VIP?

**Comment by cs6413110** [comment]
Vote to give DarkMemeGod VIP

**Comment by cs6413110** [comment]
Vote to give tony34 VIP

**Comment by CelestialKnight7** [comment]
> For context, VIPs can:
> 
> * filter words(but not allow)
> * use /newmap
> * mute
> * unmute
> * kick
> * spectate
> * live
> * switch teams in TDM
> * start TDM early
> * announce
> 
> Should we give more people VIP?

make it so they cant /live

**Comment by cs6413110** [comment]
Ok, done.

**Comment by 3foe** [comment]
bru

**Comment by CelestialKnight7** [comment]
ez

**Comment by LostKing73** [comment]
absolutly not.

**Comment by LostKing73** [comment]
> Vote to give DarkMemeGod VIP

bcuz, like, how many times has he been given a chance? 8?

**Comment by cs6413110** [comment]
for admin, once

**Comment by LostKing73** [comment]
@cs6413110 . Give me ONE good reason to give alex ANY executive powers

**Comment by LostKing73** [comment]
> It's not executive powers, that's the point.

it is. he can do things normal players cant.

**Comment by LostKing73** [comment]
> @cs6413110 . Give me ONE good reason to give alex ANY executive powers

^^^

**Comment by cs6413110** [comment]
He's basically an OG, he's always on so he can keep gpas in check, he hasn't done any cussing for a few months, it's not executive powers, VIP only gives minor commands, and everyone else seems to agree.

**Comment by LostKing73** [comment]
> He's basically an OG, he's always on so he can keep gpas in check, he hasn't done any cussing for a few months, it's not executive powers, VIP only gives minor commands, and everyone else seems to agree.

1. Tony is basically an og. he had his permissions removed but ppl like 3foe and coltin keep giving, so should he get VIP bcuz he's basically an og?
2. just bcuz he's always on doesn't matter, who cares what the gpas do if no one is on to be bothered by them, again by  that same logic, tony deserves it cuz he's on so much
3. VIP can mute and kick, 2 of the things his admin was removed for
4. idk why. like ^^^.

**Comment by DarkMemeGod411** [comment]
I am an og. i have been playing for 4 years. tony has had 1 3/4?. the admin was removed bc of /ai

**Comment by LostKing73** [comment]
and swearing. and spam kicking me. and muting me.

**Comment by LostKing73** [comment]
dont twist history to make urself seem more important

**Comment by cs6413110** [comment]
> > He's basically an OG, he's always on so he can keep gpas in check, he hasn't done any cussing for a few months, it's not executive powers, VIP only gives minor commands, and everyone else seems to agree.
> 
> 1. Tony is basically an og. he had his permissions removed but ppl like 3foe and coltin keep giving, so should he get VIP bcuz he's basically an og?
> 2. just bcuz he's always on doesn't matter, who cares what the gpas do if no one is on to be bothered by them, again by  that same logic, tony deserves it cuz he's on so much
> 3. VIP can mute and kick, 2 of the things his admin was removed for
> 4. idk why. like ^^^.

1.) He hasn't been around as much as DarkMemeGod
2.) Being on often is essentially a requirement for moderators. It's so they can, y'know, moderate?
3.) I have gotten literally SO many complaints about you doing that same thing. Plus I don't even thing he did it that much.

**Comment by BreadSpammer** [comment]
um idk if Tony has been alive that long EZ

**Comment by LostKing73** [comment]
the gpas hate me for moderating. alex wouldn't let me speak when I had a difference of opinion

**Comment by LostKing73** [comment]
also like why is coltin giving out vip
![image](https://github.com/user-attachments/assets/86614351-0728-4fb3-9632-996405a63afe)

**Comment by DarkMemeGod411** [comment]
I admit. i was bad in the past. but as aaron said. i have not done anything bad recently. i have changed

**Comment by LostKing73** [comment]
> I admit. i was bad in the past. but as aaron said. i have not done anything bad recently. i have changed

lies. yk how Ik that? bcuz u continue to lie and repeat the same actions at the lunch table. stop playing the victim

**Comment by DarkMemeGod411** [comment]
5-1 vote jonas. @CelestialKnight7 @3foe @cs6413110 @CelestialKnight7 @BreadSpammer all voted for me to have it. everyone else agrees.

**Comment by LostKing73** [comment]
If you had "changed" you would stop constantly telling me you dont like me, being dodgy and most of all... i asked you to let me and whoever i was talking to speak without you interrupting every other sentance, and you said "ill stop if you say please" excuse me? Add refusing admin to the list of misdemeanors he has

**Comment by DarkMemeGod411** [comment]
i have not interrupted recently. i asked you to say please bc you were being rude to me

**Comment by LostKing73** [comment]
> 5-1 vote jonas. @CelestialKnight7 @3foe @cs6413110 @CelestialKnight7 @BreadSpammer all voted for me to have it. everyone else agrees.

i. do. not. care. their opinions do not matter if they say they support you.

**Comment by CelestialKnight7** [comment]
bro its literally 4-1 (flat doesnt count)

**Comment by CelestialKnight7** [comment]
quit acting like ur in charge, the vote says it, Aaron said it. either way you take this you lose. just let him have vip and if it becomes a problem it can just be removed

**Comment by LostKing73** [comment]
> i have not interrupted recently. i asked you to say please bc you were being rude to me

YOU are CONSTANTLY rude to ME! IF you arent sucking up to me/anyone else (which was in preparation for this very issue) you literally are incredibly mean!

@BreadSpammer I actually am curious why you voted yes. u said that "stop sucking up meme its annoying" so why do you support it now?

**Comment by DarkMemeGod411** [comment]
how have i been mean dude. i want to know. by playing the game?

**Comment by LostKing73** [comment]
> how have i been mean dude. i want to know. by playing the game?

by saying u hate/dislike me. and idk TELLING ME TO KILL MYSELF? EXCUSE ME? ~3 MONTHS IS NOT A GOOD AMOUNT OF TIME TO FORGIVE YOU FOR THAT.

**Comment by DarkMemeGod411** [comment]
@CelestialKnight7 lk just banned me on tanks

**Comment by CelestialKnight7** [comment]
ffs

**Comment by LostKing73** [comment]
good. its deserved.

**Comment by LostKing73** [comment]
bcuz u continue to argue with me. it doesnt help ur case.

**Comment by DarkMemeGod411** [comment]
6-1 doesnt help your case

**Comment by LostKing73** [comment]
it is 6-infinity. no opinions matter.

**Comment by LostKing73** [comment]
> > how have i been mean dude. i want to know. by playing the game?
> 
> by saying u hate/dislike me. and idk TELLING ME TO KILL MYSELF? EXCUSE ME? ~3 MONTHS IS NOT A GOOD AMOUNT OF TIME TO FORGIVE YOU FOR THAT.

^^^

**Comment by LostKing73** [comment]
admitting to trying to abuse others
![image](https://github.com/user-attachments/assets/5bb24112-c556-4d19-ae99-7a4104458562)

**Comment by LostKing73** [comment]
mmmmoooooooorrrreeeeee alex saying he's not a good personnnnnnn
![image](https://github.com/user-attachments/assets/0c28b17d-fc6a-46e6-b09d-790c591c92ff)

**Comment by LostKing73** [comment]
this is pointless. alex will not get VIP. he continues to be disrespectful. enough.

**Comment by DarkMemeGod411** [comment]
mark my words. screenshot this please. i do not want admin. only vip.

**Comment by LostKing73** [comment]
can bro read?
