### ISSUE TITLE
average LostKing behavior

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#115]
![Screenshot 2024-10-30 12 12 17 PM](https://github.com/user-attachments/assets/a2c3af63-10a3-446a-bd31-fe680e1aac1f)
![Screenshot 2024-10-30 12 00 02 PM](https://github.com/user-attachments/assets/274de6fc-326c-4fe8-b548-de6ba3f2fa19)
![Screenshot 2024-10-30 11 59 44 AM](https://github.com/user-attachments/assets/c2c95f1d-4695-4f67-bc24-37c331cc8320)
![Screenshot 2024-10-30 11 59 30 AM](https://github.com/user-attachments/assets/3d030233-3a26-4490-b5d2-db1bb83a6aa8)
![Screenshot 2024-10-30 11 51 47 AM](https://github.com/user-attachments/assets/ce3ea8dc-b337-487f-93c8-7b4f1bc6e555)
![Screenshot 2024-10-30 11 51 16 AM](https://github.com/user-attachments/assets/f8ebc484-cebd-49cc-a6c2-bf06156c634b)
![Screenshot 2024-10-30 11 50 24 AM](https://github.com/user-attachments/assets/34518920-1022-4672-9549-8995b12bcd99)

**Comment by LostKing73** [comment]
yea

**Comment by CelestialKnight7** [comment]
you act like your opinion is all that matters, we've seen it before with the cosmetic issues. and as seen with the memegod issue, you are just as bad as him. so I see no reason why you shouldn't be demoted or have your admin removed

**Comment by LostKing73** [comment]
i see no reason why this is important or needs to be smth discussed. like 1. this is what alex wants 2. idc 3. like just be nice and no bully/hate, k ?

**Comment by BreadSpammer** [comment]
so if I arrest you for committing war crimes, that's hate?

**Comment by BreadSpammer** [comment]
bru

**Comment by CelestialKnight7** [comment]
1. what Alex wants is irrelevant to me, and I'm not going to stop simply because he wants this, its like donating to charity and saying "oh well Hitler would have wanted this", not gonna stop me
2. kinda the point, you dont care about the game, all you care about is your self and getting what you want
3. bro have you seen the screenshots, you AND memegod have been doing this. Both. so if one shouldnt have admin because of it, neither should the other

**Comment by LostKing73** [comment]
bro like stop bcuz this isnt rly a problem

**Comment by LostKing73** [comment]
am i harming the game. no. are you by spamming this hate. yes. end of story. I've given up on stopping alex so I don't get to this point we are at rn. please. stop.

**Comment by CelestialKnight7** [comment]
you're right, its not as big as whatever else is happening in the game but that doesn't mean its not a problem. I'm just trying to be fair. And you have been harming the game by trying to say your vote is all that matters, you act like youre the one in charge. And you werent so quick to forgive Alex after 3 months of him not giving hate, so why should I let this drop after a day?

**Comment by LostKing73** [comment]
guys

**Comment by LostKing73** [comment]
i literally. could not give to craps abt alex. its aaron's game, if alex ruins it that's his fault. i warned him. i am not a problem bcuz I dislike the person who was bullying me.

**Comment by LostKing73** [comment]
speaking of bullying you AND bread are both bullying me. literally. like stop. leab lone. i only want leabage loneage

**Comment by LostKing73** [comment]
if the issue is that i was bein mean to alex, not only have you bread and alex been mean to me, but I literally am just going to let alex destroy this community along with 3foe. idc anymore, so leab lone.

**Comment by CelestialKnight7** [comment]
youre a problem because of how you handled it.

you ignored everyone else and acted like you were the one calling the shots
you then harassed memegod in game

and speaking of bullying, what I'm doing is being fair, you bully memegod, you get punished for it. Would you call the police bullies, or a judge? No, because they're doing thier job of making it fair.

**Comment by CelestialKnight7** [comment]
and quit acting like you're the sole protector of the game from 3foe or memegod

**Comment by LostKing73** [comment]
as far as i can i am bcuz it seems u only care abt my removal when literally there are worse issues rn. **leab lone.**

**Comment by CelestialKnight7** [comment]
breaking news: criminal assaults man and then tells authority he just wants to "leab lone"

**Comment by LostKing73** [comment]
also, THATS OVER. I QUIT THAT. STOP THINKING I CARE

**Comment by CelestialKnight7** [comment]
you clearly do as youre still arguing

**Comment by CelestialKnight7** [comment]
- refuses to acknowledge the vote and the decision of the aaron
- bullies memegod
- refuses to elaborate further
- says "leab lone"

**Comment by LostKing73** [comment]
i leabd lone. leab me lone

**Comment by LostKing73** [comment]
> you clearly do as youre still arguing

I'm literally just saying leab lone. you are picking fights.

**Comment by CelestialKnight7** [comment]
bro, you can't just ignore what you did, literally this exact scenario:

breaking news: criminal assaults man and then tells authority he just wants to "leab lone"

like??? can't you see how what you're doing is ridiculous

**Comment by LostKing73** [comment]
self defense

**Comment by LostKing73** [comment]
> bro, you can't just ignore what you did, literally this exact scenario:
> 
> breaking news: criminal assaults man and then tells authority he just wants to "leab lone"
> 
> like??? can't you see how what you're doing is ridiculous


the "criminal" is called a criminal for pushing away a guy that shot him 3 times

**Comment by CelestialKnight7** [comment]
I'm calling you on his level.
you both pick fights with each other, so if one doesn't get admin neither should the other
and at least memegod can see reason when people make a collective decision

**Comment by LostKing73** [comment]
i literally am not picking a fight. LEAB LONE is not a fight

**Comment by LostKing73** [comment]
like what happend to yall agreeing that alex sucks? u literally agreed with that a week ago.

**Comment by CelestialKnight7** [comment]
im calling you a criminal because you shoot him 7 times after he was already disarmed

**Comment by LostKing73** [comment]
bro. what. me saying be quiet so I can talk isn't the same as kill yourself.

**Comment by CelestialKnight7** [comment]
> like what happend to yall agreeing that alex sucks? u literally agreed with that a week ago.

I do, but I also think you suck, you refuse to ackowledge a collective vote, you act like you're in charge, ignoring aaron in the process

**Comment by LostKing73** [comment]
k leave closed so it doesnt get spammed more than this alrdy is cuz if u open I'm just gonna close

**Comment by LostKing73** [comment]
aaron isnt always right.

**Comment by CelestialKnight7** [comment]
> bro. what. me saying be quiet so I can talk isn't the same as kill yourself.

have you seen the screenshots bro?
![Screenshot 2024-10-30 12 12 17 PM](https://github.com/user-attachments/assets/6289ba9e-4a8d-412c-b93f-fa687638a127)
![Screenshot 2024-10-30 12 00 02 PM](https://github.com/user-attachments/assets/3bcfd653-e21f-4636-886f-119146bc90fd)
![Screenshot 2024-10-30 11 51 47 AM](https://github.com/user-attachments/assets/4556b1b1-5228-4d97-b4f9-7b4c5320c6da)

**Comment by LostKing73** [comment]
i was trying my best to save.

**Comment by LostKing73** [comment]
oops

**Comment by LostKing73** [comment]
he literally is sassing me as im telling him to stop???

**Comment by CelestialKnight7** [comment]
> aaron isnt always right.

maybe, maybe. but that doesn't give you the right to just say that your vote is all that matters. you argue with reason while being respectful. which is not at all what you did

**Comment by LostKing73** [comment]
and also. I DO NOT CARE DUDE. LEAB LONE. IM DONE BRO.

**Comment by CelestialKnight7** [comment]
> he literally is sassing me as im telling him to stop???

you're both just screaming at each other is all I'm seeing

**Comment by CelestialKnight7** [comment]
> and also. I DO NOT CARE DUDE. LEAB LONE. IM DONE BRO.

then be done, but you lose your admin in the process

**Comment by LostKing73** [comment]
i dont need to lose a friendship bcuz alex is manipulative. leab lone. end of story.

**Comment by BreadSpammer** [comment]
the court case ends too ig. admin ded? @cs6413110 ???

**Comment by LostKing73** [comment]
my admin doesnt need to be revoked over this. like just focus on making main lobby, this isn't helpful at all

**Comment by LostKing73** [comment]
"fix game" noooooo ur adminnnnn needs to be revooked aaaaaaa

**Comment by CelestialKnight7** [comment]
ight then, I'll end this like a reasonable person:

@cs6413110 @BreadSpammer @LostKing73 @DarkMemeGod411 @CelestialKnight7 
Vote.
👍 = remove admin
😕 = remove admin but keep vip
👎 = leab lone

**Comment by LostKing73** [comment]
bro. leab lone

**Comment by CelestialKnight7** [comment]
ight then, I'll end this like a reasonable person:

@cs6413110 @BreadSpammer @LostKing73 @DarkMemeGod411 @CelestialKnight7
Vote.
👍 = remove admin
😕 = remove admin but keep vip
👎 = leab lone

**Comment by LostKing73** [comment]
I AM NOT SMTH THAT NEED TO BE WORKED ON. THE GAME IS. LEAB LONE.

**Comment by LostKing73** [comment]
this is insane. i literally was trying to protect game. why??

**Comment by CelestialKnight7** [comment]
because of how you handled it, again you refused to even argue it reasonably, you acted like youre in charge, and yeah the game needs to be worked on but this cannot be ignored.

**Comment by CelestialKnight7** [comment]
so instead of acting like you're the protagonist, lets end this like reasonable people:

**Comment by CelestialKnight7** [comment]
ight then, I'll end this like a reasonable person:

@cs6413110 @BreadSpammer @LostKing73 @DarkMemeGod411 @CelestialKnight7
Vote.
👍 = remove admin
😕 = remove admin but keep vip
👎 = leab lone

**Comment by LostKing73** [comment]
and literally cs just said leab lone.

**Comment by CelestialKnight7** [comment]
you clearly have not since you're still here

**Comment by CelestialKnight7** [comment]
> and literally cs just said leab lone.

and we wouldnt have know this is you didn't let the vote happen

**Comment by cs6413110** [comment]
@LostKing73 don't be mean to DarkMemeGod, even if he was mean to you in the past. I feel like it's been months since whatever he did, and I don't need to get involved in that, but despite it being months you are still going after him. We have better things to do than fight each other?

We're not removing his admin because flat still has admin and flat has committed 30000x the war crimes. But LostKing, stop overstepping your bounds. I've tried to be understanding with what my parents, flat, and DarkMemeGod have done, but ultimately you just have to live with it. You can't fight them back by being just as bad. I live with them 24/7 and fighting back just makes everything worse, for everyone.

**Comment by LostKing73** [comment]
dude. im still here bcuz ur trying to remove my admin. i don't need u  to remove

**Comment by LostKing73** [comment]
first paragraph, ik, thats wht im tryna say I'm doing???

2nd paragraph, I do not think I am  being even close to as bad as alex treated me. but @BreadSpammer and @CelestialKnight7 , you two need to actually leab lone. you 2, and I mean this a seriously as possible, actually gave me a panic attack last night with the bullyism in the dc. i will not let myself become ostracized because u think ur better at pressing a bunch of buttons in a certain order. when I say leab lone, leab lone.
