### ISSUE TITLE
Make it so you can't bind multiple actions to 1 key

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#116]
Reasons:

1: flats use to one shot ppl with 1 key which isn't fair
2: doesn't make sense, and makes game harder to play
3: Minecraft does it this way :)

**Comment by LostKing73** [comment]
make it so u cant configure that, i need grip to be e and f to be space

**Comment by CelestialKnight7** [comment]
Make it so that u cant bind multiple inputs to the same key

**Comment by BreadSpammer** [comment]
@cs6413110 @DarkMemeGod411 vote. also I'm coding this

**Comment by LostKing73** [comment]
bruh u did not need to delete?

**Comment by cs6413110** [comment]
Coding 2nd hour, but current keybinds will still persist.

**Comment by CelestialKnight7** [comment]
then just ban those accounts? or make a command that scrambles someone's keys

**Comment by LostKing73** [comment]
> then just ban those accounts? or make a command that scrambles someone's keys

ez command

**Comment by CelestialKnight7** [comment]
the 3foe downvote lol

**Comment by CelestialKnight7** [comment]
okay now to reset everyone's keys

**Comment by LostKing73** [comment]
ez
