### ISSUE TITLE
block update

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#117]
### The Basics 
blocks can no longer be placed on turrets (auto bread downvote) and placing a block on another block "fortifies" that block. it dletes the second block and makes the first block have a metal armor texture, and gives it an extra half the health of a white block if a white block was placed, or the extra health of a weak block if a weak block was placed

### Why add this?
sounds cool, more combo potential with weak/strong block, nerfs turip a bit more.

### Voting

👍 ye
👎 no(comment y)

**Comment by cs6413110** [comment]
Would placing a block on a turret heal the turret(if you are the same team)?

**Comment by LostKing73** [comment]
> Would placing a block on a turret heal the turret(if you are the same team)?

sure that's actually a good idea

**Comment by LostKing73** [comment]
> seems unnecessary, current system is fine

fine isn't good

**Comment by LostKing73** [comment]
why am i supporting this, this idea sucks
