### ISSUE TITLE
new item reverse reflect

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#118]
the basics

gives you a 50% damage reduction and pulls all projectiles towards you

why add
ez? and like uhm combos if u angle stuff right u can curve bullets or smth

vote

👍 ye
👎 ne (y)

sorry for no bolding or effort I'm on a budget

**Comment by BreadSpammer** [comment]
but why??? why take 50% damage when u can take 0???

**Comment by LostKing73** [comment]
> but why??? why take 50% damage when u can take 0???

bcuz if u took 0 ppl would say its op

**Comment by LostKing73** [comment]
its meant as a team item, ur temates can use u as a meatsheild

**Comment by 3foenation** [comment]
its bassicly reflect we have it already

**Comment by 3foenation** [comment]
exept anoying

**Comment by BreadSpammer** [comment]
how long does it last??? bc if its short, then useless

**Comment by 3foenation** [comment]
that is grapple

**Comment by LostKing73** [comment]
> its bassicly reflect we have it already

its not, it doesn't reflect anything it absorbs things. u just tink its reflect cuz of title

**Comment by LostKing73** [comment]
> how long does it last??? bc if its short, then useless

...5 seconds...? but rly long cooldown

**Comment by LostKing73** [comment]
> that is grapple

???? can u not read?

**Comment by BreadSpammer** [comment]
ppl would just run away the moment u use it, and just normal shot you until it ends

**Comment by BreadSpammer** [comment]
aka another builder counter. also too similar to usb

**Comment by LostKing73** [comment]
> aka another builder counter. also too similar to usb

how too similar to USB??

**Comment by LostKing73** [comment]
> ppl would just run away the moment u use it, and just normal shot you until it ends

gripple.

**Comment by CelestialKnight7** [comment]
ew damage mitigation

**Comment by CelestialKnight7** [comment]
besides we already have all the items "done"

**Comment by LostKing73** [comment]
ok
