### ISSUE TITLE
GPT update

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#119]
Since it's broken, I might as well add some improvements to it while I fix it.

Commands:

/gpt <prompt>
/gptclear - Clears your gpt history
/wgpt <prompt> - GPT with web access (persistent history)
/dalle2pro <prompt> - Image generation(sends image in chat) (VIP or Admin only?)

**Comment by BreadSpammer** [comment]
just add idk lol lag bye

**Comment by LostKing73** [comment]
closing cuz yes

**Comment by BreadSpammer** [comment]
don't close cuz not done

**Comment by LostKing73** [comment]
but like the vote is done and he'll do
