### ISSUE TITLE
new map

### ISSUE THREAD

**Issue by DarkMemeGod411** [cs6413110/Pixel-Tanks#125]
R18I4R6I4R45IXZX2I6X2ZXIR44IXIX10IXIR44IX2I4X2I4X2IR44I2X4IX2IX4I2R45I2X3IZ2IX3I2R46I2X2IX4IX2I2R45I2X2IX6IX2I2R43I2X2IX8IX2I2R42IX2IX2IX4IX2IX2IR42IZ2IX3ZX2ZX3IZ2IR42IX2ZX4Q2X4ZX2IR42IX2ZX4Q2X4ZX2IR41IZX2IX3ZX2ZX3IX2ZIR40IXIXIX2IX4IX2IZIXIR40IXIX2IX8IX2IXIR40IXIX3IX6IX3IXIR40IXI2X3IXZ2XIX3I2XIR40IX2IX3I2Q2I2X3IX2IR40I2XIX3I2Q2I2X3IXI2R41IXZX3Z2Q2Z2X3ZXIR41I2XIX3I2Q2I2X3IXI2R40IX2IX3I2Q2I2X3IX2IR40IXI2X2IX2Z2X2IX2I2XIR40IXIX2IX8IX2IXIR40IXIXIX10IXIXIR40IXIZIX10IZIXIR40IZX2ZX10ZX2ZIR40IZX2ZX4SX5ZX2ZIR40IXI3X10I3XIR40IXI3X10I3XIR40IXIR2IX8IR2IXIR40IX2IR2IX6IR2IZXIR41IXZIR2I2Z2I2R2IXZIR43IZXIR2IX2IR2IX2IR44I2XIR2IX2IR2IXI2R44IX2IR2IX2IR2IX2IR43IX2IR3IX2IR3IX2IR41IX2IR3IX4IR3IX2IR39IX2IR3IX6IR3IX2IR38IZIR3IX2RZ2RX2IR3IZIR38IX2IRIX2R2Q2R2X2IRIX2IR39IX2I2XR3Q2R3XI2X2IR41IX4R3Q2R3X4IR43IX3R3Q2R3X3IR45I2XR3Q2R3XI2R47IX2R2Q2R2X2IR49IX2RZ2RX2IR51IX6IR53I6R272I3R57I5R55I7R53I9R51I11R49I13R47

**Comment by DarkMemeGod411** [comment]
forgot gps whoops...

**Comment by DarkMemeGod411** [comment]
![Screenshot 2024-10-31 1 05 34 PM](https://github.com/user-attachments/assets/c364f3ca-a448-4f30-a85e-4510360679eb)

**Comment by LostKing73** [comment]
sure, why barriers in corner tho?

**Comment by DarkMemeGod411** [comment]
mouse malfunctioned,

**Comment by DarkMemeGod411** [comment]
Can i do the commit to add? :)

**Comment by DarkMemeGod411** [comment]
is it ready to add?

**Comment by CelestialKnight7** [comment]
go for it

**Comment by LostKing73** [comment]
bro he has code access too 💀

**Comment by DarkMemeGod411** [comment]
alr. i think i did it right

**Comment by DarkMemeGod411** [comment]
i think i did it right

**Comment by LostKing73** [comment]
like, yall not learning ur lessons is painful to watch

**Comment by LostKing73** [comment]
k closing cuz we cant rly test, @DarkMemeGod411 what zone.

**Comment by DarkMemeGod411** [comment]
uh, cave bc looks like a tunnel

**Comment by DarkMemeGod411** [comment]
idk why i decided to do work

**Comment by LostKing73** [comment]
sure

**Comment by DarkMemeGod411** [comment]
@BreadSpammer did i make the map right in code?

**Comment by BreadSpammer** [comment]
probably not but like only 1 way tofindo ut

**Comment by DarkMemeGod411** [comment]
yipee. it works!
