### ISSUE TITLE
new cosmetic: knight helm

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#126]
_blegh_
![image](https://github.com/user-attachments/assets/370b03e4-753b-4788-b2b8-06f121de3e54)

**Comment by LostKing73** [comment]
@CelestialKnight7 @BreadSpammer @cs6413110

**Comment by BreadSpammer** [comment]
*ahem* helment :)

**Comment by CelestialKnight7** [comment]
already have knight helme**n**ts and they look better than this

**Comment by CelestialKnight7** [comment]
all i can see is a vent with a red light on top

![image](https://github.com/user-attachments/assets/5f5ab24b-e3e4-4892-812f-06d4b6753200)

**Comment by LostKing73** [comment]
what a helmet bro. i need that. its supposed to be like this
![image](https://github.com/user-attachments/assets/5d4fd1c5-f5dc-44a2-b5e6-7d936695a2ce)

**Comment by LostKing73** [comment]
ok
