### ISSUE TITLE
Warrior Boost Rework

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#128]
### The Basics

Warrior boost will charge in a single direction, and do a sweep attack dealing big damage(300 min) where it stops, and deals knockback.

### Why add this?

Fundamentally changes warrior boost, but it works really well. should make it more of a warrior than a "aa I hit 3 people when I pressed f". 

### Might have. . .

This section is used to describe certain features it could have. 

When you hit someone mid-dash, and not at the end, it drags them with you until you finish, and they get caught in the swoosh. however, it can be boosted or grippled out of.

### Voting

👍  = Yes
👎 = No (comment why)
😕 = Maybe, this feature might help it though (comment extra/change)

**Comment by BreadSpammer** [comment]
so like plz understand how DMG works. 300 is more than an insta 🤦. more reasons that I know more and am better then u, but anyway... idk about this bc 1: #707 2: seems too complicated to code bc we've never added real knock back. the most we've done is grapple, and that is held together by duct tape.

**Comment by LostKing73** [comment]
k, ur not giving a solution tho, so un- 😕  and swap to a 👎 if u don't want. same to u alex.

**Comment by LostKing73** [comment]
and the damage can be like 200 or smth, just like warrior as a class is a glorified 2nd power bullet

**Comment by LostKing73** [comment]
so like add knockback. polishing.

**Comment by BreadSpammer** [comment]
bruh 200 is MEGOABULLET DMG. no insta clones :(

**Comment by BreadSpammer** [comment]
warrior boost rn is 100-50 I think
byeee

**Comment by LostKing73** [comment]
its 100, and thats the same as the blue bullet thing. or smth. idk, warrior boost doesn't do enough damage but idk if yall are ok with a simple damage buff

**Comment by LostKing73** [comment]
like can we aat least just buff warrior boost to like 250 dmg?

**Comment by CelestialKnight7** [comment]
> its 100, and thats the same as the blue bullet thing. or smth. idk, warrior boost doesn't do enough damage but idk if yall are ok with a simple damage buff

warrior boost sacrifices damage for movement and hit potential, the hit is basically garrenteed because of ur hitbox being massive (ur fat), meanwhile tactical gets more damage because its harder to hit (on average)

**Comment by CelestialKnight7** [comment]
> like can we aat least just buff warrior boost to like 250 dmg?

still more than tactical my dude, nope. again, tactical has a longer cooldown and harder chance to hit, so it gets more damage

warrior is easier to hit with a lower cooldown so it makes sense to lower the damage

**Comment by LostKing73** [comment]
50 more??? like that would be enough

**Comment by LostKing73** [comment]
150 damage, or a shorter cooldown. 150 damage would be perfect tho

**Comment by CelestialKnight7** [comment]
also just gonna put this out there: #15 
"either cancel boost when u hit something or u can only boost in 1 direction and can't turn mid boost"

**Comment by LostKing73** [comment]
no. those are nerfs.

**Comment by CelestialKnight7** [comment]
> 150 damage, or a shorter cooldown. 150 damage would be perfect tho

why would 150 be perfect?

I think the cooldown is fine now (although I still end up spamming f anyways) and the damage is fine

**Comment by LostKing73** [comment]
like 50 more damage? votage?

**Comment by CelestialKnight7** [comment]
sure @BreadSpammer @cs6413110 @DarkMemeGod411 VOTEE ^

**Comment by LostKing73** [comment]
> > 150 damage, or a shorter cooldown. 150 damage would be perfect tho
> 
> why would 150 be perfect?
> 
> I think the cooldown is fine now (although I still end up spamming f anyways) and the damage is fine

bcuzlike 450 isn't a clean number and 500 is. still not enough to 1 shot with sheild

**Comment by CelestialKnight7** [comment]
> no. those are nerfs.

is that not what ur Rework is talking  about, making it only boost in 1 direction?

**Comment by LostKing73** [comment]
for context, i came up with a method to make warrior boost deal 450 dmg

**Comment by CelestialKnight7** [comment]
I know, and u want that extra 50 damage so u can insta

**Comment by LostKing73** [comment]
> > no. those are nerfs.
> 
> is that not what ur Rework is talking about, making it only boost in 1 direction? "Warrior boost will charge in a single direction"

kinda, but it doesn't attack until the very end and does more damage. idc abt that one tho just like gimmie 50 dmg

**Comment by LostKing73** [comment]
evan, can i try the combo on u in game? just as a test

**Comment by LostKing73** [comment]
k we deduced its hard to hit but theoretically, it can deal enough damage to one shot with shield. 

The Combo:
Dyna
powerbullet
shotgun
warriorboost
bomb
all at the same time
+usb for extra damage

can deal +500 damage. so like, don't fix tho, bcuz its near impossible to hit

**Comment by CelestialKnight7** [comment]
ok. but btw bomb is getting yeeted. also byeeeeee

**Comment by LostKing73** [comment]
ye, but the frag bomb will make this even better lol
