### ISSUE TITLE
New Item: Spirit Jar

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#129]
### The Basics

Opens a jar, releasing a small light from inside. This is the "spirit" and it immediately zips to the nearest non-friendly tank, and attaches to it. Once attached, it will begin to slowly drain health every second, looking like this:

1 second, first hit, deals 1 damage
2 seconds, 2nd hit, deals 2 damage
3 seconds, 3rd hit, deals 4 damage
4 seconds, 4th hit, deals 8 damage
5 seconds, 5nd hit, deals 16 damage

and so on, for 10 seconds in total. The spirit can only be stopped by a toolkit or bomb.

### Why add this? 

Prevents flatting, can help start fights, gives more purpose to bomb, etc

### Might have. . .

Can't go thru void(it can rn) 
slowness
can be gripped as its flying, if you want ur low teammate to not be spirited
can go towards teammates(not u) and do the same, but healing instead of damage

### Voting

👍 = Yes
👎 = No (comment why)
😕 = Maybe, this feature might help it though (comment extra/change)

**Comment by BreadSpammer** [comment]
1: usb exists (basically does the same thing except increases dmg and is already coded)
2: bomb is getting tripple insta'd unless we add more to the total item count (in which this doesnt matter, but like @cs6413110 & @CelestialKnight7 would allow that)
3: would either be completely outclassed by fire if it was easy to remove, or an item that forces u to bring a counter (aka either u take a billion chip damage, or u take a billion shotgun dmg bc u toolkitted mid fight)

**Comment by LostKing73** [comment]
imma close cuz he isnt wrong

**Comment by CelestialKnight7** [comment]
I feel like ur better at designing items for a pve setting and not pvp, cuz this would be cool but just doesn't fit into a pvp game

**Comment by LostKing73** [comment]
> I feel like ur better at designing items for a pve setting and not pvp, cuz this would be cool but just doesn't fit into a pvp game

if I could code I would code a pve game lol
