### ISSUE TITLE
FINAL BALANCING

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#13]
okay nvm I have to re-type everything
spam here about balancing stuff unless stated otherwise
do not edit this comment

**CLASSES:**
- fire - **[DONE]**
- tactical - **[DONE]**
- stealth - **[DONE]**
- warrior - **[DONE]**
- medic - **[DONE]**
- builder - **[DONE]**

**ITEMS:**
- bomb - **[DONE]** (supply crut)
- smoke bomb - DED prob idk
- USB - **[DONE]**
- spike - **[DONE]**
- airstrike - **[DONE]**
- reflect - **[DONE]**

**PERKS:**
- shield - **[DONE]**
- thermal - **[DONE]**
- scavenger - **[DONE]**
- cooldown - **[DONE]**
- refresh - **[DONE]**
- radar - **[DONE]**
- second wind - **[DONE]**
- block upgrade - **[DONE]**
- dying core - **[DONE]**

**Comment by CelestialKnight7** [comment]
@cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 

- add dying core
- add overdrive
- replace bomb with breacher
- rework spike for bear trap (bread trap - name pending)
- cooldown perk - buff
- radar fix
- grip - fix
- remove i frames from reflect
- stealth nerf
- medic fix
- builder fix
- smoke bomb buff
- airstrike buff
-

**Comment by CelestialKnight7** [comment]
😭

**Comment by 3foe** [comment]
@cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110  @cs6413110

**Comment by cs6413110** [comment]
Ok, unignoring bc brain cells on cooldown

**Comment by cs6413110** [comment]
Radar fixed.
Level 1 -> See enemies
Level 2 -> See friends and enemies

Idk when we decided on this but I remember we did a while back and it's coded that way so... done?

**Comment by CelestialKnight7** [comment]
> @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110
> 
> * add dying core
> * add overdrive
> * replace bomb with breacher
> * rework spike for bear trap (bread trap - name pending)
> * cooldown perk - buff
> * grip - fix
> * remove i frames from reflect
> * stealth nerf
> * medic fix
> * builder fix
> * smoke bomb buff
> * airstrike buff

@cs6413110  jsut remove items from this list after they get completed or write a comment saying whats done so i can remove. Thanks

**Comment by DarkMemeGod411** [comment]
I frames from reflect are removed ages ago

**Comment by CelestialKnight7** [comment]
i thought they werent cuz the bread kept spamming about it

**Comment by LostKing73** [comment]
so like, replace smoke with the electric bullet thing. the current replacement is just big spike

**Comment by CelestialKnight7** [comment]
nah

**Comment by BreadSpammer** [comment]
airstrikes rework:
when the airstrike is placed, you will still see the airstrike symbol, but now, it will actually be moving towards the nearest player(does not target turrets) moving towards them at about half a tank's speed. the airstrike will also last 5 seconds, giving people more opportunities to get the grip in. you could also use the new bear trap, or blocks to trap them in with it.
all other stats are identical
this rework makes airstrikes better, allowing for easier one shots, and more pressure that cant be ignored, while also giving builders the chance to save their turrets by luring the airstrike away.

imagine, Helldivers laser except that it's outrunable.

**Comment by LostKing73** [comment]
bro. smoke is bad. why have it. it doesn't even work right like ik ur in there

**Comment by LostKing73** [comment]
alex, its BETTER with that, literally why downvote

**Comment by DarkMemeGod411** [comment]
bc i like the current one that is hard to block and could kill people in void

**Comment by LostKing73** [comment]
this is HARDER to block, and can still kill in the void!!!!!??????? LITERALLY read before downvoting??????

**Comment by CelestialKnight7** [comment]
make USB die on toolkit (does not do this currently) and make this effect both friendly and enemy usb's so if u want health u have to sacrifice ur buff

**Comment by CelestialKnight7** [comment]
make radar arrows disappear at close range

**Comment by BreadSpammer** [comment]
> make USB die on toolkit (does not do this currently) and make this effect both friendly and enemy usb's so if u want health u have to sacrifice ur buff

was how It originally worked, but now its on a 30 second cd, bc someone added that, and I'm too lazy now so like LAG AEF A

**Comment by LostKing73** [comment]
remove spike dissapearing after 5 seconds? like spike is usess if I cant use it to hit someone whos running by pres setting it up. in a close fight just placing it cant do enough damage to be viable

**Comment by LostKing73** [comment]
ik beartrap is  gonna be added but rn its not, so fix this

**Comment by LostKing73** [comment]
make bomb break fire

**Comment by BreadSpammer** [comment]
it doesnt? also don't use spike. its like actually usless. does basically no damage, even with spike block, and doesn't slow, so waste of an item. use dyna until bear trap added

**Comment by LostKing73** [comment]
bro. 

1. it does dissapear after 5 seconds. i tested. if not 5 seconds its too short. 
2. u are literally only proving my point by saying it sucks.
3. bear trap expected addition date: 2031

**Comment by cs6413110** [comment]
ITS SPIKE TRAP FIX

**Comment by CelestialKnight7** [comment]
we already have the final items so no point in balancing it if its going to get replaced. just cope until it's added cuz time that u want spent fixing items that will be replaced could be spent replacing the item

**Comment by cs6413110** [comment]
Me crying that we added a slowness item and now AI is going to be more pain

**Comment by LostKing73** [comment]
uhm, speaking of ai, why can ai turrets block me?

**Comment by BreadSpammer** [comment]
if we add a new item, then i'd want it to be a light damage item. one that does a bit less damage then dynamite, but is easier to hit, and has big AOE.

**Comment by LostKing73** [comment]
nuke 2.0 its the same but green

**Comment by BreadSpammer** [comment]
yes but like not copywrite totem unless Aaron approves

**Comment by 3foe** [comment]
![minecraft-minecraft-totem](https://github.com/user-attachments/assets/cd2d96de-26c7-4699-a232-32aa4ba78dcb)

**Comment by CelestialKnight7** [comment]
is airstrike done?

**Comment by 3foe** [comment]
What about reworking tacticle?

**Comment by DarkMemeGod411** [comment]
no Tactical changes. works well as-is

**Comment by BreadSpammer** [comment]
so like I say we should change the block perk to include all items, not just block, so it can be used with more classes

**Comment by cs6413110** [comment]
what does that mean

**Comment by BreadSpammer** [comment]
Item Enhancer:

gives a (25,50,75)% chance to enhance any item you use, making them stronger

- airstrike: crosses twice, making an x of explosions
- glu: heals 25% more
- tape: heals 25% more
- shield: shield gives 0.5 seconds of I frames when used
- smoke bomb: deals chip damage to ppl inside
- bomb/breacher? : does an aoe explosion for 50 DMG/idk breacher lol. deals more damage?
- dyna: deals more damage & bigger explosion
- usb: increases multiplier
- weak: strong
- strong: gold
- spike/bear trap: longer stun time/ more damage
- reflect: longer I frames

this makes it so its not just a block perk, and helps anyone who uses it

**Comment by 3foe** [comment]
That's gambling. Since we are replacing adrenaline with a health-activated perk the new perk should be health-activated too.

**Comment by CelestialKnight7** [comment]
> We just need one item and one perk

no? we have all the items
1. shield
2. tape
3. glu
4. airstrike
5. bomb (replaced with breacher)
6. block
7. block
8. usb
9. spike (replaced with trap)
10. reflect
11. smoke bomb
12. dyna

**Comment by 3foe** [comment]
hey none of us have had an idea that all of us agree on, and I came up with one on my own:

Regen
Ai have regeneration over time, we could make this a perk because , 
1) takes no time to add since its already in the game
2) we debated giving it to the tank already
3) its not broken ability wise

**Comment by LostKing73** [comment]
"on my own" yeaaa... suuuure....

**Comment by 3foe** [comment]
ye but it could be a perk

**Comment by CelestialKnight7** [comment]
okay so @cs6413110 some stuff left:
- can u make it so every cool down also says the actual time left and not just the cool down bar, (rounded up to the tens place in decimal) if the ability is ready it just wont have a number
- usb nerf by making friendly usbs also die on toolkit so people have to sacrifice their buff for healing

stuff idk if u did yet:
- scavenger buff/fix by making it return time for all non-item abilities
- cool down buff by increasing its effect
- second wind stuff - is it done? balanced? etc?

**Comment by BreadSpammer** [comment]
second wind is done i think. its only a 25% increase so it's not op.

**Comment by CelestialKnight7** [comment]
what did u change about stealth @cs6413110?

**Comment by CelestialKnight7** [comment]
I cant read

**Comment by cs6413110** [comment]
Extra energy to boost

**Comment by CelestialKnight7** [comment]
oki

**Comment by CelestialKnight7** [comment]
![Screenshot 2024-12-03 1 47 31 PM](https://github.com/user-attachments/assets/21d37cf6-da52-40f9-be3b-73071d956579)
beautiful. well done Bois (Aaron)

**Comment by LostKing73** [comment]
Done then? Reopen if not
