### ISSUE TITLE
New Item: Extreme Firepower

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#131]
### The Basics

using this item activates an artillery system on your tank that makes you fire in 3 sidebyside streams and 5x speed for 5 seconds (normal shooting, not shotgun).  However, ur rotation speed is sluggish, and you move as if you are toolkitting. This SOUNDS rly op, until u realize if u just boost out of the way ur good.

### Why add this? 

so I can go brrrrrrrt, and also is prly good against block spammers and flatters

### Might have. . .

functions with whatever firing type is on(so it'll work with shotgun, aka op)
you can't gripple while using
you cant boost while using(warrior boost not included)

### Voting

👍 = Yes
👎 = No (comment y)
😕 = I want ___ out of the **Might have. . .** section (comment)

**Comment by CelestialKnight7** [comment]
make it do its own thing instead of using ur active shooting type, for example it will shoot a volley of (what I imagine to be) autocannon shots that would detonate on impact. and as u said u cant grapple/boost (including warrior boost (it will still give i-frames but u wont gain the speed buff) movement speed will be slowed etc.

**Comment by CelestialKnight7** [comment]
this is 2/4 items needed to expand the roster

**Comment by cs6413110** [comment]
NOO

**Comment by LostKing73** [comment]
> make it do its own thing instead of using ur active shooting type, for example it will shoot a volley of (what I imagine to be) autocannon shots that would detonate on impact. and as u said u cant grapple/boost (including warrior boost (it will still give i-frames but u wont gain the speed buff) movement speed will be slowed etc.

what if it shot 3 continuous beams that did little damamage but hit fast(like 1 dmg, but fires every .2 seconds)

**Comment by CelestialKnight7** [comment]
u still need 2 more good items in order for this or frog nade to be added. also aaron's approval cuz #(whatever issue said no more random stuff being added)

**Comment by CelestialKnight7** [comment]
> > make it do its own thing instead of using ur active shooting type, for example it will shoot a volley of (what I imagine to be) autocannon shots that would detonate on impact. and as u said u cant grapple/boost (including warrior boost (it will still give i-frames but u wont gain the speed buff) movement speed will be slowed etc.
> 
> what if it shot 3 continuous beams that did little damamage but hit fast(like 1 dmg, but fires every .2 seconds)

I was thinking more of the autocannon from drg, u press button and u just spam explosive projectiles for a bit. Although this does seem more like a class ability than an item the more I think about it

**Comment by LostKing73** [comment]
ye thats what i thought to but like we cant add another class ig

**Comment by LostKing73** [comment]
> u still need 2 more good items in order for this or frog nade to be added. also aaron's approval cuz #(whatever issue said no more random stuff being added)

707

**Comment by 3foe** [comment]
I like the item but I need a few things specified
- Is it going to be like a laser or will it be dodgeable
- how slow will the barrel movement be
- this gets OP with Warrior Boost so I don't think it would work with that
- if you can use other items this gets overpowered imagine the item bradley stole from me tire clamp imagine if you could stop a person from moving and then go BBBRRRRRRR
- this does not counter flatting
- *The biggest reason* what Item will be removed for this to work (will we make it so there are 20 item slots instead of 16 or are we removing smoke bomb or smt to add it)

**Comment by 3foe** [comment]
also new name

**Comment by LostKing73** [comment]
I like the item but I need a few things specified

* Is it going to be like a laser or will it be dodgeable

a laser, but u can still dodge by like boosting thru it

* how slow will the barrel movement be

idk how to describe, like if ur toolkit movementspeed was the same as rotation, its slow.

* this gets OP with Warrior Boost so I don't think it would work with that

not that op since u still cant look around

* if you can use other items this gets overpowered imagine the item bradley stole from me tire clamp imagine if you could stop a person from moving and then go BBBRRRRRRR

we're not doing tire clamp, and I'm pretty sure u can gripple out of beartrap

* this does not counter flatting

it does. they run, u can laser them, since it is 3 beams that all go straight, it is hard to NOT hit

* _The biggest reason_ what Item will be removed for this to work (will we make it so there are 20 item slots instead of 16 or are we removing smoke bomb or smt to add it)

none removed, if u actually read evans comments, you would see that this would be a new item, not a replacement

**Comment by BreadSpammer** [comment]
flat shut. no one wants ur opinion or ur pfp on our screens. anyway

step 1: hit a grapple
step 2: use item
step 3: healing item profit

**Comment by LostKing73** [comment]
> flat shut. no one wants ur opinion or ur pfp on our screens. anyway
> 
> step 1: hit a grapple step 2: use item step 3: healing item profit

ye ez

**Comment by cs6413110** [comment]
https://www.codewars.com/kata/51ba717bb08c1cd60f00002f/train/javascript
```javascript
const solution = a => {
  let b = [];
  for (let i = 0; i < a.length; i++) {
    let final = current = a[i];
    let l;
    for (l = i+1; l < a.length; l++) {
      if (current+l-i === a[l]) final = a[l]; else break;
    }
    console.log(current, final, l, i+1)
    if (l-i-1 <= 1) {
      b.push(current); 
      if (current !== final) l--;
    } else {
      b.push(current+'-'+final);
    }
    i = l-1;
  }
  return b.join(',');
}
```

**Comment by cs6413110** [comment]
aaaaaaaaaaaa im so dum wrong issue

**Comment by cs6413110** [comment]
oh well i guess it force killed flat

**Comment by LostKing73** [comment]
ez
