### ISSUE TITLE
New Item: Scramble

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#132]
### The Basics

Shoots a wave-like attack that randomizes the person it hits's shield health. It will also change what type of block the blocks it hits are, and randomize a turrips health.

### Why add this?

another iteeeem

### Voting 

👍 = Yes
👎 = No (comment why)

**Comment by 3foe** [comment]
this can buff your oppondent plus it doesn't even make sense how does scrambling a turrets code give it more or less HP

I think its uses should be different, it should

get rid of shield
stop turrets from shooting
cancel toolkits or any healing (like glue)
make any item on cooldown have a little bit more cooldown
cancel airstrikes
cancel radar for a few seconds
(any other uses)

**Comment by LostKing73** [comment]
aaand spam ew. ok cleaned

**Comment by BreadSpammer** [comment]
seems useless.

**Comment by LostKing73** [comment]
> seems useless.

anti block spam

**Comment by 3foenation** [comment]
people could put someone in block then change to barrior or void block

**Comment by BreadSpammer** [comment]
is there a problem???

**Comment by LostKing73** [comment]
> people could put someone in block then change to barrior or void block

those arent swappable.. you cant change them and things cant be changed into them

**Comment by LostKing73** [comment]
Dum idea
