### ISSUE TITLE
All new Item Ideas

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#135]
jonas couldn't handle my ideas on his issues so new issue :D

**Scrambler (but better)**
Uses:
cancels airstrikes
gets rid of sheilds
stops turrets from shooting
stops healing like toolkits and glue
if an item is on CD it adds like 10-15 secs to the CD time

**why add**
it has multiple uses and stops mid fight kitting

**Chain Bomb**
it is like a throwable chain saw it deals tick damage to everything around it and slows tanks because their tires are slashed

**Why add**
it doesn't buff tactile because its tick damage
it stops flatting
it counters turret campers
its a combo of 3 unused items spike bomb and arstrike since it has the best of all 3 it may be used

**Coolant**

increases firerate by 50% but decreases later by 25%

**Why Add**
helps you hit runners
adds an item that can be used for close range
promotes using skill instead of one shots

**Comment by 3foe** [comment]
Vote here for scrambler

**Comment by 3foe** [comment]
vote here for chain bomb

**Comment by 3foe** [comment]
vote here for coolant

**Comment by LostKing73** [comment]
vote nhere for no

**Comment by 3foe** [comment]
Thats hate please stop

**Comment by LostKing73** [comment]
we dont nned ur spam(its bad+not needed+fueled by jealousy+no one asked+ratio'd+this is what I'm working on rn so we don't need u to remake my spam into smth wors)

**Comment by 3foe** [comment]
Thats hate please stop

**Comment by 3foe** [comment]
I think that my ideas are better, therefore they have the right to be voted on, just like yours, I could go on your issues copy paste what you said and be done and close it but I don't please show me the same respect that I am showing you. this is not "jealousy" I simply belive that these ideas are better.

**Comment by LostKing73** [comment]
i think that noone cares(correct)

**Comment by 3foe** [comment]
dude chill its not that deep

**Comment by LostKing73** [comment]
s-s-shuttttttt

**Comment by 3foe** [comment]
thats what I am telling you to do, nobody asked you to come to my issue just to close it and change the purpose

**Comment by 3foe** [comment]
you literally need idea to get extrme fire power nad frag bomb to be added don't try to shoot any down

**Comment by LostKing73** [comment]
s-s-s-spammmmmmmm

**Comment by 3foe** [comment]
you. yourself. called you ideas " ez spam quality" so don't call my issues spam when you ideas are spam

**Comment by 3foe** [comment]
jonas I will do the same you your issues as you do here

**Comment by LostKing73** [comment]
instead of being actually helpful, u threaten to destroy. k. yea no we totally want u to be admin. sure.

**Comment by BreadSpammer** [comment]
all of the ideas are bad anyway so like who cares

**Comment by LostKing73** [comment]
ez
