### ISSUE TITLE
New Item: Fuse

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#136]
### The Basics

Shoots a thingy that sticks to an enemy, any damage you take, they take, and any they take, you take.

### Why add this?

itemmmmm also haaaaalp

### Voting

👍 Yes
👎 No (comment y)

**Comment by BreadSpammer** [comment]
this would just devolve into either a useless item, or a super annoying item that makes u always win

**Comment by LostKing73** [comment]
its like an op reflect that can hit from anywhere, bcuz if  u take damage to someone else, the person u stuck the thing in takes damage from that too. could be nerfed by they get ur healing too

**Comment by BreadSpammer** [comment]
k so basically, u fite until u drained them of their shield and atleast some of their HP, then u medic and use the item, and then u win

**Comment by LostKing73** [comment]
skill issue
