### ISSUE TITLE
new item: scan

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#137]
**the basics**

scans your screen by turning it green and dark(image attached) which can see stelths, but like now ur vision is green while u can see them

**why add this**

anti-stelth, and if yall can come up with another thing it could do that'd be great thx

**voting**

👍 yes
👎 no (comment y)

**image**
![image](https://github.com/user-attachments/assets/8829321e-a25a-4910-a724-540ae65ef09f)

**Comment by BreadSpammer** [comment]
is like super hyper specific, and useless. even if it was good for stealths, just use usb which also increases damage?

**Comment by LostKing73** [comment]
> is like super hyper specific, and useless. even if it was good for stealths, just use usb which also increases damage?

I'm asking for yall to help by giving it more things, idk it could be cool, calm down

**Comment by BreadSpammer** [comment]
nah bad idea

**Comment by LostKing73** [comment]
bruh. then improve it.

**Comment by 3foe** [comment]
when I improve ur ideas you hate on them

**Comment by LostKing73** [comment]
womp

**Comment by LostKing73** [comment]
oh ok then
