### ISSUE TITLE
New Item: Hydraulics 

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#138]
### The Basics

This item will make you "lift" everything in a 3x3 area and throw it, dealing damage to whaetver/whoever is thrown and whatever/whoever is hit. you cant shoot while lifting/holding. you press the item, which lifts, and press again to hold. you have 70% movement speed while holding, and cant boost

### Why add this?

iteeeeeeeem also like cool ig and anti flat, if u pick them up u can throw them into a corner/at teammates or even just throw blocks at them

### Voting

👍 yes
👎 no (comment why)

**Comment by BreadSpammer** [comment]
#707

**Comment by LostKing73** [comment]
bro we need more items dum

**Comment by LostKing73** [comment]
evan literally is saying we need more items so I'm spamming

**Comment by BreadSpammer** [comment]
ye but this is too much effort

**Comment by LostKing73** [comment]
skill issue

**Comment by BreadSpammer** [comment]
where is my @cs6413110 to clear out these issues

**Comment by LostKing73** [comment]
womp

**Comment by BreadSpammer** [comment]
ye lk, this idea is kinda cringe. would take too much effort to code and wouldn't be fun to use after all the blocks die

**Comment by LostKing73** [comment]
> ye lk, this idea is kinda cringe. would take too much effort to code and wouldn't be fun to use after all the blocks die

👍 ur opinion is actually valid so. . . ok
