### ISSUE TITLE
like halp

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#139]
![image](https://github.com/user-attachments/assets/33886605-3bad-427e-891b-ddd0ae8ec31f)

like, stop coltin from doing this, and ig remove his admin while ur at it cuz boom abuse proof wow
![image](https://github.com/user-attachments/assets/012999f4-b5c4-4f2d-9fc7-278f68ed341f)

**Comment by LostKing73** [comment]
@cs6413110 @BreadSpammer @CelestialKnight7 @DarkMemeGod411

**Comment by 3foe** [comment]
nah

**Comment by 3foe** [comment]
ive seen worse from literally everybody here

**Comment by LostKing73** [comment]
off topic.

**Comment by 3foe** [comment]
Who died and made you god? that's literally not the topic it is the topic if it's off-topic then we are not talking about removing his admin in that case the new topic is Bananas

**Comment by 3foe** [comment]
🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌

**Comment by 3foe** [comment]
> 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌 🍌

**Comment by LostKing73** [comment]
bro.

**Comment by 3foe** [comment]
thts what i am trying to say, you said admin abuse is off topic. its not. at all.

I have seen literally every person here spawn armadas of ai to crate farm how is using / live on another person not even yourself a crime compared to that?

**Comment by 3foe** [comment]
k time to actually address you concerns, besides a few messages convince me why Lighttrap shouldn't have VIP

**Comment by 3foenation** [comment]
that was not spam people deserve things you know and that waw from like a YEAR ago so you out of date

**Comment by 3foenation** [comment]
yes i agree

**Comment by 3foenation** [comment]
was*

**Comment by 3foe** [comment]
second besides some chat SS tell me why coltin shouldn't have admin

**Comment by 3foe** [comment]
dude just edit your comment if you have a typo

**Comment by 3foe** [comment]
1 nah
2 100% shouldent be on
3 ye but were not talking bout tony
4 what did lightrap do to deserve this?
5 what did coltin do to deserve this

**Comment by 3foenation** [comment]
sure he says things but i  can understand because jonas keeps on bullying him so he is mad and he keeps on getting banned and muted I can understand the mute but not the ban and not the bullying

**Comment by 3foenation** [comment]
also why do we never listen to my comments.

**Comment by 3foenation** [comment]
so do we agree that some people bully me and my friends and even matthew

**Comment by 3foe** [comment]
I talked to tony about him needing to be respectful to jonas, however, he does deserve something. I will stay out of whatever punishment that goes on tony as long as it is reasonable.

**Comment by 3foe** [comment]
> so do we agree that some people bully me and my friends and even matthew

ye but it doesn't matter

**Comment by 3foe** [comment]
jonas is the problem rn we need to talk about him

**Comment by 3foe** [comment]
Jonas this is directed for you.

I have told Tony to chill on you, you can punish him as long as it is reasonable, however, it is your job as a moderator to try to promote the game's public image, and I find that you have failed in that job. When you bad mouth other people you make yourself look bad and as a public representative of the game when you bad mouth anyone let alone another representative you make the game look bad. Please start doing your job and promote the game instead of hurting it, please stop shooting down me and my brother and his friends simply because it is us, start contributing beyond making "ez spam quality" ideas and alienating our only players against you and shooting down ideas that don't belong to you

**Comment by LostKing73** [comment]
spam bye

**Comment by LostKing73** [comment]
also mathew you literally have no power. don't act like just cuz u blackmailed aaron u get to be in charge of me

**Comment by 3foenation** [comment]
you just tried to get out of it again good job for showing that you cant own up to your mistakes.

**Comment by LostKing73** [comment]
ope more spam

**Comment by 3foenation** [comment]
when i make a good point you say an dark as spam everything I say is "invalid"

**Comment by 3foenation** [comment]
see

**Comment by 3foenation** [comment]
who edidted that

**Comment by 3foenation** [comment]
its supposed to say insead of an  DMG and mark or say as spam

**Comment by BreadSpammer** [comment]
ok so like for 3foenation's admin, the only reason he had it is bc to monitor the sevies, but like now he's helping them apparently, and also sevies don't play at gpa anymore so we can do his job now, so like ded

**Comment by 3foenation** [comment]
i need to even out the abuse on the GPA players because they are abused and I either unban or unmute them so they will CONTINUE playing not stop because someone is bullying them.

**Comment by 3foenation** [comment]
i noticed that everything that matthew said and most of what I said was marked as spam we DO NOT GET HEARD this is a problem everyone should be able to contribute.

**Comment by DarkMemeGod411** [comment]
> coltin, I editd your comment, you see DarkMemeGod hates being called dark which you accidentally did in that comment so I made it say DMG instead

thank you mattew. someone understands that

**Comment by 3foe** [comment]
your welcome

**Comment by 3foe** [comment]
Coltin there is no punishment system besides what Aaron says goes. Aaron is not intervening meaning he does not care or wont take a side, do not rise to their deliberate provocation on an unimportant issue. There is no need to defend yourself as there is no real attack, the only thing they can do is state their opinion which is invalid because it is deliberately biased

**Comment by 3foe** [comment]
> also mathew you literally have no power. don't act like just cuz u blackmailed aaron u get to be in charge of me

Jonas I think you and I know this is not true for one I did not blackmail Aaron in any way. second I do have more power here and if showing you where your place is will get you to shut up so be it, tread lightly jonas you are on thin ice.

**Comment by 3foenation** [comment]
i dont think i said dark or even tried to mention dmg but good to know

**Comment by 3foenation** [comment]
oh i mispelled sorry on accedent i realize that now it was a mistake sorry DMG

**Comment by DarkMemeGod411** [comment]
> oh i mispelled sorry on accedent i realize that now it was a mistake sorry DMG

ur good

**Comment by BreadSpammer** [comment]
ew why did I look at this issue again

**Comment by LostKing73** [comment]
> Jonas I think you and I know this is not true for one I did not blackmail Aaron in any way. second I do have more power here and if showing you where your place is will get you to shut up so be it, tread lightly jonas you are on thin ice.

then what do you call threatening to kill game if aaron doesn't give you admin/code access?

**Comment by LostKing73** [comment]
its kinda funny how personal mathew takes it when I say that this other person has VIP when they shouldnt

**Comment by LostKing73** [comment]
not that i care, but more coltin abuse
![image](https://github.com/user-attachments/assets/6be2de9b-8bfe-4d18-8c27-32558ac6b4f2)
and the logs version:
![image](https://github.com/user-attachments/assets/c6211ffd-7a3a-4cc1-8c7e-6004e7ff4c93)

**Comment by LostKing73** [comment]
> when i make a good point you say and mark as spam everything I say is "invalid"

btw, I assume he meant "and mark as spam" not "an DMG as spam"

**Comment by LostKing73** [comment]
> i need to even out the abuse on the GPA players because they are abused and I either unban or unmute them so they will CONTINUE playing not stop because someone is bullying them.

there is a hard line between **moderating** and **bullying** I am not at fault if someone says the n word and calls me mean bcuz I mute them. you unmuting them IS a problem, however, bcuz nobody is going to learn their lesson. all they will learn is to ask you to unmute them, bcuz u lack the common sense to ask another admin why they are muted.

**Comment by 3foe** [comment]
> its kinda funny how personal mathew takes it when I say that this other person has VIP when they shouldnt

personal? um this isn't personal for me this is professional, you are hurting the game and now I have to make you stop wouldn't you be annoyed if you had to baby sit one of your co-workers, in fact I am doing more than baby sit you I have to hold you by the hand and tell you right from wrong now.

**Comment by LostKing73** [comment]
this isnt like, ur game tho? no one wants u here, ur holding ur "boss" at gun point and saying "I'm helping"

**Comment by 3foe** [comment]
> > i need to even out the abuse on the GPA players because they are abused and I either unban or unmute them so they will CONTINUE playing not stop because someone is bullying them.
> 
> there is a hard line between **moderating** and **bullying** I am not at fault if someone says the n word and calls me mean bcuz I mute them. you unmuting them IS a problem, however, bcuz nobody is going to learn their lesson. all they will learn is to ask you to unmute them, bcuz u lack the common sense to ask another admin why they are muted.

If someone calls you mean its for a reason, it could be that even a sevie can see that you are mean. let me address the situation, you called me flat. again. like how many times is this? and tony once again said he that's mean and you muted him because he called you mean. he had a fair reason to call you mean because you were being mean and you muted him for it. Moderating is to preside over or to make a situation less extreme when you cause the situation you need to be muted not someone who comments on it in an attempt to stop the situation from happening again.

**Comment by DarkMemeGod411** [comment]
![Screenshot 2024-11-05 11 34 15 AM](https://github.com/user-attachments/assets/0762cde9-b87c-4693-a66f-fd56fcb7b405)

**Comment by DarkMemeGod411** [comment]
![Screenshot 2024-11-05 10 40 31 AM](https://github.com/user-attachments/assets/ecbda16f-fbce-4400-a76c-fbc24e2a0d5e)

**Comment by 3foe** [comment]
DMG did I not say that tony deserves some punishment for what he said?

I am not saying tony is right to insult LostKing I am saying jonas is wrong to insult tony

**Comment by DarkMemeGod411** [comment]
i am worried abt this. i don't want this to end with anyone getting in trouble. (it happened before). this will not end well. Lets get real, real going for a change. 
Tony deserves some punishment for constant swearing. 
coltin deserves the power he has. 
Aaron is the main coder so he owns game (technically bc it's his work)
Lostking has not been harmful to game, he helps more than he hurts
as far as lighttrap goes, idc if he has vip, (probably not) 
Bread has not been harmful. (he helps game a lot)
Celestial has not been harmful. (he helps game ALOT)
I have not been harmful. (i help game, (very little) )
In my opinion, This issue has harmful comments from both sides. idc what we do, But no one will be harmed from this. and in my opinion, no one deserves to get in any form of trouble.

**Comment by 3foe** [comment]
you started out good but I dont think that bread or Celestial are very beneficial besides ideas which we have too many of and jonas just does art whish is what you do DMG I think that you help the game more that anyone but aaron that includes me

**Comment by 3foe** [comment]
we need something to hold people accountable to their actions some form of punishment system

**Comment by DarkMemeGod411** [comment]
i do not help the game as much as Celestial or bread. i have more commits than lk. but that doesnt prove much

**Comment by LostKing73** [comment]
lol im not even gonna try. ur wrong, I'm right, end of story. idc man. like, just don't spam meaningless stuff, and stop acting like u deserve admin/code acess

**Comment by DarkMemeGod411** [comment]
who do u mean by that?

**Comment by LostKing73** [comment]
ur not the problem alex. so not u.

**Comment by 3foe** [comment]
bruh ima copy and paste what you said but this time it will be true

**Comment by 3foe** [comment]
lol im not even gonna try. ur wrong, I'm right, end of story. idc man. like, just don't spam meaningless stuff, and stop acting like u deserve admin/code access

**Comment by LostKing73** [comment]
wait until he reads the third sentance. its gonna be so funny guys

**Comment by 3foenation** [comment]
> > i need to even out the abuse on the GPA players because they are abused and I either unban or unmute them so they will CONTINUE playing not stop because someone is bullying them.
> 
> there is a hard line between **moderating** and **bullying** I am not at fault if someone says the n word and calls me mean bcuz I mute them. you unmuting them IS a problem, however, bcuz nobody is going to learn their lesson. all they will learn is to ask you to unmute them, bcuz u lack the common sense to ask another admin why they are muted.

i ask them why they are muted they ALWAYS say its because of you and that's all I need to unmute

**Comment by LostKing73** [comment]
bcuz when they swear or make death threats, i do my job and **mute them**

**Comment by 3foe** [comment]
If they think you are mean ofc they are going to be mean back do you job and be nice to them and moderate them

**Comment by LostKing73** [comment]
wow such good english

**Comment by 3foe** [comment]
want to know something else that's good, the point I made.

**Comment by LostKing73** [comment]
i dnt think bro understands sarcasm

**Comment by 3foe** [comment]
I dont think you understand taking a hint

**Comment by LostKing73** [comment]
> I dont think you understand taking a hint

id don't think bro understand that idc
