### ISSUE TITLE
[VOTE] boom boom/not die perk update

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#140]
changes: 
- explode timer increased from 0.5 to 1 second
- you don't die until u explode, so u can change where u detonate (creeper style)

pros:
- more fun combos instead of just getting lucky (grappling ppl, popping their shields before death, faking ppl out with the not die perk, etc)
- easier kills on ppl who were far away when u died

cons:
- more reaction time to live for gud players

stuff for both perks: (not voted on)
- adding exploding animation for before u detonate to make gameplay more clear
- adding animation for not dying with the not die perk to make gameplay more clear

for exploding changes
👍 = ye add
👎 = ew no

**Comment by 3foenation** [comment]
what do you mean by, you don't die until u explode, so u can change where u detonate (creeper style)

**Comment by BreadSpammer** [comment]
creeper from Minecraft :)

**Comment by 3foe** [comment]
I think that the perk needs a massive nerf 

increase the time it takes to explode to 3 secs and add a red gradient on the tank that shows when it will blow up

**Comment by BreadSpammer** [comment]
@3foe this is the nerf. that makes it so u can react to them exploding and can boost/reflect i frame the explosion, or grapple out. this also gives the person who's exploding, more of a skill ceiling while using the perk. instead of just hoping to get lucky, they can influence their success :) im adding this now...

**Comment by 3foe** [comment]
just remove it...

**Comment by LostKing73** [comment]
> just remove it...

just dont skill issue. . ?

**Comment by LostKing73** [comment]
mind changed, just revert

**Comment by LostKing73** [comment]
> adding animation for not dying with the not die perk to make gameplay more clear

make it a totem pop

**Comment by 3foe** [comment]
yes

**Comment by 3foe** [comment]
![image](https://github.com/user-attachments/assets/9a59c5de-eef1-47bc-9d1f-febe684e20a7)

**Comment by 3foe** [comment]
its a png and gif, so we can put it over a tank

**Comment by LostKing73** [comment]
bruh we will never be dmca'd by mc, we gain no profits from this game, so we cant be copywrited. also like its a waste of time for them

**Comment by 3foe** [comment]
exactly

**Comment by DarkMemeGod411** [comment]
Copywrite is not a problem unless it's disney. they sued a mother bc her 4 year old died, and they put the mickey ears on the tombstone

**Comment by LostKing73** [comment]
aaand its not disney so were good

**Comment by 3foe** [comment]
fair enough ig

**Comment by LostKing73** [comment]
> but like still its kinda cringe for a perk to be mc related. its fine with like cosmetics and death effects bc those r just references, but having it be an actual thing in game, that's too far

deepfry the gif, you wont be able to tell

**Comment by BreadSpammer** [comment]
VOTE @cs6413110 @CelestialKnight7 @DarkMemeGod411 @BreadSpammer @LostKing73

murder the explode perk bc takes negative skill to use, is just luck based, and is annoying to fite
👍 = kill
👎 = save

**Comment by LostKing73** [comment]
Nuke tank go bye bye is good, now like close cuz gambling is fine?

**Comment by BreadSpammer** [comment]
gambling animation 🔫

**Comment by LostKing73** [comment]
Like ok ig

**Comment by CelestialKnight7** [comment]
> bruh we will never be dmca'd by mc, we gain no profits from this game, so we cant be copywrited. also like its a waste of time for them

that doesn't mean we should add it, we should add something unique to our game that actually fits rather than copying an idea

**Comment by LostKing73** [comment]
but no animation?
