### ISSUE TITLE
New Item: Transmuter

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#142]
### The Basics

Shoots a wave attack that transforms fire and blocks into blocks and stronger blocks respectively. If you hit a gold block with this, it explodes. this is great against fire and FOR fire. 

### Why add this?

good for/against fire

### Voting

👍 yes
👎 no (comment why)

**Comment by 3foe** [comment]
how does this make sense? also we want global items, not class-specific items, this literally would never be used by a non-fire user.

**Comment by BreadSpammer** [comment]
I don't get it. bad item lol

**Comment by LostKing73** [comment]
use on blocks to make them better. white block on turip > gold block on turip

**Comment by 3foe** [comment]
so nobody wants it then. nobody.

**Comment by 3foe** [comment]
> I don't get it. bad item lol

this good enough?

**Comment by BreadSpammer** [comment]
just use weak block if u care that much? or just let ur turret have 500 HP and just run a healing item so u don't die

**Comment by LostKing73** [comment]
if bread closes this ill not reopen

**Comment by BreadSpammer** [comment]
bad item

**Comment by LostKing73** [comment]
ok
