### ISSUE TITLE
[NEW ITEM] [VOTE] Name Pending

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#145]
### The Basics

Shoots out a short beam that changes whoever it hit's zone texture for 30 seconds. if we decide to add the beast from the deep, it will appear for the person who gets hit by this and can only attack them.

### Why add this?

Would be a great confusion item(just have to make sure it loads quick enough so u can actually see instead of everything bein invis while its loading) and would be really funny to see someone running away from a non existant giant creature

### Voting

👍 yes
👎 no(comment why)

**Comment by REXYTrex** [comment]
think it would be cool but should add a bar or smthn that charges up so you can dodge it and the person using it cant move while charging so it is fair and not op.

**Comment by LostKing73** [comment]
aint no way another gpa is on the github

**Comment by LostKing73** [comment]
> how about we add zones first

how about you stop stating the obvious and wasting everyones time

**Comment by BreadSpammer** [comment]
like it's just a useless item???? no damage. its almost like smoke bomb except smoke actually does something

**Comment by DarkMemeGod411** [comment]
why is there a gpa on the github? anyway, it feels like a confusing item.

**Comment by LostKing73** [comment]
AY DONT CLOSE

**Comment by LostKing73** [comment]
> like it's just a useless item???? no damage. its almost like smoke bomb except smoke actually does something

its pretty much a gambling smoke bomb. it could be rly good bcuz the leviathanis unkillable, but if they just go from cave to ice its like a flashbang lol. ig it doesn't rely work cuz loading between zones takes a bit, but still, it could be cool if we fix that

**Comment by 3foenation** [comment]
that no gpa he got ont recently and he at estmark also y it smoke bomb but no damage

**Comment by BreadSpammer** [comment]
we do not need more gambling. for example: imagine if every character in smash had a move like game n watches judge. it would be so cringe to play bc less skill

**Comment by 3foe** [comment]
PTSD triggered. **remembers that match when I got 9ed 3 times**

**Comment by DarkMemeGod411** [comment]
i remember when i hit 9 sleeps in a squad strike without missing as jigglypuff

**Comment by LostKing73** [comment]
> we do not need more gambling. for example: imagine if every character in smash had a move like game n watches judge. it would be so cringe to play bc less skill

2 is not everything

**Comment by LostKing73** [comment]
> PTSD triggered. **remembers that match when I got 9ed 3 times**

skill issue

**Comment by LostKing73** [comment]
listen. imma close not bcuz the GAMBLING is the bad part, but bcuz if u get hit, ur going to get lagged for like 5 seconds bcuz of how the zones load. this isnt a bad idea, but wouldnt rly work bcuz of that.
