### ISSUE TITLE
Removal of Nuke Tank

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#146]
ondeath(t, m={}) {
    let core = Engine.hasPerk(t.perk, 7), x = t.x-99, y = t.y-99;
    if (core) setTimeout(() => A.template('Damage').init(x, y, 298, 298, [0, 100, 300, 500][core], t.team, this), 500);
    this.logs.push({m: this.deathMsg(t.username, m.username), c: (m.username === undefined ? '#FF8C00': (Engine.getTeam(m.team) === 'RED' ? '#FF0000' : (Engine.getTeam(m.team) === 'BLUE' ? '#0000FF' : '#FF8C00')))});
    for (let i = this.ai.length-1; i >= 0; i--) if (Engine.getUsername(this.ai[i].team) === t.username) this.ai[i].destroy();
    if (t.socket) t.ded = true;
    if (m.socket) m.socket.send({event: 'kill'});
    if (m.deathEffect) t.dedEffect = {x: t.x, y: t.y, r: t.r, id: m.deathEffect, start: Date.now(), time: 0};
  }

**Comment by 3foe** [comment]
I already removed it in my last commit if we want it back just revert it or copy paste the code back in

**Comment by 3foe** [comment]
thumbs up to keep it this way thumbs down to change back

**Comment by BreadSpammer** [comment]
flat ur dumb. u removed the entire code for death XD

**Comment by 3foe** [comment]
I noticed
XIFING
