### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#147]
![Screenshot 2024-11-07 10 16 06 AM](https://github.com/user-attachments/assets/693f58ca-6550-419f-a839-7a111bb7ce81)
game need fixing I think it bcuz of auto login

**Comment by 3foenation** [comment]
UUUUUUUMMMMMMM
[Uploading Screen recording 2024-11-07 10.22.40 AM.webm…]()
look at the hotbar

**Comment by 3foenation** [comment]
[Uploading Screen recording 2024-11-07 10.22.40 AM.webm…]()

**Comment by 3foe** [comment]
feature

**Comment by 3foenation** [comment]
yea

**Comment by LostKing73** [comment]
bro has no patience to wait untill they finish uploading ez

**Comment by BreadSpammer** [comment]
wasn't me trust :)

**Comment by LostKing73** [comment]
> no i think it wants us to login and it put it there and wdym it is done

no ur images
