### ISSUE TITLE
JONAS look

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#148]

**Comment by 3foenation** [comment]
![Screenshot 2024-11-07 3 56 53 PM](https://github.com/user-attachments/assets/2dfcdfc4-016a-4e60-8115-0bb62df35c26)

**Comment by LostKing73** [comment]
what is that

**Comment by 3foenation** [comment]
aggred you said you wanted to see it

**Comment by LostKing73** [comment]
dum

**Comment by BreadSpammer** [comment]
????
