### ISSUE TITLE
AI update

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#149]
There are a few issues with AI here are the bugs and features that need to be addressed

- AI always spawns on at 1 1 1 no matter what you put in for the cords

- it is hard to what coords there are exactly we should make the command have the ability to spawn at player spawn, at the admin using the command, or be able to spawn them on a player

- /ai is hard to use bc it requires 6 numbers there should be a command like a guider where it has a background of x coord, y coord z coord, etc for every command

**Comment by LostKing73** [comment]
1. this is just a 3foe dum moment
2. remove /ai? its only for admin abuse now @cs6413110

**Comment by BreadSpammer** [comment]
so like first of all, there is already #107 for ai issues... and second. 2/3 of ur "issues" aren't really issues. the imbiguity helps stop admin abusers, and ai cords work normally. although I do think you should be able to put squiglies in the ai spawn command to make the coords base off of your position

**Comment by LostKing73** [comment]
k like u gonna read breads comment or what

**Comment by LostKing73** [comment]
bro how dum are you on a scale of 10 to 10 (10 being brain dead lobotomy style)

**Comment by LostKing73** [comment]
you literally can just spa on 107, stop reopening this there's already an issue

**Comment by LostKing73** [comment]
ez lol, dum realized
