### ISSUE TITLE
warrior

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#15]
either cancel boost when u hit something or u can only boost in 1 direction and can't turn mid boost

**Comment by LostKing73** [comment]
neither cuz already nerfed.

also, FIRST CLOSE BAM

**Comment by CelestialKnight7** [comment]
THE POINT OF THIS IS TO UNNERF IT CUZ THE NERF IS CRING AND KILLS THE CLASS CUZ AARON JUST SAID LIKE YE 1 FRAME OF BOOST. SO
step 1: unnerf set back to normal
step 2: actually use good idea to nerf it without killing it
step 3: gud game

**Comment by BreadSpam** [comment]
cant be saved from the fix

**Comment by LostKing73** [comment]
bruhhhhhhhh

**Comment by LostKing73** [comment]
its not 1 frame anymore. its the length of a normal boost, which is fine. yall don't even play it. i use it, and it doesn't feel op or weak

**Comment by CelestialKnight7** [comment]
Bro what are you talking about I play warrior all the time and the only reason I'm not recently is cuz the inventory is non-existent.

**Comment by LostKing73** [comment]
bruh. its not like u keep sayin it is. and these "buffs" are just nerfs

**Comment by CelestialKnight7** [comment]
that's cuz these are nerfs for the original warrior not current warrior omg I've said this like 70 times

**Comment by LostKing73** [comment]
bruh what? ur nerfing smth' that isnt a problem/doesnt exist. it was already nerfed.

**Comment by CelestialKnight7** [comment]
O. M. G.
I LITERALLY SAID IT 5 TIMES IN THIS ISSUE ALONE
the. current. nerf. is. not. well. done.
we will haveee to unnerf it to its previous state
so that we can nerf it properly because the current nerf sucks

that means we will not be nerfing warrior currently we will be nerfing the old warrior by going back


AND STOP CLOSING THE FUCKIGN ISSUE

**Comment by LostKing73** [comment]
why is this a bad nerf? what is wrong with how it works rn?

**Comment by CelestialKnight7** [comment]
it could show u/test it if the inventory worked, but it feels underwhelming, with the limited time in warrior boost it means "you cant hit as easily" (but this doesn't affect the actual hit rate anyways, its still as easy to hit you just have be closer which isn't a problem in shotgun fights) but the lack of time in warrior boost also nerfs the mobility of it. besides I would rather have a mechanics type nerf as mentioned above rather than a nerf that just changes some numbers. Besides the current nerf doesn't solve the core problem of warrior anyways which is a free hit for 100 damage as that can still be done easily.

**Comment by LostKing73** [comment]
its u and breads job to make the map and then the area/menu for it. so if u want it done, do it

**Comment by LostKing73** [comment]
aaron told me to have yall do it.

**Comment by LostKing73** [comment]
all u need to do is make the map cuz u are good with that(cuz drg) bread is bein lazy/cant do anything untill u make the map. unless we use my map, we are all waiting on u

**Comment by CelestialKnight7** [comment]
my point still stands that you started this and then abandoned it for other people to actually do the work.
anyways level editor paste-ing doesn't work

**Comment by LostKing73** [comment]
i didnt "abandon" it. im still inputting my ideas. its just whenever I try to do work, yall immediately shut it down, so I'm letting u try and ur slacking.

**Comment by LostKing73** [comment]
also @cs6413110 fix that

**Comment by LostKing73** [comment]
also also, @CelestialKnight7 get on tonks, and ill show u the boost

**Comment by 3foe** [comment]
bro... I took half health damage from one boost warrior ---> nerf

**Comment by LostKing73** [comment]
no, u got hit by my shotgun and power bullet as well. warrior only does 100 damage.

**Comment by LostKing73** [comment]
k, closing cuz evan dumb moment

**Comment by 3foe** [comment]
Nerf/ Rework ideas 

Life steal tank?
have the boost become one frame but still do 100 dmg (basically a melee attack)
make the boost deal no dmg
make the boost's direction be unchangable

**Comment by 3foe** [comment]
everyone should vote for it to be closed plus evan is in charge of this not u

**Comment by LostKing73** [comment]
bruhh dude we dont want life steal, and evan is not realizing that its already nerfed, and I main warrior and its good enough to fight people, so its fine.

**Comment by LostKing73** [comment]
all of these nerfs make it way worse

**Comment by 3foe** [comment]
I think it's good enough to fight people, but that's not the problem; it's TOO good. You get double the hit chance of tactile, you get I frames with it, and you can catch up to runners. It's tactile on steroids.

**Comment by LostKing73** [comment]
let this isue dieeeeeee

**Comment by LostKing73** [comment]
mathew. it is not too good. it has the length of a boost, and deals 100 damage. it is exactly where it should be. i would even say its a bit weak, but I loved the super warrior boost so whatever

**Comment by LostKing73** [comment]
the i frames are for barely any time to matter. if you gripple insta its like 100% hit rate, and I can easily miss I frames

**Comment by 3foe** [comment]
so you point out its one singular weakness, grapple (I wouldn't count it as a counter). It is weak because of that, look at tactile, shield reflect healing items medic.  For the iframe issue you have 2 boosts which means you have 1 sec of iframes where you can be untouchable and do 2 shotguns, with reflect that's 1.5 secs of I frames and you can deal 3 shotguns and a reflected shotgun meaning 400 damage.

definite nerf

**Comment by CelestialKnight7** [comment]
> Nerf/ Rework ideas
> 
> Life steal tank? have the boost become one frame but still do 100 dmg (basically a melee attack) make the boost deal no dmg make the boost's direction be unchangable

thats a complete new class not even a rework, a rework would be when we made the boost the f ability

**Comment by CelestialKnight7** [comment]
> bruhh dude we dont want life steal, and evan is not realizing that its already nerfed, and I main warrior and its good enough to fight people, so its fine.

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

**Comment by CelestialKnight7** [comment]
also im just gonna delete any 3foe comments to save brain cells

**Comment by LostKing73** [comment]
thx

**Comment by LostKing73** [comment]
> > bruhh dude we dont want life steal, and evan is not realizing that its already nerfed, and I main warrior and its good enough to fight people, so its fine.
> 
> i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

lol ez, idk why it would need a nerf tho since its already nerfed.

**Comment by CelestialKnight7** [comment]
![image](https://github.com/user-attachments/assets/e9c42bda-a0df-48f6-b8c5-069dd5f2bc5f)
pov a warrior just used their f ability

**Comment by CelestialKnight7** [comment]
also rip image resolution

**Comment by LostKing73** [comment]
literally i play it every day, and it isn't too op, or not op enough. personally, I wish I could still boost thru blocks, but like I get why that's not added back. it doesn't need to be unnerfed, then re-nerfed.

**Comment by LostKing73** [comment]
ajkghbkajwfbganfkj flat stop

**Comment by CelestialKnight7** [comment]
> i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

just leab lone

**Comment by LostKing73** [comment]
yall, why leab lone? it doesnt need to be changed, so why have an issue abt it?

**Comment by CelestialKnight7** [comment]
i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

i want to leave this open until i cant test warrior for myself anyways, also i got kicked out of doing stuff for lobby xd

**Comment by LostKing73** [comment]
o ok then

**Comment by LostKing73** [comment]
...now?

**Comment by CelestialKnight7** [comment]
nah lazy ill do at lunch or somethin

**Comment by LostKing73** [comment]
k...

**Comment by CelestialKnight7** [comment]
k

**Comment by LostKing73** [comment]
finally thank you

**Comment by CelestialKnight7** [comment]
actually...

**Comment by CelestialKnight7** [comment]
hehe

**Comment by LostKing73** [comment]
you little
