### ISSUE TITLE
Punishment

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#150]
Aaron, you told me to stop the war with LK when I told you I wanted him to be blocked from GitHub. I did that. He has started another war, openly in front of the GPAs he declared war on me. I intend to first have my full auth back just as per our deal I didn't ask for it back when it was glitched because LK would only accuse me of admin abuse, second I would like LK's main to be permanently muted, I did not ask for this permission but I believe you would take it rather than having him banned. and third, removed from the GitHub, we will have this conversation in person later but I would like you to know this is coming. I made peace with him and tried to avoid a war but I am done putting up with his perpetual antagonizing, I hope you recognize that I tried to avoid a war but he has crossed a line and if I do not stand up to him now we may have issues later, I hope in time we can slowly give his privileges back but he has broken my trust and then he denied my mercy.

Aaron if you have an issue with anything I said here please talk to me in person at home, and I can elaborate. LK because I know you will close the issue, making this issue only gives Aaron time to be your attorney before I execute what I said I would do.

**Comment by LostKing73** [comment]
@BreadSpammer @CelestialKnight7 @cs6413110

**Comment by LostKing73** [comment]
> I'll talk to Aaron about it to see if we can just end this man but like no promises

pls bcuz like he is so selfish and egotistic(like more than alex and that's saying smth)

**Comment by DarkMemeGod411** [comment]
> > I'll talk to Aaron about it to see if we can just end this man but like no promises
> 
> pls bcuz like he is so selfish and egotistic(like more than alex and that's saying smth)

is that a compliment or an insult to me, lol

**Comment by LostKing73** [comment]
vote btw alex

**Comment by LostKing73** [comment]
oooh look the (not so) big baddie is here.

**Comment by BreadSpammer** [comment]
vote doesn't really matter. everyone wants flat gone. its just the act of making sure he cant destroy servers after the fact

**Comment by DarkMemeGod411** [comment]
I don't want to be involved in this.

**Comment by LostKing73** [comment]
lol, u think ur our boss just bcuz u blackmailed aaron?

**Comment by DarkMemeGod411** [comment]
what does he mean by "after tomorrow he will be removed"?

**Comment by LostKing73** [comment]
> what does he mean by "after tomorrow he will be removed"?

he's making empty threats to scare us

**Comment by 3foe** [comment]
> what does he mean by "after tomorrow he will be removed"?

for one Alex you are involved you voted, if you wish to stay neutral do nothing voting is something, second I hold the power to block people from GitHub, I haven't used that privilege until now when Aaron and I talk about the extent of what lk has done, he will have lost admin, speaking privileges, and GitHub privileges.

**Comment by LostKing73** [comment]
again, dont be scared of mathew bcuz he says he's the boss. he isn't. he's just someone with a napolean complex who blackmailed aaron.

**Comment by 3foe** [comment]
saying it doesnt make it true

**Comment by LostKing73** [comment]
it being true makes it true

**Comment by 3foe** [comment]
reality is what it is, I hope you realize lashing out will not help you or delay the inevitable, it will only hurt you

**Comment by 3foe** [comment]
by nature your comments are not true

**Comment by LostKing73** [comment]
hey, mathew? you are forcing him to do something he does not want to do in reward of not getting him in trouble. that is blackmail

**Comment by 3foe** [comment]
🤓 🫵

**Comment by 3foe** [comment]
this is a "nobody asked issue"

**Comment by LostKing73** [comment]
lol, imagine thinking ur opinion is valued by any of us

**Comment by 3foe** [comment]
no opinion matters here only ability

**Comment by LostKing73** [comment]
@cs6413110 dtap this idot

**Comment by LostKing73** [comment]
theres a striking difference between our issues. mine is a vote, getting overrun by u spaming and spam closing, while urs is a more.. authoritarian approach where only you can have an opinion

**Comment by 3foe** [comment]
you are irrelevant in my issue you do not have the rank to talk in it

**Comment by LostKing73** [comment]
erm 🤓☝️

**Comment by LostKing73** [comment]
k like truce forlike 15 mins or smth i gotta take a test

**Comment by LostKing73** [comment]
ok done thx

**Comment by BreadSpammer** [comment]
just leave all the war issues closed. just clutters my notfications

**Comment by LostKing73** [comment]
> just leave all the war issues closed. just clutters my notfications

alr, we know we don't want him anyways

**Comment by LostKing73** [comment]
lol he changed vote to punishment to make it look like were on his side

**Comment by 3foe** [comment]
lol just to make u shut

**Comment by LostKing73** [comment]
K lol, all i see is u forcefully changing what the other side presents
