### ISSUE TITLE
Punishment

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#151]
Aaron, you told me to stop the war with LK when I told you I wanted him to be blocked from GitHub. I did that. He has started another war, openly in front of the GPAs he declared war on me. I intend to first have my full auth back just as per our deal I didn't ask for it back when it was glitched because LK would only accuse me of admin abuse, second I would like LK's main to be permanently muted, I did not ask for this permission but I believe you would take it rather than having him banned. and third, removed from the GitHub, we will have this conversation in person later but I would like you to know this is coming. I made peace with him and tried to avoid a war but I am done putting up with his perpetual antagonizing, I hope you recognize that I tried to avoid a war but he has crossed a line and if I do not stand up to him now we may have issues later, I hope in time we can slowly give his privileges back but he has broken my trust and then he denied my mercy. 

Aaron if you have an issue with anything I said here please talk to me in person at home, and I can elaborate. LK because I know you will close the issue, making this issue only gives Aaron time to be your attorney before I execute what I said I would do.

**Comment by LostKing73** [comment]
ooh im so scared of ur blackmail-fueled power

**Comment by BreadSpammer** [comment]
oh no we're all gonna die

**Comment by LostKing73** [comment]
ya so pretty much hes complaining bcuz i told him to not spam ai for the gpas but he decided to anyways.

**Comment by LostKing73** [comment]
then he spam reloaded me

**Comment by 3foe** [comment]
I did not ask for comments from the peanut gallery

**Comment by 3foe** [comment]
this is a co owners only issue

**Comment by LostKing73** [comment]
this is a nobody asked

**Comment by LostKing73** [comment]
dum

**Comment by LostKing73** [comment]
like nobody agrees to this. dum.

**Comment by DarkMemeGod411** [comment]
matthew. i say this as a friend.
i do not want this to be an option. no one should be removed from the github. it would only cause more wars

**Comment by LostKing73** [comment]
ye the only person who "started a war" was u

**Comment by 3foe** [comment]
DMG this is a co owner only issue but since it is a genuine comment I will answer. I have dealt with jonas for the past few weeks and I realize that keeping him around will only cause more wars removing him will be better for tanks.

**Comment by 3foe** [comment]
@cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 vvvvv

**Comment by LostKing73** [comment]
lol no

**Comment by cs6413110** [comment]
Talk in person, after school, after I've had time to decide.

**Comment by 3foe** [comment]
k this can stay closed now bc the point is fulfulled
