### ISSUE TITLE
decrease map maker size

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#152]
whenver a map is big, usually ppl don't like it, and it also discourages good map making, so revert to old size

👍 yes
👎 no

**Comment by BreadSpammer** [comment]
just dont be a memegod and use literally all of the space

**Comment by LostKing73** [comment]
> just dont be a memegod and use literally all of the space

do you mean don't use all of the space or do

**Comment by BreadSpammer** [comment]
dont use the entire space. that's what void blocks are for

**Comment by DarkMemeGod411** [comment]
When i have the chance. i fill the entire canvas.

**Comment by LostKing73** [comment]
> dont use the entire space. that's what void blocks are for

yea but like its annoying to carve out a map. at least give us like line, circle, and square tools

**Comment by LostKing73** [comment]
and you are skill issue, just fix, u have so many braincells

**Comment by LostKing73** [comment]
skill issue, i could do it

**Comment by 3foenation** [comment]
we need bigger maps because we are getting more people
