### ISSUE TITLE
ACCHEM

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#153]
![image](https://github.com/user-attachments/assets/d849ec40-9018-4494-887a-70747b17924d)

**Comment by 3foenation** [comment]
proof of what tony was trying to put in chat

**Comment by BreadSpammer** [comment]
???? literally no one cares

**Comment by 3foe** [comment]
swearing
as an admin?
tsk tsk tsk

**Comment by LostKing73** [comment]
i sais whoever, idk why its not allowed, but tony was LITTERALLY SAYING "nigg r" in chat earlier.

**Comment by LostKing73** [comment]
try it. say whoever in chat.

**Comment by LostKing73** [comment]
can you have braincell for once?

**Comment by LostKing73** [comment]
no. ok

**Comment by 3foe** [comment]
If I had a dime for every time jonas made a hypocrite moment

**Comment by 3foe** [comment]
id be rich

**Comment by 3foe** [comment]
so rich the number couldent be quantified

**Comment by LostKing73** [comment]
bro what? it literally is the word whoever

**Comment by LostKing73** [comment]
why reopen? what are you gaining? what is the point of this issue? are you just reopening to spite me?

**Comment by LostKing73** [comment]
Bro my chrumb died :(

**Comment by LostKing73** [comment]
![Screenshot_20241108_104720_Discord.jpg](https://github.com/user-attachments/assets/c1a4f2ff-a455-48c6-b015-65ed3db24ea2)

Tony spamming nword. Dum.

**Comment by 3foenation** [comment]
and someone could find out his password to that everyone knows his password

**Comment by LostKing73** [comment]
bro why do you defend him so much there's so much evidence against him

**Comment by BreadSpammer** [comment]
ye the word whoever includes the word h#e, so like that's why

**Comment by LostKing73** [comment]
well allow the farming tool then
