### ISSUE TITLE
Totally tanks related

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#154]
dont talk if dont know

MLA Citation

Overview: This worksheet is designed to act as a learning resource/refresher for you to not only improve your current understanding of both MLA, but to also retain that information moving forward. Knowing how to properly cite information can be useful for a variety of applications. Such applications include college essays, research papers (for academic or professional purposes), speeches, non-fiction manuscripts, etc. Although there are many different styles of citation beyond MLA, we are only going to focus on this style, as it’s most common in secondary and post-secondary institutions.

Please utilize Purdue Owl MLA website to answer the following questions.
[MLA Formatting and Style Guide // Purdue Writing Lab](https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_formatting_and_style_guide.html) 

MLA Format  

What does the acronym MLA stand for? 
	Modern Language Association

What information do you need to include when creating a works cited entry for a book?
First name, last name, the title of the book, the city of publication, publisher, and publication date.

Where should you place the page numbers on your MLA document? What else gets listed next to your page #’s? 
	Page number should be in the top right corner and your last name should be before it.
	

What information should you include when creating a works cited entry for a website?
Author/Editor names or Compiler name, Article name, Title of the website, Release Date and revisions, Publisher name/date, Paragraph numbers, URL, Date Accessed.

When creating a works cited entry, what should you do if you cannot find the author’s name, publication date, or some other piece of information?
	Include as much provided information as possible. With no known author, use a shortened version of the title in the parenthetical citations around your name. 

What lines get indented on a works cited page? Also, how is a works cited page organized (ex: chronologically, sequentially, alphabetically)
Indent the second and subsequent lines of citations. Works cited should be sorted alphabetically.

What is the difference between directly quoted information and paraphrased information?

Paraphrasing uses some similar working or structure, enough that it is not unique, whereas a direct quote uses consecutive words in succession.

Bonus Question: Why not always directly quote information? What advantages does paraphrasing sometimes offer over directly quoting info?

Paraphrasing is useful for quoting long passages that may be loosely connected to your argument but is better tied in as evidence with the context that paraphrasing can provide.
	
	

MLA Practice:
Create a works cited entry for a free reading book of your choice. Below your citation, please also include what the in-text citation would look like if you were to cite information from this book. 

		Golding, William. Lord of the Flies. Classroom Complete Press Ltd, 1990. 

Create a works cited entry for the following website: [How Do You Grow a 2,000-pound Pumpkin? | HowStuffWorks](https://home.howstuffworks.com/grow-giant-pumpkin.htm). Also please include what the in-text citation would look like if you were to cite information from this website.

		Vega, Muriel. “How Do You Grow a 2,000-Pound Pumpking?” HowStuffWorks, HowStuffWorks, 14 Oct. 2022.
			home.howstuffworks.com/grow-giant-pumpkin.htm

Let’s pretend Frankenstein was written by four authors: Mary Shelley, Mark Twain, Emily Dickinson, and George Orwell. How would you format these names on a works cited entry?

		Shelley, Mary, Twain, Mark, Dickinson, Emily, and Orwell, George. Frankenstein. 1818 ed., Dover Publications, 1994.

Click on this link to view the goodreads homepage for the novel The Talisman. How would you create a works cited entry for this book? https://www.goodreads.com/book/show/59219.The_Talisman?from_search=true&from_srp=true&qid=UAyo6PnK4R&rank=1 

                          Steven King, Peter Straub. The Talisman.
	          		E-book, goodreads.com, 1984.
Part 2: Peer-Reviewed Resources

What does it mean for information to have been peer-reviewed?

Information has been fact checked by a fellow peer, commonly someone who has scholarly or expertise in the field. 

What benefit does citing peer-reviewed information have for you as an author? 
It adds credibility and ensures correct information.

Why is citing information arguably easier with academic search engines as opposed to traditional ones? (a.k.a. Why is it easier to research/cite info from Google Scholar as opposed to Google)
The information required to create a MLA citation is much more easily accessible and provided. Information on Google Scholar must be fact checked and presented in a citable format for cross-referencing. 

Why is it important to only focus on key words when typing into a search bar of an academic search engine?
SEO sites target these keyword and by using them you will get the most relevant information.

Click on the EHS Library Database Resources link and look over the available resources listed. Select one and search for something. Describe what information you found using the online resource you selected. 
I found information about typing and the series of lessons to steadily learn touch typing.

**Comment by CelestialKnight7** [comment]
ez ty
