### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#155]
Jonas, Aaron and I talked and you will 
-Be VIP on probation
-   you no longer have code access or collaborator

**Comment by 3foe** [comment]
welp u saw it so it can stay closed

**Comment by LostKing73** [comment]
dum lol

**Comment by 3foe** [comment]
ill pretend I didn't see that so your VIP lasts more than a day

**Comment by LostKing73** [comment]
uh huh "lil bro"
