### ISSUE TITLE
JONAS. I have need of you

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#156]
I need you to make a 'cosmetic'

it will be lightning themed and animated as such:
an initial explosion of lightning, followed by lightning arc-ing around the tank for 1 second after.

this may or may not be for the dying core animation

**Comment by LostKing73** [comment]
my eyes lit up when i read the  title. ok lemme read actual issue now

**Comment by LostKing73** [comment]
alr bet. blue lightning(more like electricity) or yellow(more like lightning)

**Comment by CelestialKnight7** [comment]
blu

**Comment by LostKing73** [comment]
gotchu

**Comment by LostKing73** [comment]
i got wet hands on loop im locked in

**Comment by LostKing73** [comment]
_reguritates_
![image](https://github.com/user-attachments/assets/aa5f2b81-0389-4c07-b898-801dddfad524)

**Comment by LostKing73** [comment]
oop lemme remove lines

**Comment by LostKing73** [comment]
_reguritates x2_
![image](https://github.com/user-attachments/assets/9b1e0f88-4d9b-4a86-80e1-701544f968f3)

**Comment by LostKing73** [comment]
@CelestialKnight7 :D ?

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/82a46c1d-b6ff-4977-9835-109f928dfc33)

**Comment by LostKing73** [comment]
alt if u want ig 
![image](https://github.com/user-attachments/assets/11ff6b70-ea14-4441-ac66-058a675c9a6e)

**Comment by CelestialKnight7** [comment]
I like the first one but can u make it in all directions and more, idk lightning-y. like more sharp lines and arcs. idk what I'm saying

**Comment by BreadSpammer** [comment]
just make it the among us guardian angel animation

**Comment by CelestialKnight7** [comment]
> I like the first one but can u make it in all directions and more, idk lightning-y. like more sharp lines and arcs. idk what I'm saying

also it should be coming out of the tank not hitting the tank

**Comment by LostKing73** [comment]
> > I like the first one but can u make it in all directions and more, idk lightning-y. like more sharp lines and arcs. idk what I'm saying
> 
> also it should be coming out of the tank not hitting the tank

whaaaaaa? to the 2nd, the first ok

**Comment by CelestialKnight7** [comment]
2nd ok ig but it would be better if it was 4 and again, making it arc-ing

**Comment by LostKing73** [comment]
ok, imma just improve later lol

**Comment by cs6413110** [comment]
done?

**Comment by LostKing73** [comment]
> done?

yea he can deal with them, its not like he's doing me any favors, close

**Comment by CelestialKnight7** [comment]
bruh
