### ISSUE TITLE
@everyone @everyone @everyone ALL BREADS ON DECK

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#157]
Literally make images. Like actually. Tired of saying it. Work or no nugs. Work or I take your fix privileges.

**Edit as needed**.

Text(Need to be done by a non-bread):
- Descriptions for classes and items
- Actual introduction to game
- Steam game description(long term)

Images:
- Descriptions for classes and items
- Help menu
- add a stealth energy bar (max energy 30)

Menus:
- Shop menu with price tags
- Re-add old inventory
- Multiplayer Menu(see me for details)

**Comment by LostKing73** [comment]
u also need steam banner

**Comment by LostKing73** [comment]
like, backround, logo, and shop icon

**Comment by LostKing73** [comment]
> Descriptions for classes and items

vote: hovering over what ur buying opens a white rectangle to the side that has a description of what the thing ur buying is (a LOT of images)

**Comment by BreadSpammer** [comment]
working on turrets not having color

**Comment by DarkMemeGod411** [comment]
i can make the introduction to game image. if needed. also tell me what that would need to include.

**Comment by DarkMemeGod411** [comment]
what would be needed for the welcome to game image?

**Comment by cs6413110** [comment]
Uh, basic controls, gameplay, goals, idk

**Comment by DarkMemeGod411** [comment]
ok i can make that, can be done in 1-2 working days. (i can do it 7th hour)

**Comment by BreadSpammer** [comment]
I think the welcome thing will just be a tutorial

**Comment by BreadSpammer** [comment]
YAS KYU 6 SLAIN IRL EZZZ. fixed turret base not having color eZZZ

**Comment by 3foenation** [comment]
what does this mean fix what the menu or cosmetics

**Comment by BreadSpammer** [comment]
relaod and look at a turret's base :D

**Comment by 3foenation** [comment]
i dont see anything

**Comment by LostKing73** [comment]
wait can i ping @everyone

**Comment by LostKing73** [comment]
sorry whoever that is

**Comment by DarkMemeGod411** [comment]
glasgow scotland pings ez

**Comment by cs6413110** [comment]
devolved
