### ISSUE TITLE
Can someone HALP?

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#158]
mathew messed up the wiki, so can someone fix the wiki (without messing up the lore page bread)

please, it was literally good until he messed it up

**Comment by BreadSpammer** [comment]
idk look at the old repository and copy from there, and then cope until flat gets booted

**Comment by 3foe** [comment]
so I didn't mess with your lore stuff, I only made a different post. your page is fine and I won't mess with it. I merely provided the storyline that you lacked

**Comment by LostKing73** [comment]
> so I didn't mess with your lore stuff, I only made a different post. your page is fine and I won't mess with it. I merely provided the storyline that you la

I wasn't talking abt my lore flat. you broke the wiki by removing sections and not making it have a main section. also, you touched it? EXCUSE me?

**Comment by LostKing73** [comment]
i. actually. do not like you flat. you ruin everything. you are a disgrace. a stain.
