### ISSUE TITLE
FIX

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#163]
here is motivation to make menus:
![Screenshot 2024-11-13 11 46 40 AM](https://github.com/user-attachments/assets/91e0b3a7-5735-48a2-a40e-4e882e5ad106)
NOW FIX

**Comment by LostKing73** [comment]
ez lol

**Comment by LostKing73** [comment]
i also cant comment on that issue bcuz of flat's napolean complex soooo
