### ISSUE TITLE
Ban tony34.

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#164]
along with the dozens of other evidence, he also said this today.
![image](https://github.com/user-attachments/assets/a1674e4e-4f98-437c-a588-2fec58d5d08c)
may I remind you he spammed alt accounts with my first and last name.

👍 ban
👎 no I like people who treat players rudely

**Comment by cs6413110** [comment]
Problem is banning is ineffectual until people can't instantly create new accounts.

**Comment by 3foenation** [comment]
so somone got his and my password so im not sure that was him it could have been but I have changed my password, Aaron can you change his password in the morning

**Comment by LostKing73** [comment]
> Problem is banning is ineffectual until people can't instantly create new accounts.

then what do we do? wait?

**Comment by LostKing73** [comment]
> we can just ban the accounts tony uses. or mute, i'm on enough to help with muting them. and i do believe that was tony on the account at the time of the incident

he is ALWAYS on when it happens, literally this isn't the first time, and why do you keep supporting him coltin?

it doesn't matter if we mute him, coltin or flat will just unmute

**Comment by 3foenation** [comment]
for the record i unmute when ik it is'nt him he tells me when it's not him in 5th hour and I can tell because  he does not do that usually

**Comment by LostKing73** [comment]
> for the record i unmute when ik it is'nt him he tells me when it's not him in 5th hour and I can tell because he does not do that usually

just bcuz he tells u smth doesn't mean its true. literally obv he would be lying so u unmute him

**Comment by 3foe** [comment]
You have to keep in mind that his account was hacked. it may not be his fault. just because Tony tells coltin something doesn't mean it's not true. however bro does deserve to be banned, however, CS is right on this point it is ineffectual to ban, until the alt problem is fixed. if only people would put as much effort into solving that as they do to attacking me

**Comment by BreadSpammer** [comment]
its not "hacked", he just leaked his password. like just dont do that and you'll be fine

**Comment by LostKing73** [comment]
> You have to keep in mind that his account was hacked. it may not be his fault. just because Tony tells coltin something doesn't mean it's not true. however bro does deserve to be banned, however, CS is right on this point it is ineffectual to ban, until the alt problem is fixed. if only people would put as much effort into solving that as they do to attacking me

oh so his acc is hacked every single day? at all hours? and he as a person is hacked?

**Comment by BreadSpammer** [comment]
just Perma mute him. Ik he can be cringe at times, but he is like top 3 most consistent players of tanks. like bro is on even after school. he is our top customer lol

**Comment by LostKing73** [comment]
> just Perma mute him. Ik he can be cringe at times, but he is like top 3 most consistent players of tanks. like bro is on even after school. he is our top customer lol

cant perma mute, coltin and flat will just unmute without reason

**Comment by DarkMemeGod411** [comment]
i have been spotted at 6:00 in the morning on weekends.

**Comment by BreadSpammer** [comment]
the remove 3fonation and 3foe ez

**Comment by LostKing73** [comment]
> the remove 3fonation and 3foe ez

like duh

**Comment by LostKing73** [comment]
> i have been spotted at 6:00 in the morning on weekends.

that's just a mental disease, not smth to brag abt

**Comment by 3foe** [comment]
I'm not against whatever u do to tony he has had more than enough chances, however he is our main player so we kinda need him.

**Comment by DarkMemeGod411** [comment]
i play more than tony.

**Comment by LostKing73** [comment]
> I'm not against whatever u do to tony he has had more than enough chances, however he is our main player so we kinda need him.

so perma mute, but fix alts

**Comment by 3foe** [comment]
tony34's punishment:

👍 = mute for like an eternity
👎 = perma mute
🚀 = ban
😕 = I like racist people who swear ( nothing)

**Comment by LostKing73** [comment]
make it so when he join he jsut joins a fake lobby with ais with our usernames
