### ISSUE TITLE
New Perk: Missles+

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#165]
### The Basics

Fires your power bullet, it slows down to a stop(scribble in picture), then it rockets towards nearest enemy(if seen)

pretty much, when it is stopped, it scans for enemies in its vision, then shoots towards them.

### Why add this?

New perk, adds easier aiming that still can be dodged.

### Image

![image](https://github.com/user-attachments/assets/0b08a07b-83bd-48d7-98f5-3b00ccbc0b67)

### Voting

👍 yes
👎 no (comment why)

**Comment by 3foe** [comment]
aimbot = no skill

**Comment by CelestialKnight7** [comment]
cool idea but one of the main things we want to avoid with perks is changing the base game, Aaron agrees with me on this, that perks should add extra stuff not buff or change current mechanics such as shooting, boosting, power missile, toolkit etc.

**Comment by LostKing73** [comment]
closing cuz of evan, not flat
