### ISSUE TITLE
Lore

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#166]
Jonas, I know that you want to have lore. I get it you don't want me involved, however I know you want to be a part of it but I am willing to copy-paste what you want in. I would like to work with you to make the leviathan make sense for being in the game, would you read the storyline I made and tell me about any tweaks that you want.

**Comment by LostKing73** [comment]
no. no lore, no wiki. im sure @BreadSpammer and @CelestialKnight7 agree with me here, we don't need any lore.

**Comment by 3foe** [comment]
um ok... we don't need to delete what we worked for tho Ig it can stay and mold

**Comment by 3foe** [comment]
btw I unlocked repost

**Comment by LostKing73** [comment]
> um ok... we don't need to delete what we worked for tho Ig it can stay and mold

no. you didn't work on that, gpt did. and also, literally we don't need lore.

**Comment by 3foe** [comment]
dude I spent and hr and a half typing it out by hand, there was no ai involved except to identify plot holes

**Comment by 3foe** [comment]
dawg what does roblox have to do with pixel tanks?

**Comment by 3foe** [comment]
and if you are ok with you lore being deleted then I will delete it if u want

**Comment by LostKing73** [comment]
> dawg what does roblox have to do with pixel tanks?

is what urs is. also, I literally just said delete the ENTIRE wiki. we don't need it

**Comment by LostKing73** [comment]
omg bro stop spamming lore. we dont need it. get rid of it. that's also not what the leviathan is.

**Comment by DarkMemeGod411** [comment]
> > dude I spent and hr and a half typing it out by hand, there was no ai involved except to identify plot holes
> 
> so like, idc, we don't need ur roblox lore or my "dark ages spawn" lore (as alex has called it)

true.
