### ISSUE TITLE
Missle Barrage

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#167]
This will be a new perk, it firse missiles all around you the damage and amount and when it fires depends on the perk

tier 1: at 1/5 Hp fire 10 missiles randomly that deal 10 damage

tier 2: at 1/3 and 1/5 HP fire 20 missiles that fire randomly that deal 20 dmg

tier 3at 1/5, 1/3, and 1/2 HP fire 30 missiles that deal 20 dmg

**Comment by CelestialKnight7** [comment]
so at tier 20 that's 400 damage if they all hit one person
and at tier 3 that's 600 damage.

also stop locking the conversation

**Comment by LostKing73** [comment]
thank you evan. flat, its a bad idea, thats not prejudice, thats called an _opinion_

**Comment by 3foe** [comment]
randomly fired, it's just like bread's frag bomb, except deals less dmg, also we can tweak the numbers

**Comment by 3foe** [comment]
also no I will not stop locking it when I know all jonas is going to to is spam hate and predjudice

**Comment by cs6413110** [comment]
lag cringe
