### ISSUE TITLE
Chat filter

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#168]
With the colorful imaginative mind of Tony, I have realized we need a better filter, and there is a main problem with our current filter, you can't say words like whoever because the word hoe is in it, things like that make it hard to filter everything, anyone have an ex fix for this?

**Comment by DarkMemeGod411** [comment]
yeah, mute those who swear.

**Comment by LostKing73** [comment]
> yeah, mute those who swear.

actual smartest thing you have said.

**Comment by BreadSpammer** [comment]
K but the filter prioritizes letting ppl speak, so it's really ez to cuss

**Comment by LostKing73** [comment]
> yeah, mute those who swear.

^^^

**Comment by BreadSpammer** [comment]
Best solution is to have no traitor admins that unmute ppl so they actually get punished

*cough* 3foe and 3foenation *cough*

**Comment by 3foenation** [comment]
ill stop unmuting when they ask because it seems the muting has gone down but it is still there

**Comment by LostKing73** [comment]
> ill stop unmuting when they ask because it seems the muting has gone down but it is still there

Bro just bcuz qe are muting doesnt mean its a reason to unmute him
