### ISSUE TITLE
Menu Complaints

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#169]
Shop:
- Ghost and Mandalorian are copyright
- Shop to Class Tab symbols are inconsistent(Probably inconsistent with inventory too).
- Does Cost have a semicolon instead of a colon?
- Due to htmlifiying and the way menus are set up, it's easier to have one menu with all the buttons lined out instead of many tabs. Since the tabs are really big with little information, can we just have the tabs all laid out on the main shop menu instead(less bandwidth, less coding, less cringe, less effort to find price, less effort to buy, less confusion)?

Multiplayer:
![image](https://github.com/user-attachments/assets/94969dad-3144-4e18-b60a-8cc6a69f3077)
- Add the same background image in main and shop menus(ask evan idk)
- Make the play button a more appealing color
- Imagine the minecraft multiplayer screen. That's partially what we are going for. Lemme make a google drawings or something rq:
![Screenshot 2024-11-14 10 36 43 AM](https://github.com/user-attachments/assets/90494ebc-f664-4366-8635-218267ca9340)
successful google drawings speedrun

**Comment by cs6413110** [comment]
Wait um, I just realized. Change the JOIN button at the top to be like custom server or seomthing. 

Basically, you click one of the saved servers or custom server and it will hightlight it. Then you select gamemode and then click play to join.

Total online players will show up next to each saved server and next to each gamemode once selected.

**Comment by CelestialKnight7** [comment]
> Shop:
> 
> * Ghost and Mandalorian are copyright
ghost I'll change, but bruh I literally stole a knight helmet stamp that is not the mandalorian
> * Due to htmlifiying and the way menus are set up, it's easier to have one menu with all the buttons lined out instead of many tabs. Since the tabs are really big with little information, can we just have the tabs all laid out on the main shop menu instead(less bandwidth, less coding, less cringe, less effort to find price, less effort to buy, less confusion)?
expain.

**Comment by cs6413110** [comment]
Basically make it so instead of tabs, just put all the price/descriptions/buying button in one menu for all the classes.

**Comment by cs6413110** [comment]
I.e all 6 tabs bradley made next to each other in place of the class icons.

**Comment by LostKing73** [comment]
aaa lag bye (ill do later)

**Comment by CelestialKnight7** [comment]
can I get another google drawings Speedrun cuz my one braincell stopped working

**Comment by CelestialKnight7** [comment]
> aaa lag bye (ill do later)

(never*)

**Comment by cs6413110** [comment]
noooooooooooooooooo

**Comment by cs6413110** [comment]
![Screenshot 2024-11-14 11 13 19 AM](https://github.com/user-attachments/assets/e124b098-4461-4571-9a46-6ade12bcd13d)

**Comment by CelestialKnight7** [comment]
oki, and this is just for classes?

**Comment by cs6413110** [comment]
I think the perk menu would actually explode if we tried to fit that all in, but maybe idk. We can stack the buttons since you go from purchasing to upgrading so maybe..

**Comment by BreadSpammer** [comment]
Ok so like menus aren't my job? :)

**Comment by LostKing73** [comment]
@cs6413110 
![image](https://github.com/user-attachments/assets/d1a59e76-e66d-4bca-ace8-d959c0fa7311)
better?

**Comment by BreadSpammer** [comment]
ew

**Comment by BreadSpammer** [comment]
just don't change it, and don't remove defense cuz why>>

**Comment by LostKing73** [comment]
> just don't change it, and don't remove defense cuz why>>

bruh shut with ur complaints, he literally has already explained why. if ur not gonna work, don't be in here

**Comment by BreadSpammer** [comment]
i literally just made shop menu what r u talking about??? i also fixed turret colors, and more.

**Comment by BreadSpammer** [comment]
u also didn't even include coords

**Comment by LostKing73** [comment]
i love it when i spend an hour on smth and 🍞 looks at it for less than 5 seconds and says ew

**Comment by LostKing73** [comment]
you can downlad the image and ifgure out coords for urself, idk how to do

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/97ad0efd-1517-4dd0-8bd2-9438b271c0ab)
better..? @cs6413110

**Comment by LostKing73** [comment]
theres no way to make bg the same as floor. idk.

**Comment by CelestialKnight7** [comment]
> theres no way to make bg the same as floor. idk.

I have the background floor as its own image, just make the background transparent and I can add it

**Comment by LostKing73** [comment]
> > theres no way to make bg the same as floor. idk.
> 
> I have the background floor as its own image, just make the background transparent and I can add it

oka (thank goodness I left tab open

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/8175ca3a-84c0-46d2-9165-eb969eddb4f2)

**Comment by BreadSpammer** [comment]
Btw what even is the shop background? Is it just the floor texture downscaled, then made lighter???

**Comment by LostKing73** [comment]
@CelestialKnight7 ?????

**Comment by CelestialKnight7** [comment]
paid Bradley to do

**Comment by LostKing73** [comment]
> paid Bradley to do

bruh fix, what are u even working on

**Comment by BreadSpammer** [comment]
ye I made the shop menu already. just need to get coords next hour (hopefully dont get killstreaked In there)

**Comment by CelestialKnight7** [comment]
> > paid Bradley to do
> 
> bruh fix, what are u even working on

school

**Comment by LostKing73** [comment]
> > > paid Bradley to do
> > 
> > 
> > bruh fix, what are u even working on
> 
> school

that's not important

**Comment by CelestialKnight7** [comment]
![pixil-layer-Background](https://github.com/user-attachments/assets/02c5ddfc-77e7-4b3c-9cd2-7455e71b69a9)
bruh first thing to come up when I look up background on my computer

**Comment by CelestialKnight7** [comment]
its not even accurate bruh, why are there 2

**Comment by CelestialKnight7** [comment]
![background for tonks](https://github.com/user-attachments/assets/be65f979-2da5-47ca-b9cc-dd510a475ff3)
here's actual

**Comment by LostKing73** [comment]
finally

**Comment by LostKing73** [comment]
@cs6413110 this?
![image](https://github.com/user-attachments/assets/d7e28729-fef0-4ec2-87f9-0c4e315ee587)

**Comment by BreadSpammer** [comment]
me when perk menu:

**Comment by BreadSpammer** [comment]
ok so I don't wanna make 25 menus for perks, so here's my compromise
![Screenshot 2024-11-19 7 59 06 AM](https://github.com/user-attachments/assets/ce64d5d9-e4ff-4f8e-b08a-466a793aa7be)
I say we put text at the bottom that will change when u hover over an icon.

if u hover over nothing: "hover over an icon for details"

if hovering over something, @cs6413110 code and I'll add the text. make it also include the cost

**Comment by BreadSpammer** [comment]
this is for a few reasons:
1: there are too many perks lol. I cant fix our existing thing for classes, unless we boot one.
2: 0 effort, so game finishes faster
3: I get my sugar intake

**Comment by CelestialKnight7** [comment]
Aaron said he can make the dialouge boxes with code, also did u not listen yesterday
its gonna be made so there are 9 boxes each with a box below them
the top box is the icon of the perk that will tell you the description when u hover over it
the bottom box will tell you the price to upgrade, the icon will change based on what the next tier is or what the current tier is that u own.

**Comment by BreadSpammer** [comment]
oooooooh um ok

**Comment by CelestialKnight7** [comment]
ye remove all excess buttons except for t1,  and then make the button that says the price and u click that to purchase

**Comment by BreadSpammer** [comment]
![shop2](https://github.com/user-attachments/assets/dbdcff07-9e06-4619-9225-45dd347a7ef8)

**Comment by BreadSpammer** [comment]
coords = 792, 842, 194, 80, for the button

**Comment by BreadSpammer** [comment]
![FIXEDAEAZZZ](https://github.com/user-attachments/assets/347e8ff3-c1a8-48bc-a582-41b06c8fdfe1)

**Comment by CelestialKnight7** [comment]
whatever ask @cs6413110

**Comment by cs6413110** [comment]
He's making me code more because he's lazy and he wants it to be symetrical.

**Comment by BreadSpammer** [comment]
EezedzeEZzeZZEZEZzeeZZEZeZEZEeZeZZEZEreZREZREEZeZeZrZZEeZWeZeZeZEZEeZeZeZeZEZEeZeEezeeeZeZreZeZEZeZEZEeASZeZEZ EZZEzeEZz4ZEzezezeEzzeezeZ$EzEzZEezzeZezezEzZEZEeZezEZzEzeZEeZz4ZEEZzeezZREZeZzezeEZZEeZezeEZEzezezEzZEzeREZeZreZeZEEZEZeZezeEZ$EZeZeZEEZEZeesZE

**Comment by CelestialKnight7** [comment]
it would be symmetrical if each box has its own button underneath :/

**Comment by CelestialKnight7** [comment]
also I'm not gonna pay u if ur lazy

**Comment by BreadSpammer** [comment]
ig im deleting random images now

**Comment by BreadSpammer** [comment]
@CelestialKnight7 get me the old crate menu so i can unblur it, and ping me in github when u do so i can fix.

**Comment by BreadSpammer** [comment]
actually a lot of the menus are just blurry bc of some random stuff.

crate
inventory
all of the tabs
singleplayer (doesnt really matter bc will probably change)
keybinds
multiplayer (changing)

if u have these unblurred, just send them to me so i can use photoshop to enlarge without a blurage

**Comment by CelestialKnight7** [comment]
its cuz Aaron resizes them artificially so it blurs

![crate](https://github.com/user-attachments/assets/742dc5b4-caa1-47bf-bddc-9aa3d73179ee)
![item-tab](https://github.com/user-attachments/assets/7e04b772-cb6d-4511-a527-a557c8368dd7)
![classTab](https://github.com/user-attachments/assets/eecd2aae-18c6-40b2-9e13-c56770bee9d2)
![cosmeticTab](https://github.com/user-attachments/assets/da2206e6-fe29-41fb-95b6-06cb2be8e0fa)
![perkTab](https://github.com/user-attachments/assets/801efd19-8e9d-45bc-b673-967ef61d369d)
![multiplayer](https://github.com/user-attachments/assets/39fd4d4a-2313-4706-91cf-9aa8279afb71)
![inventory](https://github.com/user-attachments/assets/598a1053-f424-4909-bdd8-0a4463a473a6)

don't have keybinds menu (u made it)

**Comment by CelestialKnight7** [comment]
@BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer

**Comment by CelestialKnight7** [comment]
> > the cosmetic one is outdated I just realized 💀
> 
> how so?

the DED button at the bottom isn't supposed to be there

**Comment by LostKing73** [comment]
there isnt one?

**Comment by LostKing73** [comment]
oh the ghostbusters thing on this one?
![image](https://github.com/user-attachments/assets/3862339c-9c0e-4044-99a2-188dad32d6c1)

**Comment by CelestialKnight7** [comment]
> nvm acquired

stoopid

**Comment by BreadSpammer** [comment]
lol lag bye

**Comment by BreadSpammer** [comment]
YAS DONT HAVE TO WROK
