### ISSUE TITLE
lore -_-

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#170]
vote cuz flat=incompotent

👍 = no lore at all
👎 = I create new and improved lore with an actual cohesive thought
👀 = flat's lore only
🚀 = combine me and flats lore
😕 = use my previous lore

**Comment by LostKing73** [comment]
like, we dont need lore. (also alex tbh my "new" lore would be rly good ngl)

@CelestialKnight7 @cs6413110 @BreadSpammer

**Comment by BreadSpammer** [comment]
ye no good option. either bad, bad, bad, or bad. i dont even like the lore i made. lore is just cringe, removing...

**Comment by BreadSpammer** [comment]
@cs6413110 can u remove wiki?

**Comment by 3foe** [comment]
We should not remove the wiki. I have stuff on how to play the game. The GPAs constantly asked me questions, so I made a wiki with the answers. However, I deleted Lore because LK asked me to. idc about having lore but, if we want lore I want actually lore not what jonas had. ALERT NEW ZONE DISCOVERED THE DEEP, with no context.

**Comment by LostKing73** [comment]
> We should not remove the wiki. I have stuff on how to play the game. The GPAs constantly asked me questions, so I made a wiki with the answers. However, I deleted Lore because LK asked me to. idc about having lore but, if we want lore I want actually lore not what jonas had. ALERT NEW ZONE DISCOVERED THE DEEP, with no context.

Listen. The wiki isnt needed bcuz we dont need gpas on the github, and thats the only way to give the wiki. If you wanted context, you shouldve asked, not added your own fan book.

**Comment by LostKing73** [comment]
k. like, if yall wanna know, the leviathan was created by a mining company for deep sea mining. that's literally it lol

**Comment by 3foe** [comment]
> > We should not remove the wiki. I have stuff on how to play the game. The GPAs constantly asked me questions, so I made a wiki with the answers. However, I deleted Lore because LK asked me to. idc about having lore but, if we want lore I want actually lore not what jonas had. ALERT NEW ZONE DISCOVERED THE DEEP, with no context.
> 
> Listen. The wiki isnt needed bcuz we dont need gpas on the github, and thats the only way to give the wiki. If you wanted context, you shouldve asked, not added your own fan book.

i son't need to ask you to update something I co-own

**Comment by LostKing73** [comment]
> > > We should not remove the wiki. I have stuff on how to play the game. The GPAs constantly asked me questions, so I made a wiki with the answers. However, I deleted Lore because LK asked me to. idc about having lore but, if we want lore I want actually lore not what jonas had. ALERT NEW ZONE DISCOVERED THE DEEP, with no context.
> > 
> > 
> > Listen. The wiki isnt needed bcuz we dont need gpas on the github, and thats the only way to give the wiki. If you wanted context, you shouldve asked, not added your own fan book.
> 
> i son't need to ask you to update something I co-own

you don't co-own pickle tanks.

**Comment by 3foe** [comment]
:/

**Comment by 3foe** [comment]
🤨

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/0466dcab-924b-49a8-80cd-35d6a7d14d5c)

**Comment by LostKing73** [comment]
also also, we went from:

Welcome to the Pixel Tanks Wiki!
You'll find information here on the following topics:

Game overview
Game mechanics
FAQ And More!
Helpful Links
[Overview](https://github.com/cs6413110/Pixel-Tanks/wiki/Overview) [FAQ](https://github.com/cs6413110/Pixel-Tanks/wiki/FAQ) [Bugs](https://github.com/cs6413110/Pixel-Tanks/wiki/Bugs)

What is Pixel Tanks?
Pixel Tanks is a multiplayer and singleplayer battle royale indie game. It is very buggy and experimental since it is in its alpha days. We are currently lacking the programmers and graphic designers to be able to ever get out of alpha. It is designed to be a unblockable fun minigame to play with friends at work or school.

How do I play?
To play, copy and paste the following in the URL bar: data:text/html,<script src='http://141.148.128.231'></script>

Alt links: data:text/html,<script src='https://cs6413110.github.io/Pixel-Tanks/public/js/pixel-tanks.js'></script>

To create your own alt link, simply use static hosting to host the game files.

What are the Controls?
to move you use W-A-S-D
to use toolkit you press the "Q" key
to grapple you press "R"
to use items you press "1-2-3-4"
to talk you press ENTER


to


Welcome to the Pixel-Tanks wiki!
