### ISSUE TITLE
Mourn the Drone

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#171]
Beloved fren,

  **You did not have to fall
  You were all we hoped for
  The way your annoying scanning 
  Persistent, yet comforting
  flowed with your rhythmic whirring
  Your faithful, enduring presence
  a testament to friendship
  Perhaps you were too good
  For a world too cruel; unable to see your beauty
  They called you *gnat*, as you followed them
  Through fierce battles toward destined victory
  Too few knew you, and now
  As we say our final farewells,
  Forgotten beyond the cliffs of times past
  We may forget, but where we are
  We only went because you followed**

👍 = salute
❤️ = pay respects
👀 = remember
🎉 = keep as an easter egg
👎 = remove
🚀 = replace with levithan thing idk

**Comment by LostKing73** [comment]
Make it an item. 

You place, it stays in place like a turip and heals whatever gets close. Good for builder, bad for movement classes like warrior a d fire. (GREAT against fire tho)

**Comment by LostKing73** [comment]
Like, 25 hp a second

**Comment by DarkMemeGod411** [comment]
Harbinger, you will be missed my drone.
Harbinger
you were a drone
and it was flown
i don't wanna write a full eulogy

**Comment by LostKing73** [comment]
the drone's name was lil guy not whatever harbinger is.

**Comment by DarkMemeGod411** [comment]
I'm gonna miss the lil guy. 
Goodbye lil guy
how quick you could fly
why did you have to die

**Comment by CelestialKnight7** [comment]
rip bozo, he will be missed.

**Comment by LostKing73** [comment]
> Make it an item.
> 
> You place, it stays in place like a turip and heals whatever gets close. Good for builder, bad for movement classes like warrior a d fire. (GREAT against fire tho)

^^^?

**Comment by LostKing73** [comment]
...

**Comment by LostKing73** [comment]
why no @CelestialKnight7

**Comment by BreadSpammer** [comment]
all he's doing now is taking up lines of code. it is time for his execution

**Comment by cs6413110** [comment]
@LostKing73 @CelestialKnight7 @DarkMemeGod411 @BreadSpammer 

Final Vote

Kill drone y/n?

**Comment by LostKing73** [comment]
ooh i was first in his list :D

**Comment by BreadSpammer** [comment]
Guys think about it: remove drone = less lines of code and less images, aka minus liek 10 frames of load. 10*1000 times u load game /60 for seconds... that's minutes of time save from the removal :D

**Comment by LostKing73** [comment]
remove drone= more room for leviathan :D

**Comment by BreadSpammer** [comment]
Nah more room for gold blocks
