### ISSUE TITLE
AI TURRETS

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#174]
can HAVE CLASSES, AND CAN PLACE TURRETS

D:
![Screenshot 2024-11-18 8 05 23 AM](https://github.com/user-attachments/assets/8a3abc6e-2340-4d32-9f8b-67b3cc1a5de8)

**Comment by CelestialKnight7** [comment]
also when an ai places a turret there's like a 50% chance that the parent ai dies (like braindead not DED DED) and the breaks other ai

**Comment by BreadSpammer** [comment]
bruh I thought we fixedthis

**Comment by BreadSpammer** [comment]
idk why this is happening. fixing

**Comment by cs6413110** [comment]
Fixed

**Comment by LostKing73** [comment]
w turip.
![image](https://github.com/user-attachments/assets/243fb00b-bc5f-43f2-a11e-56b70e0f7fa1)
caused by: bread owned the team, left, and this happened? i think?

**Comment by BreadSpammer** [comment]
Leader turrip
