### ISSUE TITLE
I still need a perk?

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#175]
C'mon guys. It's been a few months since you suggested this and we still haven't finished the brainstorming phase. We just need one more perk.

For the spammers:
- No influencing movement speed
- No on death perks
- No adding new firing types/items/features
- No overpowered perks

**Comment by LostKing73** [comment]
Energize

faster shooting speed. thats it.

does that count as the third bullet point? idk, but if yea just downvote, get ready for a lot of spam lol

**Comment by LostKing73** [comment]
shockwave

blasts people away when you boost

**Comment by LostKing73** [comment]
-name pending-

placing blocks makes them be 1 level higher (old builder passive, weak to strong, strong to gold)

**Comment by DarkMemeGod411** [comment]
Health vision, Name pending,
Old tactical passive: see healthbars

**Comment by BreadSpammer** [comment]
1: boring, and ruins ppls muscle memory
2: too much effort
3: too good :)
4: radar already does I think?

**Comment by LostKing73** [comment]
im pretty sure it doesnt

**Comment by BreadSpammer** [comment]
then fix

**Comment by LostKing73** [comment]
burh, fix by adding this

**Comment by BreadSpammer** [comment]
no? that doesnt add anew perk. arewetalking about the same thing?

**Comment by LostKing73** [comment]
> no? that doesnt add anew perk. arewetalking about the same thing?

I'm saying add my prk

**Comment by cs6413110** [comment]
I'm ok with the old builder passive

**Comment by BreadSpammer** [comment]
Blood Magic:

gain the ability to use stuff when they are on cooldown at the cost of health.

every second saved on the coodown this way will deal 5 damage (for example, shooting an extra mega bullet will deal 150 damage to you in compensation)

this ability will go on cooldown after using it on something, based off of the item that it was used on,

damage death this way is true damage, which bypasses shields, and you CAN kill urself, but u wont get the kill.

synergies:
- medic class ability can be semi-spammed, due to it healing you 250 back over time, so u can spam heal teammates with this, or maybe even infinitely chain it with time
- builder could build twice the amount of turrets in the same amount of time
- at the cost of ur health bar, u can essentially double boost, or double grip.
cons:
- super duper ez to accudentally use it and waste health and a perk

VOTE

**Comment by BreadSpammer** [comment]
> I'm ok with the old builder passive

u want old builder back? u want the suffer?

**Comment by LostKing73** [comment]
spam tape

**Comment by LostKing73** [comment]
not if i wait a ittle bit

**Comment by BreadSpammer** [comment]
k but still. ur losing out on another perk if u do that, such as gambling

**Comment by LostKing73** [comment]
> k but still. ur losing out on another perk if u do that, such as gambling

noooooooooo gambling :((((((((

**Comment by 3foe** [comment]
ok @cs6413110 thoughts on my missle barrage?

**Comment by 3foe** [comment]
I want cs's opinion btw not anyone elses

**Comment by 3foe** [comment]
This will be a new perk, it firse missiles all around you the damage and amount and when it fires depends on the perk

tier 1: at 1/5 Hp fire 10 missiles randomly that deal 10 damage

tier 2: at 1/3 and 1/5 HP fire 20 missiles that fire randomly that deal 10 dmg

tier 3 at 1/5, 1/3, and 1/2 HP fire 20 missiles that deal 10 dmg

**Comment by LostKing73** [comment]
so, u want to, instead of seeing all the downvotes and accepting it, ask the person you are blackmailing abt ur perk. am I wrong? (if u delete then I'm right)

**Comment by 3foe** [comment]
missiles will fire at random and most likely only 3 or so will actually hit (may need a buff)

**Comment by 3foe** [comment]
> so, u want to, instead of seeing all the downvotes and accepting it, ask the person you are blackmailing abt ur perk. am I wrong? (if u delete then I'm right)

um I don't understand what ur trying to say here, like give it to me again but in english

**Comment by LostKing73** [comment]
> > so, u want to, instead of seeing all the downvotes and accepting it, ask the person you are blackmailing abt ur perk. am I wrong? (if u delete then I'm right)
> 
> um I don't understand what ur trying to say here, like give it to me again but in english

you are ignoring everyone else's opinions and instead just asking the person who you have blackmailed(cs) instead.

**Comment by 3foe** [comment]
wait, guys. though. Remember how Warroir used to break all blocks? how about we make that a perk, it's bomb on steroids. (may be in violation of changing boost but it doesn't actually change it it just buffs it)

**Comment by 3foe** [comment]
> > > so, u want to, instead of seeing all the downvotes and accepting it, ask the person you are blackmailing abt ur perk. am I wrong? (if u delete then I'm right)
> > 
> > 
> > um I don't understand what ur trying to say here, like give it to me again but in english
> 
> you are ignoring everyone else's opinions and instead just asking the person who you have blackmailed(cs) instead.

k, I want cs's opinion cause his opinion is the only one that matters. let's be real here. also, you and bread are always going to be biased so it's not actual criticism.

**Comment by DarkMemeGod411** [comment]
My opinion (idk if its valid) is:
1: it's another before death perk
2: actually a good idea
3: by random: wdym

**Comment by 3foe** [comment]
its health activated not death activated
yay someone can see common sense
?

**Comment by DarkMemeGod411** [comment]
will it just go randomly. or like 1 in 20 directions, Completely random, or in one of a defined number of directions?
