### ISSUE TITLE
VIP's

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#177]
Many new players want to be VIP and don't know how to get it. What are the requirements for getting VIP Aaron? A list of players who want to be VIPs is

- mangogodd
- tony34 💀 
- Lxst_Mqc1ek
- person2
- every other player (those are the ones who directly told me thewantednt it tho

we need to know what the requirements are to have VIP, (making cosmetics, etc)
also, do we want GPAs on the Git Hub?

( I mainly want Aarons opinion but everyone has the right to their opinion)

**Comment by DarkMemeGod411** [comment]
We don't want GPAs on the github. (that would lead to spam and github getting blocked)

Tony does NOT deserve vip.
mangogodd doesn't either,
lxst_mqc1ek: nope
person 2 nope

**Comment by LostKing73** [comment]
oh so NOW we have a right to our opinion? well mine is this:

no VIP for gpa's. gpas are not people AT gpa, but players that are not:

LostKing
bradley
Celestial
DarkMemeGod
3foenation (kinda)
3foe (ehhhhhhhh)
cs641311

other requirements are:

being in the 10th grade or higher
actually having a cell
not having blackmailed
not having a username that is a ripoff of someone else's
not being tony34

**Comment by LostKing73** [comment]
and no gpas on github. it is for coders(me included, you not allowing me to code doesn't mean I'm not a coder)

**Comment by 3foe** [comment]
DMG, you make a valid point GitHub would only get blocked if GPAs went on it.
LK that comment was dangerously close to an attack, but rip off username is crazy, the crazier part is that's exactly when I tell coltin

**Comment by CelestialKnight7** [comment]
people on the GitHub are major contributors to the game, (me, Aaron, bradley, but some others as well such as lk and Dmg)

as for the requirements for vip, I'd say you would need to be promoted by Aaron himself so he has control of who's running around with commands,

but you'd also want them to do meaningful work for the game too, quality work not some random cosmetic that looks bad just so that they can say they did something. (also ATM we don't need more cosmetics).

**Comment by BreadSpammer** [comment]
just make it cost 50 bucks ;)

**Comment by LostKing73** [comment]
> DMG, you make a valid point GitHub would only get blocked if GPAs went on it. LK that comment was dangerously close to an attack, but rip off username is crazy, the crazier part is that's exactly when I tell coltin

that's wild. i literally just share my opinion and you call it an "attack". if you want this to be business and not personal, don't take it personally

**Comment by BreadSpammer** [comment]
and can be deleted at any time for misbehavior. no refunds

**Comment by LostKing73** [comment]
like, the only thing they do is make like 1 cosmet that doesn't fit, then they say they want VIP bcuz they did it. like, fanart appreciated, but nah?

**Comment by 3foe** [comment]
Idk if 10th grade should be the cutoff Im thinking high school,
having a cell is more of a admin thing
not even going to respond to that
💀 that's crazy and true
valid

**Comment by 3foe** [comment]
> like, the only thing they do is make like 1 cosmet that doesn't fit, then they say they want VIP bcuz they did it. like, fanart appreciated, but nah?

real

**Comment by 3foe** [comment]
so its decided pay 50$ for VIP? ;)
 aaron thoughts

**Comment by LostKing73** [comment]
bro like did you read anyone elses(mine)? clearly that's a joke, absolutely no way are we going to scam gpas, that would actually get us in trouble

**Comment by 3foe** [comment]
hence the winking face

**Comment by 3foe** [comment]
**edit this comment for the requirements**

Grade - 9th?
contributions - making art/ cosmetics ? (prob more or smt else)
reputation - hasn't sworn?
support - has the support of 3 or more players and an admin that's not 3foenation? (sorry coltin but u would say they deserve it with no other reason)

**Comment by LostKing73** [comment]
cant edit it. you made it so I cant.

**Comment by CelestialKnight7** [comment]
just comment ur edits by copy and pasting into comments

**Comment by LostKing73** [comment]
**edit this comment for the requirements**

Grade - high school 
contributions - not art related, imagine if someone drew luffy and then begged mapa or whatever to be in charge/ in the credits, I don't think we should EVER give any more people vip/admin
reputation - n/a literally like having a cell + read previous
support - has the support of all admins except coltin

**Comment by BreadSpammer** [comment]
true requirments:

vip: 20 bucks first purchase. if removed, can rebuy for 10$
admin: 50 bucks first purchase. if removed, can rebuy for 25$

any purchase can be denied, and any removals are semi pernament, and NO REFUNDS

**Comment by cs6413110** [comment]
why sell admin

**Comment by BreadSpammer** [comment]
bc if they admin abuse and they get their admin removed, then ez 50 bucks :D aaron gets hius paycheck

**Comment by LostKing73** [comment]
no buying admin. vip, sure, whatever, but not admin

**Comment by CelestialKnight7** [comment]
make it so its renting vip, 10$ a month

**Comment by LostKing73** [comment]
> make it so its renting vip, 10$ a month

$20 for first month, $10 each mont after. how would we split the pay? or all proceeds go to arnab

**Comment by cs6413110** [comment]
Also we could put together a gofundme to unban jfl
The gpas are very passionate about that

**Comment by LostKing73** [comment]
:(

**Comment by 3foe** [comment]
1 chiken nuggie

**Comment by LostKing73** [comment]
bradleyyyyyyyyyyyyyyyy you broke gaaaaaaaaaaaame

**Comment by DarkMemeGod411** [comment]
so ur saying i would need to pay money?

**Comment by LostKing73** [comment]
> so ur saying i would need to pay money?

yea actually

**Comment by DarkMemeGod411** [comment]
Make the paying only for new vips. 
(im broke)

**Comment by 3foenation** [comment]
> oh so NOW we have a right to our opinion? well mine is this:
> 
> no VIP for gpa's. gpas are not people AT gpa, but players that are not:
> 
> LostKing bradley Celestial DarkMemeGod 3foenation (kinda) 3foe (ehhhhhhhh) cs641311
> 
> other requirements are:
> 
> being in the 10th grade or higher actually having a cell not having blackmailed not having a username that is a ripoff of someone else's not being tony34

so every GPA is now at eastmark and you know I don't have a phone so mabey rephrase that

**Comment by 3foenation** [comment]
i took away any other people vip so I will tell him about the change if we agree$20 the first month $10 then months after

**Comment by 3foe** [comment]
bru we are kidding about the money

**Comment by 3foe** [comment]
i think

**Comment by BreadSpammer** [comment]
bruh its pernament. 20$ for vip, the 10$ fee is only if u get ur vip demoted

**Comment by 3foenation** [comment]
k

**Comment by LostKing73** [comment]
> bruh its pernament. 20$ for vip, the 10$ fee is only if u get ur vip demoted

ok but only cuz its more simple and easier to keep track of

**Comment by BreadSpammer** [comment]
this wont be a thing that is on a website or anything bc that is effort. we just advertize to random gpas :D

**Comment by CelestialKnight7** [comment]
we'd have to nerf vips In this case cuz all of them will be spamming /kill

**Comment by DarkMemeGod411** [comment]
vip doesnt have /kill or /live

**Comment by CelestialKnight7** [comment]
huh, what do they have?

**Comment by LostKing73** [comment]
@CelestialKnight7 that's not all, i dont remember but u can use /help to see all

**Comment by DarkMemeGod411** [comment]
its outdated.

**Comment by LostKing73** [comment]
o, well like vips cant rly admin abuse

**Comment by LostKing73** [comment]
k, well we need this all wrote out, cuz @3foe is saying its $5 a month. @BreadSpammer write it out ples

**Comment by 3foe** [comment]
So Aaron coltin and I talked and this is what we came up with, VIP will cost 5$ a month and coltin will be the one to collect. It is easier to do 5 a month since a parent may notice 20$ missing from their child's piggy bank, so 5$ is ideal. It also means that after 5 months they have paid more money than if we went with 20$. We may make more money from the 10$ after that but if we take it away they feel like we are scamming them out of 20$.

**Comment by DarkMemeGod411** [comment]
so who would be paying the money?

**Comment by LostKing73** [comment]
the issue is that we would have to have coltin making sure that the prices are paid every month, and I do not in the slightest trust coltin

**Comment by DarkMemeGod411** [comment]
i do not want to pay money

**Comment by LostKing73** [comment]
> i do not want to pay money

we get it

**Comment by 3foe** [comment]
bruh current people don't have to pay

**Comment by BreadSpammer** [comment]
I say we add a new role "Moderator" which isn't admin level, but has powers to authoritize game, and then we nerf vip for the gpas. current VIPs get mod, so they aren't clumped in with the gpas. mods would have access to things like /allow, /lockchat, /lockdown, /ban, /pardon, /mute, /unmute, /vip, /removevip,  and all the vip things. vip would also lose mute and unmute, but will gain some new commands that will be available to all roles:

/Nick & /unnick. hides ur username, cosmetics, color, and etc for everyone else, other than you, and vice versa. (/playerlist will reveal nicked players)

/gpt >:)

VIPs and above will also have some extra perks:

10x and 100x crate opens
making private servers
access to github

**Comment by LostKing73** [comment]
not those last 3 tho, cuz

unfair advantage

unfair advantage(kill farm)

spam

**Comment by 3foenation** [comment]
> the issue is that we would have to have coltin making sure that the prices are paid every month, and I do not in the slightest trust coltin with money

why is that becuz you wont get it aaron will and I may or may not have him pay a service fee but he WILL get it and when he is gone it will go to matter ig

**Comment by LostKing73** [comment]
> > the issue is that we would have to have coltin making sure that the prices are paid every month, and I do not in the slightest trust coltin with money
> 
> why is that becuz you wont get it aaron will and I may or may not have him pay a service fee but he WILL get it and when he is gone it will go to matter ig

nope, its because

1. you don't know what a period is
2. you literally just said that you would take money for yourself
3. you are like, 7.

**Comment by LostKing73** [comment]
> k, well we need this all wrote out, cuz @3foe is saying its $5 a month. @BreadSpammer write it out ples

k, fine.

Can we agree on this:

VIP access costs $20. It is not a subscription; admins can remove members at any time. All admins must approve anyone purchasing VIP access.

**Comment by LostKing73** [comment]
> idk about that, my concerns about the money thing is still there and still unadressed

what concerns

**Comment by BreadSpammer** [comment]
we need to make a tanks club for this to actually work. like where else would we meet up with gpas to do transactions?

**Comment by LostKing73** [comment]
> we need to make a tanks club for this to actually work. like where else would we meet up with gpas to do transactions?

morning table ig. but I don't think the school would be chill with a club abt a game that is made to be immune to the schools restrictions

**Comment by LostKing73** [comment]
whatever, i guess done?
