### ISSUE TITLE
explosives deal self damage

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#178]
feature:

other than bomb(gonna be replaced anyways) all explosions (nuke,power, mega, dyna, etc) deal half damage to the user

nerfs gripple insta and gripple airsrike

**Comment by 3foe** [comment]
nuh uh

**Comment by 3foe** [comment]
look at any other battle royale/ team game Are there self-damaging things?

**Comment by BreadSpammer** [comment]
ye no lol. that would make fighting ppl so annoying. also just an uneeded nerf to explosions? liek airstrike dies, and tactical just becomes worse bc screw u.

**Comment by LostKing73** [comment]
agreed, but only bcuz of what bread said. flat... did u even think abt what u said before u said it?

**Comment by LostKing73** [comment]
> look at any other battle royale/ team game Are there self-damaging things?

YES
