### ISSUE TITLE
NEW MENU

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#179]
i created a new menu that took me a week but here it is
![pixilart-drawing (2)](https://github.com/user-attachments/assets/3e45ce50-f857-40aa-84e9-56dc4657ce21)

**Comment by 3foenation** [comment]
where the tank usually is you click on it and then you go to inventory

**Comment by LostKing73** [comment]
ew. how did that take a week. we also cant have circle buttons

**Comment by 3foenation** [comment]
why not circle

**Comment by LostKing73** [comment]
too hard to code? like stupid hard? not worth?

**Comment by 3foenation** [comment]
if i need to i can make them boxes I showed other people and they said it was the goat

**Comment by 3foenation** [comment]
just because you are lazy doesent mean we all are

**Comment by LostKing73** [comment]
bro. no. i said it was hard. not that I didn't feel like coding it.

**Comment by 3foenation** [comment]
so not everyone is lazy let everyone vote

**Comment by LostKing73** [comment]
it doesnt look good enough to match the effort needed to code circle buttons. @DarkMemeGod411 close please

**Comment by 3foenation** [comment]
also because you say no to everything I do I'm not going to accept your opinion

**Comment by LostKing73** [comment]
> also because you say no to everything I do I'm not going to accept your opinion

so because you don't like my opinion you arent going to accept it? that's not how that works

**Comment by 3foenation** [comment]
no beacues you opion is always no

**Comment by 3foenation** [comment]
so im sayoing no to no

**Comment by DarkMemeGod411** [comment]
i appreciate the effort, i really do. but i have to close the issue bc lk told me too. sorry

**Comment by LostKing73** [comment]
> no beacues you opion is always no

bcuz ur work is always lazy and not good. if it was good I would say yes. we also don't even need a menu?

**Comment by LostKing73** [comment]
thx alex

**Comment by 3foe** [comment]
Coltin the menu is 1) worse than the current one 2) unneeded as we have an up-to-date one 3) the GPAs are only saying its good because they want to be on your good side.

**Comment by BreadSpammer** [comment]
^^^ realest thing ive ever heard from flat in ever

**Comment by LostKing73** [comment]
so like what i was saying. thx ig
