### ISSUE TITLE
Single Player Rework

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#181]
basically a bunch of old ideas that im reviving and putting into this issue... *breathes*

1: new menu/level theme/system

basically, the levels will be split into worlds, kinda like mario, except they are just for zones, and dont really provide a gameplay purpose (unless we add special blocks). each world is unlocked linearly, but u unlock all levels in a world at the same time, and u only need to complete a specific number of levels in each word to progress (so if 1 level is impossible, wont ruin ppl's lives)

2: alternative objectives for levels

instead of literally just kill everyone for an objective, we can add more :). btw I'm nerfing stealth to ai. they can see u if they look directly at u, but not any other angle, and automatic detection will override invis.

these will make levels not only more interesting, but it will also have the potential to make them super duper imposible (protect the president when 8 enemies spawn on u)

MAIN OBJECTIVES: (what u need to do to beat the level)
- reach the end: the only goal is to get to the end of the level (marked in the editor). doesn't matter if everyone is alive... u just gotta make it there
- kill everyone: kill everyone
- survive: u just need to live for 1 minute to win this level. enemies will get longer and longer automatic detect ranges the longer the level goes on, in order to stop cheese.
- retrieval: get the key item at the goal, and then get back to spawn, alive. reach the end with extra steps
- assassination: a key personnel will spawn at the goal block. your job is to kill them, and that's it. there will often be other ai in your way, tho.
- escort:  u get a defense type ai that is ur teamate, and he has ur level. if he dies, u fail. otherwise identical to a "reach the end" level.

SIDE OBJECTIVES: extra missions for each type of level
- reach the end: pacifist (no kills), speedrun (beat in the time limit)
- kill everyone: no damage (git gud), speedrun
- survive: no damage, stealth (never seen by ppl u arent supposed to kill)
-  retrieval: pacifist, speedrun
- assassination: speedrun, stealth
- escort: no damage on teamate, no damage

if u want to make it like a cringe mobile game, u can add a 3 star system (1 star for beating the level, and 1 for each objective)

3: extra rewards:

actually give gud amounts of stuff when beating levels, along with extra for modifiers, bonus objectives, and our own handpicked difficulty rating.

ik it's a lot, but like it would make single player so much more fun if we added. so vote

**Comment by LostKing73** [comment]
so like, yes lol. this is exactly what I was saying

**Comment by LostKing73** [comment]
1 is what im thinking so i vote 1

**Comment by LostKing73** [comment]
wait bro 2 is leviathan levels, like trying to escape or smth

**Comment by DarkMemeGod411** [comment]
I like the defend the turret idea. I Would love to have that added

**Comment by DarkMemeGod411** [comment]
unrelated, Person2 just gmailed me

**Comment by DarkMemeGod411** [comment]
no, about "Theres a bug with single player where you k*ll someone" as the title

**Comment by DarkMemeGod411** [comment]
i deleted it instead of opening it

**Comment by LostKing73** [comment]
bruh just open it, its not a pipe bomb, and if its a bug then we need to fix???????

**Comment by CelestialKnight7** [comment]
> instead of literally just kill everyone for an objective, we can add more :). btw I'm nerfing stealth to ai. they can see u if they look directly at u, but not any other angle, and automatic detection will override invis.

don't, its supposed to be if they see u at all (when ur not invis or from the flicker) they will know where u are until u go further away where they will forget ur existance

**Comment by LostKing73** [comment]
so, like, @cs6413110 , give bread nugs for this. he literally stole my cell and used it in this and that's so funny. this is pretty much the exact idea in my head

**Comment by 3foe** [comment]
slight issue, we get rewards but what are coins used for when u get rank 20?

**Comment by LostKing73** [comment]
> slight issue, we get rewards but what are coins used for when u get rank 20?

perks, classes

**Comment by DarkMemeGod411** [comment]
make the turret ai able to see them. so normal ai can't see them but turrets can in single player

**Comment by BreadSpammer** [comment]
> make the turret ai able to see them. so normal ai can't see them but turrets can in single player

nah lets just make it so ai can see u at close quarters, like actual players. most survival levels would be longer then their cooldown time anyway

**Comment by CelestialKnight7** [comment]
> > > instead of literally just kill everyone for an objective, we can add more :). btw I'm nerfing stealth to ai. they can see u if they look directly at u, but not any other angle, and automatic detection will override invis.
> > 
> > 
> > don't, its supposed to be if they see u at all (when ur not invis or from the flicker) they will know where u are until u go further away where they will forget ur existance
> 
> I mean ig, but like I don't want stealth to cheese a large majority of the levels. they could just hide/sneak past all of the ai in surival levels and reach the end levels :/

ok but then stealth would be worse at other levels where u have to kill everything (unless u can pick them off 1 by 1).
I mean it basically saying that stealth shouldn't be good at 'stealthing'.

**Comment by CelestialKnight7** [comment]
> slight issue, we get rewards but what are coins used for when u get rank 20?

porks

**Comment by BreadSpammer** [comment]
already have a solution so problem solved :D

**Comment by CelestialKnight7** [comment]
but what if u leave close quarters will the ai still know?

**Comment by LostKing73** [comment]
also, you still cant gripple ai

also also, the shooting animation is still broken in singleplayer

**Comment by 3foe** [comment]
and level 9 is  basically impossible due to lag

**Comment by 3foe** [comment]
have u played it?

**Comment by LostKing73** [comment]
> have u played it?

yes. its not that hard.

**Comment by 3foe** [comment]
... It's laggy, and the grapple is slower than a normal player. you haven't played it and you are lying to everyone here

**Comment by LostKing73** [comment]
> ... It's laggy, and the grapple is slower than a normal player. you haven't played it and you are lying to everyone here

idk why its laggy, but u don't gotta accuse me dude. i literally did. its a bunch of long tunnels leading to an open area with some blocks spread about in clusters with a ton of ai. i literally am like ht1 in this game

**Comment by BreadSpammer** [comment]
It's not that ai are har for u, it's hard for new players

**Comment by BreadSpammer** [comment]
Also lk ur not ht1 lol. Level 9 is easily beatable if u take ur time and use the correct items

**Comment by LostKing73** [comment]
> Also lk ur not ht1 lol. Level 9 is easily beatable if u take ur time and use the correct items

describe ht1 then

**Comment by CelestialKnight7** [comment]
shut about ur made up minecraft ranks. everyone is bad at game except aaron

**Comment by cs6413110** [comment]
*4k footage of aaron dying to ai*

**Comment by BreadSpammer** [comment]
ai are like hard to fight fair in like a 1v10, but are ez to cheese.

**Comment by LostKing73** [comment]
> ai are like hard to fight fair in like a 1v10, but are ez to cheese.

Bro, anything is hard in a 1v10, that doesnt mean ai is hard

**Comment by BreadSpammer** [comment]
all of the world maps for single player (not resized yet so like ded).

and yes, ik i included 100 buttons. shouldnt be that hard to make 100 unique levels with all the modifiers we can add to it, and we will probably add more as we make levels

![world1](https://github.com/user-attachments/assets/a970b57b-062b-49aa-bd1b-d2cd08547ab3)
![world2](https://github.com/user-attachments/assets/6156f79c-af10-4bc3-95f1-65bef657352b)
![world3](https://github.com/user-attachments/assets/014167ab-dbef-45ad-b9d5-577cd71b5773)
![world4](https://github.com/user-attachments/assets/ea4679d3-7971-47a3-bba4-1a7e23bd4779)
![world5](https://github.com/user-attachments/assets/dd50ebd6-7809-413a-af0d-62108e6812be)

**Comment by LostKing73** [comment]
ONE HUNDRED??? bro, like, we are gonna not have to release all at once, like over time

**Comment by LostKing73** [comment]
ugh but dont expect max quality

**Comment by 3foe** [comment]
I can do levels and help yall with it, also LK I get u put time and effort into the images for the levels but I think it should be unique and have the level pattern different cause what u got is just a recolor. its not that big of a deal but fixing that menu should be on our radar

**Comment by 3foe** [comment]
also send a screen shot of the level

**Comment by BreadSpammer** [comment]
ok so like 1: no. 2: @cs6413110 u need to add all of the modes for single player like reach the end, and survive, and all the fail objectives so we can do real level design instead of just random spam 🔫

**Comment by cs6413110** [comment]
We haven't talked enough about the different singleplayer types.

**Comment by BreadSpammer** [comment]
It's on the thing. Ngl the defend one is cringe, but the other 2, u should work on. Do survive first bc it's ez to code. Just make it also check for if the timer runs out along with the enemy count

**Comment by BreadSpammer** [comment]
@cs6413110 5-0 vote CODEEEEEE

**Comment by CelestialKnight7** [comment]
gud:
- kill everything
- get to exit
- survive

we really only need 3 just to add some diversity and mix up the gameplay

**Comment by LostKing73** [comment]
get to exit is good cuz leviathaann woooo

**Comment by BreadSpammer** [comment]
ye but I kinda just made defense bc out of ideas. I removed and added 2 more which make more sense

**Comment by BreadSpammer** [comment]
where is my @cs6413110 >:(. literally ignoring this issue

**Comment by BreadSpammer** [comment]
ok so I think imma change the fail objectives to side objectives, and certain fail conditions will be changed to whole missions

**Comment by BreadSpammer** [comment]
edited the top comment to include the new bonus objective system

**Comment by cs6413110** [comment]
1.) Which levels will be which level type?
- The current menu doesn't have anything for that
- I doubt we have the capacity to make a new menu

2.) What will AI rank be based on? (Editor/Player Rank/Level Number)

3.)

Ok with:
- Genocide
- Extraction
- Survival

Not ok with:
- Boss fights(We can't even make basic AI)

Extra XP/Money stuff I'm ok with:
- Breaking every block
- < 2mins

Maybes:
- No damage(so annoying if you screw up, plus not really realistic)
- don't break any blocks(dum, also have you seen level design?)
- No class/items/etc.



Coding:
Possible level editor output:
[*level type*[1-3], *maybe rank range*, *zone*, *level code*],

Should be easy from there. Multiplayer will ignore the first one.

**Comment by BreadSpammer** [comment]
1. Level type is decided in the editor

2. Rank = (world number - 1)*5. So world 1 = rank 0, world 2 is rank 5, and etc

**Comment by BreadSpammer** [comment]
3 = check main comment instead of Evan's. Also I think we should change no damage to full hp, no toolkit.

**Comment by BreadSpammer** [comment]
so like code, and make the ai their right level ((world number-1)*5)
world 1 = 0, world 2 = 5, world 3 = 10, world 4 = 15, world 5 = 20

**Comment by BreadSpammer** [comment]
### literally not coded

**Comment by cs6413110** [comment]
Accidently typed fix before the issue number in the commit so...

**Comment by cs6413110** [comment]
Need better pause menu

**Comment by BreadSpammer** [comment]
add rewards to win menu (when the game ends, add parameters to the function, that you can put extra numbers into)
