### ISSUE TITLE
Better Matchmaking

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#184]
Basically, multiplayer gamemodes will be split into 2 categories: casual, and competitive, to make game more fair

Casual games are basically just to hang out and play with friends, with no real attention to balance. U can join games with anyone despite the rank difference. This is for ffa, and defense.

Competitive games are for like actually trying to play. The game will refuse to match u with players that are atleast 5 ranks higher than u. If ur game doesn’t fill up by 40 seconds, the next 20 seconds, the game will gradually fill up with bots to play with u, so even when no one is online, ppl can still play all the gamemodes. You can manually join a game while underleveled, but you can’t join an under leveled game as a high rank. This is for duels and tdm

This lets low rank ppl actually play the game and feel gud bc they aren’t getting 2 shot

**Comment by CelestialKnight7** [comment]
pass

**Comment by BreadSpammer** [comment]
not coded uh uh uh :)

**Comment by LostKing73** [comment]
no. too much work rn, and not needed(case in point: remvise absolutely obliterating lvl 20s)
