### ISSUE TITLE
Ai are too op

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#185]
They have frame perfect reaction times, have unpredictable movement, perfect aim, no cooldowns, etc. 

they need to have more predictable movement, and have chances to not aim perfectly, and have their game view delayed by a set time depending on rank to simulate human reaction times

**Comment by CelestialKnight7** [comment]
skill issue

**Comment by BreadSpammer** [comment]
stop saying skill issue. its an actually problem. even if the best players can beat them, its not like someone who haso nly played for 3 minutes can. they need nerfing

**Comment by LostKing73** [comment]
> stop saying skill issue. its an actually problem. even if the best players can beat them, its not like someone who haso nly played for 3 minutes can. they need nerfing

no, like, that's how you learn? ai literally only need to be fixed, not nerfed. they arent op at all, and singleplayer just shouldn't have only level 20 ais if u rly think they need a nerf

**Comment by BreadSpammer** [comment]
Ye, 2 birds with 1 stone. Delete complexity so it optimizes game, and makes them easier to fire

**Comment by LostKing73** [comment]
eh sure idc. i can dtap them either way

**Comment by cs6413110** [comment]
3rd quarter
