### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#186]
@BreadSpammer
- Filter out old images
- Give me spike trap info
- Redo item images

@CelestialKnight7
- New perk image
- Breacher Image
- Micromanage bradley images

@DarkMemeGod411
- Make steam description
- Research

@LostKing73 
- Consolidate zone info
- Vote on leviathan thing

@cs6413110 
- Remove perk 7's 2nd and 3rd levels
- Make keybind names user-friendly
- Zones
- AI
- Singleplayer
- Shops

Nug Requirements:
- All items finished
- All perks finished

**Comment by LostKing73** [comment]
ugh but like why vote when you could just addddddddddddddddd

**Comment by DarkMemeGod411** [comment]
so? wdym by research?

**Comment by LostKing73** [comment]
so, when u say consolodiate or whatever zone info, what u need to know? gimmi list

**Comment by LostKing73** [comment]
@cs6413110 I need to know now cuz i cant do after school

**Comment by BreadSpammer** [comment]
Everyone else: 1 img, a paragraph, some info

Bread: 12 Picasso level paintings

**Comment by cs6413110** [comment]
Bro forgot my todo list

> Everyone else: 1 img, a paragraph, some info
> 
> Bread: 12 Picasso level paintings

**Comment by cs6413110** [comment]
I actually have so much homework I can't remember all of it at once and need to write the cringe down

**Comment by BreadSpammer** [comment]
ik urs sucks but like im also procrastinating stuff brh

**Comment by cs6413110** [comment]
> ik urs sucks but like im also procrastinating stuff brh

Then do homework instead of playing crystal?

**Comment by BreadSpammer** [comment]
nah

**Comment by DarkMemeGod411** [comment]
Wdym by research, i understand the steam desc. but what do u want me to research?

**Comment by LostKing73** [comment]
> so, when u say consolodiate or whatever zone info, what u need to know? gimmi list

@cs6413110 . what do you mean by consolidate zone info. what do you need to know

**Comment by BreadSpammer** [comment]
*lag byea*

**Comment by LostKing73** [comment]
> Tell me what needs to be done.

uh, like, 

1. deciding if we have enough zones
2. making 3 maps for each zone
3. coding and implementing
