### ISSUE TITLE
Leviathan Vote

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#187]
_sigh_ I guess I have to put this to a vote, but let me give you a little reminder beforehand.

### The Leviathan

The Leviathan is a creature located in the depths that represents a failed creation. It is a large, unkillable "boss" designed for single-player mode. The Leviathan roams around in its idle animation, moving at the same speed as a walking tank, until it spots a player directly in front of it. At that point, it will charge at the player with the speed of a boost before slowing down slightly to maintain a speed just below that of a boost.

If the Leviathan grabs you, you will be trapped in its mouth for 5 seconds before being crushed. While you're in its mouth, you can use the gripple to escape; however, you will take damage over time while being crushed. The lower your health, the faster you will be crushed.

The Leviathan is intended to be an obstacle, not an enemy. Missions involving the Leviathan focus solely on escape and survival. This addition is new and will likely be a surprise for players who are not expecting it.

**Comment by LostKing73** [comment]
vote on comment above, but if u have amnesia

👍 yes
👎 no

**Comment by LostKing73** [comment]
If you intend to downvote or have any questions, please ask. I want this to be approved, and if I can persuade you to approve it or clarify any doubts, I would be happy to do so.

**Comment by CelestialKnight7** [comment]
I want to murder it, even in Subnautica u can kill the leviathans if u try hard enough

**Comment by CelestialKnight7** [comment]
just give it like 3000 hp

**Comment by LostKing73** [comment]
so, the issue with that, is that it would be really easy to kill, even if we gave it like 10000 hp. because if you just follow behind it, it'l almost never get you. and if you DO kill it, the entire mission is just empty and not a challenge anymore. If there were, like, 3 leviathans at once, maybe, but idk, I just feel like that wouldn't be as good as just making it unkillable

**Comment by BreadSpammer** [comment]
only once entire game gets finished.

**Comment by LostKing73** [comment]
> only once entire game gets finished.

right. this is post-zones, which is one of the last on the list

**Comment by CelestialKnight7** [comment]
make it attack you more aggressively if you attack it, and give it turrets

**Comment by CelestialKnight7** [comment]
u could still say its a failed/escaped experiments as the experiment was an attempt to weaponize it that backfired cuz u just gave a bunch of guns to a creature that you've been torturing for whatever long

**Comment by LostKing73** [comment]
> make it attack you more aggressively if you attack it, and give it turrets

listen, turrets will not look good, and will just make it more complicated. its supposed to be a hunt, and not feel like you are doing a giant snake shooting bullets. 

can you clarify what you mean by more aggressively?

**Comment by CelestialKnight7** [comment]
my idea of what this would look like is eater of worlds and destroyer of worlds from terraria, it feels like ur making eater of worlds cuz that mainly just has a charge attack and its own fat. while I'm trying to make destroyer of worlds cuz its more mechanical and has turrets and I think would be more fun to either escape or attempt to fight

**Comment by LostKing73** [comment]
had to rewrite with ai to understand it gimmie 1 sec

If you attack it, its window for retaliating will be shorter, meaning it will launch more frequent attacks against you. Additionally, it will not simply leave you alone after a while (I'm not sure if it would do that initially or not); it will continue to pursue you relentlessly.

**Comment by LostKing73** [comment]
oh ok, yea that aggresion system works. all of it.

**Comment by CelestialKnight7** [comment]
> my idea of what this would look like is eater of worlds and destroyer of worlds from terraria, it feels like ur making eater of worlds cuz that mainly just has a charge attack and its own fat. while I'm trying to make destroyer of worlds cuz its more mechanical and has turrets and I think would be more fun to either escape or attempt to fight

also I'm not talking like every segment or just all over, I'm talking like 2 or 3 turrets

**Comment by LostKing73** [comment]
> my idea of what this would look like is eater of worlds and destroyer of worlds from terraria, it feels like ur making eater of worlds cuz that mainly just has a charge attack and its own fat. while I'm trying to make destroyer of worlds cuz its more mechanical and has turrets and I think would be more fun to either escape or attempt to fight

eater of worlds is like exactly what it is. listen, how about we add it WITHOUT turrets, and if we feel like it need something extra, that will be what we try first.

**Comment by CelestialKnight7** [comment]
ok

**Comment by CelestialKnight7** [comment]
also I think it would be better to not just have the grab attack, but also a charge attack (pretty much just warrior, it charges at u and if it hits u, u take damage but it doesn't grab you, I imagine this attack would happen more often than the grab one cuz if its constantly grabbing you it could get annoying

**Comment by LostKing73** [comment]
> also I think it would be better to not just have the grab attack, but also a charge attack (pretty much just warrior, it charges at u and if it hits u, u take damage but it doesn't grab you) I imagine this attack would happen more often than the grab one cuz if its constantly grabbing you it could get annoying

the issue with that is that its face is the weapon. if it charges, it would slam you into its mouth. Also, this would kind of mess with its attack method, because it chases you down normally.

**Comment by LostKing73** [comment]
> I'm with Evan, I want murder

k... I've already agreed to that, but like just so yall know, attacking it wouldn't be worth it. it would have like 10k hp and not give xp. if it gave xp, people could just farm it.

**Comment by cs6413110** [comment]
Nah, post steam

**Comment by LostKing73** [comment]
> I'm with Evan, I want murder

and if that's all you needed, then upvote please

**Comment by LostKing73** [comment]
> Nah, post steam

huh?

**Comment by LostKing73** [comment]
oh what? thats like REALLY far in the future tho, is it not?

**Comment by LostKing73** [comment]
> Tired of coding functionality while waiting for images and user-friendliness to catch up

like, uh, fix. read todo list (now fix list cuz flat=dum)

**Comment by LostKing73** [comment]
bro. @CelestialKnight7 @3foe your problems are solved. why still downvote.

**Comment by LostKing73** [comment]
thank you 3foe. @CelestialKnight7 is busy i assume

**Comment by LostKing73** [comment]
> only once entire game gets finished.

@BreadSpammer please upvote if you have approved

**Comment by LostKing73** [comment]
> will upvote when entir game is finished

n-no. this vote is now. i need to know that is approved if I am to work on it. the entire game will be finished months from now. please upvote now, or your vote will simply be treated as an upvote, since you have agreed to upvote in the future.

**Comment by BreadSpammer** [comment]
lag bye

**Comment by LostKing73** [comment]
bruhhhhhhhhhh

**Comment by LostKing73** [comment]
@cs6413110 ?

**Comment by cs6413110** [comment]
cuz don't wanna code

**Comment by LostKing73** [comment]
wwell im sure bread would help.

**Comment by LostKing73** [comment]
> bread can't code something like that

well like teach, idk.

**Comment by CelestialKnight7** [comment]
> > I'm with Evan, I want murder
> 
> k... I've already agreed to that, but like just so yall know, attacking it wouldn't be worth it. it would have like 10k hp and not give xp. if it gave xp, people could just farm it.

to discourage people from farming it make it really dangerous so that actually killing it would be near impossible. also its like the warden from mc, idk what it drops I wanna murder it

**Comment by CelestialKnight7** [comment]
> > bread can't code something like that
> 
> well like teach, idk.

bread cannot learn its bread

**Comment by CelestialKnight7** [comment]
I'll upvotes if it it gives money/xp when it dies, and to balance this, good luck actually killing it

**Comment by CelestialKnight7** [comment]
also I agree with Aaron, cool project and all but we need the game to be actually done first

**Comment by LostKing73** [comment]
> also I agree with Aaron, cool project and all but we need the game to be actually done first. I also like the idea of enemy variety and not just all tanks

100% I agree to not do this first.

**Comment by LostKing73** [comment]
> > > I'm with Evan, I want murder
> > 
> > 
> > k... I've already agreed to that, but like just so yall know, attacking it wouldn't be worth it. it would have like 10k hp and not give xp. if it gave xp, people could just farm it.
> 
> to discourage people from farming it make it really dangerous so that actually killing it would be near impossible. also its like the warden from mc, idk what it drops I wanna murder it

it is like very hard to kill, and with 10k hp and this aggression system... ig. sure. but like, not so much to where u  level up 20 times. like, 2.5k xp and 20k gold?

**Comment by CelestialKnight7** [comment]
> > > > I'm with Evan, I want murder
> > > 
> > > 
> > > k... I've already agreed to that, but like just so yall know, attacking it wouldn't be worth it. it would have like 10k hp and not give xp. if it gave xp, people could just farm it.
> > 
> > 
> > to discourage people from farming it make it really dangerous so that actually killing it would be near impossible. also its like the warden from mc, idk what it drops I wanna murder it
> 
> it is like very hard to kill, and with 10k hp and this aggression system... ig. sure. but like, not so much to where u level up 20 times. like, 2.5k xp and 20k gold?

sounds good to me (I have no idea why the xp and gold economy is like)

**Comment by BreadSpammer** [comment]
Note: it takes 20100 xp for rank 20

**Comment by BreadSpammer** [comment]
Also I don't like leviathan bc this is literally just a funny tank game. Like why snake,?

**Comment by LostKing73** [comment]
> Also I don't like leviathan bc this is literally just a funny tank game. Like why snake,?

why not>

**Comment by LostKing73** [comment]
actually. why not

**Comment by LostKing73** [comment]
@DarkMemeGod411 for cleanliness, please hide all comments as "resolved"

**Comment by 3foe** [comment]
ye that too many comments that ain't happening

**Comment by LostKing73** [comment]
bruh nobody asked you flat. stop hate spamming

**Comment by LostKing73** [comment]
won so closing
