### ISSUE TITLE
Banners Vote

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#189]
are we still doin this? 

(copied from Celestial) after the war we now have an actually decent idea for banners, they would show up maybe at the start of a round to flex, and when you are killed. you can add stats to your banner to flex, choose the background, and your tonk will be the pfp (cosmets and all).

kinda like apex:
![image](https://github.com/user-attachments/assets/566ce839-1307-4660-a7d1-64e111695dfe)

You can choose 3 stats, and like uh yea

votage

**Comment by LostKing73** [comment]
why downvote, @DarkMemeGod411 ?

**Comment by DarkMemeGod411** [comment]
wait, wrong issue sorry

**Comment by LostKing73** [comment]
> wait, wrong issue sorry

oookay

**Comment by LostKing73** [comment]
u wnna upvote then?

**Comment by DarkMemeGod411** [comment]
can i have it say "has played for 4 1/2 years"

**Comment by LostKing73** [comment]
> can i have it say "has played for 4 1/2 years"

time played might be something we consider.

**Comment by BreadSpammer** [comment]
Again, after game done
