### ISSUE TITLE
[VOTE] Lore

### ISSUE THREAD

**Issue by BreadSpam** [cs6413110/Pixel-Tanks#19]
read both lore pages in the wiki (bread's lore & lk's lore), and vote on which is better (or less cringe)
note that mine is unfinished

🚀 = bread's version
👀 = lostking's version
👎 = both shut cring

**Comment by BreadSpam** [comment]
@LostKing73 @DarkMemeGod411 @cs6413110 @CelestialKnight7 VOTEEEE

**Comment by LostKing73** [comment]
bruh. no voting. this isnt something that is worth our time.

**Comment by LostKing73** [comment]
i made the lore as a little easter egg that ties in well with Zones. revising the lore isn't smth I'm against, but making completely new lore is uneccary

**Comment by BreadSpam** [comment]
bad lostking

**Comment by LostKing73** [comment]
omggggggg like whyyyyyyyyyyyy

**Comment by LostKing73** [comment]
nyeh

**Comment by CelestialKnight7** [comment]
both ur lores suck

**Comment by LostKing73** [comment]
> both ur lores suck

it doesnt matter, just leave as is is my point

**Comment by CelestialKnight7** [comment]
solved

**Comment by LostKing73** [comment]
alr, evan dont delete this

whats been decided:

bread will attempt to make hislore work with mine as a sort of prequel.

**Comment by BreadSpam** [comment]
k sure I'll do that

**Comment by LostKing73** [comment]
^^^ by???

**Comment by LostKing73** [comment]
reminder, bread, that it has to fit in with my lore, it cant be just some random blurb

**Comment by LostKing73** [comment]
revoked cuz bread is dumb and doesnt know how to work together

**Comment by BreadSpam** [comment]
bruh ur lore is so weird?? why is there light and dark and why r u the main character??? tanks isn't a fantasy world

**Comment by BreadSpam** [comment]
cant combine bc it's so bad

**Comment by LostKing73** [comment]
can u like stop baby raging? i gave you your pacifier, now just keepto urself. i don't want new players to think ur lore is real, that's why I'm changing the title.

**Comment by LostKing73** [comment]
im also not the main character, and why cant it be?
