### ISSUE TITLE
Sprays

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#190]
emotes replacement

### The Basics

Using a key(that cant be reminded for simplicity's sake, like ` or smth) you "spray" smth that you chose in ur inv on the floor.
you can also place the on your blocks in the inv, so when u place a block, it has the spray on it kinda like a sticker.

### Why add this?
is cool, can differentiate blocks from placed blocks

### Voting
👍 ye
👎 nah(comment y)

**Comment by LostKing73** [comment]
i say nah cuz like effort

**Comment by BreadSpammer** [comment]
Ded
