### ISSUE TITLE
IRL shops

### ISSUE THREAD

**Issue by DarkMemeGod411** [cs6413110/Pixel-Tanks#192]
(LK idea)
1: i have made the 3d model of the tanks block. 
2: sell the models
3: we get money
4: aaron gets all money earned
5: aaron profits
github wont let me upload the files so trust me :)

**Prices**
block: $5.00
Tank: $20.00

**Comment by LostKing73** [comment]
honestly, merch isnt a bad idea.(i say this bcuz i came up with it first)

**Comment by DarkMemeGod411** [comment]
make tanks shirts

**Comment by LostKing73** [comment]
watchu mean "kinda"?!

**Comment by DarkMemeGod411** [comment]
the 3d printing was my idea

**Comment by LostKing73** [comment]
ok whatever its nobodies idea

**Comment by BreadSpammer** [comment]
Merch store

**Comment by DarkMemeGod411** [comment]
update: jonas was right.

**Comment by LostKing73** [comment]
> update: jonas was right.

right abt? the fact u cant print it? bcuz obv u cant? not without a printer?

**Comment by BreadSpammer** [comment]
ok so like about giving all the money to Aaron... he is like deathly allergic to spending money. I say the funds go into funding the tanks club or something. although it doesn't really matter if we don't get any money so FIX

**Comment by 3foe** [comment]
naw money goes into getting bread nugs

**Comment by DarkMemeGod411** [comment]
yeah, i modeled it. github wont let me upload the file so...

**Comment by 3foe** [comment]
also, Aaron and I have a 3D printer. Aaron is the only one who knows how to use it lol XD but I can have him tell me how to use it and then we can make the merch.

**Comment by DarkMemeGod411** [comment]
what prices ar we thinking?
Blocks will be $2-$5 each?

**Comment by LostKing73** [comment]
$5 each, no deal on a bundle

**Comment by DarkMemeGod411** [comment]
Should we make small ones for cheaper. or only one size?

**Comment by LostKing73** [comment]
> Should we make small ones for cheaper. or only one size?

only one size. and said size is .7 in I think

**Comment by LostKing73** [comment]
and maybe like a "art from LostKing" thing, like a drawing of The Leviathan or smth, signed, for $20 if they want that for some reason

**Comment by DarkMemeGod411** [comment]
yeah. the printed tanks for $20? $30?

**Comment by LostKing73** [comment]
20.

**Comment by LostKing73** [comment]
and i just need to size them properly

**Comment by 3foe** [comment]
jonas, I don't think that anybody wants a signed copy of the Leviathan, loi the GPAs hate you. maybe they could pay for u not to sign it?

**Comment by DarkMemeGod411** [comment]
3foe that was uncalled for.

**Comment by DarkMemeGod411** [comment]
anyway. shops are a good idea

**Comment by LostKing73** [comment]
> jonas, I don't think that anybody wants a signed copy of the Leviathan, loi the GPAs hate you. maybe they could pay for u not to sign it?

alex isn't wrong. you didn't need to instagate me.

**Comment by 3foe** [comment]
no i'm serious we could capitalize on that

**Comment by 3foe** [comment]
like money, also thoughts about actually doing a GoFundMe for JFL?

**Comment by LostKing73** [comment]
> like 5 dollars for an unsigned one and 3 for a signed one. they hate you so they actually might do that

dude.

**Comment by 3foe** [comment]
Hey i'm asking you what you want to do. its a suggestion, and they do hate you btw.

**Comment by 3foe** [comment]
for the go fund me aaron and I spit balled it yesterday, we said we would have to ask u so jonas, thoughts?

**Comment by LostKing73** [comment]
> Hey i'm asking you what you want to do. its a suggestion, and they do hate you btw.

literally tony. and its bcuz I'm like the only admin that actually moderates

**Comment by DarkMemeGod411** [comment]
So the prices at the top are accurate?
also aaron gets free copys of all products

**Comment by LostKing73** [comment]
> So the prices at the top are accurate? also aaron gets free copys of all products

bruh, all admins get free stuff

**Comment by LostKing73** [comment]
> like 5 dollars for an unsigned one and 3 for a signed one. they hate you so they actually might do that

1. they don't ALL hate me, like, only the abusers and people you lied to
2. giving out non-signed art is dum. they can just put their signature on it and say its theirs

**Comment by DarkMemeGod411** [comment]
should we do requests? like if someone wants a specific color to make their tank irl?

**Comment by LostKing73** [comment]
also, i made a tank model a bit ago, here's info for it

$20 for black, $25 for a color from what you have available, and whatever a roll would cost+$30 for a custom color

**Comment by DarkMemeGod411** [comment]
![Screenshot 2024-11-22 12 01 44 PM](https://github.com/user-attachments/assets/f26b4dd3-cdb0-410b-9450-5ed926460699)
![Screenshot 2024-11-22 12 01 23 PM](https://github.com/user-attachments/assets/a0ed5842-1ea5-4a0b-8e56-f8e398c969e9)
I made the model. took all of 5 minutes

**Comment by DarkMemeGod411** [comment]
if needed i have a bulk file with 4 of em to print at once

**Comment by LostKing73** [comment]
waaaaaaaaaaaaay too deep. i literally said make LESS deep

**Comment by LostKing73** [comment]
you cant look at the first image and say it looks the same

**Comment by BreadSpammer** [comment]
1: edges are sharp, not square
2: ye deep af. i say make the corners at NOT a 45 degree angle. like half that probably
3: just lemme do lol

**Comment by DarkMemeGod411** [comment]
not as deep as u think

**Comment by BreadSpammer** [comment]
false lol

**Comment by LostKing73** [comment]
literally we have eyes. bread do, alex work on maps :/

**Comment by BreadSpammer** [comment]
the more I look at the block texture, the more I realized the lighting Is wrong if that's how it actually looks.

its either inverted, or the lighting is from the other corner lol

**Comment by LostKing73** [comment]
> the more I look at the block texture, the more I realized the lighting Is wrong if that's how it actually looks.
> 
> its either inverted, or the lighting is from the other corner lol

yea the coloring is wrong, but don't change cuz it still looks good

**Comment by LostKing73** [comment]
@BreadSpammer do, alex doesnt know how to

**Comment by LostKing73** [comment]
> Dead issue?

honestly yea

**Comment by LostKing73** [comment]
not doing, k bye

**Comment by DarkMemeGod411** [comment]
Ik this issue is ded. But.. ![20241201_064539.jpg](https://github.com/user-attachments/assets/edd0ee31-a4c7-4d19-b36d-67ff345d88e7)

**Comment by DarkMemeGod411** [comment]
@LostKing73 ez?

**Comment by LostKing73** [comment]
idk dude. doesnt change the past
