### ISSUE TITLE
FIX THIS IS SO BROKEN

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#193]
@CelestialKnight7 @BreadSpammer @cs6413110 @DarkMemeGod411 
![image](https://github.com/user-attachments/assets/e3c55b45-6e8e-44bd-afea-18df41f57140)

**Comment by LostKing73** [comment]
i tried, and it works

**Comment by cs6413110** [comment]
*sigh*

**Comment by LostKing73** [comment]
i got like a million dollars in 5 minuets

**Comment by cs6413110** [comment]
```javascript
ondeath(t, m) {
    if (t.username !== PixelTanks.userData.username) {
      let e = 0;
      for (const ai of this.ai) if (Engine.getTeam(ai.team) === 'squad') e++;
      if (e === 1) {
        setTimeout(() => {
          PixelTanks.user.player.implode();
          Menus.menus.victory.stats = {kills: 'n/a', coins: 'n/a'};
          Menus.trigger('victory');
        }, 3000)
      }
      return PixelTanks.user.player.killRewards();
    }
    t.ded = true;
    PixelTanks.user.player.implode();
    Menus.menus.defeat.stats = {kills: 'n/a', coins: 'n/a'};
    Menus.trigger('defeat');
  }
```

Shouldn't be happening.

**Comment by cs6413110** [comment]
Someone messed with singleplayer code so I'm just breaking it further

**Comment by LostKing73** [comment]
remove single player, make a test server, fix/test on test server, then re-release

**Comment by 3foe** [comment]
the glitch isnt workign for me

**Comment by LostKing73** [comment]
> the glitch isnt workign for me

dk

**Comment by 3foenation** [comment]
same here exept it works for my alt i think it is the lvl but Ig not becuz lk could not fo it

**Comment by LostKing73** [comment]
dude. have you been to any english class ever?

**Comment by LostKing73** [comment]
Same here, except it works for my alternate account. I think it is the level, but I guess not because LostKing couldn't do it.

**Comment by LostKing73** [comment]
that easy

**Comment by LostKing73** [comment]
> Same here, except it works for my alternate account. I think it is the level, but I guess not because LostKing couldn't do it.

however, I just said that I COULD do it.

**Comment by 3foenation** [comment]
this is the glich in motion WE need to fix it 
[Uploading Screen recording 2024-11-22 9.57.36 AM.webm…]()

**Comment by 3foenation** [comment]
umm ok it no work

**Comment by 3foenation** [comment]
[Screen recording 2024-11-22 9.57.36 AM.webm](https://github.com/user-attachments/assets/77c8a0d7-0c6f-4202-9117-ff87c76d1a65)

**Comment by 3foenation** [comment]
there

**Comment by cs6413110** [comment]
Somehow, ondeath calls aren't giving the entity that is being killed(you), resulting in it thinking you killed an AI.

**Comment by LostKing73** [comment]
how are yall screen recording lol

**Comment by 3foenation** [comment]
do screenshot then at the settings area click the video  sign

**Comment by DarkMemeGod411** [comment]
> do screenshot then at the settings area click the video sign

That works?

**Comment by LostKing73** [comment]
> > do screenshot then at the settings area click the video sign
> 
> That works?

nooooooooooooooo hes just lieing
