### ISSUE TITLE
Pixel Tanks Club

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#195]
its exactly what it sounds like. we need to make a club for general tanks work and for big events. we also need a place to sell the stuff (vip, blocks, pardons).

so like anyone know how clubs work? how they are made, what are the requirements, etc.

also funds will go into the club for things like sugar :)

**Comment by LostKing73** [comment]
as i said in the vip issue,

I don't think the school would be chill with a club abt a game that is made to be immune to the schools restrictions

**Comment by BreadSpammer** [comment]
ok but like how do u even make one?

**Comment by BreadSpammer** [comment]
we could just call it a "video game" club on the outside

**Comment by LostKing73** [comment]
> we could just call it a "video game" club on the outside

already is one

**Comment by cs6413110** [comment]
I think we need a sponsor

**Comment by LostKing73** [comment]
> ok but like how do u even make one?

you need a teacher ik that

**Comment by BreadSpammer** [comment]
hALP all my teachers suck :(

**Comment by BreadSpammer** [comment]
and/or don't like me

**Comment by LostKing73** [comment]
> ok then just call it coding club

pretty sure that's already a thing.

**Comment by cs6413110** [comment]
https://ehs.qcusd.org/Clubs

**Comment by cs6413110** [comment]
We need suitable bans and profanity filters to be able to make a club for this

**Comment by LostKing73** [comment]
yall. I don't think the school would be chill with a club abt a game that is made to be immune to the schools restrictions

**Comment by BreadSpammer** [comment]
there is no such thing as a "video game club", but like if we called it that, then random ppl would join

**Comment by BreadSpammer** [comment]
well there is obviously e sports

**Comment by 3foenation** [comment]
how would we make pixel tanks competive tho

**Comment by BreadSpammer** [comment]
its not? lol. that's not the point of the club

**Comment by LostKing73** [comment]
> there is no such thing as a "video game club", but like if we called it that, then random ppl would join

there is. they changed the name

**Comment by BreadSpammer** [comment]
ok so like what if we just showcase the game on something that's not a Chromebook, so they don't know that ppl can play on chrumb

**Comment by LostKing73** [comment]
> ok so like what if we just showcase the game on something that's not a Chromebook, so they don't know that ppl can play on chrumb

like wut. and why would ppl join if its advertised and not bein on chrumbs

**Comment by BreadSpammer** [comment]
we don't have normal ppl join lol. its for ppl who already know what pixel Tanks is

**Comment by LostKing73** [comment]
> we don't have normal ppl join lol. its for ppl who already know what pixel Tanks is

gl with that tho. gl with finding a cool teacher too. I'm all for this, but I don't think it would work

**Comment by BreadSpammer** [comment]
there isn't a coding club >:)

**Comment by BreadSpammer** [comment]
I mean there's like robotics but this is just for coding in general. it would probably be ez to make in comparison to a tonks club

**Comment by 3foenation** [comment]
> its not? lol. that's not the point of the club

if wd do do it on esports we would have to make it competitive so people would play and esports is all about tornaments

**Comment by BreadSpammer** [comment]
were not doing it at e sports lol why do u think that?

**Comment by LostKing73** [comment]
> I mean there's like robotics but this is just for coding in general. it would probably be ez to make in comparison to a tonks club

aight.

**Comment by BreadSpammer** [comment]
@3foenation shut

**Comment by LostKing73** [comment]
> ok so we call it a coding club, but we mostly work on tanks, and if anyone asks, they are "beta testers"

w, perfect. @cs6413110 agreed? also, whos the teacer

**Comment by 3foe** [comment]
as long as 5 or more people want to play a game then we can make it a team

**Comment by 3foe** [comment]
and we have 5 ppl

**Comment by BreadSpammer** [comment]
idk I want my own club. let's just make a coding club and have everyone just play tonks in it lol

**Comment by BreadSpammer** [comment]
and we'll find the teacher along the way

**Comment by BreadSpammer** [comment]
I'll ask the admins next week bc imma get permission from my parents to do this first

**Comment by LostKing73** [comment]
> mr lauretta might sponsor, or let us join esports

no.

**Comment by LostKing73** [comment]
> as long as 5 or more people want to play a game then we can make it a team

we were literally just saying it wouldn't be a competitive esports team. why cant yall read that

**Comment by cs6413110** [comment]
I vote we drop this because we are too busy making the game.

**Comment by LostKing73** [comment]
> I vote we drop this because we are too busy making the game.

i vote we do this once game done

**Comment by cs6413110** [comment]
ok, closing
