### ISSUE TITLE
Finishing Game

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#196]
Classes: Done
Rank Damage Balancing: Done
Perks: Done, except for images
Items: One left, pending for past 2 months

I vote we just keep bomb. The incapability of making a single image is delaying months of coding effort. 

This just leaves:
Zones
Singleplayer
Leviathan
Bugfixing
Optimization
AI

I'm setting deadlines. If failed, the feature will just be removed from the game. Simple as that. It's been too long and we've done too little. Images are worlds of complexity beyond what we seem to be able to do, so we will cut corners for images at every chance.

Zones - 2 weeks. I need image % competition and the current list of planned zones.
* Maps - This is probably the highest priority. All maps suck or got removed for no reason.
* Images - Needed ASAP.
* Coding - This will take 2 days to code. Plan accordingly.

Singleplayer - 1 month. I need levels, levels, levels. No offensive symbols on the designs plz.
* Maps - We need 
* Images - We need a better menu and consistent victory and defeat screens
* Coding - I need plenty of time.

Leviathan - I don't wanna code. Not setting too much of a deadline, but the dead conversation is really annoying.
* Debate - Are we doing this or not? It's much easier to not, but uh idk.

Bugfixing - 3rd quarter
* Coding - I need uninterrupted spamless months.

Optimization - 3rd quarter
* Coding - I need uninterrupted spamless months.

AI - 3rd quarter
* Coding - I need uninterrupted spamless months
* Debate - I need to know what items we are limiting

**Comment by BreadSpammer** [comment]
ai should be above bigs and optimization bc those are breadable somewhat. zones should be ez, just add the comparability and I'll do all the image stuff. u need to add single player stuff asap so I can start working on levels for them.

**Comment by cs6413110** [comment]
@LostKing73 

I need, rn, the names of all the zones and which ones are completed. I want zones done today.

**Comment by LostKing73** [comment]
oh, and dont forget banners

**Comment by LostKing73** [comment]
> @LostKing73
> 
> I need, rn, the names of all the zones and which ones are completed. I want zones done today.

:O. ok, but like idk if that's possible. there's like... 18 maps needed

**Comment by LostKing73** [comment]
> oh, and dont forget banners

yk what, honestly, we don't rely need them tbh

**Comment by cs6413110** [comment]
Also
@LostKing73 @CelestialKnight7 @BreadSpammer @DarkMemeGod411 

We need to keep the issue level below 5 to keep focused.

**Comment by LostKing73** [comment]
> @LostKing73
> 
> I need, rn, the names of all the zones and which ones are completed. I want zones done today.

k.

Cave - Done
Crystal - Done
Battlegrounds - Done obv, its just normal
The Surface - not doing this one, so ignore
Ice Cavern - Done
The Deep - Done

do you need images?

**Comment by BreadSpammer** [comment]
bruh stats aren't even hard? ur just lazy

**Comment by LostKing73** [comment]
ok image spamming

gonna send in 1 comments per zone

**Comment by LostKing73** [comment]
The Deep
weak:
![image](https://github.com/user-attachments/assets/6d39266e-afc0-4cc6-a901-e7263208444c)

strong:
![image](https://github.com/user-attachments/assets/0c83ee9f-8ad4-4907-80e2-8e2011422f00)

gold:
![image](https://github.com/user-attachments/assets/6ef984ff-4228-4eda-9b25-478070d17502)
barrier:
![image](https://github.com/user-attachments/assets/47d28447-58ff-46fd-ba78-94f89b8c4682)
void:
![image](https://github.com/user-attachments/assets/4c5e29ac-40fd-4190-b698-679dd2d6fc4e)

**Comment by LostKing73** [comment]
floor:
![image](https://github.com/user-attachments/assets/a2304e4a-ac15-419c-997f-efffebd61e60)

**Comment by CelestialKnight7** [comment]
> I vote we just keep bomb. The incapability of making a single image is delaying months of coding effort.

SKOOL WORKKKKKKKKKKKKKKKK ILL GIT TO IT CHIL

**Comment by cs6413110** [comment]
> > I vote we just keep bomb. The incapability of making a single image is delaying months of coding effort.
> 
> SKOOL WORKKKKKKKKKKKKKKKK ILL GIT TO IT CHIL

Easier to just kill bomb than wait months in hope of things getting better. School work is only going to get worse. We're past our deadlines.

**Comment by LostKing73** [comment]
oh no :( cave and ice are saved one breads old acc, and thos comments are gone

**Comment by LostKing73** [comment]
its fine, ill just pull from code

**Comment by DarkMemeGod411** [comment]
> > > I vote we just keep bomb. The incapability of making a single image is delaying months of coding effort.
> > 
> > 
> > SKOOL WORKKKKKKKKKKKKKKKK ILL GIT TO IT CHIL
> 
> Easier to just kill bomb than wait months in hope of things getting better. School work is only going to get worse. We're past our deadlines.

We need to finish game. I agree with aaron. If i can do ANYTHING let me know

**Comment by LostKing73** [comment]
Ice

weak:
![image](https://github.com/user-attachments/assets/345ba7d8-8930-48c3-bf80-f3d00064e010)

strong:
![image](https://github.com/user-attachments/assets/1bed964c-a51c-47a8-9e66-09d1cecb831a)

gold:
![image](https://github.com/user-attachments/assets/8a72c62f-7c18-460b-b40f-9e56dc5fab06)

barrier:
![image](https://github.com/user-attachments/assets/160a6538-b960-4b51-8a71-8756dd40399d)

void:
![image](https://github.com/user-attachments/assets/f3172a46-ce49-4624-b72c-88a8d0718bea)

floor:
![image](https://github.com/user-attachments/assets/f7e01e04-1e5d-42b5-9912-f3131eb6ac4f)

**Comment by cs6413110** [comment]
> > > > I vote we just keep bomb. The incapability of making a single image is delaying months of coding effort.
> > > 
> > > 
> > > SKOOL WORKKKKKKKKKKKKKKKK ILL GIT TO IT CHIL
> > 
> > 
> > Easier to just kill bomb than wait months in hope of things getting better. School work is only going to get worse. We're past our deadlines.
> 
> We need to finish game. I agree with aaron. If i can do ANYTHING let me know

@DarkMemeGod411 Maps for zones. You have made some of the best maps and we need more.

**Comment by LostKing73** [comment]
> do u want me to make 12 maps today?

ig. thats what cs is saying.

**Comment by BreadSpammer** [comment]
@DarkMemeGod411 just make as many maps as u can. go home and make more maps. so when we have like 10-20 we will probably get like 5 gud ones to add

**Comment by LostKing73** [comment]
> @DarkMemeGod411 just make as many maps as u can. go home and make more maps. so when we have like 10-20 we will probably get like 5 gud ones to add

we only need 12 in total

**Comment by LostKing73** [comment]
@cs6413110 . 

Zones is 100% done image-wise.

**Comment by DarkMemeGod411** [comment]
i can get 2 done today

**Comment by cs6413110** [comment]
Ok, so here is how they will be uploaded.

Each zone will have a folder in the block folder.
Inside each folder will be all the zones images.

@LostKing73  can you do this?

**Comment by LostKing73** [comment]
> Ok, so here is how they will be uploaded.
> 
> Each zone will have a folder in the block folder. Inside each folder will be all the zones images.
> 
> @LostKing73 can you do this?

yes, but actually no

**Comment by BreadSpammer** [comment]
my job now :(

**Comment by cs6413110** [comment]
uploaded

**Comment by BreadSpammer** [comment]
was*

**Comment by LostKing73** [comment]
watchu mean was

**Comment by BreadSpammer** [comment]
was my job :( (stolen)

**Comment by LostKing73** [comment]
o

**Comment by DarkMemeGod411** [comment]
> > > > > I vote we just keep bomb. The incapability of making a single image is delaying months of coding effort.
> > > > 
> > > > 
> > > > SKOOL WORKKKKKKKKKKKKKKKK ILL GIT TO IT CHIL
> > > 
> > > 
> > > Easier to just kill bomb than wait months in hope of things getting better. School work is only going to get worse. We're past our deadlines.
> > 
> > 
> > We need to finish game. I agree with aaron. If i can do ANYTHING let me know
> 
> @DarkMemeGod411 Maps for zones. You have made some of the best maps and we need more.

Done, ur welcome @cs6413110

**Comment by LostKing73** [comment]
> > @DarkMemeGod411 Maps for zones. You have made some of the best maps and we need more.
> 
> Done, ur welcome @cs6413110

nnnnnnnnope. u still got 2 more gem maps to do @DarkMemeGod411

**Comment by DarkMemeGod411** [comment]
Oh. I can definitely make them on Monday
