### ISSUE TITLE
Challenges

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#20]
Special single player levels that unlock every 10 levels, yes, ik smth like this has been proposed but shhhhhh. this is assuming there are 50 singleplayer levels. each win gives a page, which can be seen in the inv, and is MORE LORE MWAHAHAHAHA

### level 10
**The Knight's Challenge**

not evan btw, A level 10 ai to fight against. pretty normal fight.
grants page 1

### level 20
**Bread's Challenge**

A level 20 ai named Bread to fight against. tougher fight
Grants page 2

### level 30
**Celestial Knight's Challenge** 

A level 30 ai named CelestialKnight to fight against. very tough fight
Grants page 3

### level 40
**cs641311's Challenge**

A level 40 ai named cs641311 to fight against. near impossible fight
Grants page 4

### level 50
**The King's Challenge**

A level 50 ai named LostKing to fight against. is this even possible?
Grants page 5

**Comment by LostKing73** [comment]
challenge names up for discussion

**Comment by LostKing73** [comment]
pages will document the "before the war" and how the war started, from the shared logs of bread and Celestial knight, or smth like that idk

**Comment by BreadSpam** [comment]
too ez. literally just strafe for 5 hours and win. also just add bosses? (old idea from 2 years ago)

**Comment by LostKing73** [comment]
^^^ ik, this is like a better version ig? but since they are level 50 and would have classes, I would hope that would make them more of a fight.

**Comment by BreadSpam** [comment]
^^^ eh not really. lvl 50 would have big damage, but only about 800 HP. would probably get strafed on. I want to add bosses, but that would take too much effort

**Comment by LostKing73** [comment]
double the level then? how much helth would 100 have?

**Comment by BreadSpam** [comment]
level 100 makes them 1 shot u not fun. we will probably make a special ai type with custom moves and stuff.

**Comment by BreadSpam** [comment]
making new issue for designing boss ai type

**Comment by LostKing73** [comment]
then leave this open

**Comment by LostKing73** [comment]
bcuz thats what the boss ai would be used for

**Comment by cs6413110** [comment]
#707 wait NUU

Basically how do you expect me to code this when I'm kicked out of the house, broke, licenseless, dying to 4 AP classes, coding an eternal list anyway, and only have like a few months to finish?

**Comment by LostKing73** [comment]
> #707 wait NUU
> 
> Basically how do you expect me to code this when I'm kicked out of the house, broke, licenseless, dying to 4 AP classes, coding an eternal list anyway, and only have like a few months to finish?

ye fair enough, closing this and the other one
