### ISSUE TITLE
Nug Requirements

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#201]
Decision on removing/keeping for:
- Drone
- Bomb
- Smoke Bomb

Image for the block perk

Fix resizing on tabs
Fix death effects tab

**Comment by CelestialKnight7** [comment]
drone - ded
bomb - breacher
smoke - fix or ded, im fine with either at this point

**Comment by LostKing73** [comment]
ded,ded,ded.

**Comment by BreadSpammer** [comment]
drone - ded
bomb - breacher
smoke - fix

**Comment by BreadSpammer** [comment]
![pixil-frame-0 (1)](https://github.com/user-attachments/assets/ef778d6d-55d9-4b36-88cf-8cfacd35af8b)
perk image

**Comment by BreadSpammer** [comment]
i think that means nugs :)

**Comment by cs6413110** [comment]
Nope, bc didn't finish the votes

**Comment by cs6413110** [comment]
and following debate

**Comment by DarkMemeGod411** [comment]
give the man some nugs. good work bread

**Comment by LostKing73** [comment]
9 items so clean, remove glue cuz u used when i didnt do anything and didn't even notice

**Comment by BreadSpammer** [comment]
nah ur dumb. 12 it is.

**Comment by BreadSpammer** [comment]
Railgun (20 cooldown, 100 damage)

when used, your tank will charge up a beam, which takes 1 second, and while charging, you have toolkit speed. when the shot is released, it travels INSTANTLY, piercing through enemies, dealing 100 damage.

this is a unique damage item that doesn't synergize with insta, and has a good list of use cases, and counters.

pros:
- travels instantly, so gud players can always hit it.
- pierces though enemies, making it gud for team fights
- pretty ez to code

cons:
- can be easily I framed through, similar to airstrike
- cant pierce through blocks

VOTE 👍 or 👎

**Comment by DarkMemeGod411** [comment]
Add

**Comment by BreadSpammer** [comment]
@cs6413110 don't downvote just bc u want 9 items >:( actually judge it

**Comment by LostKing73** [comment]
> @cs6413110 don't downvote just bc u want 9 items >:( actually judge it

we judged that we want 9 items

**Comment by BreadSpammer** [comment]
No we didn't. @CelestialKnight7 exist

**Comment by LostKing73** [comment]
> No we didn't. @CelestialKnight7 exist

we being me and aaron

**Comment by LostKing73** [comment]
no, but would rather just have 9

**Comment by BreadSpammer** [comment]
got my nugs
