### ISSUE TITLE
great map

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#204]
R62X5GXR3XGX5GXR5XR35XR5XR2X2R3XR3XR5XR35XR5XRX2R4XR3XR5XR35XR5X3R5XR3XR5XR35X5RXSR6XR3XR5XR39XRX3R5XR3XR5XR39XRXRX2R4XR3XR5XR39XRXR2X2R3XR3XR5XR35X5RXR3XGX5GX5GX5R31XR27XR31XR27XR31X5GX5GX5GXR3XGX5R33XR3XR5XR5XR3XRXR37XR3XR5XR5XR3XRXR37XR3XR5XR5XR3XRXR37XR3X5RX5RXR3XRX4R34XR7XR5XRXR3XRXR37XR7XR5XRXR3XRXR37XR7XR5XRX2RX2RXR35X5RX5RX5R2X3R2X5R2369

**Comment by LostKing73** [comment]
no lol

**Comment by BreadSpammer** [comment]
f tier map: reason: no swastica
