### ISSUE TITLE
LOADING SCREEN

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#205]
im not entirly done 
![pixilart-drawing](https://github.com/user-attachments/assets/387e5e3c-31a7-4b84-ac28-34b1586e757d)
imagine a tank going from left to right to load in

**Comment by 3foenation** [comment]
I AM NOt DONE i want to know if yes continue so I don't spend hours for nothing

**Comment by LostKing73** [comment]
no. we dont need one+flashbanged

**Comment by 3foenation** [comment]
its is a LOADING SCREEN

**Comment by 3foenation** [comment]
DMG reopen please

**Comment by cs6413110** [comment]
We'll just keep the current loading thing for now.

**Comment by 3foenation** [comment]
its not done i told you

**Comment by LostKing73** [comment]
> its not done i told you

then why would you ask if you should continue
