### ISSUE TITLE
Update Trailers

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#207]
should we add update trailers to the game for major updates. the GPAs liked the idea, we could do a trailer of the leviathan, and then say the same thing about the trailer release date, "it's coming soon". it would be fun, give me smt to do , and actually help the player base.

**Comment by LostKing73** [comment]
no, bcuz too much work for this, and we don't need cring voice acting, and how would we even do that??? no

**Comment by LostKing73** [comment]
or they could just show the game. not needed

**Comment by LostKing73** [comment]
besides, im doin a tonks yt channel, so that'll do the same thing

**Comment by LostKing73** [comment]
which is why the channel would be best

**Comment by 3foe** [comment]
why do u have collab

**Comment by LostKing73** [comment]
so i can actually do things

**Comment by 3foe** [comment]
ya know what whatever, ur on proabtion for 2 weeks, then ur good to go. just don't try to purposely annoy me or anyone else and were good. aaron you shoulda talked to me first.

**Comment by LostKing73** [comment]
> ya know what whatever, ur on proabtion for 2 weeks, then ur good to go. just don't try to purposely annoy me or anyone else and were good. aaron you shoulda talked to me first.

i assume by probation u mean ur gonna watch me for 2 weeks?

**Comment by 3foe** [comment]
basically, but id rather not find anything
