### ISSUE TITLE
Bug with the Deep

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#208]
in the deep you can't see normal firing type, you can see shotgun but not long-range shots. this bug doesn't effect any other zone tho

**Comment by LostKing73** [comment]
tested and true, its not just blending in with the floor, its just not there

**Comment by cs6413110** [comment]
nope, cap

**Comment by BreadSpammer** [comment]
no its blending in. ur just blind

**Comment by cs6413110** [comment]
tested, it IS blending in with the floor

**Comment by BreadSpammer** [comment]
I'm gonna chance bullet texture to be seen better

**Comment by BreadSpammer** [comment]
grey background, black interior

**Comment by BreadSpammer** [comment]
outline*
