### ISSUE TITLE
Titles

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#209]
we need title ideas to put on banners here is a list of titles we could have

The Immortal Being -- take damage from a player and live with 1hp left (fire and gambling don't count)

The Undying --- kill a player at 1 hp left

The Converted -- die to a player 

The Hunter -- have a 5 player kill streak

The Streak have a 10-player killstreak

Blazing Demon -- have a 20 killstreak

Death Incarnate -- have a 50 killstreak

Coldblooded--- kill 5 people in the same server

Annihilator -- kill 25 people in the same server 

Apex Predator -- kill 50 people in the same server

Grim Reaper -- kill 100 people in the same server

Equal to the Heavens -- kill an admin (in duels)

Over Heaven --- Kill an owner (in duels)

Protagonist -- kill 2 or more people with the same attack

Ally -- join a team

Team War Amateur -- when you are on a team kill someone on a different team

Team War Rookie -- same thing but 5 kills

Team War Veteran -- same thing but 10 kills

Shattered -- die with a killstreak fo 5

Heart Broken -- die with a killstreak of 10

The Crusader -- kill a player that killed you

Blazing Ravenger --- get a killstreak of 3 off of a person who killed you

King of the Server -- be the only one alive in a server with 5+ people

The King --- have everyone in the server be on your team 

** we will probably need even more titles bc of more things being added to the game**

**Comment by LostKing73** [comment]
dawg we arent doing banners

**Comment by LostKing73** [comment]
cool, but not doing

**Comment by cs6413110** [comment]
Roblox behavior

**Comment by LostKing73** [comment]
that too
