### ISSUE TITLE
Boss AI Type

### ISSUE THREAD

**Issue by BreadSpam** [cs6413110/Pixel-Tanks#21]
This type of ai will have aimbot, 10 times the normal HP, and wont have items, but will always have a class which will have a special effect, and depending on the class, will get unique ai and maybe a passive

Tactical: 
Ability: the boss tank will get slowed for 5 seconds, after which, will shoot 60 missiles in all directions (/yeet)
Passive: power bullets this ai shoots will be converted to mega bullets, and this missile is homing. will always target the closest target to ensure hits

Stealth: 
Ability: the boss will teleport behind the lowest enemy tank in a 10 block radius, and then bc of their ai, will instantly shotgun them
Passive: is always invisible. always targets the lowest player

Builder: 
Ability it stops moving like a turret but fires 4 streams of bullets or missiles like a death laser
passive spawns turrets behind the furthest player

Fire:
Ability every 500 damage it takes it spews lava that is like a spike but better does 100 dmg a sec and slows down players
Passive a ring of fire that A) is around the  boss or B) has a very wide radius to stop players from running away at low health

Medic: 
(should this be a boss tank?)

Warrior:
revert to old warrior lol

**Comment by cs6413110** [comment]
Simply just do yeet = true;

**Comment by 3foe** [comment]
thx for the /yeet command :D also I can work on ideas if u want ill edit in bold or smt

**Comment by 3foe** [comment]
oh :(

**Comment by 3foe** [comment]
ig it was full on admin abuse

**Comment by 3foe** [comment]
still want me to help with abilitys?

**Comment by BreadSpam** [comment]
removed bc couldn't find a way to stop the gpas from accessing

**Comment by LostKing73** [comment]
just like make it admin only lol

**Comment by BreadSpam** [comment]
more complicated than u think

**Comment by LostKing73** [comment]
uhm like no? just copy the code from an admin command and use that

**Comment by LostKing73** [comment]
#707

**Comment by cs6413110** [comment]
![image](https://github.com/user-attachments/assets/d536a9a7-80c1-4642-b307-4dd3ef24e39a)

**Comment by LostKing73** [comment]
noooooo
