### ISSUE TITLE
add a counter for gambling

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#210]
make it be under ur healthbar or something and it shows only for you.
it counts how many times u won at gambling in a row per life

itl be funny

**Comment by LostKing73** [comment]
it was only doin that many gambles btw cuz I set it do be 75% to gamble instead of 50% (I fixed don't worry)

**Comment by cs6413110** [comment]
ez

**Comment by BreadSpammer** [comment]
change the damage number to a light blue "Saved!"

**Comment by CelestialKnight7** [comment]
make it like the healthbar so that only the person and ghosts can see it

**Comment by CelestialKnight7** [comment]
> it was only doin that many gambles btw cuz I set it do be 75% to gamble instead of 50% (I fixed don't worry)

idk what ur talking about im still winning like 7 times in a row

**Comment by BreadSpammer** [comment]
and then if u get saved again, it will say "Saved! x2" and etc

**Comment by CelestialKnight7** [comment]
or just a number works too

**Comment by CelestialKnight7** [comment]
@BreadSpammer do

**Comment by LostKing73** [comment]
> > it was only doin that many gambles btw cuz I set it do be 75% to gamble instead of 50% (I fixed don't worry)
> 
> idk what ur talking about im still winning like 7 times in a row

idk luck ig

**Comment by CelestialKnight7** [comment]
adddd

**Comment by BreadSpammer** [comment]
bruh I'm a busy brread

**Comment by BreadSpammer** [comment]
this is unessecary and idk how to code. aaron's adding the animation, and if u want this, its coming from cs
