### ISSUE TITLE
Item Spam

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#212]
basically imma spam as many item ideas as i can until we get 1-2 gud ones

if u wish any of these ideas were changed slightly, then do as u will. anything for another upvote :)

as always 👍 = yas, 👎 = ded

**Comment by BreadSpammer** [comment]
### Thermal Overdrive

boosts your speed, and your main attack damage by about 1.5x, but also makes your tank take 1.5x more damage

**Comment by BreadSpammer** [comment]
### Tether Resist:

makes enemy bullets magnetize towards you, but you take 33% damage from them. gud for tanking damage from an insta, or for your teamates

**Comment by BreadSpammer** [comment]
### Homing Missiles

deploys 4 minature missiles that have a center point, which is first on you. you can use the item again (like dyna) to fire off the center point. and the missiles will follow. the missiles wont explode on blocks. but will only explode if either the missile collides with a tank, or the center point hits a block. each missile does 35 damage and has powermissile's explosion distance

**Comment by DarkMemeGod411** [comment]
i like Homing missiles. add.

**Comment by BreadSpammer** [comment]
### Siphon

steal any helpful effects of nearby tanks and give them to yourself (reflect, glu healing, shield, medic healing, warrior boost, stealth, usb, etc), along with hp

i like this one bc it counters the op item shield, and makes it so u dont have to run shield if u just yoink from someone else :D

**Comment by BreadSpammer** [comment]
### Making smoke not useless

increase the radius, make it actually obscure vision in that area, and make it so allies can see through it so u can use it more effectivley.

**Comment by BreadSpammer** [comment]
### Supply Drop

calls down 4 crates which, when destroyed, gives 50% of your cooldowns back each. enemy players can steal them to take the cooldowns for themselves

**Comment by LostKing73** [comment]
bread, maybe make an idea that like does melee-ish damage around you and removes grapples attatched? kinda l;ike bomb, but more for damage?

**Comment by BreadSpammer** [comment]
### Drone, the item

When shot, the drone will fly about 2.5 blocks forward, dealing 100 damage to anyone it hits. If the drone doesn't hit anyone when it stops moving, it will fire a laser at the nearest enemy tank, and will despawn.

Laser stats:
80 Dmg
Powerbullet speed

25 cooldown

**Comment by LostKing73** [comment]
no cuz insta

**Comment by BreadSpammer** [comment]
### Recall

30 cooldown

When you use it the first time, you place down a "waypoint" at your feet, that anyone can see. When you use it again (like dyna), you will teleport to the waypoint after 1 second. If the item recharges before you use it, using it again will overwrite the first waypoint and make a new one

This item seems op, but has tons of counter play. First of all, you can trap/camp the recall to get an ez kill, especially if ur builder. Secondly, the waypoint only has 100 hp, and can be destroyed, which will cause their recall to simply fail. Finally, insta.

**Comment by DarkMemeGod411** [comment]
ngl recall sounds awesome. happy thanksgiving. i am in a food-coma rn

**Comment by DarkMemeGod411** [comment]
im gonna share an idea. 

### EMP
When you use it enemies in a 4 block radius have their cooldowns activated. if no one is in the area, the emp hits u and activates your cooldowns

why add this?: bc it is a unique item and would be a interesting addition to the game.

**Comment by LostKing73** [comment]
> im gonna share an idea.
> ### EMP
> 
> When you use it enemies in a 4 block radius have their cooldowns activated. if no one is in the area, the emp hits u and activates your cooldowns
> 
> why add this?: bc it is a unique item and would be a interesting addition to the game.

nno, cuz like super annoying, completely counters that onne perk with the toolkit give cooldowns

**Comment by DarkMemeGod411** [comment]
ok. so what are we thinking of adding. i like supply drop

**Comment by BreadSpammer** [comment]
### Fix Coating

8 second cooldown

Covers your tank in a substance that will limit the damage you take to 100 for a second. 

Aaron's idea, my name lol

**Comment by cs6413110** [comment]
*Heavy Coating
*Heavy Gear

**Comment by LostKing73** [comment]
why would anyone use this? pretty much makes it so u cant escape for a second, and also, if it only lasts a second, ppl could use, then insta cuz its so fast

**Comment by LostKing73** [comment]
> *Heavy Coating *Heavy Gear Message ID: ***@***.***>

why do we have to name it? its name doesn't show in game OH MY GOODNESS I GOT ANOTHER IDEA

**Comment by BreadSpammer** [comment]
> why would anyone use this? pretty much makes it so u cant escape for a second, and also, if it only lasts a second, ppl could use, then insta cuz its so fast

1: warrior + spin = ez
2: atleast flat's 1 key wouldn't work, bc half his insta would miss, and ppl will boost away from u when u use this, so u cant really chain an insta
3: stop trying to downvote spam me, its a good idea :(

**Comment by LostKing73** [comment]
> > why would anyone use this? pretty much makes it so u cant escape for a second, and also, if it only lasts a second, ppl could use, then insta cuz its so fast
> 
> 1: warrior + spin = ez 2: atleast flat's 1 key wouldn't work, bc half his insta would miss, and ppl will boost away from u when u use this, so u cant really chain an insta 3: stop trying to downvote spam me, its a good idea :(
1. if you can hit it, ig, but u get more value if u just power bullet, bcuz then u  could hit a shotgun and dyna
2. block(even better, spike), this, insta.
3. stop making ideas for insta, do smth cooler

**Comment by BreadSpammer** [comment]
> > > why would anyone use this? pretty much makes it so u cant escape for a second, and also, if it only lasts a second, ppl could use, then insta cuz its so fast
> > 
> > 
> > 1: warrior + spin = ez 2: atleast flat's 1 key wouldn't work, bc half his insta would miss, and ppl will boost away from u when u use this, so u cant really chain an insta 3: stop trying to downvote spam me, its a good idea :(
> 
> 1. if you can hit it, ig, but u get more value if u just power bullet, bcuz then u  could hit a shotgun and dyna
> 2. block(even better, spike), this, insta.
> 3. stop making ideas for insta, do smth cooler

1: u can use power bullet still? this item doesn't change that unless ur using ur power bullet specifically at close range.
2: so u would need to run 3 items for that, so only shield?
3: its not for insta, its supposed to be an alternative to dynamite that doesn't synergize with insta, now plz change ur vote so @cs6413110 doesn't auto downvote :(

**Comment by LostKing73** [comment]
> 1: u can use power bullet still? this item doesn't change that unless ur using ur power bullet specifically at close range. 2: so u would need to run 3 items for that, so only shield? 3: its not for insta, its supposed to be an alternative to dynamite that doesn't synergize with insta, now plz change ur vote so @cs6413110 doesn't auto downvote :(

1. so insta, I literally would be using pwr bullet at close range btw
2. like, yea??? that's fine???
3. proven that it works with insta, and its just useless if you DONT use with insta

**Comment by BreadSpammer** [comment]
check tanks chat

**Comment by LostKing73** [comment]
> check tanks chat

nah

**Comment by LostKing73** [comment]
Harden (pause)

pull all blocks in a 3x3 square around you into you and heal half the health of each block you pull in. block counter, turip counter, 2 item healing item

**Comment by BreadSpammer** [comment]
there is already enough turret counters, and this just helps builders, bc after u eat all the blocks on the map, u can just eat ur own gold/strong block for an ez 250 HP every 8 seconds

**Comment by LostKing73** [comment]
> there is already enough turret counters, and this just helps builders, bc after u eat all the blocks on the map, u can just eat ur own gold/strong block for an ez 250 HP every 8 seconds

wouldn't work on improved blocks then. it would just suck it in and heal u 100 hp, then convert the block to white, spit it out back to  where it was

**Comment by 3foe** [comment]
##Fix

makes bread give good ideas

**Comment by LostKing73** [comment]
lol none of yal know how bold works

**Comment by BreadSpammer** [comment]
I mean ok then it doesn't counter turret, and also this item would just just be either op or useless depending on how long the match has been going on (how many blocks still exist)

**Comment by LostKing73** [comment]
> I mean ok then it doesn't counter turret, and also this item would just just be either op or useless depending on how long the match has been going on (how many blocks still exist)

rrrright, which makes it not op. u would eventually run out, and also there would prly be a cap of 300 hp healed per burst so stelth can hide in the corner of the + map and heal to full instantly

**Comment by BreadSpammer** [comment]
its just weird to have ur main healing source be situational

**Comment by 3foe** [comment]
what abt the electric chain idea?

**Comment by LostKing73** [comment]
> its just weird to have ur main healing source be situational

so don't use it. a new item doesn't have to be something you have to use

**Comment by LostKing73** [comment]
> what abt the electric chain idea?

too much work-around for it, its cool on paper but not rly worth the effort it would take to work out the kinks

**Comment by BreadSpammer** [comment]
### Drone

goes out in a straight line at a very slow pace (half of a bullet's speed), placing explosives where it goes (basically dynamites). if you use the item again, or the drone hits someone, all of the explosive will go boom. if u are hit with one, you will take 100 damage, regardless of how many explosions actually hit u

**Comment by CelestialKnight7** [comment]
> ### Fix Coating
> 8 second cooldown
> 
> Covers your tank in a substance that will limit the damage you take to 100 for a second.
> 
> Aaron's idea, my name lol

pretty much just reflect but worse

**Comment by LostKing73** [comment]
> ### Death Seal
> _You are destined to lose. . ._
> 
> This item allows you to cast a curse that strikes an opponent. If you die, they die as well. However, you can only use this ability once per life, and it lasts for only 10 seconds before becoming ineffective.
> 
> While this item is extremely powerful, its effectiveness is limited by the short duration and the one-use restriction per life.

also, if ur opponent uses this on you, it cancels each other out. it also is a slow moving projectile, not easy to hit

**Comment by CelestialKnight7** [comment]
cring tho cuz once per life but its dependent on u dying?
so just spike/block someone, put it on them, then walk into turrets (possibly theirs) and then u both die

**Comment by LostKing73** [comment]
> cring tho cuz once per life but its dependent on u dying? so just spike/block someone, put it on them, then walk into turrets (possibly theirs) and then u both die repeat until rage quit

fair enough lol

**Comment by LostKing73** [comment]
you wouldnt BOTH die, they would die instead, but what you said still works

**Comment by LostKing73** [comment]
### Vote

Items are now unlocked through single-player mode, enhancing its functionality beyond just XP and money. When an item is unlocked, a screen appears showing the name of the item and a brief description of its function.

**Comment by LostKing73** [comment]
you still start with 4, speaking of, we need to change what the 4 starter items are cuz they're dumb

**Comment by cs6413110** [comment]
> pretty much just reflect but worse

Finally, actual brain cells being used on items.

The item's actual name now is fortify ig. Yes, it's very similar to reflect, but I think it's different enough that's it's ok.

a.) Reflect has the potential to return that damage back to the enemy, fortify does not
b.) Fortify has a much lower cooldown
c.) Fortify has a slightly higher skill ceiling

It's not the best idea, but we're out of time and I see none better.

**Comment by LostKing73** [comment]
Flash Freeze

_Frostbitten attacks. . ._

For 3 seconds, your bullet attacks—both normal and shotgun (excluding power bullets or items)—deal double damage. After that, you enter a thawing phase where you deal normal damage for 1 second, followed by 3 seconds of reduced damage at half the normal rate. Finally, you return to your standard damage output until the item effect ends.

**Comment by 3foe** [comment]
Cabels

A cable that stops people from moving away from you (like a 5 block radius tho), (flatting is solved)

**Comment by cs6413110** [comment]
Do I just code fortify?

**Comment by cs6413110** [comment]
Tallying:
Cables: -1
Flash Freeze: 0
Drone: 0
Death Seal: -3
Reckless Boost: -3
Mirror: 0
Harden: 0
Reckless Spin: 0
**Fortify: +2**
EMP: 0
Recall: 0
Drone v0: -1
**Supply Drop: +3** Added
Smoke Rework: -1
Siphon: -2
**Homing Missiles: +1**
Tether Resist: -2
Thermal Overdrive: -2

**Comment by LostKing73** [comment]
ewewewew not homing missiles

**Comment by LostKing73** [comment]
not homing missiles cuz that would mean coding a whole new projectile

**Comment by cs6413110** [comment]
Ye work.
Fortify has more votes tho

**Comment by cs6413110** [comment]
Whenever I ask people if I should just code it, they despawn. It's kind of annoying.

**Comment by cs6413110** [comment]
I think I'm just going to do it and close this.

**Comment by LostKing73** [comment]
> Whenever I ask people if I should just code it, they despawn. It's kind of annoying.

just do. also can you reboot please?

**Comment by LostKing73** [comment]
i added the other zones maps, but I need ur reboot

**Comment by LostKing73** [comment]
also, "fix coating" or fortify, is 5-1. ( I changed my vote in my head cuz I'm too lazy to change physically

**Comment by BreadSpammer** [comment]
### FIX

Description:

Fixes

Example:

Flat in the game, use will auto ban. Leviathan not added, use will add. Your health is low, use will make it 0
