### ISSUE TITLE
Item Tab

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#214]
@cs6413110 you said to do, but like, idk image size, what image I'm basing it off, and what items are in it, and what the new items look like, and if you want it to be not  grid omg I just got an idea hold on

**Comment by LostKing73** [comment]
lemme cook:

**Item Tab, Rebooted:**

The items are to the left and right, and you can see one at a time, big in the middle. using left and right arrow keys you can change which item is in the middle, and therefore which one is selected. this would actually make it less difficult in the code, because you wouldn't need a clickable button, instead having simply to press left/right.

ill make an example image rn

**Comment by LostKing73** [comment]
clicking one over would look like this
![image](https://github.com/user-attachments/assets/bf7ccf28-f652-4858-883c-07bb06b69a5b)

**Comment by LostKing73** [comment]
they wouldnt be less detail like shown here, just smaller, but I cant show that lol

**Comment by LostKing73** [comment]
YO AND THEY COULD HAVE ITEM NAME ABOVE SO PPL WOULD KNOW WHAT THEYR ACTUALLY CALLED

**Comment by BreadSpammer** [comment]
or just don't add item names lol

**Comment by LostKing73** [comment]
> or just don't add item names lol

sure, but this would be cool(and easy) too

**Comment by cs6413110** [comment]
Exceeds breadable workload

**Comment by LostKing73** [comment]
> Exceeds breadable workload

its easier than what we have right now. all you need is blank, and the image without square can be re-sized onto it and cycled.

**Comment by BreadSpammer** [comment]
![pixil-frame-0 (18)](https://github.com/user-attachments/assets/567f724a-86f5-4631-98c9-6c10a68361a5)
![pixil-frame-0 (19)](https://github.com/user-attachments/assets/bd7ac28c-3a1e-4e9d-8c34-173474266496)

**Comment by LostKing73** [comment]
why with the colors? it makes it harder to just resize and put them on

**Comment by cs6413110** [comment]
kso
Bob=rate

**Comment by LostKing73** [comment]
> kso Bob=rate

wha?

**Comment by BreadSpammer** [comment]
colors make the item look cooler so like they're better :)

**Comment by LostKing73** [comment]
> colors make the item look cooler so like they're better :)

whatever, maybe color code based on type, blue for healing, red for dmg, etc

**Comment by BreadSpammer** [comment]
ye, but also nah

**Comment by LostKing73** [comment]
> ye, but also nah

ur cring

**Comment by CelestialKnight7** [comment]
no to new item tab idea, I can resize the old one cuz I'm gonna be fixing the inventory menu stuff until the day I die and also bread xif all the background colors so they make sense

**Comment by LostKing73** [comment]
:(

**Comment by cs6413110** [comment]
Another instance of LostKing making a good idea(like lobby) but it was impossibly unbreadable due to requiring images.

**Comment by LostKing73** [comment]
> Another instance of LostKing making a good idea(like lobby) but it was impossibly unbreadable due to requiring images.

ughhhhhhhhhh like I wish I existed 4 years ago
