### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#217]
Last time i posted this i think you did not know what is was
![pixilart-drawing (1)](https://github.com/user-attachments/assets/993bf23c-ec79-433e-a287-762f3a4b21a7)
background can be whatever idc but you gotta tell me or let you edit it. loading screen by the way

good=tumbs up
bad=thumbs down (tell why)

**Comment by 3foenation** [comment]
iDEAS

**Comment by BreadSpammer** [comment]
cringe, also the proportians are wrong, and this is just not needed

**Comment by LostKing73** [comment]
lol, flat jr., we know what its supposed to be, and that oesnt change how bad it is.
