### ISSUE TITLE
Leviathan

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#219]
It was voted to be added in #187 .

@cs6413110 do you need more info to specify for leviathan? if not, please get started as soon as possible.

**Comment by cs6413110** [comment]
1.) Vote
- Bradley didn't vote
- Me and Evan are both against it
- The majority of your votes are slightly biased

2.) Concept
- The Leviathan is too lore-related
- The Leviathan doesn't make sense to be in a tank pvp game

3.) Timeline
- We have many things more important than adding stuff
- Like freaking 5 months ago I said we aren't adding anything new
- #707
- Time should be reserved for the important things: finishing items, optimization, and singleplayer


If we are doing it, at the very least it will be after single player.

**Comment by LostKing73** [comment]
1. bradley said yes to it. hes just dum so he didn't upvote, and even if he downvoted its still 4-3.
2. evan agreed too. idk why he didn't change his vote
3. idk what u mean by that
4. it isn't. what lore?? there isn't any anymore, and yet it still works.
5. its only a "tank" pvp game bcuz you haven't added leviathan yet. it still works. 
6. all other things are classified as adding stuff.
7. womp
8. womp
9. this is important. this is zones, and singleplayer, and multiplayer.
10. why do you still thinks its an "if". its been confirmed. and like that doesn't work bcuz the deep levels require leviathan. every single one.

**Comment by LostKing73** [comment]
Leviathan needs to work in singleplayer AND multiplayer, bcuz multiplayer zones will have leviathan in them. this is so ppl can work together to fight it (this would be FUN and add more than just "I shoot u now u shoot me", which is the point of zones kinda)

**Comment by 3foenation** [comment]
> 1. bradley said yes to it. hes just dum so he didn't upvote, and even if he downvoted its still 4-3.
> 2. evan agreed too. idk why he didn't change his vote
> 3. idk what u mean by that
> 4. it isn't. what lore?? there isn't any anymore, and yet it still works.
> 5. its only a "tank" pvp game bcuz you haven't added leviathan yet. it still works.
> 6. all other things are classified as adding stuff.
> 7. womp
> 8. womp
> 9. this is important. this is zones, and singleplayer, and multiplayer.
> 10. why do you still thinks its an "if". its been confirmed. and like that doesn't work bcuz the deep levels require leviathan. every single one.

womp womp, Aaron has different priorities so IF we add it it will be MUCH later.

**Comment by cs6413110** [comment]
1.) Bread:
![Screenshot 2024-12-03 11 10 20 AM](https://github.com/user-attachments/assets/24063ac5-6331-4781-994a-86111f0152da)
2.) Idk, says here:
![Screenshot 2024-12-03 11 10 40 AM](https://github.com/user-attachments/assets/28dbc12f-fb85-4393-97f5-64efb9688f85)
3.) Flats makeup the deciding votes
![Screenshot 2024-12-03 11 11 36 AM](https://github.com/user-attachments/assets/7807ea3a-9683-4023-b842-f34a5ada5a81)
4.) Ok, but it originated from lore.
5.) I don't think we should add something like this so late game that changes a lot of the vibe/theme of the game.
6.) *Adding NEW ideas
7.) Wdym womp, we shouldn't even be working on this
8.) Again, we shouldn't even be waiting time discussing new things
9.) It's not that important. It's a side... obstacle?
10.) Why would a level require it?

**Comment by cs6413110** [comment]
@BreadSpammer @CelestialKnight7 
What are your opinions on this?

**Comment by BreadSpammer** [comment]
Leviathan CRING. I never liked it anyway

**Comment by 3foenation** [comment]
that was not me

**Comment by 3foenation** [comment]
what did it say

**Comment by LostKing73** [comment]
talking to cs rn

**Comment by CelestialKnight7** [comment]
same thing as some of lostkings other ideas, they're awesome but just don't fit silly tank game. stuff like this fits in rainworld because of the massive biodiversity of the creatures - it doesn't stand out. but in tank game, if you have a giant behemoth of a snake it would feel out of place.

ye I used to agree to it but I silently changed my vote back a couple weeks ago

**Comment by LostKing73** [comment]
> same thing as some of lostkings other ideas, they're awesome but just don't fit silly tank game. stuff like this fits in rainworld because of the massive biodiversity of the creatures - it doesn't stand out. but in tank game, if you have a giant behemoth of a snake it would feel out of place.
> 
> ye I used to agree to it but I silently changed my vote back a couple weeks ago

...aaron says it fits in. he just said that irl

**Comment by CelestialKnight7** [comment]
source?

**Comment by LostKing73** [comment]
> cap

he literally did. the issue is it would take too long

**Comment by CelestialKnight7** [comment]
ahem:

>5.) I don't think we should add something like this so late game that changes a lot of the vibe/theme of the game.

**Comment by CelestialKnight7** [comment]
...
>The Leviathan doesn't make sense to be in a tank pvp game

**Comment by LostKing73** [comment]
he changed his mind idk

**Comment by 3foenation** [comment]
i dont think he did we have more important things to focus on not random idea not based on a tank game

**Comment by LostKing73** [comment]
absolutly nobody asked for ur non-existant opinion coltin

**Comment by LostKing73** [comment]
leviathan was upvoted. end of story. anything changed will be because me and @cs6413110 talked abt it.


Im frustrated because y'all pushed it back, saying "we'll do it last", and now it is been pushed to a point where we cannot make it in time. i will close with the reminder to @cs6413110 that if there is time to do anything extra, this is the thing to do.

**Comment by CelestialKnight7** [comment]
bro thinks hes in charge. again. for like the 5th time

**Comment by LostKing73** [comment]
> bro thinks hes in charge. again. for like the 5th time

I think that I am entitled to an opinion :/ I literally am just being hard- headed abt this. its a good feature, ik videogames, ik good features

**Comment by LostKing73** [comment]
oh my goodness. leviathan is just 
![image](https://github.com/user-attachments/assets/304ed33c-6115-45cc-a232-3550cf22584c)

**Comment by CelestialKnight7** [comment]
that doesnt look like a tank. again- its cool but shouldn't be in tank game

**Comment by LostKing73** [comment]
> that doesnt look like a tank. again- its cool but shouldn't be in tank game

can you shut dude. are the blocks tanks? its a tank game, better fix that. are the items tanks? its a tank game, better fix that.

**Comment by BreadSpammer** [comment]
blocks are just the base of a tank, so his point still stands

**Comment by LostKing73** [comment]
> blocks are just the base of a tank, so his point still stands

no they arent. have you looked at blocks and the base of the tanks? not the same. also, blocks have collision, tanks don't. also items. like, dum?????????????? 


literally, when the warden was added to mc, did yall say "hey whats the warden doing in my block game, he's not a creeper >:("

**Comment by BreadSpammer** [comment]
yes they did. every og player said that lol. also that Minecraft, where they have liek 60 different mobs. this is tank game, where there are only tanks

**Comment by LostKing73** [comment]
> yes they did. every og player said that lol. also that Minecraft, where they have liek 60 different mobs. this is tank game, where there are only tanks

exactly. and now the warden is accepted. now swap mc for pickle and warden for leviathan

**Comment by LostKing73** [comment]
and there isnt only tanks. turret."ooh its a tank without treads" no it isn't. it uses the same head model, but functionally, its a turret, not a tank. no shotgun, items, boost, moving, gripple.

**Comment by BreadSpammer** [comment]
I have things to do, and Aaron's never coding it anyway, so bye

**Comment by LostKing73** [comment]
> I have things to do, and Aaron's never coding it anyway, so bye

still a chance, and u were never on the radar to code it (lack of cells)
