### ISSUE TITLE
cwowns

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#22]
![dark_crown](https://github.com/user-attachments/assets/a6d18337-6fa4-4135-ab69-d574d47407ea)
![lostcrown](https://github.com/user-attachments/assets/f6878940-8552-4e18-aad8-77c00de69549)
![darkcrown](https://github.com/user-attachments/assets/4d69ec4f-feef-4a7b-8694-50baed7057de)
![thedark](https://github.com/user-attachments/assets/94b37501-9e14-4286-8139-f5ffb3bdb77a)
![pixil-frame-0 (95)](https://github.com/user-attachments/assets/fe0ba1c6-0904-4f6f-bd23-fc1f2e054043)

**Comment by LostKing73** [comment]
dark_crown
lostcrown
darkcrown
thedark
bluecrown

**Comment by DarkMemeGod411** [comment]
I have 2 from like 5 months ago 
![crimson](https://github.com/user-attachments/assets/1c7dbc66-cb25-40d9-845c-b3a6a19d8404)
![Redcrown](https://github.com/user-attachments/assets/d32be68a-505d-40f1-a5d4-b066ab833c5c)

**Comment by LostKing73** [comment]
ewwwwww

**Comment by LostKing73** [comment]
also this isnt even a vote, its just for aaron so he can add them back and FIXXXXXXXXXXX

**Comment by CelestialKnight7** [comment]
> ik it doesn't matter but I have 2 from like 5 months ago ![crimson](https://private-user-images.githubusercontent.com/145387003/368609749-1c7dbc66-cb25-40d9-845c-b3a6a19d8404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Njk4NjIsIm5iZiI6MTcyNjY2OTU2MiwicGF0aCI6Ii8xNDUzODcwMDMvMzY4NjA5NzQ5LTFjN2RiYzY2LWNiMjUtNDBkOS04NDVjLWIzYTZhMTlkODQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNDI2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDljNjc1MTA0MTdlNWRkNGNjNzg1ODVkMDI1NDY1NDU3OGFkMGM0N2RmNTdjZDBkNjRmNzMyZmJjMGJiNDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2rmlWL0j5z8gb_5aw22EjLBiwcs0VgbpPAEkLMwbaQA) ![Redcrown](https://private-user-images.githubusercontent.com/145387003/368609764-d32be68a-505d-40f1-a5d4-b066ab833c5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Njk4NjIsIm5iZiI6MTcyNjY2OTU2MiwicGF0aCI6Ii8xNDUzODcwMDMvMzY4NjA5NzY0LWQzMmJlNjhhLTUwNWQtNDBmMS1hNWQ0LWIwNjZhYjgzM2M1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNDI2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTA4MGFhMTQyOWZkYTUwMGI4NTM2Y2E0M2MwYmM5YmQ2MDJkN2IwNTI4ZjRiYjA0YzVhZGU3M2E4ZTUxNTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1NORLgNIjHLg26j_sRUwUIc6H4MpvlYivYM9ntUX2w)

iron man themed

**Comment by CelestialKnight7** [comment]
> also this isnt even a vote, its just for aaron so he can add them back and FIXXXXXXXXXXX

no they were removed for a reason

**Comment by CelestialKnight7** [comment]
> ![dark_crown](https://private-user-images.githubusercontent.com/175903140/368600350-a6d18337-6fa4-4135-ab69-d574d47407ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Njk4OTQsIm5iZiI6MTcyNjY2OTU5NCwicGF0aCI6Ii8xNzU5MDMxNDAvMzY4NjAwMzUwLWE2ZDE4MzM3LTZmYTQtNDEzNS1hYjY5LWQ1NzRkNDc0MDdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNDI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWY1MmFkZDNjYzJmM2NmMjFlMGM3OTQwN2NlNGI5OTZjOGI2ZTAxODE1ZTM0N2IwNzIxOTJmMjgwODEwMGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.boKYLIfBYsW4PhTLfgMA9X0EKe4mDjzEiNFfZjlV3KU) ![lostcrown](https://private-user-images.githubusercontent.com/175903140/368600413-f6878940-8552-4e18-aad8-77c00de69549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Njk4OTQsIm5iZiI6MTcyNjY2OTU5NCwicGF0aCI6Ii8xNzU5MDMxNDAvMzY4NjAwNDEzLWY2ODc4OTQwLTg1NTItNGUxOC1hYWQ4LTc3YzAwZGU2OTU0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNDI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTRmZTBjNDAxYjc4MjQzYTkxZDhiMmQ0MDI2N2FmMjY3Mzc1NmIzOWJmOWUwNTgwM2E1MDU3MmRmYTk5NWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mYCToAub0QfPC6DUh77OmgkUDot7C8Sv6ptIdUaVTuE) ![darkcrown](https://private-user-images.githubusercontent.com/175903140/368600510-4d69ec4f-feef-4a7b-8694-50baed7057de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Njk4OTQsIm5iZiI6MTcyNjY2OTU5NCwicGF0aCI6Ii8xNzU5MDMxNDAvMzY4NjAwNTEwLTRkNjllYzRmLWZlZWYtNGE3Yi04Njk0LTUwYmFlZDcwNTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNDI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmVmOTVhOTdiM2I1NDljMjUwMGI3NDgyN2NhNGE3YzQxN2E3MjQ4MWZjM2RlMjNkODJhNDZhODY3YTg3ZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j1enZvcI4kLx7Q9PdgHHRuDbZ-0ahml9httMgDFlEZE) ![thedark](https://private-user-images.githubusercontent.com/175903140/368600652-94b37501-9e14-4286-8139-f5ffb3bdb77a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Njk4OTQsIm5iZiI6MTcyNjY2OTU5NCwicGF0aCI6Ii8xNzU5MDMxNDAvMzY4NjAwNjUyLTk0YjM3NTAxLTllMTQtNDI4Ni04MTM5LWY1ZmZiM2JkYjc3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNDI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzQ2OGIxMDEwYTUyNDJlYWNhNDUyMjNlOGFkZDdkMTc2YWY5MDYzNTRiMjc5MjljMTgxOTFiYjY2YjhhNzBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UyBsprdUe0jnfvpShRqiyoh_Zi24L3CUohxSpkDYiO4) ![pixil-frame-0 (95)](https://private-user-images.githubusercontent.com/175903140/368600761-fe0ba1c6-0904-4f6f-bd23-fc1f2e054043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Njk4OTQsIm5iZiI6MTcyNjY2OTU5NCwicGF0aCI6Ii8xNzU5MDMxNDAvMzY4NjAwNzYxLWZlMGJhMWM2LTA5MDQtNGY2Zi1iZDIzLWZjMWYyZTA1NDA0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNDI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTdkYWNmYmM5NmY0OTRiNTI3YzhlZWY1NmYxOWFmNjk2NWMzYzllM2Q4NDQwZjZhNmI1NTJiNDQwYTVjNjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uJREJkn2AHB_T-ph41zwp_wu7eOm4l4_XuBel1rUWrQ)

1. ew
2. bruh stap with the halves
3. same as 2
4. thats not even a crown and looks bad
5. removed cuz inflating the loot pool and also looks kinda bad

**Comment by LostKing73** [comment]
^^^ bruh, they broke game. i dont even want the first and last one

**Comment by LostKing73** [comment]
they bein added back untill @BreadSpam makes inv and cruts

**Comment by DarkMemeGod411** [comment]
1: good
2: meh
3:meh
4: sure
5: sure

**Comment by CelestialKnight7** [comment]
bro thinks he makes the rules

**Comment by LostKing73** [comment]
1 and 5 are to be removed, but need to be added to not break game

**Comment by LostKing73** [comment]
still an admin, evan

**Comment by LostKing73** [comment]
pls dont start fights

**Comment by BreadSpam** [comment]
they only break game when removed bc they weren't removed in all the texture packs

**Comment by CelestialKnight7** [comment]
> pls dont start fights

you're the one saying these things should be added regardless while bradley and I both think they shouldnt as they dont look that good and they inflate the lootpool too much

**Comment by LostKing73** [comment]
yes, but he added 2 other crowns without asking anyone, and that arent ry needed. yes they look good, but the two halves would be better. it's like collecting all pieces of armor.

**Comment by LostKing73** [comment]
> > pls dont start fights
> 
> you're the one saying these things should be added regardless while bradley and I both think they shouldnt as they dont look that good and they inflate the lootpool too much

bro. i don't need the first and last ones. THOSE will inflate the lootpool. the halved ones are fine. also, if smth is happening and you say "I don't want that to happen" that's starting a fight

**Comment by BreadSpam** [comment]
bro I don't want to get 5 crowns. I want to get unique cosmetics when I get a legendary or mythic. not just another crown

**Comment by BreadSpam** [comment]
bruh 4 crowns is still too much. u get one, and 2 is absolute maximum

**Comment by LostKing73** [comment]
bro it aint four, its 2. and 3 ig if u want the ones evan is adding

**Comment by LostKing73** [comment]
the half and half's are 2. thats all I want... and thedark but like I'm not gonna get into that

**Comment by CelestialKnight7** [comment]
> > > pls dont start fights
> > 
> > 
> > you're the one saying these things should be added regardless while bradley and I both think they shouldnt as they dont look that good and they inflate the lootpool too much
> 
> bro. i don't need the first and last ones. THOSE will inflate the lootpool. the halved ones are fine. also, if smth is happening and you say "I don't want that to happen" that's starting a fight

THATS called having a discussion

**Comment by LostKing73** [comment]
> > yes, but he added 2 other crowns without asking anyone, and that arent ry needed. yes they look good, but the two halves would be better. it's like collecting all pieces of armor.
> 
> bro why u putting this on me, you wanted them, you wanted me to add them, and then i removed them later because I decided that they didn't make the cut

u didn't add them. u added some random crowns that u made.

**Comment by CelestialKnight7** [comment]
oh u talking about the whole ones

**Comment by LostKing73** [comment]
ALL I WANT IS THE TWO HALF AND HALFS. THATS 2, WHICH BREAD SAID IS FINE

**Comment by CelestialKnight7** [comment]
yeah i stand by that cuz they look better than the halves

**Comment by LostKing73** [comment]
dum

**Comment by CelestialKnight7** [comment]
breadley says 2 total not 2 new ones

**Comment by CelestialKnight7** [comment]
theres already 2 in the game

**Comment by LostKing73** [comment]
bro. just have the half and halves. they arent new, THE ONES U ADDED ARE NEW

**Comment by LostKing73** [comment]
T_T why are u doing thisssssssssss

**Comment by CelestialKnight7** [comment]
ye and they look better than the halves, idk why ur so obsessed with having all ur cosmetics be cut in half but it doesnt look as good

**Comment by LostKing73** [comment]
just add the two half crowns... thats all I'm asking for...

**Comment by LostKing73** [comment]
its not even as big of a deal as its bein made...

**Comment by BreadSpam** [comment]
u can have the half and half, but all other crowns and cringe terminators you've added die

**Comment by BreadSpam** [comment]
just have the blue one ppl like and the og terminator, but no white terminator

**Comment by BreadSpam** [comment]
k so we have a deal?

**Comment by BreadSpam** [comment]
u get to keep 2 half and halfs and that one terminator

**Comment by CelestialKnight7** [comment]
no im not budging on this. The half and half ones arent as good as one thats flat across as it interupts the sytle of the art for what? For another color theme? One that doesn't match at all for no reason. Its not even like they're blended to look good. It just cuts off in the middle for no reason making it look (for lack of a better term) bad. The full crowns are better as the art style is consistent throughout and they can also still fit with terminator, possibly better because it wont look like half the tank is be flipped negative.

**Comment by CelestialKnight7** [comment]
> u get to keep 2 half and halfs and that one terminator

neither of the halves are being added

**Comment by CelestialKnight7** [comment]
This isnt even me trying to be selfish, these cosmetics just dont look good because they're cut in half for literally no reason.

**Comment by LostKing73** [comment]
bro. stlye of the art? if nobody wears them, as you have said, why do you care? also, the style of the art is pixels. I'm not gonna change how I make cosmetics bcuz u are bein like this. AND half cosmets are made to match with terminator. yk who made terminator? YOU.. or bread idk but u get the point

**Comment by BreadSpam** [comment]
ye ik they look bad I just want to get this over with so I can do something useful

**Comment by LostKing73** [comment]
its a 2-1 vote evan. they are bein added

**Comment by BreadSpam** [comment]
hmmm

**Comment by LostKing73** [comment]
like also, why is it not cool?

**Comment by BreadSpam** [comment]
bc looks bad?

**Comment by BreadSpam** [comment]
just have a crown??? they already look good?

**Comment by LostKing73** [comment]
k... whatever 2-1

**Comment by BreadSpam** [comment]
new solution: if it's lk's client, it draws a half and half. if it's anyone else's client, its full

**Comment by CelestialKnight7** [comment]
> bro. stlye of the art? if nobody wears them, as you have said, why do you care? also, the style of the art is pixels. I'm not gonna change how I make cosmetics bcuz u are bein like this. AND half cosmets are made to match with terminator. yk who made terminator? YOU.. or bread idk but u get the point

if nobody wears them why should they be added? Its better to have good cosmetics that people actually want to use than a cosmetic specifically designed for you only. This is one of the reasons I didn't want admin cosmetics. You used to make good cosmetics but then you started cutting everything in half for some reason which just ruins them. And again, these look worse on terminator because it looks like half the tank is being reflected. And furhtermore not every cosmetic needs to match terminator

**Comment by CelestialKnight7** [comment]
> new solution: if it's lk's client, it draws a half and half. if it's anyone else's client, its full

no

**Comment by BreadSpam** [comment]
k lol

**Comment by LostKing73** [comment]
> new solution: if it's lk's client, it draws a half and half. if it's anyone else's client, its full

like that's fine too

**Comment by LostKing73** [comment]
bro... SOMEONE is bein selfish...

**Comment by CelestialKnight7** [comment]
Ye YOU. cuz u want ur specifically designed cosmetics that only you want

**Comment by BreadSpam** [comment]
just have 1 generic crown so its unique and not just added to the pile

**Comment by BreadSpam** [comment]
and not based on lore

**Comment by LostKing73** [comment]
> Ye YOU. cuz u want ur specifically designed cut in half gross cosmetics that only you want

k... terminator. like what

**Comment by LostKing73** [comment]
its a 2-1. no vote matters

**Comment by LostKing73** [comment]
bcuz evan is so stubborn

**Comment by CelestialKnight7** [comment]
WHERE is this 2-1 vote ur talking about

**Comment by BreadSpam** [comment]
@cs6413110 @DarkMemeGod411 @CelestialKnight7 @LostKing73 @BreadSpam

**Comment by LostKing73** [comment]
and thinks everything that isnt his is ugly.

**Comment by LostKing73** [comment]
u guys are 2 i mean

**Comment by LostKing73** [comment]
eavnn will never actualy listen to my side, bread is bread.

**Comment by CelestialKnight7** [comment]
> bro... like why tho. why not leave it as it was. it was fine. just don't make it common. and who cares? that's like part of the game

I removed them for a reason, because they didn't make the cut, as I keep saying they're cut in half for no reason and actually look good if they're consistent. And I care, because I dont want some cring cosmetics inflating the lootpool which ruins (notqutie ruins but you get it) the game for everyone else

**Comment by BreadSpam** [comment]
what's better? full crowns, or half and half crowns
👍 = full crowns
👎 = half crowns

**Comment by LostKing73** [comment]
BRO THEN MAKE TERMINATOR FULL WHYS THAT IN HALF

**Comment by BreadSpam** [comment]
bc then it would cover the whole body

**Comment by CelestialKnight7** [comment]
BECAUSE THATSHOW IT WAS DESIGNED AND IT LOOKS GOOD LIKE THAT. THATS THE COSMETIC THATS THE POINT IS THAT IT COVERS HALF THE TANK.
YOU're JUST SPLITTING URS IN HALF FOR NO REASON

**Comment by LostKing73** [comment]
dum... why do yall make so much drama, just like leave it be. it doesn't impact gameplay

**Comment by CelestialKnight7** [comment]
thats another terrible argument. thats the same argument that greedy corperate companies make when they charge $40 for a cosmetic item and then argue "WeLl iTs OnLy CosMetIc" just because its a cosmetic doesnt mean it doesnt matter. Think deep rock, do you think that they dont care about their cosmetics and how they look? No, of course not, because they care about every aspect of their game. Thats why its so good

**Comment by CelestialKnight7** [comment]
And bro deleted the vote

👍 = full corn
👎 = half corn

**Comment by LostKing73** [comment]
bro, like not all cosmetics in drg are perfect. also, don't vote, we all know the outcome

**Comment by LostKing73** [comment]
like noone else uses the doll eyes or whatever its called, but I do, and I like it.

**Comment by LostKing73** [comment]
"i dont think it looks good" well I do. my opinion matters just as much as yours does.

**Comment by LostKing73** [comment]
yes. its you two against me. i understand that. but what can we do to make the cosmetic look better without making it all one color?

**Comment by BreadSpam** [comment]
bruh he ony wears the crowns bc they are like the only rare cosmetics???

**Comment by LostKing73** [comment]
you want it more blended as you said somewhere idk? how about this?
![image](https://github.com/user-attachments/assets/a2a6922b-eb71-40c3-9c23-03435747b764)

**Comment by BreadSpam** [comment]
ew

**Comment by LostKing73** [comment]
> bruh he ony wears the crowns bc they are like the only rare cosmetics???

my point is, insteadof fighting, why not improve them?

**Comment by LostKing73** [comment]
> ew

k, make a better version then! i would enjoy seeing other versions that are not all of one color.

**Comment by BreadSpam** [comment]
there is already enough stupid crowns im not making more

**Comment by LostKing73** [comment]
if neither of u (especially u evan, mr graphic designer) cannot make a better version, then it is the best it can be. if it the best it can be, it will be added.

**Comment by LostKing73** [comment]
here is another attempt, if you want it actually to be inverted, this is what it would look like

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/41141f80-4cd4-4ed8-96c4-6fc16f3251dc)

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/41141f80-4cd4-4ed8-96c4-6fc16f3251dc)

**Comment by cs6413110** [comment]
AHHHHHHHHHHHHHH

**Comment by CelestialKnight7** [comment]
> if neither of u (especially u evan, mr graphic designer) cannot make a better version, then it is the best it can be. if it the best it can be, it will be added.

i did, its one consistent color

**Comment by CelestialKnight7** [comment]
> ![image](https://private-user-images.githubusercontent.com/175903140/368633690-41141f80-4cd4-4ed8-96c4-6fc16f3251dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzQ2NDIsIm5iZiI6MTcyNjY3NDM0MiwicGF0aCI6Ii8xNzU5MDMxNDAvMzY4NjMzNjkwLTQxMTQxZjgwLTRjZDQtNGVkOC05NmM0LTZmYzE2ZjMyNTFkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNTQ1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTMxNDI4NmFmODJhZmQxNDljNTA2MWRiNjhiMTRlYjdkYzZiYjdlZDEzMjMzNDU2M2NjYzU5NTI3OTU1Yzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.euEs-FMOz9CU6XRayTUhMRLsDtiRGyN-yu4J1kNzUrA)

honestly looks better than the silver one but still no

**Comment by CelestialKnight7** [comment]
talked about it with aaron in person and he has his own idea that im fine with.

**Comment by cs6413110** [comment]
Ok here's the deal. Lk you can have your 2 crown cosmets but no more crown/half cosmets for the rest of the year. Put your focus back on making actual cosmetics for the general population. The crowns will be added to the admin pool and at the end of the year the admin pool will be deleted.

**Comment by cs6413110** [comment]
Both agree?

**Comment by LostKing73** [comment]
> talked about it with aaron in person and he has his own idea that im fine with.

which is?

**Comment by LostKing73** [comment]
LITERALLY YES

**Comment by LostKing73** [comment]
my comp cant handle this issue, so since resolved, @cs6413110  fix everything

**Comment by LostKing73** [comment]
k so like fi aaron and then close

**Comment by LostKing73** [comment]
fixxxxxxxxxxxx and also like dont touch oneterminator its fine

**Comment by CelestialKnight7** [comment]
jk idc anymore, ill just do another purge at the end of the year

**Comment by LostKing73** [comment]
bruh just like fix @cs6413110

**Comment by cs6413110** [comment]
![Screenshot 2024-09-18 10 11 41 AM](https://github.com/user-attachments/assets/eaa09992-3824-48c3-89fb-33ae7599371b)

**Comment by LostKing73** [comment]
z

**Comment by cs6413110** [comment]
Bro, like, you don't need neth bc you have a 100% chance to lose the gear. Diamond is better for defensive crystal because of more kb, allowing you to get blasted far enough with the first pop to retotem, etc. Neth is better for offensive because you can't get kb hit as much and you can rush harder thanks to armor toughness. But you can get dtapped slightly easier once they get that kb in. Also getting underledged is literally a death sentence.

**Comment by LostKing73** [comment]
nuh, i like cool blast resistance and no go bye bye when lava

**Comment by cs6413110** [comment]
okah, but also you get targeted if you have netherite

**Comment by LostKing73** [comment]
no im stelthy
