### ISSUE TITLE
cooldown timers

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#220]
make timers for the cooldowns instead of just the bar.
on top of the bar, during while an item is on cooldown. a white number will be displayed above it that shows how much time is left on the cooldown rounded up to the tens place in decimal.

**Comment by BreadSpammer** [comment]
![image](https://github.com/user-attachments/assets/46538073-3b9a-4f04-a20e-2130dd0ce21d)
