### ISSUE TITLE
W(ork)

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#223]
So, me and aaron talked and...

As far as i can tell, @cs6413110 needs to code:

- More optimization
- AI stuff
- Whatever else is needed for singleplayer

And we (@BreadSpammer @LostKing73 @CelestialKnight7 @DarkMemeGod411 ) need to:

- Decide on whos making which of the zones
- Make our 20 maps each

Anything need to be changed/added/removed?

**Comment by LostKing73** [comment]
For the deciding the zones we're gonna do for singleplayer, i believe since there is 5 zones being split between 4 ppl, itll work like this:

- @LostKing73 do 40. Bcuz i want to do the deep, but i want to know if i can do leviathan or not in it first, so ill do gem in the meantime. So deep and gem for me.

- @DarkMemeGod411 I was mentioning this to him, and he threw a... for lack of better words, threw a fit, and called dibs on ice. So he gets ice ig

- @BreadSpammer decide if you want cave or battlegrounds, talk with Celestial abt who gets what

- @CelestialKnight7 decide if you want cave or battlegrounds, talk with bread abt who gets what

Good with yall? @cs6413110 anything to add?

**Comment by CelestialKnight7** [comment]
what numbers are cave and battlegrounds?

**Comment by LostKing73** [comment]
> what numbers are cave and battlegrounds?

numbers?

**Comment by CelestialKnight7** [comment]
like the level numbers / difficulty. I think the deep is like 81-100 or something

**Comment by LostKing73** [comment]
idk, @BreadSpammer but images for each level here pls

**Comment by CelestialKnight7** [comment]
ez

**Comment by LostKing73** [comment]
> bruh I thought I'm making all of them? I already finished 1-20 for world 1

oookay, just thought it would be easier on u. i still wanna do deep though, so like ill make them without leviathan for now???

**Comment by LostKing73** [comment]
closing ig cuz bread wants to make it take longer/suck
