### ISSUE TITLE
Evan=dum moment

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#225]
how does level editor import work
halp

1,'battlegrounds','R968I9X6QX2I9R33IX2IXZX5Q5X5IX4IR33IX4IXI5X3GX5IXIX2IR33I2X3IXIX3IX4ZGX3IXI2XIR33IX4IXIX3IX3GX6GX3IR33IZI4XI3GIX4QX4IXI4R33IX15QX3IX5IR33IX6I2X7QXI2X6IR33IXZ4XI10QI2XZ2X3IR33X2Z4X2QX4QX2IXIX2Z2Q3XR33X4Z2X2I2XIX6IX2Z2X2Q2R33X8IX2GZI2GIXIXQZ2XGX2R33I4X4IX2IX3ZX2IQ2Z2XGX2R33X3IX4IQXIXSXIXQIX2Z2XG2XR33X3IQ2X2IX2ZX3IX2IX2Z2X4R33X3IXQ2XIXIGI2ZGX2IX8R33X3IXQ3IX6IXI2X2I4X2R33X3IX4IXIX2QX4QX2IX2IX2R33IGI2X3I2QI10XIX2IXIR33IX6I2X9I2XIGI2XIR33IX5IX4I3X4QX7IR33I4XIX5GXIXGXGQ2XI4ZIR33IX3GX6IXIX2ZX2QXIX4IR33IXI2XIQ2ZX2IXGXGXGXQ2IX3I2R33IX2IXIXZQ2XI3X6QIX4IR33IX4IX3QX11ZXIX2IR33I9X9I9R1045

fix

**Comment by DarkMemeGod411** [comment]
open it, type zone, and import the normal code, no zone name

**Comment by CelestialKnight7** [comment]
no work

**Comment by CelestialKnight7** [comment]
I imported just:
R968I9X6QX2I9R33IX2IXZX5Q5X5IX4IR33IX4IXI5X3GX5IXIX2IR33I2X3IXIX3IX4ZGX3IXI2XIR33IX4IXIX3IX3GX6GX3IR33IZI4XI3GIX4QX4IXI4R33IX15QX3IX5IR33IX6I2X7QXI2X6IR33IXZ4XI10QI2XZ2X3IR33X2Z4X2QX4QX2IXIX2Z2Q3XR33X4Z2X2I2XIX6IX2Z2X2Q2R33X8IX2GZI2GIXIXQZ2XGX2R33I4X4IX2IX3ZX2IQ2Z2XGX2R33X3IX4IQXIXSXIXQIX2Z2XG2XR33X3IQ2X2IX2ZX3IX2IX2Z2X4R33X3IXQ2XIXIGI2ZGX2IX8R33X3IXQ3IX6IXI2X2I4X2R33X3IX4IXIX2QX4QX2IX2IX2R33IGI2X3I2QI10XIX2IXIR33IX6I2X9I2XIGI2XIR33IX5IX4I3X4QX7IR33I4XIX5GXIXGXGQ2XI4ZIR33IX3GX6IXIX2ZX2QXIX4IR33IXI2XIQ2ZX2IXGXGXGXQ2IX3I2R33IX2IXIXZQ2XI3X6QIX4IR33IX4IX3QX11ZXIX2IR33I9X9I9R1045

**Comment by 3foe** [comment]
achem. your pings are weak

**Comment by 3foe** [comment]
@BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer @BreadSpammer

**Comment by LostKing73** [comment]
spam+cring cuz flat

**Comment by CelestialKnight7** [comment]
answer the question then stoopid

**Comment by CelestialKnight7** [comment]
and how about instead of insulting me you answer the question

**Comment by BreadSpammer** [comment]
you copy the whole thing, brackets and all,

**Comment by BreadSpammer** [comment]
also I already did battlegrounds so like converted

**Comment by CelestialKnight7** [comment]
thank you

**Comment by CelestialKnight7** [comment]
bread > jonas

**Comment by CelestialKnight7** [comment]
nvm It didnt work

**Comment by CelestialKnight7** [comment]
halp

**Comment by cs6413110** [comment]
fixed

**Comment by LostKing73** [comment]
ok, its not though

**Comment by LostKing73** [comment]
nvm im dum
