### ISSUE TITLE
EZ

### ISSUE THREAD

**Issue by BreadSpam** [cs6413110/Pixel-Tanks#23]
![ALLOFTHEABOVE](https://github.com/user-attachments/assets/6dba3350-8f26-4a4d-8f7c-5613dc38d551)
@cs6413110 @CelestialKnight7 @LostKing73 @DarkMemeGod411 

ITS BEAUTIFIULL makei t a menuauoi8diuw hjasiodaiofoijadsfoihafdiulasdiufadsf

**Comment by LostKing73** [comment]
what

**Comment by DarkMemeGod411** [comment]
my eyes

**Comment by CelestialKnight7** [comment]
the mactera grabber still has the box lol

**Comment by CelestialKnight7** [comment]
and ye this is just how humans work. When you first learn photoshop this is the first thing u make

**Comment by CelestialKnight7** [comment]
![failed! (1)](https://github.com/user-attachments/assets/a05d8e53-37c0-4476-bae2-0dd7285373b1)
![DISASTER (2) (2)](https://github.com/user-attachments/assets/e90f6732-11c2-4277-a965-3b554c72a108)

**Comment by cs6413110** [comment]
wat

**Comment by CelestialKnight7** [comment]
pov: me when i was learning photoshop

**Comment by BreadSpam** [comment]
so basically lets make the img at the top the new crate area
👍 = yAS
👎 = ew

**Comment by BreadSpam** [comment]
so basically lets make the img at the top the new crate area
👍 = yAS
👎 = ew

**Comment by LostKing73** [comment]
ded

**Comment by BreadSpam** [comment]
I should copy versions of this img and spam it on a new img :)
