### ISSUE TITLE
[BUG] First map when loading in will not have a zone

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#230]
Example:

Noone is in the game. you load in, and the map is supposed to be cave, but it shows as battlegrounds instead. /newmap (in this example) changes the map into one from gem, and the textures show as gem. /newmap again then (in this example) changes back to the first map, and it is cave now.

halp

**Comment by BreadSpammer** [comment]
it seems like this has been fixed. cant load maps so this isn't an issue XD

**Comment by LostKing73** [comment]
cs said fixed

**Comment by LostKing73** [comment]
tf u downvoting for, its not a vote, its a bug????

**Comment by BreadSpammer** [comment]
nah broken

**Comment by BreadSpammer** [comment]
well, game broken :)
