### ISSUE TITLE
DarkMemeGod.

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#237]
I am not going to assume anything. Is this or is this not you. ![Screenshot_20241205_190037_Discord.jpg](https://github.com/user-attachments/assets/741f04fd-083f-4037-a464-59b8048c944e)

**Comment by LostKing73** [comment]
Im dum lol. Obv its not u. Sorry.

**Comment by DarkMemeGod411** [comment]
no capital B at the end.
