### ISSUE TITLE
Moderator Rank

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#239]
With GPA's able to purchase VIP Moderator rank needs to be added here is the list of commands it should have
/mute
/unmute
/ban
/pardon
/lockdown
/chatlock
/kick
and anything else VIP has

**Comment by 3foe** [comment]
/warn (new command) warns a player that they are about to get muted if they have 3 warnings they get muted for an hr or smt

**Comment by 3foe** [comment]
add?

**Comment by LostKing73** [comment]
> /warn (new command) warns a player that they are about to get muted if they have 3 warnings they get muted for an hr or smt

just talk to them

**Comment by LostKing73** [comment]
> well if an admin syas don't do something and leaves and then he does it again and another amdin warns him he can get like 20 warnings before he gets muted. that's what happened with tnoy. with /warn 3 strikes ur out.

... @CelestialKnight7 what do u think

**Comment by 3foe** [comment]
ye like everyone is screaming at u to add @cs6413110

**Comment by LostKing73** [comment]
i wish i could hide for dum. scroll slightly up 3foe

**Comment by cs6413110** [comment]
Just not necessary. The goal is to make the game, not a power hierarchy we'd fail to enforce. We aren't good admins/moderators.

**Comment by BreadSpammer** [comment]
bruh

**Comment by DarkMemeGod411** [comment]
bruh indeed

**Comment by cs6413110** [comment]
Moderating just isn't what the goal is so it's not worth the lines of code.

**Comment by CelestialKnight7** [comment]
@BreadSpammer making this ur job for no reason and also ur scheduled to fix the internet therefore you cannot lag bye

**Comment by CelestialKnight7** [comment]
time to play close the issue war

**Comment by BreadSpammer** [comment]
But drone is worth the lines?

**Comment by DarkMemeGod411** [comment]
> But drone is worth the lines?

True. but cs said we will talk abt this after break
