### ISSUE TITLE
Balancing Moment

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#243]
We need to add additional rewards on kills to prevent 3rd parties. Why?

When you get a kill, you're likely to be low enough that you need to use healing items and/or kit.

This disadvantages you against literally anyone who shows up for like 20 seconds.

We can either give full hp, partial hp, Regen, etc.

Also I think we should add AI's auto Regen to normal tanks to prevent people from HAVING to use toolkit even to heal a small portion of hp.

**Comment by 3foe** [comment]
also while we are at it make it so if u leave the game it during combat u die when u rejoin and when u leave the last person to shoot u gets kill credit

**Comment by 3foe** [comment]
o btw i am still working on what we talked about Tuesday I'm coming up with ideas and when I have 3 good ones ill suggest to you personally, I think I have one good idea for rn but ill have a few more in case u disagree

**Comment by BreadSpammer** [comment]
if kill, then for the next 10 seconds, reduce the time wait for Regen go from whatever it was, to 1 second

**Comment by cs6413110** [comment]
Adding...

**Comment by LostKing73** [comment]
> o btw i am still working on what we talked about Tuesday I'm coming up with ideas and when I have 3 good ones ill suggest to you personally, I think I have one good idea for rn but ill have a few more in case u disagree

Dude literally just tell us. This game is a team effort, not the 3foe show.
