### ISSUE TITLE
the world is ending there's no one to spam about banners whatarewegoingtodoAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by DarkMemeGod411** [cs6413110/Pixel-Tanks#246]
Lk got his account removed. @cs6413110 will have to fix

**Comment by 3foe** [comment]
I can see, also Celestials acc got removed too.

**Comment by LostKing-27** [comment]
thats more like it. evan, i assume?

**Comment by DarkMemeGod411** [comment]
test

**Comment by 3foe** [comment]
I see it

**Comment by BreadSpammer** [comment]
ye Evan died we just tested it

**Comment by BreadSpammer** [comment]
lol wat

**Comment by BreadSpammer** [comment]
Double close DEDDD

**Comment by cs6413110** [comment]
The lack of productivity makes github relatively useless except for me to code.

**Comment by DarkMemeGod411** [comment]
Wdym the end of gihub?
