### ISSUE TITLE
/live imporvment

### ISSUE THREAD

**Issue by BreadSpam** [cs6413110/Pixel-Tanks#26]
basically make it so when u /live, it basically works like if u respawned (cooldowns, and remove the "F to Respawn" while ur alive)

**Comment by LostKing73** [comment]
ok? no other info?

**Comment by BreadSpam** [comment]
accidentally pressed enter

**Comment by LostKing73** [comment]
z

**Comment by LostKing73** [comment]
ye figs

**Comment by LostKing73** [comment]
z
