### ISSUE TITLE
Menus bug

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#260]
when you change the amount of crates u want to open, the inner part of the button doesn't change, and stays on 1.

I think this is bc of the New button animation which is kinda cringe. it always happens, despite if you set it to true or false. it overrides it

**Comment by cs6413110** [comment]
Already accounted for this. Was saving this for last minute polishing as lag and the entirety of singleplayer is more important. But here you go:

To make a menu re-render its buttons, do:
```javascript
Menus.menus[<menuname>].loaded = false;

// or in context

this.loaded = false;
```

The next time the menu tries to redraw it will cull the buttons.

**Comment by BreadSpammer** [comment]
like u expect me to know where to put that in code

**Comment by cs6413110** [comment]
coupling with First world problems
