### ISSUE TITLE
Banners Spam

### ISSUE THREAD

**Issue by DarkMemeGod411** [cs6413110/Pixel-Tanks#262]
**ok, gonna spam banners here cuz they were confirmed. only decorational, not stats. note, all bold text is me, lk
each banner is 60 wide 120 tall**

![image](https://github.com/user-attachments/assets/bc8c0626-7fd3-46da-af1b-169c547dfd06)
![image](https://github.com/user-attachments/assets/d0ccde42-ce6e-4fe7-bed8-3c343a34e4e1)
![image](https://github.com/user-attachments/assets/2dc1ca12-1699-44cc-a9e8-9a9f93a54bec)
![image](https://github.com/user-attachments/assets/98cc4488-caa5-40df-912d-9e6ac8ab49c4)
![image](https://github.com/user-attachments/assets/5c0cf955-f0d9-4e94-8a40-349af6e7493d)
![image](https://github.com/user-attachments/assets/0a574941-b20a-45ae-a398-6345276eb239)
![image](https://github.com/user-attachments/assets/a9aec6ac-4921-4872-816b-61d4ad1d433a)
![image](https://github.com/user-attachments/assets/a115b0ac-ac1a-47ae-a214-b4a447b63ccf)
![image](https://github.com/user-attachments/assets/941c5d1f-6822-487e-9550-4f75ae300498)

**Comment by DarkMemeGod411** [comment]
ok, if u need it its here

**Comment by BreadSpammer** [comment]
nah @logstink needs

**Comment by cs6413110** [comment]
?
