### ISSUE TITLE
3foenation is a problem

### ISSUE THREAD

**Issue by DarkMemeGod411** [cs6413110/Pixel-Tanks#268]
**1. He is a flat jr, so he needs to be at least vip so flat cannot use admin through him
2. he refuses to let me have an opinion
3. he abuses admin when he gets upset abt smth
4. he spams
5. he puts 0 effort into cosmets and refuses to let them be denied**

**my offer: decrease to VIP, like flat.**

**Comment by DarkMemeGod411** [comment]
s

**Comment by DarkMemeGod411** [comment]
I have nothing to do with this issue

**Comment by cs6413110** [comment]
bhruh

**Comment by 3foenation** [comment]
1idc what you think
2 because you always downvote and you are annyonign to gpas and that makes it harder to moderate
3 I'm literally explaining smth
4 wdym
5 umm so i put in more effort than you i moderate gpas wich there are some gay ones

**Comment by 3foenation** [comment]
ummm that like was very common becasue you were doing that for no reason and no every gpa hates you and I got admin mainly to moderate gpas

**Comment by 3foenation** [comment]
umm i dont sear im just saying gay GPAs

**Comment by 3foenation** [comment]
are you sure about that

**Comment by 3foenation** [comment]
umm sure you said swearing and spamming

**Comment by BreadSpammer** [comment]
> and I got admin mainly to moderate gpas

gpas went extinct, they evolved into sevies

**Comment by CelestialKnight0** [comment]
ye vip him bye

**Comment by BreadSpammer** [comment]
ok so DED 3foenation? kk removing his admin
