### ISSUE TITLE
When Turrets get hit with fire boost after being hit from fire ability, game crashes

### ISSUE THREAD

**Issue by BreadSpam** [cs6413110/Pixel-Tanks#27]
aaron plz fix its sso annoying when im 1v1ing and then game dies
![leech](https://github.com/user-attachments/assets/2bbe697a-7d58-4170-9145-72830ab6bec7)

**Comment by LostKing73** [comment]
nooooooooooooo dont grab me aaaaaaaaa

**Comment by LostKing73** [comment]
how? theres no inv cuz u havent added

**Comment by BreadSpam** [comment]
ok its actually when it's onfire from f ability, then boost

**Comment by BreadSpam** [comment]
FIXXX#e d rez k ieijIIKiIALEKDAID WBNREISANF LKa killl EzZZZZZ GEkeltr tKISKllelledssatstreakkeddd RESZZZZZZ klkjlkjaflkjfd lkajflkajdlkf jGOTTEkmeme ezz kiLLL sSTRREAKKKK LESGOOO INSTwntataAAAAAA EZzwsaewrW aWFA ASD  LAFfa fAFFAFF f
