### ISSUE TITLE
stelf boosting scam

### ISSUE THREAD

**Issue by CelestialKnight0** [cs6413110/Pixel-Tanks#273]
when boosting while u don't have enough energy it still consumes energy despite not getting the invis boost.

literally by all definitions of the word: a scam

halp

**Comment by cs6413110** [comment]
Scam = good

**Comment by cs6413110** [comment]
The code shouldn't be doing this... have you double checked?

**Comment by cs6413110** [comment]
It doesn't even charge you until after your boost

**Comment by CelestialKnight0** [comment]
still very much there, if energy is low enough to not have the stealth boost it wont do the stealth boost but it will still subtract energy

**Comment by CelestialKnight0** [comment]
ty
