### ISSUE TITLE
don't make me

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#279]
![image](https://github.com/user-attachments/assets/4192811c-12ee-4c12-bd70-a6e453b53fc3)

**Comment by DarkMemeGod411** [comment]
what did i do?

**Comment by 3foe** [comment]
you said that I should be muted. and trust me I can do far worse than this. aaron you said only sparks would fly and I told you that you were wrong. I also told you that you don't have a bargaining chip, the only reason why I haven't sent this is because this is you thrid strike and you will get expelled, and you wont graduate high school. give me a good reason why I shouldn't send this.

**Comment by 3foe** [comment]
tell me Aaron is pixel tanks worth your degree, you don't have a bargaining chip I don't care about pixel tanks, I have other ways to entertain myself during school. my only question is do I need to include you in this email?

**Comment by 3foe** [comment]
mom and dad can't save you I have already talked to them about doing this and it is up to me, stalling wont help give me a good reason why I shouldn't before school ends. and don't say ill get in trouble too because you said it yourself I haven't helped the game I've only hurt it. I have SS evidence

**Comment by DarkMemeGod411** [comment]
3foe, don't send that email, my parents are already annoyed by my c's in math, do not send that email

**Comment by DarkMemeGod411** [comment]
they are already talking about taking me out of the district. I am sorry

**Comment by 3foe** [comment]
oh well. I wont kill u

**Comment by 3foe** [comment]
but LK and bread have no hope

**Comment by 3foe** [comment]
Celestial although he had hate for me said nothing, and Aaron still needs to provide a reason why I should spare him

**Comment by DarkMemeGod411** [comment]
the email will also punish u tho?

**Comment by 3foe** [comment]
no bcuz i did nothing to help the game as aaron has stated multiple times

**Comment by 3foe** [comment]
also bcuz I would be the one to report it

**Comment by CelestialKnight0** [comment]
alr idc send it. so what if there's an unlockable game. here's how this will go

1. u send e-mail
2. we get called to office
3. we explain ourselves
4. say you've been constantly abusing Aaron for the last however long (could also say that you were the one that forced Aaron to make the game for some Reverse payback but it would be best to stick to the true story to show how much of a prick you are)
5. maybe we get in trouble for a bit although it would likely be mostly with our parents for getting in trouble at school
6. the end

**Comment by CelestialKnight0** [comment]
oh yeah and Aaron dies

**Comment by 3foe** [comment]
the point is the game dies, cause yall can't deal with other poeple

**Comment by CelestialKnight0** [comment]
or we could also just delete the game.
all or nothing

that way no one wins - and the game is almost done anyways so we can just wait until we graduate to publish it

**Comment by 3foe** [comment]
the point is to kill the game not you guys

**Comment by 3foe** [comment]
if the game is going to be weaponized I am taking it down

**Comment by CelestialKnight0** [comment]
ok then lets kill the game, without you. what do you gain from killing the game anyways. I seriously cant see what you can gain from this other than just blackmail material

**Comment by 3foe** [comment]
I havent decided to send it, I have no real reason to. the only one I have is that you are all jerks and you deserve this. you only play nice if someone is going to bonk you on the head and tell you to stop.

**Comment by BreadSpammer** [comment]
> ![image](https://private-user-images.githubusercontent.com/127255188/396211658-4192811c-12ee-4c12-bd70-a6e453b53fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNzU0NDcsIm5iZiI6MTczNDM3NTE0NywicGF0aCI6Ii8xMjcyNTUxODgvMzk2MjExNjU4LTQxOTI4MTFjLTEyZWUtNGMxMi1iZDcwLWE2ZTQ1M2I1M2ZjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxODUyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzJiYzkyMGZiNGU1MTM0MzIxNTRjOGM2YjNmMzExYjY4ZmUzNGJjZTc2YTEwZjg4NjhkOWQ3NjU0MjA0ZWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W3UmRnJ7sj9TD2PSClXyFNaEdZSPUQDERaUgLRWixis)

do it u wont

**Comment by 3foe** [comment]
@DarkMemeGod411 I'm soryy but now i have to send it

**Comment by DarkMemeGod411** [comment]
Please dont\

**Comment by 3foenation** [comment]
why am i not in it

**Comment by 3foe** [comment]
sent

**Comment by DarkMemeGod411** [comment]
3foe, please, DONT

**Comment by 3foenation** [comment]
ig i did not help much but

**Comment by 3foe** [comment]
jk lol

**Comment by 3foe** [comment]
I don't need to send it bcuz bread is being dum

**Comment by 3foenation** [comment]
i dont think alex dersve to be in there or mabey even

**Comment by DarkMemeGod411** [comment]
> i dont think alex dersve to be in there or mabey even

thank you

**Comment by 3foe** [comment]
I have no quarrel with u DMG, I just need to decide if I want to put in evan and aaron

**Comment by 3foenation** [comment]
idc about even but he is probbly the least annoying other than DMG

**Comment by 3foe** [comment]
Evan is just being real, no need to be mad at him

**Comment by BreadSpammer** [comment]
do
it
u
wont

**Comment by 3foe** [comment]
but aaron has been a jerk im on the fence with him

**Comment by 3foenation** [comment]
oh he will

**Comment by DarkMemeGod411** [comment]
> do it u wont

Not helping

**Comment by 3foe** [comment]
bradley are you stupid?

**Comment by 3foe** [comment]
like genuinley

**Comment by BreadSpammer** [comment]
like the email is gonna do anything XD. he porb wont even read it, let alone do anything about it

**Comment by 3foenation** [comment]
honestly i think he should send it about some people

**Comment by 3foe** [comment]
ye bread and LK are dead

**Comment by 3foenation** [comment]
dang byebye tanks

**Comment by 3foenation** [comment]
only got onwer rank to demoote him

**Comment by 3foe** [comment]
being LK's cheer leader

**Comment by DarkMemeGod411** [comment]
am i on the list?

**Comment by 3foenation** [comment]
jk not only

**Comment by 3foenation** [comment]
i dont think so

**Comment by 3foenation** [comment]
honasly i would not put aaron on becuz it is his last year

**Comment by 3foe** [comment]
only bread and LK are ded

**Comment by BreadSpammer** [comment]
literally @3foenation @DarkMemeGod411 have u learned anything about flat? ye says he's gonna destroy game" like very week lol, and it never works

**Comment by 3foenation** [comment]
and his collage

**Comment by 3foe** [comment]
but I won't send it till the last straw is drawn

**Comment by 3foe** [comment]
and there is only one straw left, you guys need to tread lightly

**Comment by 3foenation** [comment]
bcuz he doesent pull the trigger

**Comment by 3foe** [comment]
and bradley if you say do it again I will. trust me I'm not bluffing

**Comment by 3foenation** [comment]
bro i will not be suprised after what youguys did to him and a little me

**Comment by BreadSpammer** [comment]
> sending

bro sending t already stop stalling

**Comment by BreadSpammer** [comment]
SEND. IT.

**Comment by DarkMemeGod411** [comment]
NOT WITH MY NAME ON IT.

**Comment by 3foe** [comment]
Hey, my goal isn't to get a position in the game, it was never blackmail, its revenge. don'tt say I didn't warn you

**Comment by CelestialKnight0** [comment]
ok coward

**Comment by 3foenation** [comment]
just send it

**Comment by CelestialKnight0** [comment]
lol bye

**Comment by DarkMemeGod411** [comment]
not with my name on it please

**Comment by 3foenation** [comment]
i doubt it will

**Comment by 3foe** [comment]
I already sent it

**Comment by 3foenation** [comment]
i think you are good DMG

**Comment by 3foe** [comment]
and I am sending steps that can be done to block it

**Comment by 3foe** [comment]
only bread and LK were murdered

**Comment by 3foenation** [comment]
show them you sent it

**Comment by BreadSpammer** [comment]
step 1: try to block it
step 2: see that bloxfruits updated, and ruined ur life (ur whole life is robux)
step 3: cry in the corner about ur failure to block
step 4: repeat cuz ur just trying to take out ur sadness on us, bc that's all u have left XD

**Comment by 3foenation** [comment]
@3foe reopen

**Comment by 3foe** [comment]
I know how to block it, I don't think you understand I am the one person you shouldn't have made upset, too bad you made a poor choice. @3foenation there is no point in reopening it I already told the school how to block it

**Comment by 3foenation** [comment]
k

**Comment by 3foe** [comment]
I made it so that nobody gets in trouble I simply just tld the school how to block it

**Comment by CelestialKnight0** [comment]
flat

**Comment by BreadSpammer** [comment]
> I know how to block it

XD good one
