### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by BreadSpammer** [cs6413110/Pixel-Tanks#281]
why is it so squished??? I hate it. its so hard to read the text, and it broke some UI too. someone halp

**Comment by cs6413110** [comment]
Be more specific

**Comment by CelestialKnight0** [comment]
he saying make it taller

**Comment by CelestialKnight0** [comment]
by 900%

**Comment by BreadSpammer** [comment]
the letters are too close together

**Comment by CelestialKnight0** [comment]
hes saying make the letters smaller so theyre futher apart

**Comment by BreadSpammer** [comment]
erswsdfghjkljuhygtfdsedf

**Comment by cs6413110** [comment]
veto

**Comment by BreadSpammer** [comment]
no, fix, or find the cause so I can 🚀

**Comment by cs6413110** [comment]
Find a font then?

**Comment by BreadSpammer** [comment]
The font didn't change tho... something else ruined it

**Comment by BreadSpammer** [comment]
bruh close my issue with honor

**Comment by CelestialKnight0** [comment]
he's saying remove chat so that there are no small letters
