### ISSUE TITLE
gambecore

### ISSUE THREAD

**Issue by CelestialKnight0** [cs6413110/Pixel-Tanks#282]
make a class that has a 50% chance to give you a +500% damage buff, increased movement speed and I frames for 5 seconds and will heal you to full, but a 50% chance to just die on the spot. this can be prevented however by using the gambling perk which if activated when you die from losing your class ability will allow you to continue living. In this case you could then use the gambling item (which kills a random person on the map (possibly you)) which if you are fortunate enough to get a kill with scavenger equipped, you could then use your class ability again and possibly heal to full with that juicy damage buff. however if you were to lose that 50/50 from using your class ability, you would have to rely on your gambling perk again to save you. if you are successful you would then have to wanderer around the map in search of a crate, eventually you find one defended by a bread with 40 turrets (no surprise). unfortunately for him you are a professional gambler and simply walk in, break his crate, and leave using only 20 gambles to survive the turrets. Now that you have your class ability back you use it again, unfortunately you lose, looks like all your luck was used to survive those turrets, but fortunately for you, you still have that gambling item. You use it and it kills bread instantly along with his now 208 turrets. You get your class ability back just as bread respawns and unfortunately for him, you finally win that 50/50 and absolutely demolish him so hard that his router dies and account gets deleted from the sheer damage inflicted, both physically, mentally, and emotionally.

**Comment by BreadSpammer** [comment]
adding...

**Comment by cs6413110** [comment]
k sure 🤤

**Comment by BreadSpammer** [comment]
> **bruh? is this joke?**

no
