### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#29]
When you guys get the server to lag and freeze out can you log what you did to make that happen so I can work on performance debugging?

**Comment by BreadSpam** [comment]
spammed /target 3foe 10000000000 a million times

**Comment by 3foe** [comment]
who ran that command?

**Comment by LostKing73** [comment]
z

**Comment by LostKing73** [comment]
i also spammed /target cs641311

**Comment by LostKing73** [comment]
@cs6413110 game broken figs

**Comment by BreadSpam** [comment]
FIGS

**Comment by BreadSpam** [comment]
can u add an admin only button at the top like FFA shortcut that reboots so we can fix ourselves?

**Comment by LostKing73** [comment]
why admin only

**Comment by LostKing73** [comment]
just have it reboot urself

**Comment by BreadSpam** [comment]
sometimes u cant use commands bc the game is freaking ded

**Comment by BreadSpam** [comment]
and u cant save game without reboot

**Comment by LostKing73** [comment]
nonono i mean the button would only reboot u

**Comment by LostKing73** [comment]
o wait i actually read

**Comment by LostKing73** [comment]
ye add

**Comment by LostKing73** [comment]
lag bye
