### ISSUE TITLE
Wiki - Classes.

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#30]
currently, most of the info is outdated/ opinion based. can someone fix this?

link:
https://github.com/cs6413110/Pixel-Tanks/wiki/Classes

**Comment by DarkMemeGod411** [comment]
Can i do it :)

**Comment by LostKing73** [comment]
no.

**Comment by LostKing73** [comment]
especially not since u continue to gaslight me.

**Comment by DarkMemeGod411** [comment]
wdym gaslight

**Comment by DarkMemeGod411** [comment]
how am i gaslighting you?

**Comment by LostKing73** [comment]
you said, and i quote "yes, the pentagram in the middle had to be scaled down 90% to fit in the print bed" then, I asked if you were actually having it printed, and you said no.

**Comment by 3foe** [comment]
💀

**Comment by DarkMemeGod411** [comment]
for context 3foe its the demon sword from adventure time

**Comment by 3foe** [comment]
don't say your going to print the sword if ur not going to

**Comment by LostKing73** [comment]
^^^^ literally yes

**Comment by DarkMemeGod411** [comment]
is aaron here?

**Comment by LostKing73** [comment]
idk

**Comment by LostKing73** [comment]
he WAS here

**Comment by DarkMemeGod411** [comment]
He is at colledge career center rn i think bc spotted

**Comment by LostKing73** [comment]
a

**Comment by DarkMemeGod411** [comment]
ye he is here maybe an sat or smn?

**Comment by DarkMemeGod411** [comment]
u want a mt dew?

**Comment by DarkMemeGod411** [comment]
SPOTTED

**Comment by 3foe** [comment]
gimme ur mt dew

**Comment by 3foe** [comment]
cleaning up spam

**Comment by BreadSpam** [comment]
k I'll do ig

**Comment by LostKing73** [comment]
thx

**Comment by cs6413110** [comment]
someone delete this comment pls :)

**Comment by BreadSpam** [comment]
ok done close

**Comment by CelestialKnight7** [comment]
rip

**Comment by LostKing73** [comment]
danks
