### ISSUE TITLE
**aaron only**

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#32]
Aaron can u change my password
my friend knows it
Ill text u what I want it

**Comment by cs6413110** [comment]
okah

**Comment by LostKing73** [comment]
hey whos this issue for

**Comment by LostKing73** [comment]
uh @cs6413110 can i have my scythe back please?

**Comment by LostKing73** [comment]
bread says he's fine with it

**Comment by BreadSpam** [comment]
1. Aaron doesn't read closed
2. adding it back will add more complications such as flat wanting one

**Comment by LostKing73** [comment]
aaaaaa just dont tell him then..

**Comment by 3foe** [comment]
...
idc bout grapple 
yet

**Comment by LostKing73** [comment]
aaaaaaaa aaron why are you letting urself be abused by flat

**Comment by BreadSpam** [comment]
bruh removed for a reason?

**Comment by LostKing73** [comment]
ye cuz hate + jealus + grrr

**Comment by BreadSpam** [comment]
not me being jealous, just the inevitability of gpas getting jealous

**Comment by LostKing73** [comment]
ye thats what i mean
