### ISSUE TITLE
tank

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#33]
lighttrap is making good tanks on pixel art i think we should hire I am going to tell him to send it to Aaron and look at your email tomorrow.

**Comment by 3foenation** [comment]
btw lighttraps real name is max

**Comment by LostKing73** [comment]
put the art here.

**Comment by 3foenation** [comment]
i cant because my camra no work

**Comment by CelestialKnight7** [comment]
??? its a download?

**Comment by 3foenation** [comment]
idk but he somehow sighned out just now so he has to redo I have him email it to you through school k
look at it tomorrow ok

**Comment by BreadSpam** [comment]
bruh why is everyone trying to take my job??? (don't answer)

**Comment by 3foenation** [comment]
the tank desing not cosmetic

**Comment by BreadSpam** [comment]
bruh I drew those too?

**Comment by 3foenation** [comment]
oh

**Comment by cs6413110** [comment]
> bruh why is everyone trying to take my job??? (don't answer)

![image](https://github.com/user-attachments/assets/daa87bff-d452-457a-857c-5f7079456b9f)

**Comment by 3foenation** [comment]
EZ

**Comment by LostKing73** [comment]
z, also closing cuz like no we're fine, wealready have like 90% artists

**Comment by BreadSpam** [comment]
SPOTTED means to get seen and the person who has spotted you, says "SPOTTTTTTTT" or "SPOTTTED" or "SPOTAGEE SPOT PSOTPSOPTOSPOT" etc
