### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#35]
@BreadSpam @cs6413110 @CelestialKnight7 
![image](https://github.com/user-attachments/assets/30d0069d-8b49-460a-8ac7-23a8f0528db1)

**Comment by CelestialKnight7** [comment]
ye make everyone owner

**Comment by LostKing73** [comment]
he un banned but still fix

**Comment by CelestialKnight7** [comment]
*inhale
@cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110

**Comment by LostKing73** [comment]
fixxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by 3foe** [comment]
guess what

**Comment by 3foe** [comment]
aaron cant revert :)

**Comment by 3foe** [comment]
plus it was a joke

**for context**
jonas said he wouldn't annoy me as a joke to annoy me and I said I 'wouldent ban him'
he was banned for a total of 0.5 seconds and has his admin back in full

**Comment by BreadSpam** [comment]
bruh u closed it before I could

**Comment by LostKing73** [comment]
absolutly not. @cs6413110 figs

**Comment by 3foe** [comment]
also u did the same thing to me times 100k and to tony and to coltins alt and to DMG. if I did keep u banned it would be a fitting punishment

**Comment by LostKing73** [comment]
k, good for u. @cs6413110 halp

**Comment by 3foe** [comment]
read first comment. he and I had an agreement I got him out of hot water and he gives me this. there ain't nothing u can do to change that

**Comment by 3foe** [comment]
if u reopen fine but it will hurt ur crediblity

**Comment by LostKing73** [comment]
lol what

**Comment by BreadSpam** [comment]
bruh u didnt get him out of hot water, u simple didn't push him in lol

**Comment by LostKing73** [comment]
my credibility? with who?

**Comment by 3foe** [comment]
dude, I got all of you out of hot water... I know you wont belive me so you can ask Aaron

also, it hurts ur credibility to whine over a joke especially when you pulled it first

**Comment by DarkMemeGod411** [comment]
what do you mean by that. what hot water was i in?

**Comment by LostKing73** [comment]
aaron was in hot water

**Comment by LostKing73** [comment]
o wait i didnt read

**Comment by LostKing73** [comment]
lol, mathew, im not on a list. im fine. yall are in danger.

**Comment by DarkMemeGod411** [comment]
i assume he means their dad was gonna tell admin abt us

**Comment by LostKing73** [comment]
ye but like, im a ghost

**Comment by DarkMemeGod411** [comment]
i shuld change my account img just in case

**Comment by BreadSpam** [comment]
like bruh its not like I've never been searched before lol

**Comment by DarkMemeGod411** [comment]
ye after someone ratted us out bc of the holy Unmboker

**Comment by BreadSpam** [comment]
flat, ur not saving us, your just not murdering us

**Comment by LostKing73** [comment]
ye, hes just tryna scare us, @cs6413110 make all admins into owner

**Comment by LostKing73** [comment]
> flat, ur not saving us, your just not murdering us

but is bullyism

**Comment by 3foe** [comment]
jonas

**Comment by 3foe** [comment]
you absolutly cannot be talking

**Comment by 3foe** [comment]
alex

**Comment by LostKing73** [comment]
lol and you can?

**Comment by 3foe** [comment]
rant

**Comment by DarkMemeGod411** [comment]
yes?

**Comment by DarkMemeGod411** [comment]
what?

**Comment by 3foe** [comment]
talk abt everything jonas has don to you

**Comment by LostKing73** [comment]
alex u better not be on his side

**Comment by 3foe** [comment]
jonas

**Comment by LostKing73** [comment]
u gotta realize that he is much worse than any of our beef

**Comment by DarkMemeGod411** [comment]
i am not gonna join any side, i dont want to be yelled at by anyone so.. im out of here

**Comment by LostKing73** [comment]
k? imma set aside my dislike to dislike flat

**Comment by 3foe** [comment]
what you have done to him is worse than any 'beef'

**Comment by 3foe** [comment]
im out to lol

**Comment by 3foe** [comment]
jonas you made it clear months ago that you are not my friend, so let me warn you I do not have much tolerance for repeated and intentional attacks

**Comment by DarkMemeGod411** [comment]
i dont want to be in the middle of an argument between friends, I respect cs641311, i respect Celestial, and i respect bread, and as much as it hurts to say, i respect lk.

**Comment by 3foe** [comment]
and evan plz stop I realize you are aarons friends and i wont do anything bout u but please stop

**Comment by DarkMemeGod411** [comment]
Stop the fighting, i cant afford to lose allies, its not like i have an unlimited amount of allies

**Comment by 3foe** [comment]
for u alex ill stop even looking at this issue

**Comment by LostKing73** [comment]
AA the spam

**Comment by DarkMemeGod411** [comment]
Im going radio silent until the arguments end, if u need me ping me. ill be on tanks soon

**Comment by LostKing73** [comment]
> i dont want to be in the middle of an argument between friends, I respect cs641311, i respect Celestial, and i respect bread, and as much as it hurts to say, i respect lk.

k... saying this doesn't help me but, no u don't (respect me)? like the amount u have gaslit me when it benefits you in no way is insane

**Comment by LostKing73** [comment]
lol making another issue cuz spam
