### ISSUE TITLE
bring popcorn and get ready for a drama

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#36]
I looked through GitHub and took pics of everything someone said remove bread or shut or anything like that to bread. would it be funny to make a conteplation of that with music like Mr blue sky

**Comment by LostKing73** [comment]
spam

**Comment by BreadSpam** [comment]
top 10 quotes of 2024 ez

**Comment by 3foe** [comment]
nobody asked you  i was actually asking bradley because I don't want to hurt his feelings

**Comment by LostKing73** [comment]
k. this is bread i dont want it

**Comment by LostKing73** [comment]
bruh. opinion gone cuz deleted comment

**Comment by LostKing73** [comment]
lol ez flat abuse

**Comment by 3foe** [comment]
please stop or i will block you from the github

**Comment by 3foe** [comment]
bro I warned you... before you are blocked I would like to ask. were you ever really my friend or were you just using me from the moment I brought you into the group

**Comment by LostKing73** [comment]
huh? who do u think i am, alex? i literally just dont want to be oppresed

**Comment by LostKing73** [comment]
for someone whos so against their parents, u sure act a lot like them.

**Comment by 3foe** [comment]
what did I do to 'oppress you'. help you keep you chromebook, keep pixel tanks running, slap you on the wrist for being an idiot?

**Comment by LostKing73** [comment]
lol, ban me, remove my admin, abuse power, delete comments, spam open issues that have nothing to do with the game, shall I continue? the only reason that u have power is bcuz u are abusing aaron while he's in a tough place. that is not a healthy behavior in the slightest.

**Comment by LostKing73** [comment]
i didnt. the playerbase did. and it wasn't a ban, it was a shutting

**Comment by 3foe** [comment]
i have not abused power the only questionable thing is banning u and it was a joke.

**Comment by 3foe** [comment]
the reason why I realize dyou were never my friend is because YOU cast the final vote to perma mute me and remove me from github

**Comment by 3foe** [comment]
the player base did nothing

**Comment by 3foe** [comment]
you backstabbed your last freind.

dont think I'm right? is anyone here your friend?

**Comment by BreadSpam** [comment]
so like sure u can waste ur time ig. make

**Comment by LostKing73** [comment]
> you backstabbed your last freind.
> 
> dont think I'm right? is anyone here your friend?

yes. @cs6413110 @CelestialKnight7 @BreadSpam. @LtNathanTanaka even

**Comment by 3foe** [comment]
no only u and evan commented

**Comment by LostKing73** [comment]
k resolved

**Comment by LostKing73** [comment]
checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" checkmate "nuh uh" 

this entire convo^

**Comment by 3foe** [comment]
ur signiture move is nu uh

**Comment by 3foe** [comment]
also get blocked L

**Comment by 3foe** [comment]
K jonas is blocked

**Comment by 3foe** [comment]
ima make a new issue

**Comment by BreadSpam** [comment]
rip

**Comment by CelestialKnight7** [comment]
my eyes grew braincells in order to have enough sentience to regret looking at this issue

**Comment by LostKing73** [comment]
blocking me doest do anything btw
