### ISSUE TITLE
cs641311...

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#37]
@BreadSpam, @CelestialKnight7, and I, @LostKing73 agree that all three should get full auth so the flatter himself cannot flatten us. thank you for your time.

**Comment by BreadSpam** [comment]
@LostKing73 if we all have owner, then that violates flat's "no insta agreement", bc in it, it states that he gets power over who has/dosent have admin, and there's nothing we can do about that, so ded

**Comment by LostKing73** [comment]
lol what? that means he has more power than Aaron. @3foe can you like not be so stingy with ur "rules"? @cs6413110 ignore that part of the rules, its just one part that protects us from flat abuse.

**Comment by 3foe** [comment]
dude, im not being stingy, you are. also nobody agrees that u should get full auth. 
you aside bradley did and he full on told you no

**Comment by LostKing73** [comment]
more abuse
![image](https://github.com/user-attachments/assets/2e0d0224-796c-4e09-9b89-6d98193e1abc)

**Comment by CelestialKnight7** [comment]
bro im just gonna break the game

**Comment by LostKing73** [comment]
like at this point that would be better

**Comment by 3foe** [comment]
I talked to aaron and he is staying out of it he says it s a you and me problem jonas not a github problem so keep the beef off the github, he also said you are not going to get full auth

**Comment by BreadSpam** [comment]
@LostKing73 ye basically were in flat tyranny phase rn so just bunker down

**Comment by 3foe** [comment]
i will give you your admin back though

**Comment by LostKing73** [comment]
omg lol im gonna talk to him, dontclose

**Comment by 3foe** [comment]
maybe just vip

**Comment by 3foe** [comment]
ill tell him to look at this issue rn

**Comment by 3foe** [comment]
you account if fixed, you just have VIP because that's all you are a very important issue I belive that admin is only for developers. if bradley AND even agree I have no problem with giving you admin

**Comment by CelestialKnight7** [comment]
game fixed enjoy ur lobby

**Comment by 3foe** [comment]
YAY

**Comment by LostKing73** [comment]
k like brain ded moment
