### ISSUE TITLE
Perk: Menacing Aura

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#41]
ok ok the name is cring but hold on its kinda cool

### The Basics
Any one within (1 block at level one, 2 at level 2, 3 at level 3) block distance from you is slowed by (small amount level 1, increases each level, @CelestialKnight7 can decide on this) This would help defend against flatting. 

### Why add this?
This would help defend against flatting, combo well with tactical, stealth, warrior, and maybe even builder. it is not as op as block since you could gripple or boost out, but would pair well with items like airstrike( cuz we all know airstrike needs smth at this point).

### Voting

👍 = yes
👎 = no (comment why)

**Comment by LostKing73** [comment]
@BreadSpam @cs6413110 @CelestialKnight7

**Comment by DarkMemeGod411** [comment]
Great idea, thanks for pinging me

**Comment by LostKing73** [comment]
i thought i might as well

**Comment by cs6413110** [comment]
annoying to fight someone with this. effectively essential for shotgun

**Comment by cs6413110** [comment]
Oh, also, if someone looked menacing, I would actually run faster

**Comment by BreadSpam** [comment]
bro this is worse than block it's like ur permanently tool kitting

**Comment by CelestialKnight7** [comment]
ew

**Comment by LostKing73** [comment]
No, UR not slow, the enemy is

**Comment by BreadSpam** [comment]
ye its annoying for them, not u

**Comment by BreadSpam** [comment]
also op, 👎

**Comment by CelestialKnight7** [comment]
closing cuz ew
