### ISSUE TITLE
A Sequel to Perks: Overdrive

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#42]
**IGNORE THIS TOP COMMENT, SCROLL DOWN TO VOTE FOR NEW IDEA**

### The Basics
When you max out a perk, you can spend a TON of money(like a million) to get an "Overdrive" for that perk. Instead of having 2 perks, having an overdrive takes up both spots, and is a overpowered "super" version of that perk

### Why add this? 
This adds more reason to grind for money, and another way to be op, but still balanced.

### Examples (can be changed)

Menacing Aura - The aura now limits the player effected by Menacing Aura to only move as fast as the player using Menacing Aura (this does not include gripples or being gripped)
 
...i cant think of more ideas rn...

### Voting

👍 = Yes
👎 = No (comment why)

**Comment by LostKing73** [comment]
also, comment ideas for examples. i'll start

**Comment by LostKing73** [comment]
Overdrive Radar

using the regular shooting can give your bullets a small amount of guidance towards the nearest enemy.

possible alternates:
shooting will make your bullets come out of ur barrel, the guide to wherever ur mouse was when you shot the bullets

**Comment by LostKing73** [comment]
@cs6413110 @CelestialKnight7 @BreadSpam @DarkMemeGod411

**Comment by cs6413110** [comment]
#707

**Comment by BreadSpam** [comment]
^^^

**Comment by BreadSpam** [comment]
how about make this adrenilane (so if u take a perk + adrenilane, then that perk gets overdrived)

**Comment by CelestialKnight7** [comment]
> how about make this adrenilane (so if u take a perk + adrenilane, then that perk gets overdrived)

would solve the problem of us needing to replace adrenaline

**Comment by LostKing73** [comment]
Thats a thing? Sure that also sounds cool

**Comment by DarkMemeGod411** [comment]
saturday github notfifications, what is this, Work?

**Comment by BreadSpam** [comment]
There is no rest to the spam

**Comment by cs6413110** [comment]
Fix
Sent from my iPhone

On Sep 22, 2024, at 10:20 AM, BreadSpam ***@***.***> wrote:

﻿

There is no rest to the spam

**Comment by LostKing73** [comment]
AAAA TOO MANY WORDS

**Comment by LostKing73** [comment]
> how about make this adrenilane (so if u take a perk + adrenilane, then that perk gets overdrived)

I like this idea best, everyone agree to using that and implementing this idea?

**Comment by cs6413110** [comment]
Fix
Sent from my iPhone

On Sep 22, 2024, at 4:52 PM, LostKing ***@***.***> wrote:

﻿

how about make this adrenilane (so if u take a perk + adrenilane, then that perk gets overdrived)

I like this idea best, everyone agree to using that and implementing this idea?

**Comment by LostKing73** [comment]
VOTEEEEEEE @cs6413110 @CelestialKnight7

**Comment by CelestialKnight7** [comment]
good idea but im not commited yet, what would this do to each perk?

**Comment by cs6413110** [comment]
Ye like refresh

**Comment by cs6413110** [comment]
Also, this is technically worse for our timeline because we need to make 8 more perk enhancements instead of just making 1.

**Comment by BreadSpam** [comment]
8 unorigonal ideas, or 1 original idea?

**Comment by LostKing73** [comment]
> good idea but im not commited yet, what would this do to each perk?

can you list each and say what they do? cuz idk

**Comment by LostKing73** [comment]
like each perk, not overdrived

**Comment by 3foe** [comment]
also make adrenaline a level 20 perk now

**Comment by LostKing73** [comment]
> emergency shield: when this pops, gain 1 second of i frames **so the issue with warrior now is for everyone oh no** thermal armor: radius doubled (so imagine the 2x2 spawn. if u stood in the center, it would cover the whole thing scavenger: gain 150 HP on kill lower cd: chance for any cooldown to be not used when used. (aka free item) **imagine u hit the Insta key but u get another dynamite so ur insta fails** refresh: half of toolkit Cooldown refreshed on toolkit completion **medic flash back** radar: all bullets shot get a small amount of aimbot **imagine the shot gun fights** advanced grip: Cooldown reduced even when hitting someone >:) **advanced grip flashback** not done yet: chance to live increased to 75% **hard countered by fire**

I literally said not overdrive. what do they NORMALLY DO

**Comment by LostKing73** [comment]
bruh, DONT HIDE. WHAT DO THEY NORMALLY DO SO I CAN HAVE AN OPINION

**Comment by CelestialKnight7** [comment]
me omw to go to hell and find the old perk issue

**Comment by CelestialKnight7** [comment]
1. emergency shield: if your health drops below 25 hp you gain a shield equal to your remaining hp. / unlocks at level 2 / 2 tiers (increase minimum hp to trigger this to 50 hp (and thus the possible max hp of the shield)
2. thermal armor: anything on ur hitbox takes damage (2 dmg per idk) / unlocks at level 4 / 3 tiers (increases dmg to 5 / 8)
3. scavenger: get some time back (25% time) for your other cool downs (toolkit/class/power missile) from kills / unlocks at level 6 / 3 tiers (increases amount of cooldown regenerated to 50% / 75%) (yes I'm aware this is a tactical buff ur welcome)
4. faster cooldown: all of your cooldowns are (5% faster) / unlocks at level 8 / 3 tiers (increases Regen to 10% / 15%)
5. refresh: on completion of a toolkit you get 50% time back to all item cooldowns / unlocks at level 10 / 2 tiers (increases cooldown regenerated to 100%)
6. radar: radar: pings the nearest non-stealthed enemy / unlocks at level 12 / 2 tiers: allow you to see allies as well
7. advanced hook: your grapple has a lower cooldown if you miss a player, but you cannot grapple walls / unlocks at level 14 / 3 tiers (increases how much cooldown you get back if you miss) - [might be ded idk yet]
8. ded / adrenaline / overcharge
9. dying core: when taking lethal damage, there is a 10% chance to not die, with 1 second of invincibility / unlocks at level 18 / 3 tiers, increase chance to not die 10% -> 25% -> 50% (the only cooldown is how lucky you are)

**Comment by LostKing73** [comment]
thank youuuuuu

**Comment by LostKing73** [comment]
1. it also releases a knockback shockwave
2. damage increase(?) fire trail(?)
3. instantly get all cooldowns back on a kill
4. cooldown speed increase(?) you move faster(?)
5. toolkits are faster(?) get 100% of the time back
6. scans every 5 seconds within a small radius, when someone is in that radius when scanning, you automatically shoot there.
7. grapple breaks the block you use it on(unless void)
8. n/a cuz would be paired with everything else
9. it becomes a 70/30 to live, and the damage that would've killed u is reflected(could be like 20, so not too op, or like reflecting an insta so BOOM damage)

**Comment by LostKing73** [comment]
uhm feel free to disect it

**Comment by CelestialKnight7** [comment]
1. pass
2. dmg increase - pass / fire trail - mimicking fire class too much
3. maybe
4. cooldown increase - maybe / speed increase - less maybe
5. (already get 100% of cooldowns back) pass
6. pass
7. maybe (perk is still unfinished)
8. N/A
9. pass but heres my idea: for every 50/50 you win, the chances increase by 5 so the next would be a 55/45, then 60/40 and so on maxing out at 90/10

**Comment by LostKing73** [comment]
ooh i like ur 9

**Comment by LostKing73** [comment]
for max ezzage

**Comment by LostKing73** [comment]
uhm, make a list pls then im a tired

**Comment by BreadSpam** [comment]
already made one??? @CelestialKnight7 approve

- emergency shield: when this pops, gain 1 second of i frames **so the issue with warrior now is for everyone oh no**
- thermal armor: radius doubled (so imagine the 2x2 spawn. if u stood in the center, it would cover the whole thing
- scavenger: gain 150 HP on kill
- lower cd: chance for any cooldown to be not used when used. (aka free item) **imagine u hit the Insta key but u get another dynamite so ur insta fails**
- refresh: half of toolkit Cooldown refreshed on toolkit completion **medic flash back**
- radar: all bullets shot get a small amount of aimbot **imagine the shot gun fights**
- advanced grip: Cooldown reduced even when hitting someone >:) **advanced grip flashback**
- not done yet: chance to live increased to 75% **hard countered by fire**

**Comment by CelestialKnight7** [comment]
1. you gain a shield that naturally recharges out of combat? (combat being defined as taking damage in the last 20 seconds)
2. when you die, release a fiery explosion (not actual fire dot but a visual effect) would be a 4x4 radius (closest thing to nuke tank) (also there would be 2 second windup before the explosion)
3. after a kill you gain a +10% damage bonus for 5 seconds
5. while toolkitting you have no cooldowns (joke) 
7. displays enemies health bars and turret ammo counts
8. N/A
9. for every 50/50 you win, the chances increase by 5 so the next would be a 55/45, then 60/40 and so on maxing out at 90/10

**Comment by LostKing73** [comment]
1. eh..
2. ooh, but no windup cuz there's no point then
3. that's like nothing, also usb moment
4. make a serious one then
5. ye makes sense, but not as good as the others
6. n/a
7. yes

**Comment by CelestialKnight7** [comment]
2. how about 0.5 second windup cuz u gotta give them some time to react (also damage would be 200)
3. +20% but still 5 seconds
4. nah
5. well the others are cooldown based or damage upgrades so radar has to fit with original radar and have synergy with classes and items (ie: tactical)

**Comment by CelestialKnight7** [comment]
also i feel like 1 could be good and would allow you to swap something out for that shield spot that everyone uses

**Comment by LostKing73** [comment]
true

**Comment by LostKing73** [comment]
yes to all

**Comment by BreadSpam** [comment]
:(

**Comment by CelestialKnight7** [comment]
4. receiving healing restores time on your items cooldown with the time being decreased contingent upon the amount of healing recieved (medic synergy also passive cooldown reduction from just using healing items)

**Comment by CelestialKnight7** [comment]
base advanced grip btw: when you grapple a person you get the base cooldown, but if you grapple a wall the cooldown is reduced by t1: 1/3rd, t2: 2/3rds, t3: 100%. so at t3 u can spam gripple as much as u want with a 0 second cooldown. this makes it easier to grapple people without worrying about grappling into a turret den.

overdrive: the grapple can curve a maximum of 20 degrees to attempt to hit something

**Comment by CelestialKnight7** [comment]
buff cooldown reduction perk tho so
t1: 10% reduced
t2: 15% reduced
t3: 25% reduced

**Comment by CelestialKnight7** [comment]
1. you gain a shield that naturally recharges out of combat? (combat being defined as taking damage in the last 20 seconds)
2. when you die, release a fiery explosion (not actual fire dot but a visual effect) would be a 4x4 radius (closest thing to nuke tank) (also there would be 0.5 second windup before the explosion which does 200 dmg)
3. after a kill you gain a +20% damage bonus for 5 seconds
4. 25% chance when using an item/ability for it to not be used/go on cooldown
5. receiving healing restores time on your items cooldown with the time being decreased contingent upon the amount of healing received (medic synergy also passive cooldown reduction from just using healing items)
6. displays enemies health bars and turret ammo counts
7. grip - vote
8. N/A - overdrive
9. for every 50/50 you win, the chances increase by 5 so the next would be a 55/45, then 60/40 and so on maxing out at 90/10

**Comment by CelestialKnight7** [comment]
> buff base cooldown reduction perk tho so that the healing one doesnt overshadow it t1: 10% reduced t2: 15% reduced t3: 25% reduced

^^^

**Comment by DarkMemeGod411** [comment]
gotcha, i like it

**Comment by LostKing73** [comment]
neither?

**Comment by CelestialKnight7** [comment]
> neither?

then come up with one?

**Comment by LostKing73** [comment]
Already did?

**Comment by 3foe** [comment]
nah his are better

**Comment by BreadSpam** [comment]
FIXXXX

**Comment by CelestialKnight7** [comment]
downvote that man

**Comment by BreadSpam** [comment]
ahlp

**Comment by LostKing73** [comment]
bruh

**Comment by CelestialKnight7** [comment]
ok so gripple doesnt get an overdrive apparently cuz no one can vote or come up with a better idea

**Comment by BreadSpam** [comment]
bruh gave one. advanced grip gets cooldowns back even if u hit someone

**Comment by CelestialKnight7** [comment]
evil

**Comment by BreadSpam** [comment]
ye :). not gud, but evil :))))

**Comment by BreadSpam** [comment]
btw advanced grip update: animatie it like the hookshot from zelda (it won't just disappear, but instead come back to u, which indicates when u get ur cooldowns back) for polish

**Comment by LostKing73** [comment]
like a grappling hook where it bounces off the blocks well?

**Comment by LostKing73** [comment]
> ok so gripple doesnt get an overdrive apparently cuz no one can vote or come up with a better idea

I did?

**Comment by BreadSpam** [comment]
> like a grappling hook where it bounces off the blocks well?

yes exactly, but cant even try adding bc it's porl rn

**Comment by CelestialKnight7** [comment]
gripple can bounce off walls twice ez lol byeeee

**Comment by LostKing73** [comment]
> or like, make it pull blocks maybe? could be cool as a way to breach bunkers with invincible walls

^^^?

**Comment by CelestialKnight7** [comment]
nah

**Comment by BreadSpam** [comment]
FXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFXFXXIXIIXIFIFXIFIXIFFIIXFIFXIXIFXIFXIFIXGIFIFXFXIXFIFIFXXFIX XIFXIFIXFIFXFIXFIXIFXFIFIXIFX

**Comment by LostKing73** [comment]
i meant as an animation lol but alr

**Comment by CelestialKnight7** [comment]
wha. i cant read today apparently

**Comment by LostKing73** [comment]
nah i wrote it weird. i meant like it would pink off the wall it hit, but bouncy as its overclock I mean overdrive works

**Comment by LostKing73** [comment]
@CelestialKnight7 @BreadSpam @cs6413110 can we not forget that this exists?

**Comment by LostKing73** [comment]
@cs6413110 pls ad dying core or whatever its called already, perks should be done by now

**Comment by CelestialKnight7** [comment]
1. you gain a shield that naturally recharges out of combat? (combat being defined as taking damage in the last 20 seconds)
2. when you die, release a fiery explosion (not actual fire dot but a visual effect) would be a 4x4 radius (closest thing to nuke tank) (also there would be 0.5 second windup before the explosion which does 200 dmg)
3. after a kill you gain a +20% damage bonus for 5 seconds
4. 25% chance when using an item/ability for it to not be used/go on cooldown
5. receiving healing restores time on your items cooldown with the time being decreased contingent upon the amount of healing received (medic synergy also passive cooldown reduction from just using healing items)
6. displays enemies health bars and turret ammo counts
7. grip - increases the cooldown regained to 200% so you can spam ur gripple until you hit someone
8. N/A - overdrive
9. for every 50/50 you win, the chances increase by 5 so the next would be a 55/45, then 60/40 and so on maxing out at 90/10

**Comment by LostKing73** [comment]
too lazy to read so automatic approval

**Comment by 3foe** [comment]
7

**Comment by LostKing73** [comment]
ded ig? :(

**Comment by CelestialKnight7** [comment]
ye rip
