### ISSUE TITLE
 bread gave himself full auth

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#43]
he also gave it to jonas

time for judgment >:D

👍 = temporary admin removal from both of em
👎 = perma mute 
🎉 = warning
👀 = waiting for opinion

**Comment by LostKing73** [comment]
lol no

**Comment by LostKing73** [comment]
thats just like

guys remove mathew full auth?

👍 = yes
👎 = also yes
🚀 = yes but cooler

**Comment by 3foe** [comment]
the defendants have no rights lol

**Comment by cs6413110** [comment]
fixing

**Comment by 3foe** [comment]
cool can we attach a punishment if they do it again

**Comment by 3foe** [comment]
maybe remove code access?

**Comment by LostKing73** [comment]
like what is this, hitlers little brother?

**Comment by LostKing73** [comment]
lol new name for flathew

**Comment by 3foe** [comment]
who are you. alex?

**Comment by LostKing73** [comment]
hitlers little brother reopens this issue and deletes this comment

**Comment by LostKing73** [comment]
POV: ur in germany in the 1930's

**Comment by 3foe** [comment]
YOU are the one stoping everyone from reading what happened. POV ur a hypocrite

**Comment by LostKing73** [comment]
POV germany in the 1930s

**Comment by LostKing73** [comment]
> YOU are the one stoping everyone from reading what happened. POV ur a hypocrite

literally the guy deleting all the comments other than the ones enforcing his regime

**Comment by LostKing73** [comment]
all that was like an hour ago btw

**Comment by BreadSpam** [comment]
there is nothing we can do

- napoleon bonaparte

**Comment by LostKing73** [comment]
like the abuse of aaron is sickening

**Comment by cs6413110** [comment]
Fixed

**Comment by LostKing73** [comment]
> Fixed

bruh un fix

**Comment by cs6413110** [comment]
If flat is hitler's little brother, does that make me hitler? Makes sense because bradley keeps on putting sus symbols on maps.

**Comment by BreadSpam** [comment]
^^^ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by LostKing73** [comment]
lol ez, thats not wht i meant lol

**Comment by LostKing73** [comment]
so like literally POV germany in the 1930s

**Comment by LostKing73** [comment]
@cs6413110 fix. this isn't sustainable. #707

**Comment by LostKing73** [comment]
clean up the poo stain that is flat's influence on this game

**Comment by LostKing73** [comment]
hitler's little brother is so inimical bro

**Comment by LostKing73** [comment]
like literally gib our admin back. bro is not helpful in anyway to anyone.

**Comment by LostKing73** [comment]
"oooh but im helping aaronnn" NO U ARE NOT. U ARE MANIPULATING HIM IN A TIME OF NEED. THAT IS NOT HELPING

**Comment by LostKing73** [comment]
ye like wut
![image](https://github.com/user-attachments/assets/e3bb7f6c-fd18-42fc-8306-9b800744766a)

**Comment by LostKing73** [comment]
@cs6413110 fix

**Comment by BreadSpam** [comment]
G UDFFXYZHGF

**Comment by LostKing73** [comment]
flat is not beneficial

**Comment by LostKing73** [comment]
that was, what, the third time he has banned me? for what, speaking? not swearing, like the gpas were literally just doing, speaking.

**Comment by LostKing73** [comment]
there is nothing you can say that proves against that this is a regime

**Comment by BreadSpam** [comment]
I love how everyone who isn't important is known as a gpa

**Comment by LostKing73** [comment]
like ez tho

**Comment by LostKing73** [comment]
it was idkwhattoputhere
