### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#44]
if someone is frozen and someone grapples them and they leave they leave behind a husk that's broken. it breaks ur screen as well. if that husk gets damages the game crashes

**Comment by cs6413110** [comment]
What kind of admin abuse found this bug?

**Comment by LostKing73** [comment]
lol just a normal dose of flat. literally only him spam freezing a gpa

**Comment by BreadSpam** [comment]
only 1 bug found??? rookie numbers

**Comment by LostKing73** [comment]
z

**Comment by LostKing73** [comment]
just dont freeze and it isnt a problem
