### ISSUE TITLE
News

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#46]
been proposed before, but hld on, hear me out

### The Basics

Walking up to the new mailbox in the lobby lets you open up the News menu. There are tabs for each big thing we are working on. For example, rn we are doing Overdrive, Zones, and some balancing. There would then be 3 tabs, each displays a overview of what each is about, and maybe even a progress meter(prly not tho, cuz each menu has to be custom made and this would take too long)

### Why add this?

Makes the game cleaner, keeps players informed without needing them on the github, can be used for promotion ig

### Voting

:+1: = yes
:-1: = no (comment why)

**Comment by DarkMemeGod411** [comment]
wifi dying tho

**Comment by LostKing73** [comment]
we know

**Comment by LostKing73** [comment]
i'll see if I can make an example later.

**Comment by LostKing73** [comment]
welp, time to not do any work cuz I'm making an example

**Comment by BreadSpam** [comment]
gud idea, but would need to have someone write and I'm lazy. could also display the update # here

**Comment by LostKing73** [comment]
im makin an example. the squigles on the tabs need to be added in after and are the update names (cuz no space)

**Comment by BreadSpam** [comment]
ok so r we gonna make beta server separate from main server so we can text updates before releasing them, so we can number them

**Comment by LostKing73** [comment]
@cs6413110 @BreadSpam @CelestialKnight7 EXAMPLE
![image](https://github.com/user-attachments/assets/18c21543-bc57-4c9a-ad1f-8171f6532138)

**Comment by BreadSpam** [comment]
if u feel like making a whole img for it, then sure ig, but like it could just be a text box

**Comment by CelestialKnight7** [comment]
ew circle. make it a map like minecraft dungeons

**Comment by CelestialKnight7** [comment]
wiat wut is this issue about i cant read

**Comment by LostKing73** [comment]
> wiat wut is this issue about i cant read

news

**Comment by BreadSpam** [comment]
he cant read that stoopid

**Comment by LostKing73** [comment]
> if u feel like making a whole img for it, then sure ig, but like it could just be a text box

that's so lazy tho, this looks better, and isn't that hard

**Comment by BreadSpam** [comment]
k suit urself. indebted to making news for ur whole life DED ez bye

**Comment by LostKing73** [comment]
bet lol, someone still has to figure out how to get text on where all of the squiggles are

**Comment by CelestialKnight7** [comment]
still cant read

**Comment by DarkMemeGod411** [comment]
Ok good work lk, it is a good start.

**Comment by LostKing73** [comment]
overdrive example:
![image](https://github.com/user-attachments/assets/6fe0a1ba-73b1-4f11-bee3-23fe19a58a6d)

**Comment by LostKing73** [comment]
CONFIRMED THEN. SWEET. K, LIKE, WHEN ADD? AFTER MENUS?

**Comment by LostKing73** [comment]
AND SOMEONE FIGURE OUT HOW TO DO THE TEXT WHERE THE BLACK LINES ARE

**Comment by LostKing73** [comment]
@cs6413110 @CelestialKnight7 @BreadSpam

**Comment by LostKing73** [comment]
and evan, even tho u downvoted it still won, so HALP

**Comment by LostKing73** [comment]
also, once the game is complete, this could be used for minor patches/ waves of themed cosmets, like void, xmas, Halloween, and such, and they could even be time-locked?

**Comment by DarkMemeGod411** [comment]
Good idea. also like, the game has to be finished before the end of the year. Because of graduations and such, time based cosmetics have been suggested for a while. I like the idea. maybe go full wf and make them 1 crate each but for only 1-2 days. (i like this idea) 
.
i could see this working well.

**Comment by LostKing73** [comment]
mailbox, as always, instead of complaining abt how bad smth is, try making ur own.
![image](https://github.com/user-attachments/assets/d7a51c87-1082-4c37-ab05-4c7f6ab20c33)

**Comment by LostKing73** [comment]
squiggles-b-gone
![image](https://github.com/user-attachments/assets/63e5e60d-b76a-45eb-bd8f-24243c5106ac) 
![image](https://github.com/user-attachments/assets/e81317b5-27d6-4e08-8d18-564a13966624)

**Comment by CelestialKnight7** [comment]
> mailbox, as always, instead of complaining abt how bad smth is, try making ur own. ![image](https://private-user-images.githubusercontent.com/175903140/370780484-d7a51c87-1082-4c37-ab05-4c7f6ab20c33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzg5MjksIm5iZiI6MTcyNzI3ODYyOSwicGF0aCI6Ii8xNzU5MDMxNDAvMzcwNzgwNDg0LWQ3YTUxYzg3LTEwODItNGMzNy1hYjA1LTRjN2Y2YWIyMGMzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxNTM3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzBhMzg2ZGYwYjM0NWZiZjIzMGJkMzJlZTI5NjYzZDI5OTBhY2U4NmNlOTdjNDlhOTNlMDExNWU0NjQ4NTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MxAsQurp8zbAPFjQpxpZ_qCbd1_xp7FGl-pN_Kk8yfk)

where would this go

**Comment by LostKing73** [comment]
like uh bell

**Comment by LostKing73** [comment]
like prly to the right of cruts

**Comment by LostKing73** [comment]
balanecing menu
![image](https://github.com/user-attachments/assets/cdf59801-2ea0-4dd6-ad8e-3efb55c64130)

**Comment by LostKing73** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaa this is like bottom of prio list prly

**Comment by CelestialKnight7** [comment]
ye, heres the priority list

**top**
- aaron living
- removing flat
- balancing
- fixes

**mid**
- lobby
- banners
- polish
- idk

**negative**
- this

**Comment by LostKing73** [comment]
k, not upset with that

**Comment by LostKing73** [comment]
also, game still boken @CelestialKnight7 figs

**Comment by CelestialKnight7** [comment]
cuz i tried deleting twrite and game iddnt like that

**Comment by CelestialKnight7** [comment]
figs

**Comment by LostKing73** [comment]
still borken

**Comment by LostKing73** [comment]
@CelestialKnight7

**Comment by CelestialKnight7** [comment]
ye idk why

**Comment by CelestialKnight7** [comment]
thought i figs cuz i just undid but rip

**Comment by LostKing73** [comment]
...@BreadSpammer?

**Comment by cs6413110** [comment]
discord/steam
