### ISSUE TITLE
twrite/ s write list

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#47]
plz i need my admin abuse gimme the list of things I can do

**Comment by LostKing73** [comment]
lol no

**Comment by 3foe** [comment]
not asking you asking aaron. plus funny

**Comment by LostKing73** [comment]
abuse isnt funny.

**Comment by BreadSpam** [comment]
ye, especially from a flat

**Comment by LostKing73** [comment]
"waa waa stop hating" *openly admits to wanting to bully others*

**Comment by 3foe** [comment]
got it in person :)
