### ISSUE TITLE
server ded

### ISSUE THREAD

**Issue by DarkMemeGod411** [cs6413110/Pixel-Tanks#50]
fix

**Comment by DarkMemeGod411** [comment]
@cs6413110

**Comment by BreadSpam** [comment]
deal with it

**Comment by BreadSpam** [comment]
cope

**Comment by BreadSpam** [comment]
cry harder

**Comment by BreadSpam** [comment]
cry louder

**Comment by BreadSpam** [comment]
unsightly insects

**Comment by BreadSpam** [comment]
cring

**Comment by BreadSpam** [comment]
Joe mama

**Comment by BreadSpam** [comment]
lol bye

**Comment by LostKing73** [comment]
ye fix

**Comment by DarkMemeGod411** [comment]
@cs6413110 @cs6413110 @LostKing73 @CelestialKnight7 can you load into ffa?

**Comment by LostKing73** [comment]
no

**Comment by DarkMemeGod411** [comment]
can i get a... f....ffffff... FIX!

**Comment by LostKing73** [comment]
no

**Comment by DarkMemeGod411** [comment]
do u have aarons number, if so..... SPAM HIM. jk

**Comment by DarkMemeGod411** [comment]
can we fix?

**Comment by LostKing73** [comment]
no lol

**Comment by DarkMemeGod411** [comment]
k

**Comment by LostKing73** [comment]
@DarkMemeGod411 make maps for ffa pls. and not spam like bread. also, make sure to include what zon its for, and if its for the surface, make sure it is open and spread out

**Comment by DarkMemeGod411** [comment]
> @DarkMemeGod411 make maps for ffa pls. and not spam like bread. also, make sure to include what zon its for, and if its for the surface, make sure it is open and spread out

ok. can do. thanks

**Comment by DarkMemeGod411** [comment]
also fixed
