### ISSUE TITLE
Crates and Inventory

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#54]
When you change your color and you use E in the hex code, it leaves the inventory making it impossible to use hex codes with E

When you go to the crates corner and press E to open it, it simply opens inventory, not the crates menu

**Comment by 3foe** [comment]
ew the grammar i'm fixing it

**Comment by LostKing73** [comment]
the second one is cuz cruts arent done, the first is a bug @BreadSpam figs

**Comment by BreadSpam** [comment]
1: just copy + paste
2: not my problem bye
3: @cs6413110

**Comment by LostKing73** [comment]
k lol
