### ISSUE TITLE
Saw - New Item

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#55]
evan said maybe so hey this has got a chance...

### The Basics

Shoots a saw that deals 150 damage when it hits an enemy, however, it can bounce (loses 50% dmg), bounce (lose 25%), and bounce a third and final time, breaking and not dealing any damage.

### Why add this? 

New damage item for non-tacticals, and the bounce feature allows for recovery when you miss. It would also be pretty good in a hallway.

### Voting

👍 = yes
👎 = no (comment why)

**Comment by BreadSpam** [comment]
how fast is it??? bc rn, it just looks like a better dynamite, or a power bullet 2

**Comment by LostKing73** [comment]
ooh good question, i thoght  it would be rly fast, like when an actual saw bounces around

**Comment by BreadSpam** [comment]
ok so it's broken?

**Comment by LostKing73** [comment]
k... 1.5x?

**Comment by LostKing73** [comment]
doesnt have to be bad

**Comment by BreadSpam** [comment]
bro 150 damage is 50% more than dyna and power. like why use dynamite when u can use saw??

**Comment by BreadSpam** [comment]
besides just add grenade

**Comment by DarkMemeGod411** [comment]
to spot stealths and deal extra damage

**Comment by BreadSpam** [comment]
^^^ like no? why would you bounce it?? that just reduces damage. literally would just be an insta tool

**Comment by LostKing73** [comment]
uhmmmmmmm, what iffffff on its final bounce it gets stuck in the wall and becomes a spike, so it'll be good for keeping flats out of a hall?

**Comment by BreadSpam** [comment]
i said it's too good, not not good enough

**Comment by LostKing73** [comment]
lol ez, come up with something then

**Comment by LostKing73** [comment]
bruh, make an issue abt grenade. this is saw. that is a different item.

**Comment by 3foe** [comment]
It's a good idea but I share the same concern for Bradley you said it is a tool for non-isnta, but it is also a tool for more op insta. tacticle would be able to kill people with a shield because the saw would be faster than the other items and hit first therefore it is a true one-shot

**Comment by LostKing73** [comment]
ummmmm, make it deal 200 damage then

**Comment by BreadSpam** [comment]
LOSTKING ARE YOU STOOPID???

**Comment by BreadSpam** [comment]
that iS MEGOABULLET DMG

**Comment by BreadSpam** [comment]
literally would allow for an insta with shield

**Comment by BreadSpam** [comment]
close issue

**Comment by LostKing73** [comment]
> LOSTKING ARE YOU STOOPID???

yes lol, idk how to save

**Comment by BreadSpam** [comment]
i'll make new issue saving

**Comment by LostKing73** [comment]
schizo moment
