### ISSUE TITLE
Orb - New Item

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#56]
idk sounds like its cool...

### The Basics

A large, shadowy orb is fired out of your tank. It is about 3x3 tiles large, passes through walls, but explodes in a 5x5 radius when it hits void or barrier. It moves very slow, about half the non-boost normal walking speed. It deals 300 damage when it explodes(even to you), but when it is in its orb form, it will simply push opponents(and you) away from it. Bullets will be absorbed into it and not pass through.

### Why add this?

Amazing against turret campers, if someone is based up , using this will surely push them out. Its also pretty good for flatting, as if you use it behind you, you can cover your back. however, its not 100% safe, as it will deal damage to you as well if you accidentally use it in a small tunnel with void/barrier blocks.

### Voting

👍 = yes
👎 = no (comment why)

**Comment by cs6413110** [comment]
supports flatting

**Comment by LostKing73** [comment]
k, bread reason?

**Comment by LostKing73** [comment]
aslo, it can be anti flat bcuz u can push flatsaway fromwhere they r tryna go

**Comment by BreadSpam** [comment]
bc downvote

**Comment by LostKing73** [comment]
bruh. have reason ples or just dont vote

**Comment by LostKing73** [comment]
also, i already made the sprite... 
![image](https://github.com/user-attachments/assets/24e410e9-82f3-4624-b2e4-1d15d749ebf9)

**Comment by LostKing73** [comment]
uhm sure?

**Comment by BreadSpam** [comment]
it sounds bad and annoying. also how tf is this a stealth counter? its a stealth tool: u go in. then u simultaneously use and boost out for a crystal.

**Comment by LostKing73** [comment]
omg i added dtapping

**Comment by 3foe** [comment]
if a steath void bases then rip

**Comment by LostKing73** [comment]
> if a steath void bases then rip

it blows up as soon as it touches void. it couldn't reach them. unless they were close cuz 5x5 blast radius ig

**Comment by 3foenation** [comment]
to op and no nerf

**Comment by BreadSpam** [comment]
^^^ ye this item is op again. @LostKing73 u need to get a sense of scale for ur item damages

shield has 100 hp
dynamite does 100 dmg
tape heals for 125
glue heals for 150 I think maybe idk

basically DMG for items should be around 100

**Comment by BreadSpam** [comment]
and if big, damage, then make it harder to hit

**Comment by BreadSpam** [comment]
for example: airstrike. can do a one shot, but only gets hit once in a blue moon

**Comment by LostKing73** [comment]
uhm nuh uh, fix urself

**Comment by LostKing73** [comment]
it would have big cooldown?

**Comment by CelestialKnight7** [comment]
> it would have big cooldown?

but then get items back on kill so if u get a kill with it then u can just repeat, and its not fun having to wait 3 years for your items

**Comment by CelestialKnight7** [comment]
declaring this ded

**Comment by LostKing73** [comment]
oka
