### ISSUE TITLE
Banner Revival

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#57]
proposed-ish by alex

### The Basics

Banners, love em or hate em, are being added. aaron said they would be added into the lobby, but with the 14 new lobbies being made for absolutely no reason, banners need a new home. and now is where the idea comes to play. yk the two black lines on the sides of the screen? to me, those look perfect for banners. Also, new idea, animated banners, rather than bein a distraction, they animate on a kill

### Why add this?

cuz its cool. also banners liveeeee wooooooo. 

### Voting

👍 = yes
👎 = also yes (lol, its bein added, this is just documentation and organization)

**Comment by LostKing73** [comment]
k, so i need like the size of the side things so I can re-make banners.

**Comment by BreadSpam** [comment]
no menus, no banners

**Comment by CelestialKnight7** [comment]
ew do not put ur cring banner ads on the sides of my screen

**Comment by LostKing73** [comment]
cuz theyre kinda skinny, banners will not have: Stats, Names: Badges. It pretty much will just be a cool art thing

**Comment by CelestialKnight7** [comment]
so they're useless

**Comment by LostKing73** [comment]
no lol, its staying, also, no banner is an option

**Comment by LostKing73** [comment]
if u dont want, just dont use one

**Comment by CelestialKnight7** [comment]
nah

**Comment by LostKing73** [comment]
yah

**Comment by CelestialKnight7** [comment]
also whereis the bread with assigning the aaron

**Comment by LostKing73** [comment]
omg stop doin this. its bein added

**Comment by CelestialKnight7** [comment]
nah

**Comment by LostKing73** [comment]
why close? u have no reason???

**Comment by LostKing73** [comment]
if u dont want, JUST DONT USE IT

**Comment by CelestialKnight7** [comment]
u have no reason, u just told me they would be annoying as if i use them they will be like friking website ads on the side of my screen and theyre useless cuz they have no stats on them

**Comment by CelestialKnight7** [comment]
it would be unbenifitial for them to be added

**Comment by LostKing73** [comment]
its unbenefitial to spam close rather tan do smth important. let me have my banners

**Comment by LostKing73** [comment]
> u have no reason, u just told me they would be annoying as if i use them they will be like friking website ads on the side of my screen and theyre useless cuz they have no stats on them

YOU CAN CHOOSE TO NOT HAVE ONE

**Comment by LostKing73** [comment]
ITS AN OPTINON

**Comment by LostKing73** [comment]
BRUH

**Comment by CelestialKnight7** [comment]
> its unbenefitial to spam close rather tan do smth important. let me have my banners

OH, so its YOUR BANNERS. we're trying to make a game here not appeal to your every desire. You got your gross crowns, not stop trying to add useless garbage to the game

**Comment by LostKing73** [comment]
"i dont want to see that" well u have the option to turn them off "nah better make this a big thing and spamclose and turn it into spam"

**Comment by LostKing73** [comment]
> > its unbenefitial to spam close rather tan do smth important. let me have my banners
> 
> OH, so its YOUR BANNERS. we're trying to make a game here not appeal to your every desire. You got your gross crowns, not stop trying to add useless garbage to the game

bruh, perks are yours.

**Comment by CelestialKnight7** [comment]
its ur useless spam*

**Comment by LostKing73** [comment]
crowns are different. you can see crowns, banners are TOGGLEABLE. IF YOU DONT WANT, YOU CAN CHOOSE TO NOT HAVE

**Comment by CelestialKnight7** [comment]
i chose not to add useless features to the game

**Comment by LostKing73** [comment]
YOU HAVE LITERALLY NO REASON

**Comment by LostKing73** [comment]
ITS POLISH

**Comment by CelestialKnight7** [comment]
ITs THE OPPOSITE OF POLISH. ITS GARBAGE

**Comment by LostKing73** [comment]
> "i dont want to see that" well u have the option to turn them off "nah better make this a big thing and spamclose and turn it into spam"

^^^^^^^^^^^^^^^^^^

**Comment by LostKing73** [comment]
> ITs THE OPPOSITE OF POLISH. ITS GARBAGE

if you do not want to look at them, then don't. stop ruining things for other people. please

**Comment by LostKing73** [comment]
my guy. you are just complaining abt smth that can be fully turned off for you. if you do not want "ads on my screen" then don't. don't trash it for everyone else

**Comment by CelestialKnight7** [comment]
you're ruining thigns for other people other than yourself, no one wants this but you. It would be a bad feature that would look gross but youre persistant on it anyways. only you want this. this would be unbenifitial for the game as a whole yet youre the one spamming about it

**Comment by LostKing73** [comment]
theres bread

**Comment by BreadSpam** [comment]
this is just cring. i'd rather have sus ads than banners

**Comment by CelestialKnight7** [comment]
I dont care about turning it off for myself. no one wants this but you therefore they would have turned it off too. making a useless feature that only you would use that is therefore unbenifitial to the game as only you would use it

**Comment by LostKing73** [comment]
> you're ruining thigns for other people other than yourself, no one wants this but you. It would be a bad feature that would look gross but youre persistant on it anyways. only you want this. this would be unbenifitial for the game as a whole yet youre the one spamming about it

![image](https://github.com/user-attachments/assets/655771ad-5179-42ed-b940-08297c3c0956)
how does this harm the game

**Comment by CelestialKnight7** [comment]
> this is just cring. i'd rather have sus ads than banners

honestly cuz at least the ads do something for the game (make money)

**Comment by LostKing73** [comment]
im not spamming anything. im keeping this CONFIRMED issue alive

**Comment by CelestialKnight7** [comment]
im unconfirming it and shooting it in the backyard

**Comment by BreadSpam** [comment]
not confirned. the only cofirmation is this issues funeral

**Comment by LostKing73** [comment]
literally, if you dont want to see, then you don't have to. this doesn't hurt the game, and isn't a lose situation

**Comment by BreadSpam** [comment]
dEd

**Comment by LostKing73** [comment]
like, why the hate

**Comment by BreadSpam** [comment]
bc its cring, and no one wantss this. useless spam. #707

**Comment by LostKing73** [comment]
if you do not want to see it. DO. NOT. SEE. IT. ITS NOT HARD. THERE IS A NO BANNER OPTION

**Comment by CelestialKnight7** [comment]
you missed my whole argument. 
1. this gets added
2. everyone else but you turns it off
3. therefore everyone but you doesnt want it
4. it becomes a feature only you use as no one else wants it
5. this is a feautre for YOU, not the GAME

**Comment by LostKing73** [comment]
k, and how is that bad, or hurtful. all gpas would have it on too

**Comment by DarkMemeGod411** [comment]
my idea was old yeller'd

**Comment by LostKing73** [comment]
> you missed my whole argument.
> 
> 1. this gets added
> 2. everyone else but you turns it off

alex, the gpas. prly aaron but idk. they wouldn't.

> 3. therefore everyone but you doesnt want it

^^^

> 4. it becomes a feature only you use as no one else wants it

again, ^^^

> 5. this is a feautre for YOU, not the GAME

nnope cuz ^^^, and it is only a benefit, not a bad thing.

**Comment by DarkMemeGod411** [comment]
idk how it would work tho?

**Comment by DarkMemeGod411** [comment]
bc the lines are not actually images just code

**Comment by LostKing73** [comment]
ive said like 20 times

**Comment by CelestialKnight7** [comment]
he wants to put useless cosmetics on the isde of ur screen

**Comment by DarkMemeGod411** [comment]
it was my idea (kind of)

**Comment by LostKing73** [comment]
U CAN TURN THEM OFF

**Comment by CelestialKnight7** [comment]
"will not have: Stats, Names: Badges. It pretty much will just be a cool art thing" - useless feature

**Comment by CelestialKnight7** [comment]
> U CAN TURN THEM OFF

IT DOESNT MATTER

**Comment by BreadSpam** [comment]
u beat me to staleing this issue :(

**Comment by LostKing73** [comment]
> > U CAN TURN THEM OFF
> 
> IT DOESNT MATTER

why??? if ur issue is u don't want to see it, and I'm providing a way to not see them, why are you still complaining??

**Comment by LostKing73** [comment]
fine? you want stats? then itl, be more cluttered and have stats.

**Comment by CelestialKnight7** [comment]
I want banner with stats not on the side of my screen

**Comment by CelestialKnight7** [comment]
you took an idea people were hesitant about and made it worse

**Comment by BreadSpam** [comment]
I don't want banner at all I just want a menu with numbers on it stop complicating things u stoopid idot

**Comment by BreadSpam** [comment]
no one wants banners. memegod doesn't count bc he's just flat jr

**Comment by CelestialKnight7** [comment]
lol

**Comment by LostKing73** [comment]
> I don't want banner at all I just want a menu with numbers on it stop complicating things u stoopid idot

bread, ur ideas are ugly, not clean, and sound like a dev thing. that wouldn't be polsih

**Comment by DarkMemeGod411** [comment]
hurtful. I am helpful (somewhat)

**Comment by DarkMemeGod411** [comment]
> no one wants banners. memegod doesn't count bc he's just flat jr

:(

**Comment by BreadSpam** [comment]
> > I don't want banner at all I just want a menu with numbers on it stop complicating things u stoopid idot
> 
> bread, ur ideas are ugly, not clean, and sound like a dev thing. that wouldn't be polsih

ur's is worse???

**Comment by DarkMemeGod411** [comment]
> > > no one wants banners. memegod doesn't count bc he's just flat jr
> > 
> > 
> > :(
> 
> I meant like how u like to maniplulate ppl by agreeing with them

the idea was somewhat mine.

**Comment by LostKing73** [comment]
There are several reasons why a pure cosmetic update to your game can be beneficial and not bad: 1. Enhanced Player Engagement: By refreshing the visuals of your game with new cosmetic updates, you can re-engage players who may have lost interest in the game. A visual overhaul can reignite their excitement and encourage them to revisit the game. 2. Increased Monetization Opportunities: Cosmetic updates provide a great opportunity for monetization through microtransactions or in-game purchases. Players who want to customize their game experience with new skins, outfits, or visual effects may be willing to spend money on these cosmetic items, thereby increasing revenue for your game. 3. Competitive Advantage: In a saturated gaming market, regularly updating the aesthetics of your game can help set it apart from competitors. Eye-catching visuals and trendy cosmetic items can attract new players and keep existing ones interested in the game, giving you a competitive edge. 4. Community Building: Cosmetic updates can foster a sense of community among players who enjoy customizing their characters or environments. Players may share their favorite cosmetic items with each other, collaborate on creating new looks, or even participate in in-game events focused on cosmetics, strengthening the player community. 5. Longevity and Sustainability: Updating the cosmetics of your game can prolong its lifespan by keeping it fresh and relevant in the eyes of players. Regular cosmetic updates show that the game is evolving and being actively maintained, which can contribute to its long-term sustainability and success in the gaming market. Overall, a pure cosmetic update can breathe new life into your game, increase player engagement and retention, provide monetization opportunities, and help your game stand out in a competitive industry.

**Comment by LostKing73** [comment]
.>:(

**Comment by LostKing73** [comment]
> > > I don't want banner at all I just want a menu with numbers on it stop complicating things u stoopid idot
> > 
> > 
> > bread, ur ideas are ugly, not clean, and sound like a dev thing. that wouldn't be polsih
> 
> ur's is worse???

literally no? mine isn't just oop I clicked a button. wow look at all those numbers. wow, what a useless menu. wish they did something cooler to represent stats.

**Comment by LostKing73** [comment]
like, literallly im only saying on the side cuz WHERE ELSE WOULD THEY GO???

**Comment by LostKing73** [comment]
like, i would stop saying to put them there if u gave somewhere else for them to go. i even added a way for them to work with the game by making animated ones react with kills

**Comment by CelestialKnight7** [comment]
> There are several reasons why a pure cosmetic update to your game can be beneficial and not bad: 1. Enhanced Player Engagement: By refreshing the visuals of your game with new cosmetic updates, you can re-engage players who may have lost interest in the game. A visual overhaul can reignite their excitement and encourage them to revisit the game. 2. Increased Monetization Opportunities: Cosmetic updates provide a great opportunity for monetization through microtransactions or in-game purchases. Players who want to customize their game experience with new skins, outfits, or visual effects may be willing to spend money on these cosmetic items, thereby increasing revenue for your game. 3. Competitive Advantage: In a saturated gaming market, regularly updating the aesthetics of your game can help set it apart from competitors. Eye-catching visuals and trendy cosmetic items can attract new players and keep existing ones interested in the game, giving you a competitive edge. 4. Community Building: Cosmetic updates can foster a sense of community among players who enjoy customizing their characters or environments. Players may share their favorite cosmetic items with each other, collaborate on creating new looks, or even participate in in-game events focused on cosmetics, strengthening the player community. 5. Longevity and Sustainability: Updating the cosmetics of your game can prolong its lifespan by keeping it fresh and relevant in the eyes of players. Regular cosmetic updates show that the game is evolving and being actively maintained, which can contribute to its long-term sustainability and success in the gaming market. Overall, a pure cosmetic update can breathe new life into your game, increase player engagement and retention, provide monetization opportunities, and help your game stand out in a competitive industry.

ew gpt write an actual essay like a man

**Comment by LostKing73** [comment]
omg just answer my question

**Comment by CelestialKnight7** [comment]
> > > > I don't want banner at all I just want a menu with numbers on it stop complicating things u stoopid idot
> > > 
> > > 
> > > bread, ur ideas are ugly, not clean, and sound like a dev thing. that wouldn't be polsih
> > 
> > 
> > ur's is worse???
> 
> literally no? mine isn't just oop I clicked a button. wow look at all those numbers. wow, what a useless menu. wish they did something cooler to represent stats.

that could have been banners but you decided to remove the stats: "banners will not have: Stats, Names: Badges. It pretty much will just be a cool art thing" and make them purely cosmetic and annoying as now they're animated and being a distraction

**Comment by 3foe** [comment]
I agree with jonas here. what does it do to you. if you can list literally any way that it harms besides "nah" "too much effort to turn off" "brain cells" "eye's bleed" or "add are better" I will stay out of this. I want banners you can take a vote if you want but aaron has said that we will add banners this was in the development waiting room. don't try to stick it in there. please don't fight over this I don't want an admin war. let me give you a piece of advice. everyone has an opinion for a reason.

**Comment by LostKing73** [comment]
K. WHERE ELSE WILL THEY GO IF NOT ON THE SIDE

**Comment by LostKing73** [comment]
oh no, please dont flat... my argument will disappear completely... :(

**Comment by CelestialKnight7** [comment]
bro ur not even supposed to be here

**Comment by 3foe** [comment]
whos hitler jr now

**Comment by LostKing73** [comment]
k, evan. honestly. if you dont want them to b on the side, that's fine ig. i have another idea anyways. however, where would they go?

**Comment by LostKing73** [comment]
> whos hitler jr now

you.

**Comment by 3foe** [comment]
**deletes my comment**

**Comment by 3foe** [comment]
hey you guys stopped fighting :)

**Comment by LostKing73** [comment]
> **deletes my comment**

still you.

**Comment by LostKing73** [comment]
> k, evan. honestly. if you dont want them to b on the side, that's fine ig. i have another idea anyways. however, where would they go?

^^^^

**Comment by 3foe** [comment]
now onto the real question jonas has asked like 30 times. Celestial if you were in charge of adding banners where would they go. don't say trash can...

**Comment by CelestialKnight7** [comment]
they would be like the old banners that people were semi fine with. They could appear after a kill like apex legends or titanfall 2 and you could pick stats to flex and it would show you the person who killed you, maybe at some point we could have a way to inspect someone so you could see their flexage

**Comment by LostKing73** [comment]
> they would be like the old banners that people were semi fine with. They could appear after a kill like apex legends or titanfall 2 and you could pick stats to flex and it would show you the person who killed you, maybe at some point we could have a way to inspect someone so you could see their flexage

wait that's like genius. like when ur ded in splatoon

**Comment by 3foe** [comment]
guys

**Comment by 3foe** [comment]
we have kill effects how is that different?

**Comment by CelestialKnight7** [comment]
that was the old banners issue that got left in a corner cuz it was an actually good idea and not jsut an animated thing on the side (sry for the insults but it was a dum idea)

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/ef9331e8-5729-458e-9082-747c88a74d05)

**Comment by CelestialKnight7** [comment]
> we have kill effects how is that different?

nah

**Comment by LostKing73** [comment]
like that

**Comment by 3foe** [comment]
k

**Comment by CelestialKnight7** [comment]
ye kinda althought it would include stats to flex too
like dis
![image](https://github.com/user-attachments/assets/7f9f6d44-6623-4b4e-9266-31edb232f60e)

**Comment by LostKing73** [comment]
bro howd he die to the literal weakest sub in the game? anywaysm, I think that's an amazing idea

**Comment by 3foe** [comment]
byeeeee u problem now

**Comment by CelestialKnight7** [comment]
> byeeeee u problem now

it was never YOUR problem now shoo

**Comment by LostKing73** [comment]
perfect, evan make the issue so i don't get nuked

**Comment by LostKing73** [comment]
104 coments in under an hour ez

**Comment by BreadSpam** [comment]
apex moment

**Comment by LostKing73** [comment]
llol im still curious how he died to an angle shooter
