### ISSUE TITLE
New item idea: Breacher

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#59]
shoot a drill thingy that will attach to a wall(think dynamite) and after 5 seconds whatever block its attached to will explode and die (works on barrier blocks but not void blocks)

the explosion would do 100 dmg and be in a cone shape facing inward (3 blocks) (so this would counter giant thick walls of blocks) this explosion would also be large enough to hit anyone standing directly on the opposite side the the block.

this can be attached to players as well in which it would drill for 5 seconds (this does not do damage) and then explode (dealing 100 dmg), it would have a 25 second cooldown

**Comment by 3foe** [comment]
good. doesn't buff tacticle

**Comment by CelestialKnight7** [comment]
![kaboom](https://github.com/user-attachments/assets/d24144a6-651b-4693-9200-2d0c0abb59cc)

**Comment by CelestialKnight7** [comment]
very gud much quality demo

ur welcome

**Comment by cs6413110** [comment]
Ok, adding time.

**Comment by cs6413110** [comment]
Needs:
- Clarification on what the 3 block explosion is
- Drill Image
- Relative bullet speed(equivalent to dynamite?)
- Is there a difference between exploding on a player and exploding on a block.

**Comment by CelestialKnight7** [comment]
1. its a triangle with the middle distance from the center point to the midpoint of the opposite line (I forgor names of math)
2. I'll make drill img when I can
3. ig
4. nope
5. will make too
6. pain

**Comment by LostKing73** [comment]
not doing
