### ISSUE TITLE
tank

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#62]
this is one of lighttraps drwings on pixel art I know you wanted to know btw it is not fully done
![Screenshot 2024-09-27 11 08 41 AM](https://github.com/user-attachments/assets/6d7e77e9-8c6a-4e43-916f-f653927228d3)

**Comment by 3foenation** [comment]
rate it in chat

**Comment by BreadSpam** [comment]
no

**Comment by 3foenation** [comment]
why are you just mad because he might replace you

**Comment by DarkMemeGod411** [comment]
not the best. bc not right size. its great effort. thanks for sharing,

**Comment by 3foenation** [comment]
i screen shotide it so it will be right if it is used

**Comment by DarkMemeGod411** [comment]
what size is it?

**Comment by 3foenation** [comment]
*shoted*

**Comment by 3foenation** [comment]
idk

**Comment by DarkMemeGod411** [comment]
ik. what is the size of the actual image?

**Comment by 3foenation** [comment]
what size is normal pixel tank

**Comment by DarkMemeGod411** [comment]
top. 40x45 or 45x40

**Comment by BreadSpam** [comment]
also all of the cosmetics are fitted to the tank head that already exists.

**Comment by 3foenation** [comment]
it is bigger

**Comment by 3foenation** [comment]
we can adjust the tank or cosmetics

**Comment by DarkMemeGod411** [comment]
Way too much work

**Comment by 3foenation** [comment]
then we will adjust the tank

**Comment by LostKing73** [comment]
no lol, not for that ewage

**Comment by LostKing73** [comment]
bro is a beach ball

**Comment by cs6413110** [comment]
calm down with the gpa hate lol

this is called game fan art and it's essentially a compliment

**Comment by LostKing73** [comment]
beach ball

**Comment by DarkMemeGod411** [comment]
I
