### ISSUE TITLE
ai commit turret

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#63]
like halp. ai just walk into wall and go, "yeah. I can break this" and then commit turret trying to walk into a wall for the rest of their life

**Comment by DarkMemeGod411** [comment]
Haha, ye they do this alot. They just say, nah, imma sleep here

**Comment by LostKing73** [comment]
figsed

**Comment by DarkMemeGod411** [comment]
ok?

**Comment by BreadSpammer** [comment]
hjyGFDSkjalhfskgfakjsdfasdasfd
