### ISSUE TITLE
I AM HALF ABLE TO PLAY PICKLE TANKS ON MY PHONE

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#64]
not important, just saying cuz its cool
![IMG_20240928_120333](https://github.com/user-attachments/assets/9e9598da-6860-4a6f-a88b-b30c01d89d39)

**Comment by LostKing73** [comment]
bad image but that is pickle tanks on ma phone

**Comment by BreadSpam** [comment]
Ok, move

**Comment by LostKing73** [comment]
thats the other half. i can open chat(but no typing) shoot, and powerbullet.

**Comment by cs6413110** [comment]
Mobile ad tanks inc

**Comment by cs6413110** [comment]
also hax

**Comment by LostKing73** [comment]
Ye

**Comment by DarkMemeGod411** [comment]
ez!

**Comment by DarkMemeGod411** [comment]
Just got github app what do i do to use this ui?
