### ISSUE TITLE
Better Boost

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#66]
### The Basics
Boosting will leave a trail of after images that dissapear over time. an image is attatched below as an example. they woul also be in the color of you tonk to distinguish who boost is whose.

### Why add this?
boosts are just "tonk go fast" visually. this would fix that. its also kinda anti-flat bcuz it lets u know where theyre going

### Voting

👍 = yes
👎 = no (comment why)

### Example
(imagine if the pre-images were fully white)
![image](https://github.com/user-attachments/assets/20b9b0c5-f732-4e02-a1b1-ec667db9dd74)

**Comment by DarkMemeGod411** [comment]
Absolutely. Good idea. Let me know if u need my help on images

**Comment by LostKing73** [comment]
literally not smth u would make images for

**Comment by LostKing73** [comment]
it would be just ur tonk (including outlines of cosmets) but 100% white and white filled

**Comment by DarkMemeGod411** [comment]
Oh ty for the clarification.

**Comment by CelestialKnight7** [comment]
if i had a dollar for every time i had to add another button to the inventory menu....

**Comment by DarkMemeGod411** [comment]
Ikr

**Comment by LostKing73** [comment]
> if i had a dollar for every time i had to add another button to the inventory menu....

wouldn't be button? just would be ur boost?

**Comment by 3foe** [comment]
no point in this. we have eyes to track where a tank goes when it boosts. plus this gives more lag, as we all noticed this morning the lag was crippling don't add to it.

also its more work for Aaron, we need to fix the game before we make the game look polished

**Comment by CelestialKnight7** [comment]
and besides in the old polish issue this was already addressed and it would be simpler to have it be a consistent grey color rather than match the color of your tank.

**Comment by LostKing73** [comment]
"fix the game" fix WHAT? the crates? he's taking 7 years to do that anyways! no offense cs. ik this isn't #1 priority if it gets upvoted. pls also wait until I talk before close

**Comment by LostKing73** [comment]
> and besides in the old polish issue this was already addressed and it would be simpler to have it be a consistent grey color rather than match the color of your tank.

k, then make it grey instead. that would lessen lag too, since less code is searching for ur color

**Comment by CelestialKnight7** [comment]
> > and besides in the old polish issue this was already addressed and it would be simpler to have it be a consistent grey color rather than match the color of your tank.
> 
> k, then make it grey instead. that would lessen lag too, since less code is searching for ur color

ye but this is already stated elsewhere (i think)

**Comment by CelestialKnight7** [comment]
> "fix the game" fix WHAT? the crates? he's taking 7 years to do that anyways! no offense cs. ik this isn't # 1 priority if it gets upvoted. pls also wait until I talk before close

- lobby
- bugs
- balancing
- other gamemodes
- random features u and bread suggest

also in case u didnt notice aaron like died so give him a break hes doing 190% of the work anyways

**Comment by LostKing73** [comment]
wheres like, zones?

**Comment by CelestialKnight7** [comment]
> wheres like, zones?

ded cuz u or breadley commited lazy

**Comment by LostKing73** [comment]
> > wheres like, zones?
> 
> ded cuz u or breadley commited lazy

that would be @BreadSpam

**Comment by LostKing73** [comment]
uh, why didnt he pop up?

**Comment by LostKing73** [comment]
it says"and other" did his acc get taken down?? Bread, edit this comment to talk

**Comment by LostKing73** [comment]
> is issue ded yet?

no. ive given solutions

**Comment by LostKing73** [comment]
> > > and besides in the old polish issue this was already addressed and it would be simpler to have it be a consistent grey color rather than match the color of your tank.
> > 
> > 
> > k, then make it grey instead. that would lessen lag too, since less code is searching for ur color
> 
> ye but this is already stated elsewhere (i think)

huh?? just upvote and call it a day

**Comment by LostKing73** [comment]
> > "fix the game" fix WHAT? the crates? he's taking 7 years to do that anyways! no offense cs. ik this isn't # 1 priority if it gets upvoted. pls also wait until I talk before close
> 
> * lobby
> * bugs
> * balancing
> * other gamemodes
> * random features u and bread suggest
> 
> also in case u didnt notice aaron like died so give him a break hes doing 190% of the work anyways

and where banners?

**Comment by 3foe** [comment]
development waiting room

**Comment by LostKing73** [comment]
on the list. i was not talking to you flat.

**Comment by CelestialKnight7** [comment]
idk i just listed whatever i thought of first and moved on, dont take that list too seriously

**Comment by LostKing73** [comment]
k, so even tho vote is a tie it seems we have a generaly yes on this?

**Comment by 3foe** [comment]
um... I dont think thats how it works for example I could say this:

k, so even tho vote is a tie it seems we have a generaly no on this?

also aaron downvotes everything so its really 2-3 in favor of not adding it.

**Comment by CelestialKnight7** [comment]
ye, its supposed to get added anyways cuz it was in the old polish issue

**Comment by LostKing73** [comment]
k ez lol. i think the after effects bein whit will look better than gray(u said gray earlier)

**Comment by DarkMemeGod411** [comment]
> k ez lol. i think the after effects bein whit will look better than gray(u said gray earlier)

ye

**Comment by BreadSpammer** [comment]
ok um gonna try and code this by making 0 DMG explosions spawn on ur tank while you boost that look like silhouettes.

**Comment by BreadSpammer** [comment]
kinda like a trail

**Comment by LostKing73** [comment]
@BreadSpammer add, should be pretty easy

**Comment by BreadSpammer** [comment]
10x harder than u think my cell cant comprehend

**Comment by LostKing73** [comment]
theres no one to convert here u cant escape

**Comment by CelestialKnight7** [comment]
closing this issue cuz new issue saying the same thing this issue and 3 others have already said so byeee

**Comment by BreadSpammer** [comment]
issue converted lAG BYE

**Comment by LostKing73** [comment]
theres no new issue so no?

**Comment by CelestialKnight7** [comment]
the effects one?

**Comment by CelestialKnight7** [comment]
#97

**Comment by LostKing73** [comment]
thats not what that issue is abt. its different kinda

**Comment by CelestialKnight7** [comment]
-_-

**Comment by CelestialKnight7** [comment]
"pretty much, when you boost, tire treads are behind u(ik its been said before but wait)" just this + some other effects too

**Comment by LostKing73** [comment]
oh yea i forgot abt that

**Comment by LostKing73** [comment]
k hold on

**Comment by CelestialKnight7** [comment]
ez ty
