### ISSUE TITLE
voteth on new item: breacher

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#67]
which is better:

permanently removes blcok with explosion =👍 
temportarily makes block intangible with no explosion = 👎 

for context go read the other issues:
#61 breacher (intangible)
#59 breacher (explosion)

**Comment by CelestialKnight7** [comment]
suggestions to these items are allowed and encouraged unless you are flat

**Comment by 3foe** [comment]
No explosion, imagine the new insta it would be a true one-shot

**Comment by CelestialKnight7** [comment]
they are on the other side of a wall. you cant really time an insta with it

**Comment by LostKing73** [comment]
intangible is good for insta too. i cant hit u thru the wall that ur instaing me thru when I'm warrior

**Comment by CelestialKnight7** [comment]
> they are on the other side of a wall. you cant really time an insta with it

and its very obvious when the drill is placed so its ur fault for getting hit if u stand still for the whole 5 seconds and then still get instaed

**Comment by LostKing73** [comment]
> > they are on the other side of a wall. you cant really time an insta with it
> 
> and its very obvious when the drill is placed so its ur fault for getting hit if u stand still for the whole 5 seconds and then still get instaed

counterpoint: you got blocked

**Comment by CelestialKnight7** [comment]
> > > they are on the other side of a wall. you cant really time an insta with it
> > 
> > 
> > and its very obvious when the drill is placed so its ur fault for getting hit if u stand still for the whole 5 seconds and then still get instaed
> 
> counterpoint: you got blocked

its on the other side of a wall, how u gonan get blocked. and still you have 5 seconds before it detonates

**Comment by LostKing73** [comment]
it the corner of a lone barrier? idk Im grasping at straws for no reason

**Comment by CelestialKnight7** [comment]
the detonation will also have a small flash before it explodes so you can play around the explosion easier

**Comment by LostKing73** [comment]
intangible sucks. it benefits like noone but insta, and we all know insta doesn't need a buff

**Comment by 3foe** [comment]
now that i think about it if it has a lower detonation time then you can hit burrowing stealth so EXPLOSION

**Comment by LostKing73** [comment]
@CelestialKnight7 how much damage does it do upon kaboom..?

**Comment by 3foe** [comment]
if ur a stealth its a one shot :)

**Comment by CelestialKnight7** [comment]
> @CelestialKnight7 how much damage does it do upon kaboom..?

100 and the drilling does no dmg( u can look at the og issue for each idea)

**Comment by 3foe** [comment]
k

**Comment by LostKing73** [comment]
never am i talking to you flat

**Comment by LostKing73** [comment]
and thats not a quip.

**Comment by CelestialKnight7** [comment]
save the pvp for a different issue

**Comment by LostKing73** [comment]
voted and deded
