### ISSUE TITLE
lobby yippeeee

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#69]
R1041I13R26I22X11I27X120I22X5SX5I27R21I4X5I4R50I3XI3R55IXIR52I6XI6R29I13R3I3QGQI2XI2QGQI3R27IX11IR2I2X15I2R26IX11I4X17I2R25IX22ZQZX7QIR25IX22QGQX7GIR25IX22ZQZX7QIR25IX11I4X17I2R25IX11IR2I2X15I2R26I13R3I17R1524 (updated)
add/fix/do/idk i ran out of words

make main lobby i am currently making sub blocks/textures for it such as:
inventory
shop
banners
cruts
train
training dummies
wall things idk

adddddddddddddddddddd (plz)

**Comment by CelestialKnight7** [comment]
also ill make seperate texture pack for the blocks in the lobby

**Comment by LostKing73** [comment]
@cs6413110

**Comment by 3foenation** [comment]
i think this will be better

**Comment by 3foenation** [comment]
R1041I13R35I13X11I13R23IX35IR23IX35IR23I13X5SX5I13R35I4X5I4R50I3XI3R55IXIR52I6XI6R29I13R3I3QGQI2XI2QGQI3R27IX11IR2I2X15I2R26IX11I4X17I2R25IX22ZQZX7QIR25IX22QGQX7GIR25IX22ZQZX7QIR25IX11I4X17I2R25IX11IR2I2X15I2R26I13R3I17R1524

**Comment by LostKing73** [comment]
bruh no. we dont need MORE LOBBY VERSIONS

**Comment by 3foenation** [comment]
ok i just edited his

**Comment by CelestialKnight7** [comment]
took inspiration heres the new one:
R1041I13R26I22X11I27X120I22X5SX5I27R21I4X5I4R50I3XI3R55IXIR52I6XI6R29I13R3I3QGQI2XI2QGQI3R27IX11IR2I2X15I2R26IX11I4X17I2R25IX22ZQZX7QIR25IX22QGQX7GIR25IX22ZQZX7QIR25IX11I4X17I2R25IX11IR2I2X15I2R26I13R3I17R1524

**Comment by LostKing73** [comment]
guys. we are using current one. stop pls

**Comment by CelestialKnight7** [comment]
did u not hear aaron literaly less than 5 minutes ago?

**Comment by LostKing73** [comment]
no wad he say

**Comment by CelestialKnight7** [comment]
bro he asked about the lobby i was making and the imges for it

**Comment by LostKing73** [comment]
didnt he mean the menus things for the rooms? this one works!!

**Comment by cs6413110** [comment]
Literally do not care which one we use but Evan is making a special lobby with custom images so logically we should use his map since he is the only one putting image effort into this.

**Comment by LostKing73** [comment]
oh so we(aaron) have to do completely new hitboxes, wasting more time(on a lobby that was voted no already cuz its just put a bunch of boxes in a corner)? cool.

**Comment by LostKing73** [comment]
like. what? this lobby sucks. theres literally no rooms 
![image](https://github.com/user-attachments/assets/6fe79c98-994c-4ead-be22-ebe8072e2292)

**Comment by LostKing73** [comment]
except the one to the left? idk bro it makes no sense. current one is fine??

**Comment by LostKing73** [comment]
ye, dont make new one cuz new one is bad current is good

**Comment by CelestialKnight7** [comment]
leave open until i can flex my 100+ frames animation for each inventroy block

**Comment by CelestialKnight7** [comment]
also old one is cring, new one is smaller and each station has more specific areas that are smaller

**Comment by LostKing73** [comment]
dude, like if everything is just a box that's dumb

**Comment by CelestialKnight7** [comment]
and the big line is for the train which i just realized i have to draw and animate

![image](https://github.com/user-attachments/assets/86bf15e5-b2e4-4354-82da-088651d2b84d)

**Comment by CelestialKnight7** [comment]
> dude, like if everything is just a box that's dumb

have you seen the current lobby?

**Comment by LostKing73** [comment]
yes, and its good? all u need is right there

**Comment by CelestialKnight7** [comment]
its just boxes, like u said was dumb

**Comment by LostKing73** [comment]
i dont want everything to be boxes in corners :(

**Comment by CelestialKnight7** [comment]
?????? thats what the current lobby is, is just boxes sticking out of walls.

**Comment by CelestialKnight7** [comment]
if u dont like the shooting range idea just say so and i can change it if u have a better idea

**Comment by LostKing73** [comment]
i mean, like, the mineral trade thing in drg. u are saying make everything that

**Comment by LostKing73** [comment]
just a square that represent each section

**Comment by LostKing73** [comment]
i dont mean rooms, rooms is what I WANT

**Comment by LostKing73** [comment]
> if u dont like the shooting range idea just say so and i can change it if u have a better idea

nah shooting range is fine

**Comment by LostKing73** [comment]
> im saying make everyhting a terminal not a box in a corner,

i-hm. while it could work for some stuff and still be cool, what abt like inv? how would that work?

**Comment by CelestialKnight7** [comment]
> > im saying make everyhting a terminal not a box in a corner,
> 
> i-hm. while it could work for some stuff and still be cool, what abt like inv? how would that work?

the blocks currently placed (gold/strong) would be the placeholders for the stations, im currently working on invnentory

it would be in the middle and have arms that come out of the ground to make it look like it actually edits your tank

**Comment by LostKing73** [comment]
aaaaaa whatever i trust u to make smth good

**Comment by LostKing73** [comment]
eh whatever have full control i actually don't care anymore lol

**Comment by CelestialKnight7** [comment]
ok so
- make it so stealth cant break the barrier blocks in the lobby plz (make them have the same collision properties as void)
- make it so bullets appear on top of structures
- ai dummies in left corner, will get cords later

ty

**Comment by cs6413110** [comment]
uhm

**Comment by LostKing73** [comment]
@CelestialKnight7 keep working on this plessssssssssssssssssssssssssss

**Comment by LostKing73** [comment]
@CelestialKnight7 @cs6413110 can y'all like, do this?
