### ISSUE TITLE
Coding Problems for Bradley

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#74]
https://www.codewars.com/kata/5cba04533e6dce000eaf6126/train/javascript - Math practice (possible with only 18 characters)

https://www.codewars.com/kata/57cf50a7eca2603de0000090/train/javascript - String and array practice

https://www.codewars.com/kata/51e0007c1f9378fa810002a9/train/javascript - If statements

**Comment by cs6413110** [comment]
https://www.codewars.com/kata/563fbac924106b8bf7000046/train/javascript

**Comment by LostKing73** [comment]
ooh ooh me next(smth for c++) if u can

**Comment by cs6413110** [comment]
const ignore = ["the","of","in","from","by","with","and", "or", "for", "to", "at", "a"];
function generateBC(url, separator) {
  let src = '<a href="/">HOME</a>'+separator;
  const paths = url.split('/').slice(1);
  for (const path of paths) {
    let parsed = path.split('#')[0].split('?')[0];
    if (parsed.length > 30) parsed = parsed.split('-').reduce((a, c) => a+c.split('')[0].toUpperCase(), '');
    console.log(parsed);
  }
}

**Comment by cs6413110** [comment]
uhm givme 2 periods

**Comment by LostKing73** [comment]
oka

**Comment by LostKing73** [comment]
i literally have looked at one slide of a like 2 day long lesson plan so surely I got it

**Comment by cs6413110** [comment]
> https://www.codewars.com/kata/563fbac924106b8bf7000046/train/javascript

```javascript
const ignore = ['THE','OF','IN','FROM','BY','WITH','AND','OR','FOR','TO','AT','A'];
function generateBC(url, separator) {
  let paths = url.replace('https://', '').replace('http://', '').replace('www.', '').split('/').slice(1);
  let src = '<a href="/">HOME</a>'+separator;
  if (paths.length === 0) return '<span class="active">HOME</span>';
  if (paths[paths.length-1].split('#')[0].split('?')[0].split('.')[0] === 'index') paths.pop();
  paths = paths.filter(a => a !== '');
  if (paths.length === 0) return '<span class="active">HOME</span>';
  let pathage = '';
  for (const path of paths) {
    let last = path === paths[paths.length-1], parsed = path.split('#')[0].split('?')[0].toUpperCase();
    if (parsed.length > 30) parsed = parsed.split('-').filter(a => !ignore.includes(a)).reduce((a, c) => a+c.split('')[0], '');
    if (last) {
      src += '<span class="active">'+parsed.split('.')[0].replace(/-/g, ' ')+'</span>';
    } else {
      pathage += '/'+path;
      src += '<a href="'+pathage+'/">'+parsed.replace(/-/g, ' ')+'</a>'+separator;
    }
  }
  console.log(url, src.toString());
  return src.toString();
}
```

**Comment by LostKing73** [comment]
^^^ is for me?

**Comment by cs6413110** [comment]
https://www.codewars.com/kata/5cab471da732b30018968071
for lk ig

**Comment by DarkMemeGod411** [comment]
OOH. can I do one of these?

**Comment by cs6413110** [comment]
You can go on codewars and find some ig

**Comment by LostKing73** [comment]
yaaay thxxxxx

**Comment by LostKing73** [comment]
wha-how do i code it? ive never used this

**Comment by LostKing73** [comment]
like where

**Comment by cs6413110** [comment]
https://www.codewars.com/kata/531489f2bb244a5b9f00077e/
```javascript
function undoRedo(object) {
  let o = {...object};
  o.actions = [];
  o.unactions = [];
  o.get = k => o[k];
  o.set = (k, v) => {
    o.unactions = o.unactions.filter(a => a[0] !== k);
    o.actions.unshift([k, o[k]]);
    object[k] = o[k] = v;
  }
  o.del = k => {
    o.actions.unshift([k, o[k]]);
    delete o[k];
    delete object[k];
  }
  o.undo = () => {
    console.log('undo')
    if (!o.actions.length) return;
    o.unactions.unshift([o.actions[0][0], o[o.actions[0][0]]]);
    object[o.actions[0][0]] = o[o.actions[0][0]] = o.actions[0][1];
    if (o.actions[0][1] === undefined) {
      delete o[o.actions[0][0]];
      delete object[o.actions[0][0]];
    }
    o.actions.shift();
  }
  o.redo = () => {
    console.log('redo')
    if (!o.unactions.length) return;
    o.actions.unshift([o.unactions[0][0], o.unactions[0][1]]);
    object[o.unactions[0][0]] = o[o.unactions[0][0]] = o.unactions[0][1];
    if (o.unactions[0][1] === undefined) {
      delete o[o.unactions[0][0]];
      delete object[o.unactions[0][0]];
    }
    o.unactions.shift();
  }
  return o;
}
```

**Comment by BreadSpammer** [comment]
BREAD 2 HAS ARRISEN. make me collaberator

**Comment by LostKing73** [comment]
Reported

**Comment by DarkMemeGod411** [comment]
Ur joking right?.
@BreadSpammer LETS GO. Welcome back

**Comment by LostKing73** [comment]
No

**Comment by DarkMemeGod411** [comment]
Jonas, did u report him?

**Comment by LostKing73** [comment]
Yes

**Comment by BreadSpammer** [comment]
https://www.codewars.com/kata/52742f58faf5485cae000b9a/train/javascript
function formatDuration (seconds) {
  if (seconds === 0) return 'now';
  let y = 0;
  let d = 0;
  let h = 0;
  let m = 0;
  let s = 0;
  if (seconds >= 31536000) {
    while (seconds >= 31536000) {
      y++;
      seconds = seconds-31536000;
    }
  }
  if (seconds >= 86400) {
    while (seconds >= 86400) {
      d++;
      seconds = seconds-86400;
    }
  }
  if (seconds >= 3600) {
    while (seconds >= 3600) {
      h++;
      seconds = seconds-3600;
    }
  }
  if (seconds >= 60) {
    while (seconds >= 60) {
      m++;
      seconds = seconds-60;
    }
  }
  s = seconds;
  console.log(y,d,h,m,s);
  let final = "";
  if (y > 0) {
    if (y === 1) final += ("1 year");
    if (y > 1) final += (String(y)+" years");
  }
  if (d > 0) {
    if (y > 0 && (h > 0 || m > 0 || s > 0)) final += (", ");
    if (y > 0 && h === 0 && m === 0 && s === 0) final += (" and ");
    if (d === 1) final += ("1 day");
    if (d > 1) final += (String(d)+" days");
  }
  if (h > 0) {
    if ((y > 0 || d > 0) && (m > 0 || s > 0)) final += (", ");
    if ((y > 0 || d > 0) && (m === 0 && s === 0)) final += (" and ");
    if (h === 1) final += ("1 hour");
    if (h > 1) final += (String(h)+" hours");
  }
  if (m > 0) {
    if ((y > 0 || d > 0 || h > 0) && s > 0) final += (", ");
    if ((y > 0 || d > 0 || h > 0) && s === 0) final += (" and ");
    if (m === 1) final += ("1 minute");
    if (m > 1) final += (String(m)+" minutes");
  }
  if (s > 0) {
    if (y > 0 || d > 0 || h > 0 || m > 0) final += (" and ");
    if (s === 1) final += ("1 second");
    if (s > 1) final += (String(s)+" seconds");
  }
  return final;
}

**Comment by BreadSpammer** [comment]
k so like time to assign Aaron to everything. top 1 priority

**Comment by cs6413110** [comment]
https://www.codewars.com/kata/534e01fbbb17187c7e0000c6/
```javascript
const spiralize = n => {
  const spiral = [];
  for (let i = 0; i < n; i++) spiral.push([]);
  for (let layer = 0; layer < Math.ceil(n/2); layer++) {
    const length = n-layer*2, key = (layer+1)%2;
    for (let i = 0; i < n-2*layer; i++) {
      spiral[layer][layer+i] = key;
      if (i !== 0 && i !== n-2*layer-1) spiral[layer+i][n-1-layer] = key;
      spiral[n-1-layer][layer+i] = key;
      if (i !== 0 && (i !== n-2*layer-1 || (i === 1 && key === 1))) spiral[layer+i][layer] = i === 1 ? (key === 1 ? 0 : 1) : key;
    }
  }
  return spiral;
}
```

**Comment by cs6413110** [comment]
![Screenshot 2024-10-21 11 29 30 AM](https://github.com/user-attachments/assets/82bb5187-c67e-492c-ad5b-ef4d609122be)

**Comment by BreadSpammer** [comment]
I didn't get 4 kyu :(((

**Comment by BreadSpammer** [comment]
scammed

**Comment by cs6413110** [comment]
dtapped

**Comment by cs6413110** [comment]
> https://www.codewars.com/kata/52742f58faf5485cae000b9a/train/javascript function formatDuration (seconds) { if (seconds === 0) return 'now'; let y = 0; let d = 0; let h = 0; let m = 0; let s = 0; if (seconds >= 31536000) { while (seconds >= 31536000) { y++; seconds = seconds-31536000; } } if (seconds >= 86400) { while (seconds >= 86400) { d++; seconds = seconds-86400; } } if (seconds >= 3600) { while (seconds >= 3600) { h++; seconds = seconds-3600; } } if (seconds >= 60) { while (seconds >= 60) { m++; seconds = seconds-60; } } s = seconds; console.log(y,d,h,m,s); let final = ""; if (y > 0) { if (y === 1) final += ("1 year"); if (y > 1) final += (String(y)+" years"); } if (d > 0) { if (y > 0 && (h > 0 || m > 0 || s > 0)) final += (", "); if (y > 0 && h === 0 && m === 0 && s === 0) final += (" and "); if (d === 1) final += ("1 day"); if (d > 1) final += (String(d)+" days"); } if (h > 0) { if ((y > 0 || d > 0) && (m > 0 || s > 0)) final += (", "); if ((y > 0 || d > 0) && (m === 0 && s === 0)) final += (" and "); if (h === 1) final += ("1 hour"); if (h > 1) final += (String(h)+" hours"); } if (m > 0) { if ((y > 0 || d > 0 || h > 0) && s > 0) final += (", "); if ((y > 0 || d > 0 || h > 0) && s === 0) final += (" and "); if (m === 1) final += ("1 minute"); if (m > 1) final += (String(m)+" minutes"); } if (s > 0) { if (y > 0 || d > 0 || h > 0 || m > 0) final += (" and "); if (s === 1) final += ("1 second"); if (s > 1) final += (String(s)+" seconds"); } return final; }

AHHHHHH MY EYES

Literally just do:
```javascript
const formatDuration = t => {
  if (!t) return 'now';
  let y, d, h, m, s, msg = '';
  let time = [t%60, Math.floor(t/60)%60, Math.floor(t/(60*60))%24, Math.floor(t/(60*60*24))%365, Math.floor(t/(60*60*24*365))];
  for (let i = 4; i >= 0; i--) {
    if (time[i] && msg.length > 0 && time.slice(0, i).join('').replace(/0/g, '').length === 0) msg = msg.slice(0, -2)+' and ';
    if (time[i]) msg += time[i]+' '+['second', 'minute', 'hour', 'day', 'year'][i]+(time[i] > 1 ? 's' : '')+', ';
  }
  return msg.slice(0, -2);
}

```

**Comment by LostKing73** [comment]
ye like cmon man its simple

**Comment by LostKing73** [comment]
i'd like to see u try english

**Comment by DarkMemeGod411** [comment]
good line

**Comment by BreadSpammer** [comment]
wahtsa n englamasish ???

**Comment by cs6413110** [comment]
```javascript
const alpha = 'abcdefghijklmnopqrstuvwxyz'.split(''), alphabetPosition = s => s.split(' ').reduce((a, c) => a.concat(c.toLowerCase().split('').filter(a => alpha.includes(a)).reduce((b, d) => b.concat(alpha.indexOf(d)+1), []).join(' ')), []).filter(a => a.length).join(' ');
```

**Comment by BreadSpammer** [comment]
![Screenshot 2024-10-31 9 45 55 AM](https://github.com/user-attachments/assets/aca4e906-2f5c-40a8-b966-df520d021875)
YAYAYAYASYSAYSYSAYSYSYYS FIDIUXIOUFIUD(FI  IISISNTNANTAA AI AIA IVJIKIKLLLLISNTTERAKIAINKKKKKK LAHUDUIGFDA ALAFAFFLFLFLAOFILAFIAFLF EEJZIEEOOAIOZZZZ R  LEOSIOSSGOOGOOGOOGOGOGOGOGOOG LKSJFLIDSJ LIAWO IHLWDUIBAI DSKYFYUD GFKUYD HAUDYFAWGHDGUFYDAWHGUIAYLWTDFGAHWLDUIYTGAWHDLUYGAWKJ DHGAJGDV

MY LIFE IS COMPLETE
🍞 🔫 
💥 🔫 
🪦

**Comment by BreadSpammer** [comment]
@cs6413110 I'm finding all of the easiest kyu 4 and 3's (searching by most completed) and putting them here. also the only kyu 4 I did is actually the easiest kyu 4 lol

**Comment by BreadSpammer** [comment]
https://www.codewars.com/kata/521c2db8ddc89b9b7a0000c1 Turing a grid into 1 array using a snail pattern
https://www.codewars.com/kata/51ba717bb08c1cd60f00002f Return an array, where u abbreviate integers into 1 array (so like from [1,2,3,5] => [1-3, 5])
https://www.codewars.com/kata/51c8e37cee245da6b40000bd Return a string containing multiple lines, where for each line, you dtap all of the letters after the designated "end" letter.
https://www.codewars.com/kata/5254ca2719453dcc0b00027d Create all permutations of a non-empty input string and remove duplicates
https://www.codewars.com/kata/5324945e2ece5e1f32000370 big number simulator but strings

these are the 2nd-6th most dtappable kyu 4s I could find

**Comment by BreadSpammer** [comment]
'''javascript
 const snail = (array) => {
  console.log(array)
  let final = [];
  let path = [];
  let x = 0;
  let y = 0;
  let dir = 'right';
  let size = array[0].length;
  if (size === 0) return [];
  if (size === 1) return array[[0][0]];
  for (let i = 0; i < size**2; i++) {
    final.push(array[y][x]);
    path.push(x+','+y);
    if (dir === 'right') {
      if (x+1 >= size || path.includes((x+1)+','+y)) {
        dir = 'down';
        ++y;
      } else ++x;
    } else if (dir === 'left') {
      if (x-1 < 0 || path.includes((x-1)+','+y)) {
        dir = 'up';
        --y;
      } else --x;
    } else if (dir === 'up') {
      if (y-1 < 0 || path.includes(x+','+(y-1))) {
        dir = 'right';
        ++x;
      } else --y
    } else if (dir === 'down') {
      if (y+1 >= size || path.includes(x+','+(y+1))) {
        dir = 'left';
        --x;
      } else ++y;
    }
  }
  return final;
} 
'''

**Comment by cs6413110** [comment]
```javascript
const snail = a => {
  const layers = Math.ceil(a.length/2), o = [];
  for (let i = 0; i < layers; i++) {
    o.push(...a[i].slice(i, a.length-i));
    for (let l = i+1; l < a.length-1-i; l++) o.push(a[l][a.length-1-i]);
    if (!((a.length/2)%1 === .5 && i === Math.floor(a.length/2))) o.push(...[...a[a.length-1-i].slice(i, a.length-i)].reverse());
    for (let l = a.length-2-i; l >= i+1; l--) o.push(a[l][i]);
  }
  return o;
}
```

**Comment by LostKing73** [comment]
new tips:

![image](https://github.com/user-attachments/assets/9fb396c0-a62c-4a24-8c96-3fa98162efe7)

**Comment by BreadSpammer** [comment]
cringe. i think we should make it so tips are helpful for new accounts, but when ur experienced, then they just roast u :)

**Comment by BreadSpammer** [comment]
so like "Wow! You suck!" is perfect for that, but also have actually helpful ones

**Comment by LostKing73** [comment]
ok

**Comment by LostKing73** [comment]
dont delete tho, most are good

**Comment by cs6413110** [comment]
https://www.codewars.com/kata/51c8e37cee245da6b40000bd/train/javascript
```javascript
const solution = (t, m) => t.split('\n').reduce((a, c) => a.concat(m.reduce((b, d) => b.split(d)[0], c).trimEnd()), []).join('\n');
```
quick dtap

**Comment by cs6413110** [comment]
https://www.codewars.com/kata/5324945e2ece5e1f32000370/train/javascript
```javascript
const sumStrings = (a, b) => {
  a = a.split('').reverse();
  b = b.split('').reverse();
  let base = [];
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    let n = (Number(a[i]) || 0)+(Number(b[i]) || 0);
    if (base[i]) n += base[i];
    base[i] = n%10;
    if (n >= 10) base[i+1] = Math.floor(n/10);
  }
  for (let i = base.length-1; i > 0; i--) if (base[i] === 0) base.splice(i, 1); else break;
  return base.reverse().join('');
}
```

**Comment by cs6413110** [comment]
Cring that implementing your own version of math is better than the native version.

**Comment by cs6413110** [comment]
https://en.wikipedia.org/wiki/Lagrange%27s_four-square_theorem
https://www.codewars.com/kata/63022799acfb8d00285b4ea0

We dtap these

**Comment by cs6413110** [comment]
I'm thinking we can reduce time complexity to O(n) of String(BigInt(n)).length+O(n)*Math.random()*9 depending on case

**Comment by cs6413110** [comment]
[1, 4, 9]
1203840192384923492
Starts with 1, therefore, since:
100 composes
  10^2

We can assume that:
1203840192384923492
              1 00000000000^2 is less than the root, where # of zeros is floored half of the BigInt


Sample cases:
1000 = 100^2
  100^2 
leading 1 trailed by 3 zeros => 10^Math.floor(3/2)^2

Next, we can use sums to determine subsequent lower squares
1900 => 
1000 + 900
   100^2
900
  10^2*3^2
    
Not certain about the accuracy loss for overlap of 10^n.
2900
  100^2+30^2 = 1900 but where to disperse excess 1k? 
Offloading to a second 100^2 like 100^2+100^2 will only work for 4 squares up to 3900. for 4000+ we could use 200^2, but the range of 3900 to 4000 is unusable. This case is infinitely bigger for numbers up to 2^1024

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/43863884-ed78-4bd1-9ece-a0badf4b77f3)
![image](https://github.com/user-attachments/assets/1914bede-fb3a-41bb-b0f5-5ab1f1199575)

**Comment by LostKing73** [comment]
ooh and this one
![image](https://github.com/user-attachments/assets/678c79ff-7a24-4084-beab-dc62a9369cfc)

**Comment by LostKing73** [comment]
this is new too
![image](https://github.com/user-attachments/assets/8f5d86a0-343d-401c-803a-0e678063a148)

**Comment by BreadSpammer** [comment]
wrong spelling. should be "bradley was converted into LostKing's healing items"

**Comment by LostKing73** [comment]
when have you said that instead. ive only heard the version I typed

**Comment by BreadSpammer** [comment]
idk, btw this is an issue for coding???

**Comment by LostKing73** [comment]
ye but i didnt want to make a new issue for my spam

**Comment by cs6413110** [comment]
https://www.codewars.com/kata/5656b6906de340bd1b0000ac/train/javascript
```javascript
const longest = (a, b) => [...new Set([...a, ...b])].sort((a, b) => a.charCodeAt(0)-b.charCodeAt(0)).join('');
```

**Comment by DarkMemeGod411** [comment]
[https://hoclaptrinhdanang.com/downloads/pdf/javascript/Coding%20with%20JavaScript%20For%20Dummies.pdf](url)
