### ISSUE TITLE
reminder for da arnab

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#75]
code the custom cosmet thing plessssssss

**Comment by LostKing73** [comment]
@cs6413110

**Comment by LostKing73** [comment]
uhm so its like I make a fork and then cosmetics that look like smth' else will look like a new one that I made in the fork. its kinda like reaource packs in mc

**Comment by LostKing73** [comment]
its so i can look good without u complaining

**Comment by CelestialKnight7** [comment]
🤨

**Comment by CelestialKnight7** [comment]
whatever, but that means i get to purge again

**Comment by LostKing73** [comment]
no, cuz its not coded yet

**Comment by LostKing73** [comment]
@cs6413110 DOOOOOOOO

**Comment by LostKing73** [comment]
is done :D

**Comment by LostKing73** [comment]
k, NOW feel free to spam ur hate deletion

**Comment by CelestialKnight7** [comment]
yayyy
