### ISSUE TITLE
Menu Issues

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#76]
you cannot change keybinds.

you cannot go to the shop

and you cant do single player

**Comment by LostKing73** [comment]
no duh

**Comment by CelestialKnight7** [comment]
we know shut

**Comment by CelestialKnight7** [comment]
maybe if someone stopped bother aaron with blackmail and threats he could get some work done

**Comment by LostKing73** [comment]
lol ez

**Comment by LostKing73** [comment]
> maybe if someone stopped bothering aaron with blackmail and threats he could get some work done

like omg fr

**Comment by BreadSpammer** [comment]
@3foe if u click above the pause button it opens the keybinds menu, and u can exit by pressing the leaves button. barely works so u have lost the right to complain about it
