### ISSUE TITLE
possible lobby

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#77]
R1341I21R39IT3IXWXIX3IX3IT3IR39IX3IX3IX3IX3IX3IR39IX2G5IX3IX3G2X2IR39I3GX13GI3R39IX19IR39IX9SX9IR39IX19IR39I3GX13GI3R39IX2G2X3IX3IX3G2X2IR39IX3IX3IX3IX3IX3IR39IT3IX3IX3IX3IT3IR39I21R1518
![Screenshot 2024-10-17 10 59 57 AM](https://github.com/user-attachments/assets/77dc69a9-a2c2-4e22-82eb-f6e27b4a619f)

**Comment by 3foenation** [comment]
there is ai for crates and advance ai for training and then in the empty spaces we could put crates inventory and KEYBINDS and store and possibly more.

**Comment by 3foenation** [comment]
rate good or baood

**Comment by LostKing73** [comment]
rating: no

**Comment by 3foenation** [comment]
nah more votes

**Comment by LostKing73** [comment]
nnnope lol. this is like the 18th version of main lobby, WE. DO. NOT. NEED. MORE.

**Comment by 3foenation** [comment]
YES we do this one is terrible and you literally made a post for lobbies stop lying

**Comment by LostKing73** [comment]
bruh what? the one u just made is bad dummy. the issue for "lobbies" is to work on rooms for the lobby. shuttage
