### ISSUE TITLE
game broken need an aaron

### ISSUE THREAD

**Issue by 3foe** [cs6413110/Pixel-Tanks#79]
FIGSFIGIFIGSIGSIGISGIIGSIFGISFGIFSIGSFIGISFGISFIGSIGIFSGISFGISFIGSIFGISFIGSIFGISGISIGISG

**Comment by 3foe** [comment]
SACRIFICE THE BREAD TO THE FIX GODS

**Comment by CelestialKnight7** [comment]
*bullies aaron
*aaron stops working
*complains that aaron isnt working
*breaks game
*complaisn to aaron to fix game

**Comment by 3foe** [comment]
um what?

**Comment by LostKing73** [comment]
its what you are doing

**Comment by DarkMemeGod411** [comment]
> *bullies aaron *aaron stops working *complains that aaron isnt working *breaks game *complaisn to aaron to fix game

amen Evan. the most truth ever spoken

**Comment by LostKing73** [comment]
could evans deletion of admin csmets be the problem? i remember cs mentioning that they will break game if removed
![image](https://github.com/user-attachments/assets/60a6909b-e36d-4a03-9895-2bb45e9459d8)

**Comment by DarkMemeGod411** [comment]
quite possible

**Comment by LostKing73** [comment]
@cs6413110 halp

**Comment by DarkMemeGod411** [comment]
I believe that is the problem, so. fix?

**Comment by DarkMemeGod411** [comment]
this is useful for me so it may help 
[Coding with JavaScript For Dummies.pdf](https://github.com/user-attachments/files/17439064/Coding.with.JavaScript.For.Dummies.pdf)

**Comment by LostKing73** [comment]
ded

**Comment by CelestialKnight7** [comment]
( it wsant the cosmets)
