### ISSUE TITLE
vote

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#80]
vote to take away lostking's admin
1. he abuse admin
2. he mutes people for no reason
3. he kicks people for no reason
4.  you made a post of anyone abusing admin it gets taken away 

lostking's vote doesn't count by the way

**Comment by 3foenation** [comment]
thumbs up yes thumbs down no

**Comment by LostKing73** [comment]
are you is dum? (rhetorical question)

**Comment by DarkMemeGod411** [comment]
no. why? also What? Que?

**Comment by 3foenation** [comment]
let everyone vote

**Comment by DarkMemeGod411** [comment]
no. pointless, he deserves it, (I'm not joking btw)

**Comment by 3foenation** [comment]
nah did lostking hack your account

**Comment by 3foenation** [comment]
dont close everthing i have against you , are you scared your gonna get you admin taken away

**Comment by LostKing73** [comment]
no coltin. flat is the issue. idc that ur blinded by his lies.

**Comment by DarkMemeGod411** [comment]
> nah did lostking hack your account

no. Dark stands alone.

**Comment by DarkMemeGod411** [comment]
Coltin, you need to realize that he (lk) isn't the problem here.

**Comment by 3foenation** [comment]
you sure about that lk is annoying everyone in tanks with his admin I'm sure he is the promblem

**Comment by 3foenation** [comment]
> no coltin. flat is the issue. idc that ur blinded by his lies.
I'm not blinded its just the truth we both know it you are the blinded one for not seeing what you are doing

**Comment by 3foenation** [comment]
I'm not blinded its just the truth we both know it you are the blinded one for not seeing what you are doing

**Comment by martinbwg** [comment]
No name-calling please, I will talk to Aaron about this

**Comment by DarkMemeGod411** [comment]
coltin, I apologize.

**Comment by DarkMemeGod411** [comment]
I apologize sir.

**Comment by LostKing73** [comment]
don't immediatly dissolve your own argument because someone else said to darkmemegod. coltin is in the wrong, and if he thinks I am abusing admin for messing around with my friends, that is his own problem

**Comment by LostKing73** [comment]
never said you had been. i meant martinbwg

**Comment by DarkMemeGod411** [comment]
i would like to say that none of this is Aaron's fault

**Comment by 3foe** [comment]
for the record I have said nothing to anyone about jonas. at all not even aaron (the one exception is that he is trying to start a war and he needed to be shut down) anything that coltin said was his own opinion, and therefore he cannot have been manipulated by me.

however jonas somehow struck a deal with Aaron for full auth, if the situation is dire enough I will pull rank and have jonas get blocked from github as I requested that power from Aaron, I do not see a reason to do that to him until he crosses a line.

**Comment by LostKing73** [comment]
>for the record I have said nothing to anyone about jonas.

You have constantly treated me like and compared me to a 4-year-old.

>at all not even Aaron (the one exception is that he is trying to start a war and he needed to be shut down)

You, without any hint of joking in what I am typing, are the sole reason there is any drama. You and you alone are blackmailing Aaron to give you full authorization.

> anything that coltin said was his own opinion, and therefore he cannot have been manipulated by me.

You are 100% manipulating him, as the only information that he has heard is from your "side."

>however jonas somehow struck a deal with Aaron for full auth

I have full auth because I deserve it. You have full auth because you blackmailed Aaron into giving it to you.

>if the situation is dire enough I will pull rank and have jonas get blocked from github as I requested that power from Aaron

Again, this is because you do not like hearing that my opinion differs from yours, and therefore your response is using a rule that you blackmailed Aaron to get.

>I do not see a reason to do that to him until he crosses a line.

Pixel Tanks. Is. Not. Yours.

**Comment by LostKing73** [comment]
oh, and coltin? You abuse much more than i do.
![image](https://github.com/user-attachments/assets/b63866d3-9a10-43e5-a39d-3d743053ac24)

**Comment by LostKing73** [comment]
it goes on for a while.

**Comment by DarkMemeGod411** [comment]
Mattew, you will not get lostking kicked off the github if that happens again i will consider quitting. If that occurs. This is. No longer  a fair game

**Comment by 3foe** [comment]
> > for the record I have said nothing to anyone about jonas.
> 
> You have constantly treated me like and compared me to a 4-year-old. **you get treated how you act also that doesn't debunk what I said how does how you are treated effect that I have said nothing about you?**
> 
> > at all not even Aaron (the one exception is that he is trying to start a war and he needed to be shut down)
> 
> You, without any hint of joking in what I am typing, are the sole reason there is any drama. You and you alone are blackmailing Aaron to give you full authorization. ** no you started this when you decided to insult my brother and treat HIM like a 3 year old while you complain you are being treated as a 4 year old**
> 
> > anything that coltin said was his own opinion, and therefore he cannot have been manipulated by me.
> 
> You are 100% manipulating him, as the only information that he has heard is from your "side." ** I don't think you read what I said, I. have. said . nothing. therefore. he. cannot. have. been . manipulated. by. me. If you want to be treated as the age you are you will act and listen as if you are 15 you heard something like there is a barn and said oh it must be the ocean, can anyone blame me for treating you like a kid when you simply cannot understand plain English
> 
> > however jonas somehow struck a deal with Aaron for full auth
> 
> I have full auth because I deserve it. You have full auth because you blackmailed Aaron into giving it to you. ** Id agree except that isn't at all true, you have full auth because you bribed him, in capital offenses taking and offering a bribe is a higher offence than black mail, plus I didn't black mail him at all. and in no way do you deserve admin or VIP and not all all full auth since the only thing you contribute is insults and headaches**
> 
> > if the situation is dire enough I will pull rank and have jonas get blocked from github as I requested that power from Aaron
> 
> Again, this is because you do not like hearing that my opinion differs from yours, and therefore your response is using a rule that you blackmailed Aaron to get. ** You see that isn't true again how many times will you act like a 4-year-old and complain like a 4-year-old then turn tail and whine that you are treated like a 4-year-old, I am not cutting you off, yet... and If I do the reason will be because you provide nothing but headaches and drama, I am shocked that with all the lies you have told, you can lie and call it the truth**
> 
> > I do not see a reason to do that to him until he crosses a line.
> 
> Pixel Tanks. Is. Not. Yours. ** Again 4 year old, who mentioned pixel tanks, oh wait you. did I have the word pixel tanks in my comment? no, so you are acting like a 4-year-old again wishing for a mistake in my argument that you can attack. I would like to say, " Pixel Tanks. Is. Not. Yours.". Hence, your opinion is not the only opinion so stop closing issues that have legitimate grievances against you simply because "you do not like hearing that (other people's) opinion differs from yours". stop acting like a 4-year-old. stop treating other people underhandedly, lying to my face, and calling it the truth.**

**My gosh the brain cells that were lost reading Jonas's argument like that were so poorly put together that it actually sounded like he was surrendering**

**Comment by BreadSpammer** [comment]
Im not wasting my 1st hour to an essay

**Comment by LostKing73** [comment]
this isnt worth wasting my time on flat. if ur just gonna keep calling me a 4 y/o then that's how much effort ur gonna get out of me. ur wrong I'm right end of story k byeeeeeeeee

**Comment by LostKing73** [comment]
btw mathew, you have full auth because you bribed him, in capital offenses taking and offering a bribe is a higher offence than black mail, plus I didn't black mail him at all.

**Comment by 3foe** [comment]
Bro's argument changed halfway. He went from trying to argue, to "I'm right, you're wrong," to just nuh uh, to switching what I did with what he did.

**Comment by DarkMemeGod411** [comment]
Stop fighting, Can we all understand that this is just gonna result in the death of tanks?

**Comment by LostKing73** [comment]
> Stop fighting, Can we all understand that this is just gonna result in the death of tanks?

WE get that. mathew doesnt

**Comment by LostKing73** [comment]
> Bro's argument changed halfway. He went from trying to argue, to "I'm right, you're wrong," to just nuh uh, to switching what I did with what he did.

k, sucks to suck for u ig

**Comment by LostKing73** [comment]
just get better

**Comment by 3foe** [comment]
...

**Comment by 3foe** [comment]
bro did not get the point at all, this is what I mean when you act like a 4-year-old, you don't understand anything that isn't dumbed down for you, and you complain when I do that. I am saying what you say means nothing because you have used arguments that contradict one another, therefore your opinion is invalid.

**Comment by 3foe** [comment]
don't insult your intelligence by saying you don't understand what I said, believe it or not, I don't like treating you like a 4-year-old and I would love to have an intelligent conversation/debate with you instead of hand-feeding you everything.

**Comment by DarkMemeGod411** [comment]
3foe. For the love of all things holy. STOP THIS ARGUMENT. my eyes are melting just reading this. Can you understand that this could end Tanks for good. Please stop the arguments.
Thanks
Dmg

**Comment by LostKing73** [comment]
bro did not just sign his github message.

**Comment by 3foe** [comment]
I did stop it, i crushed his opposition. he has nothing to go off of except his opinion which I proved invalid

**Comment by LostKing73** [comment]
W, by acting dum he says im smart. makes sense honestly

**Comment by LostKing73** [comment]
W WE WIN GUYS I DID IT HE FINALLY STOPPED MAKING NONSENSE

**Comment by 3foe** [comment]
my final point was proven with that sentance

**Comment by DarkMemeGod411** [comment]
So the argument is ended?
Splendid

**Comment by LostKing73** [comment]
w guys

**Comment by martinbwg** [comment]
Thank you DarkMeme for being the voice of reason.  
If Matthew is called flat again, there will be consequences.  
Please use this forum for what it is meant for and have respect for each other.

**Comment by DarkMemeGod411** [comment]
you are welcome sir.

**Comment by LostKing73** [comment]
also, again, even tho it doesnt matter and idc,

"3foe doesn't abuse admin!!!"

3foe:
![image](https://github.com/user-attachments/assets/c716ebf3-40ad-4003-8521-df72418b9e9f)
