### ISSUE TITLE
flat, why?

### ISSUE THREAD

**Issue by DarkMemeGod411** [cs6413110/Pixel-Tanks#81]
![Screenshot 2024-10-18 11 38 45 AM](https://github.com/user-attachments/assets/1171b5f3-4b35-4f61-9a64-60d25dd6dca1)

**Comment by DarkMemeGod411** [comment]
@3foe

**Comment by LostKing73** [comment]
bruh cuz hes dumb like saying smth doesn't change anything

**Comment by 3foe** [comment]
you asked for an explination here it is, this is not an attempt to pressure an argument btw. jonas was acting like a 5 year old on pixel tanks chat and only saying "ew" so I said in an attempt to get an intelligent response told him a parrot which has the intelligence of a 5 year old is capable of sentences and so is he and tony sent a picture of jonas in a stroller, although jonas left before it was sent I thought it was possible for jonas to attack tony so I gave him VIP so he couldn't be banned or muted if he sent it again even though the image is accurate.

**Comment by LostKing73** [comment]
>tony sent a picture of jonas in a stroller,

when lol, i wanna see this

**Comment by DarkMemeGod411** [comment]
FLAT why say that, now i wanna see that image
