### ISSUE TITLE
add a command that gives cosmets

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#83]
bcuz for testing and so i dont have to keep asking cs to add them. this is pretty much just like me asking cs this

**Comment by CelestialKnight7** [comment]
ig ye for testing but also culd be abused for cring. whatever tho we can jsut do another account reset at some point

**Comment by LostKing73** [comment]
i need crates to be a thing ok?

**Comment by LostKing73** [comment]
no we are never going to add keybinds back they were terrible never no

**Comment by 3foe** [comment]
"Pixel Tanks. Is. Not. Yours." stop acting like it, that is just your opinion.

**Comment by 3foe** [comment]
"Pixel Tanks. Is. Not. Yours." stop acting like it, that is just your opinion.

**Comment by 3foenation** [comment]
yes we need keybinds becouse im stuck with insta combo ADD KEYBINDS

**Comment by LostKing73** [comment]
bruh one step at a time yall

**Comment by 3foe** [comment]
step one readding a basic feature to the game instead of adding an unnecessary command

**Comment by LostKing73** [comment]
just like, /pay. 

/pay LostKing cosmetic angry
/pay LostKing xp 10000000
/pay <who> <defining what> <what/how many>

**Comment by LostKing73** [comment]
or just like /give idc

**Comment by LostKing73** [comment]
@cs6413110 or @BreadSpammer add

**Comment by BreadSpammer** [comment]
I can try ig

**Comment by LostKing73** [comment]
yay

**Comment by cs6413110** [comment]
No, don't add, just fix crates

**Comment by LostKing73** [comment]
aw

**Comment by LostKing73** [comment]
no ig
