### ISSUE TITLE
LK Explanation

### ISSUE THREAD

**Issue by martinbwg** [cs6413110/Pixel-Tanks#84]
I see why there was some frustration on this forum earlier.

I hope there’s a good explanation for this

![IMG_4587 Copy](https://github.com/user-attachments/assets/b37d7972-a090-460b-ad2e-742df72fd61d)

**Comment by LostKing73** [comment]
oh haha, darkmemegod had typed that in during lunch when i was having me help me with an assignment for computer class.

**Comment by LostKing73** [comment]
i'm going to close the issue on the assumption that you are still able to read this, and so the main page is more clear

**Comment by DarkMemeGod411** [comment]
lk threw me under the bus.

**Comment by LostKing73** [comment]
ok man. i have like 20 screenshots proving you are not a good person. here is one.
![I love abusing people](https://github.com/user-attachments/assets/0645ae31-942d-4976-bffd-430b7b6e86e5)

**Comment by LostKing73** [comment]
and another
![Screenshot 2024-09-05 2 01 11 PM](https://github.com/user-attachments/assets/d4c3100e-fdc8-4720-a17a-3ce6bf6e68f7)

**Comment by DarkMemeGod411** [comment]
![Screenshot 2024-10-18 11 38 45 AM](https://github.com/user-attachments/assets/b1f20d10-139e-4526-87d8-94ee3b270200)

**Comment by DarkMemeGod411** [comment]
However
I am also a helpful person. I show respect to my elders

**Comment by DarkMemeGod411** [comment]
Lk just took away coltin's admin @martinbwg 
![Screenshot 2024-10-22 11 37 56 AM](https://github.com/user-attachments/assets/14f8f528-4cd6-46d1-9290-3608733f1a81)

**Comment by DarkMemeGod411** [comment]
![Screenshot 2024-10-22 11 39 11 AM](https://github.com/user-attachments/assets/8d72b181-8074-4106-8a16-a0dd9d56369b)

**Comment by LostKing73** [comment]
i gave back, and its was becasue he was yelling at me when he was abusing admin. not my problem.

**Comment by DarkMemeGod411** [comment]
@martinbwg I did not type that on his laptop.

**Comment by BreadSpammer** [comment]
lol lk predicted the future. @DarkMemeGod411 yes u did, also stop being such a suck up its annoying

**Comment by DarkMemeGod411** [comment]
bread. I swear, I did not type that. get the security footage. I did not. lk doesn't even let me see his screen. and I apologize if I was being a suck up

**Comment by DarkMemeGod411** [comment]
I did not do that, if I could go on his laptop, why would I think to instantly do that?

**Comment by LostKing73** [comment]
> bread. I swear, I did not type that. get the security footage. I did not. lk doesn't even let me see his screen. and I apologize if I was being a suck up

yea when you lean over the entire table to look at it. you were answering a single comptia question and typed that when I snatched my chrumbook back.

**Comment by LostKing73** [comment]
> I did not do that, if I could go on his laptop, why would I think to instantly do that?

it wasn't instant. the question was answered(incorrectly at that) so u took the time to at least click that.

**Comment by DarkMemeGod411** [comment]
Jonas. when I move my head, you move the screen to stop me, and also wouldn't Aaron have stopped me. @cs6413110 what happened at lunch yesterday

**Comment by LostKing73** [comment]
ahem. 
![image](https://github.com/user-attachments/assets/35cddc95-2b1f-4122-a8f6-a4412bfcc636)

**Comment by DarkMemeGod411** [comment]
why would I help you with work. you have said many times that you hate me, and have attacked me online many times

**Comment by LostKing73** [comment]
> Jonas. when I move my head, you move the screen to stop me, and also wouldn't Aaron have stopped me. @cs6413110 what happened at lunch yesterday

idk bro he was coding or smth smart like that. bro. literally. the gaslighting is crazy.

**Comment by DarkMemeGod411** [comment]
Aaron was on tanks. he would have seen me touch ur laptop. @martinbwg I have never touched his laptop, there is no need

**Comment by LostKing73** [comment]
> why would I help you with work. you have said many times that you hate me, and have attacked me online many times

YOU have said you hate me. I HAVE NEVER SAID I HATE YOU. and the only "attacks online" are when u spam nonsense when u think everyone is talking to u and I mute u for literally 30 seconds so I can speak! also, stop pinging him, I'm sure he has work or smth

**Comment by DarkMemeGod411** [comment]
you muted me for a whole month, you said multiple times that I am a terrible person,

**Comment by LostKing73** [comment]
i what? for a week you mean? and you ARE a terrible person, you yourself have admitted it. that is not me saying I hate you though

**Comment by LostKing73** [comment]
darkmemegod. you have made an issue that has nothing to do with you into spam centered around you. stop.

**Comment by DarkMemeGod411** [comment]
ok. sorry

**Comment by DarkMemeGod411** [comment]
Wait. you turned it onto me. by throwing me under the bus tho. I'm confused

**Comment by LostKing73** [comment]
i did not "throw you under the bus". i explained what happened. are you ok? like genuine question bcuz this is something that happened and idk how u forgot. tbh I forget stuff all the time too but still.

**Comment by DarkMemeGod411** [comment]
dude. why are you gaslighting me? you brought me into this by falsely accusing me. I did not do anything, and I apologize for making this an argument

**Comment by LostKing73** [comment]
. . .u literally did tho. . . im not falsey accusing u it actually happened

**Comment by DarkMemeGod411** [comment]
dude, I would be insulting you and deflecting, if I did it. I am cool, calm and collected, so..

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/507f17c3-0f7b-4971-931b-958f71009420)
was like this one

**Comment by LostKing73** [comment]
3.2.4 section quiz

**Comment by martinbwg** [comment]
@DarkMemeGod411 in looking at comments/actions of others, I believe you.  There are also other things that I am seeing that brings me to the same conclusion      Although it is very concerning to me, I am dropping the issue (unless something else happens).  

What I have concluded is that you care about this game given your request to stop the bickering.  Your ability to quickly apologize and to show respect is not a weakness (you gained respect for that).  Others who are criticizing you for it have hurt their reputations.  I challenge you to ignore the mean things that are currently being said and be the better man.
