### ISSUE TITLE
pork

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#85]
ok so aaron doesnt want overdrive which i can understand as its jsut more of already existing perks.

so perk spam here

**Comment by LostKing73** [comment]
huh? so instead of adding overdriv cuz its perk spam u want perk spam I'm confused

**Comment by CelestialKnight7** [comment]
aaron doesnt want overdrive cuz its more of already existing perks and hed rather have an original idea/perk as far as i understand it.

@cs6413110 clarify here

**Comment by cs6413110** [comment]
Invis when low

Resistance to one firing type, but extra damage from another

Stackable powermissle :)

Aimbot grapple

**Comment by LostKing73** [comment]
great clarification

**Comment by cs6413110** [comment]
> aaron doesnt want overdrive cuz its more of already existing perks and hed rather have an original idea/perk as far as i understand it.
> 
> @cs6413110 clarify here

I have to code 8 more perks and code a new inventory system w/limits and then I have to rewrite 100% of the perks and then we have to balance every perk again and it would take too long and we can't even get lobby done.

**Comment by cs6413110** [comment]
It's just doing more coding effort to compensate for the laziness of not being able to come up with 1 new idea.

**Comment by CelestialKnight7** [comment]
> Invis when low
>  **already came up with this and decided we didnt want to steal from a class (got turned into emergency sheild cuz item stealing is legal**
> Resistance to one firing type, but extra damage from another
> **cring**
> Stackable powermissle :)
> **?**
> Aimbot grapple
**is this bradley?**

**Comment by BreadSpammer** [comment]
Emergency cloak

when below (50,75,100) hp, turn invisible (doesn't let you go through walls unless you are stealth) until you go back above the threshold

**Comment by CelestialKnight7** [comment]
bro that was the og idea for emegency sheid and we said no robbing classes

**Comment by BreadSpammer** [comment]
and emergency shield steals from shield

**Comment by CelestialKnight7** [comment]
> thermal armor??
????

**Comment by cs6413110** [comment]
How about perk for regen heal like ai after not taking damage for a while

**Comment by LostKing73** [comment]
bruh.

Last Chance

you press, and it brings you to like 1 health, but u are teleported somewhere random

**Comment by CelestialKnight7** [comment]
> bruh.
> 
> Last Chance
> 
> you press, and it brings you to like 1 health, but u are teleported somewhere random

in front of 3 bread turrets

**Comment by LostKing73** [comment]
skill issue

**Comment by BreadSpammer** [comment]
tps u to the nearest turret

**Comment by LostKing73** [comment]
tps u two inches left

**Comment by CelestialKnight7** [comment]
i have work so ill let u spam and check in in a bit

**Comment by LostKing73** [comment]
> tps u two inches left

into a wall

**Comment by LostKing73** [comment]
become physical. you have a hitbox and unless boosted thru, u cant be moved thru

**Comment by LostKing73** [comment]
so itll fire, do abt 70% normal damage, then do 35% normal damage to anything that gets hit by whats behind

**Comment by DarkMemeGod411** [comment]
so, splash damage basically. so, it would shoot, hit enemies, then spray into multiple streams to damage others?

**Comment by LostKing73** [comment]
yes

**Comment by DarkMemeGod411** [comment]
another perk idea
Predator (name in progress)
when you get a kill, get a 25% speed boost for 10 seconds.

**Comment by LostKing73** [comment]
> powerbullet splits once it hits but does less damage on impact, like this: ![Screenshot 2024-10-22 8 46 35 AM](https://private-user-images.githubusercontent.com/175903140/378914694-903dcc0d-2f77-46b8-90da-192dbc1a4254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTI3NjgsIm5iZiI6MTcyOTYxMjQ2OCwicGF0aCI6Ii8xNzU5MDMxNDAvMzc4OTE0Njk0LTkwM2RjYzBkLTJmNzctNDZiOC05MGRhLTE5MmRiYzFhNDI1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxNTU0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWQyNjQyYTM1OTU4M2M3YTcyMmNhYWRjYTYyMjlkZGQxODdjYTg0OTJkMzYwMjA4NzYyNzg1NzRkOTczN2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z15NYeclNLikZ-f5lsqb3IoxUoFzb0lqtWMIoeUisIE)

doesnt apply to mega missle btw

**Comment by DarkMemeGod411** [comment]
perk idea.
Lethal conversion. 
when you get a kill: makes all cooldowns activate (not refresh) 
but you get a 10% dmg boost for 15 seconds (stacks so 2 kills in 15 seconds, 20% dmg boost)

**Comment by DarkMemeGod411** [comment]
perk idea:
energy flow (name in progress)
when you get a kill: increases length of boost (travels further) by 10-15%
(and could also increase cooldown length to make fair)

**Comment by LostKing73** [comment]
bruh make maps not spam alex

**Comment by DarkMemeGod411** [comment]
I will after I use the ideas I have been waiting to share

**Comment by LostKing73** [comment]
no. make maps,we need them

**Comment by DarkMemeGod411** [comment]
perk: 
steel coating
+10% health, (50 when maxed out) 
but you move much slower

**Comment by DarkMemeGod411** [comment]
gimme editor link

**Comment by LostKing73** [comment]
theres a drop off???

**Comment by LostKing73** [comment]
> gimme editor link

data:text/html,<script src='https://cs6413110.github.io/Pixel-Tanks/public/js/editor.js'></script>

**Comment by DarkMemeGod411** [comment]
ok

**Comment by LostKing73** [comment]
> Specialist: buff both firing types, but switching them is on a (10/7.5/5) cooldown normal: increase bullet speed for better snoipes shotgun: removes damage drop-off (each bullet always does 20 damage)

similarly, condense all of shotguns bullets into  a cluster that doesn't spread(still has drop off in dmg)

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/fff86382-1480-462f-b40f-a350d624a777)

**Comment by LostKing73** [comment]
> powerbullet splits once it hits but does less damage on impact, like this: ![Screenshot 2024-10-22 8 46 35 AM](https://private-user-images.githubusercontent.com/175903140/378914694-903dcc0d-2f77-46b8-90da-192dbc1a4254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTc5NzcsIm5iZiI6MTcyOTY5NzY3NywicGF0aCI6Ii8xNzU5MDMxNDAvMzc4OTE0Njk0LTkwM2RjYzBkLTJmNzctNDZiOC05MGRhLTE5MmRiYzFhNDI1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNTM0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWQ3YWQ5NTk4YjlhODFmZGI5MGI0ODIyMmQ0ODcwMWI0NjNjMDdiYmMzOGE0ZTUzMGY4OTQ1YTNjOTNhOTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WTKhBv8q6vos4MIeWdh0KWM5O5nt0RanPNrcX5T2DC0)

why not this @CelestialKnight7

**Comment by CelestialKnight7** [comment]
complicated + cring + very scenario specific

**Comment by BreadSpammer** [comment]
so like specialist y/n

**Comment by LostKing73** [comment]
> so like specialist y/n

?? english?

**Comment by cs6413110** [comment]
Dead, how about we just have 6 perks.

**Comment by LostKing73** [comment]
> Dead, how about we just have 6 perks.

if it includes the one that makes ur death a 50/50, sure. i need that.

**Comment by CelestialKnight7** [comment]
> Dead, how about we just have 6 perks.

no

**Comment by CelestialKnight7** [comment]
ideas:
- dealing damage reduces boost cd based on how much dmg u do, (100 dmg is 1 second) (could be increased with tiers maybe)
- after using ur class ability you have increased movement speed (20%) for (t1: 3 seconds/ t2: 5 seconds/ t3: 7 seconds)
- any healing you apply (to yourself or others) can overflow at (t1: 10% /t2: 25%/t3: 50%) of its original healing value and the overflow will slowly decay at a rate of (t1: 20 hp per sec/ t2: 10 hp per sec/ t3: 5 hp per sec)
- explode on death for (t1: 100 Dmg/ t2: 300 Dmg/ t3: 500 Dmg) (the explosion takes 3 seconds to activate after death)
- taking damage reduces your non-item cooldowns by (t1: 10% per 100 Dmg/ t2: 25% per 100 Dmg/ t3: 50% per 100 Dmg) ''cringe''

out of valuable spam

**Comment by CelestialKnight7** [comment]
> ideas:
> 
> * dealing damage reduces boost cd based on how much dmg u do, (100 dmg is 1 second) (could be increased with tiers maybe)
> * after using ur class ability you have increased movement speed (20%) for (t1: 3 seconds/ t2: 5 seconds/ t3: 7 seconds)
> * any healing you apply (to yourself or others) can overflow at (t1: 10% /t2: 25%/t3: 50%) of its original healing value and the overflow will slowly decay at a rate of (t1: 20 hp per sec/ t2: 10 hp per sec/ t3: 5 hp per sec)
> * explode on death for (t1: 100 Dmg/ t2: 300 Dmg/ t3: 500 Dmg) (the explosion takes 3 seconds to activate after death)
> * taking damage reduces your non-item cooldowns by (t1: 10% per 100 Dmg/ t2: 25% per 100 Dmg/ t3: 50% per 100 Dmg) ''cringe''
> 
> out of valuable spam

I really like the 2nd one (movement speed after class ability) and overflow healing as movement speed buffs, almost every class and its very versatile. And the overflow is almost a medic specific perk but can also be useful for anyone

**Comment by CelestialKnight7** [comment]
voteethhhhhhhh

movement speed pork

**Comment by CelestialKnight7** [comment]
overflow

**Comment by CelestialKnight7** [comment]
esplode

**Comment by CelestialKnight7** [comment]
u only get 2 upvotes for 3 ideas

**Comment by CelestialKnight7** [comment]
bruh

**Comment by cs6413110** [comment]
e

**Comment by CelestialKnight7** [comment]
why not movement speed, I feel like it could be a generally good perk for every class but be especially good on stealth, similar to how scav is good on almost every class but excells on tactical and warrior

**Comment by cs6413110** [comment]
fine :(

**Comment by cs6413110** [comment]
time to get warrior boosted at mock 10

**Comment by CelestialKnight7** [comment]
its after they use the ability and it would be less sped aswell so its not gonna do Dmg if they hit u

**Comment by LostKing73** [comment]
> time to get warrior boosted at mock 10

yesyesyesyesyesyes

**Comment by LostKing73** [comment]
add momentum based damage

**Comment by LostKing73** [comment]
i ate the pork. closing cuz this isnt going anywhere. reopen if u actually have an idea ig
