### ISSUE TITLE
question for cs

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#86]
@cs6413110 since I have that custom texture pack thing, could it change my gripple to be my scythe?

**Comment by LostKing73** [comment]
. . .

**Comment by cs6413110** [comment]
ye but no spin

**Comment by cs6413110** [comment]
and it would change everyone's grapples for you

**Comment by LostKing73** [comment]
> ye but no spin

i wan spin

**Comment by LostKing73** [comment]
dang ok
