### ISSUE TITLE
Damage scaling

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#88]
Only bullets/missiles scale based off rank currently. We should make all forms of damage scale with rank.

Todo:
- Fire
- Medic regen
- Warrior Boost
- glu healing (90% sure it doesn't scale)

Also USB damage scaling is busted.

Edit this issue if there is anything else related.

**Comment by LostKing73** [comment]
noo my secret leveling technique of warrior boosting everything...

**Comment by BreadSpammer** [comment]
k coding

**Comment by BreadSpammer** [comment]
vote: should shield hp scale with rank (so at rank 0, all shields u use will be 60hp which is 1/5 of ur health still) (don't take LostKing/3foe admin abuse into account)

👍 = ye balance it for low rank players
👎 = nah make shield even more op at low levels

**Comment by LostKing73** [comment]
bro like being low leveled is getting harder and harder

**Comment by BreadSpammer** [comment]
well u arent supposed to fight rank 20s at rank 0 so like

**Comment by BreadSpammer** [comment]
I say that we make "competitive" gamemodes like duels and tdm, auto set everyone's rank to 20 to make it fair.

**Comment by BreadSpammer** [comment]
I mean ye? rank wont affect tdm bc tdm is for competitive "who's better" with randomness out of the eq. rank is for FFA and singleplayer

**Comment by BreadSpammer** [comment]
I'll start coding

**Comment by BreadSpammer** [comment]
haven't coded this yet bc busy but I will

**Comment by BreadSpammer** [comment]
unless u already did?

**Comment by LostKing73** [comment]
no he just spammed close

**Comment by LostKing73** [comment]
nooooooo my warrior :(((((((((((

**Comment by LostKing73** [comment]
forget, theres better stuff to do ig

**Comment by LostKing73** [comment]
like zones :D

**Comment by BreadSpammer** [comment]
Nah
