### ISSUE TITLE
More Blocks

### ISSUE THREAD

**Issue by BreadSpam** [cs6413110/Pixel-Tanks#9]
Currently Accepted Ideas:

Oil Barrel: a block with a smaller hitbox, also explodes if broken. doing around 300 dmg

Portal: a pair of blocks, where if you step on one, it will tp u to the other one. will also have some complications, but doesn't matter until in game

feel free to propose more ideas

**Comment by LostKing73** [comment]
slime

**Comment by BreadSpam** [comment]
Fortress

an invincible block that can't be walked on, but can be grappled over, and can be shot over (can be reskined to water)

**Comment by BreadSpam** [comment]
Icicle (ice only block)

stays above the playing field, showing only a shadow, until walked over. after about 0.5 seconds, it will fall, and anyone under, will take 100 damage. after 1 more second, the icicle grows back, marked by the shadow.

**Comment by BreadSpam** [comment]
Cave In (cave only block)

a gravely looking block with 200 HP. after 3 seconds of being destroyed, the block will regenerate (unless someone is on the block), and "caving in"

**Comment by BreadSpam** [comment]
@CelestialKnight7 @cs6413110 @LostKing73 @DarkMemeGod411 vote

**Comment by CelestialKnight7** [comment]
> Fortress
> 
> an invincible block that can't be walked on, but can be grappled over, and can be shot over (can be reskined to water)

not placable only in editor

**Comment by cs6413110** [comment]
#707

**Comment by BreadSpam** [comment]
nuh

**Comment by LostKing73** [comment]
#707
