### ISSUE TITLE
I think I loaded too hard

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#90]
![image](https://github.com/user-attachments/assets/4f797baf-839e-43a6-8c88-70f31924433a)

**Comment by LostKing73** [comment]
@BreadSpammer u broke figs it

**Comment by 3foenation** [comment]
yea cant load into game FIX BREAD

**Comment by BreadSpammer** [comment]
it was Aaron. what I did isn't breaking game

**Comment by BreadSpammer** [comment]
I checked

**Comment by LostKing73** [comment]
THEN FIX IT??

**Comment by cs6413110** [comment]
I think the school wifi isn't letting websocket connections work, which is why we can't log in.

**Comment by cs6413110** [comment]
Doing a commit to test that...

**Comment by cs6413110** [comment]
Ok, nope, something else broke. Probably server side.

**Comment by LostKing73** [comment]
says socket connected

**Comment by LostKing73** [comment]
uhm when figs?

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/077187d6-fadf-4c88-a9b2-b02d3f534f51)

**Comment by cs6413110** [comment]
Ok, figsed

**Comment by LostKing73** [comment]
crates dont work tho...

**Comment by LostKing73** [comment]
on a side note, bom has the potential to be rly good. i ur close enough, its a free 50 dmg every like 2 seconds

**Comment by LostKing73** [comment]
just hit them with 10 bombs and they die

**Comment by LostKing73** [comment]
did yall live just to fix game

**Comment by cs6413110** [comment]
uh ig

**Comment by LostKing73** [comment]
why does it say no crate for u 💀

**Comment by cs6413110** [comment]
"fixed"

**Comment by LostKing73** [comment]
whats that supposed to mean

**Comment by LostKing73** [comment]
i like how noone even acknowledged the loading bar going over
