### ISSUE TITLE
New Item: Mirror

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#91]
### The Basics

When used, it repeats your last used item. The cooldown on mirror is 30 seconds.

### Why add this? 

More combo potential

### Voting

👍 = Yes
👎 = No (comment why)

**Comment by CelestialKnight7** [comment]
double block go crazy

**Comment by CelestialKnight7** [comment]
double dyna for more instas

**Comment by CelestialKnight7** [comment]
double usb for pain

**Comment by LostKing73** [comment]
W it wins

**Comment by LostKing73** [comment]
replaces bomb ig

**Comment by CelestialKnight7** [comment]
we already have a replacement for bomb

**Comment by cs6413110** [comment]
Do we have an open spot for this?

**Comment by CelestialKnight7** [comment]
nope, unless we remove usb

**Comment by LostKing73** [comment]
im fine with that

**Comment by BreadSpammer** [comment]
isn't bomb dying tho?

**Comment by LostKing73** [comment]
ye and itlle be replaced by breacheer

**Comment by 3foe** [comment]
the vote is even, imagine the insta with USB, from 20% more dmg to 40% more dmg

**Comment by LostKing73** [comment]
k so like no? anyways code @BreadSpammer and @cs6413110

**Comment by BreadSpammer** [comment]
ye imma have to say no to that one. this allows for 4 healing items + medic. actuall tank.

**Comment by BreadSpammer** [comment]
also every refresh toolkit would give you your 4 healing items back (which wouldn't be hard to pull off)

**Comment by LostKing73** [comment]
i assume tape glue sheild and this?

**Comment by 3foe** [comment]
yup

**Comment by BreadSpammer** [comment]
ye DED issue

**Comment by LostKing73** [comment]
uhm no..?

**Comment by LostKing73** [comment]
medic needs a nerf, that doesnt mean this is bad

**Comment by LostKing73** [comment]
and it's 3-2

**Comment by BreadSpammer** [comment]
3-3*

**Comment by BreadSpammer** [comment]
also take into account the 2 other votes for you are 3foe and DarkMemeGod

**Comment by LostKing73** [comment]
no, coltin and alex. its different ish

**Comment by LostKing73** [comment]
mathew is against me (and why its 3-2)

**Comment by BreadSpammer** [comment]
r u blind? me/Evan/Aaron voted against, and 3foenation is invalid, and DMG, like idk cringe. also it's not like upvoted things get added all the time

**Comment by LostKing73** [comment]
> r u blind? me/Evan/Aaron voted against, and 3foenation is invalid, and DMG, like idk cringe. also it's not like upvoted things get added all the time

eh that's true(all of what u said lol) but like this is good, why did yall downvote?

**Comment by CelestialKnight7** [comment]
no space for it + op af + really op + kinda not that good either cuz if we wanted multiple uses of an item we could make it so that u can equip 2 of an item + not doing that tho cuz op

**Comment by LostKing73** [comment]
40 second cooldown then?

**Comment by CelestialKnight7** [comment]
some things you cant fix with a cooldown. just because u have an item that oneshots everyone on the map for free, doesnt mean that giving it a 2 minute cooldown would make it balanced

**Comment by LostKing73** [comment]
what if every thing worked at half efficiency. like it would heal half, do half damage, that kind of thing

**Comment by CelestialKnight7** [comment]
better but i also dont think its that good of an item either, yes i said it would be op, but it doesnt add anything unique to the game as other items. similar to aaron's problem with overdrive it doesnt add anything on its own unlike items like airstrike, breacher, or reflect.

**Comment by LostKing73** [comment]
ok

CONVERSATION COMPLETE
YOUR SCORE:
★★★★★
CONGRATS!
PERFECT SCORE!

**Comment by 3foe** [comment]
my issues are from least to biggest

1 the name (how does a mirror become a fricking stick of dynamite)

2 everything evan said

3 ptsd from Bradley with 4 tapes

**Comment by LostKing73** [comment]
1. its a copy from a mobile game, clash royale. idk bro
2. ye
3. but like who doesn't want that :D
