### ISSUE TITLE
inventory block vote

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#92]
pick one
![pixil-frame-8](https://github.com/user-attachments/assets/40b4b000-f7c0-48a5-a197-5dd345828a6d)
![inventoryblock](https://github.com/user-attachments/assets/08800c4f-f540-4131-9427-41e8a54a4b02)

**Comment by CelestialKnight7** [comment]
green or white, this will be the block you interact with to open inventory, it is 3x3

**Comment by CelestialKnight7** [comment]
@cs6413110 @BreadSpammer @LostKing73 @DarkMemeGod411

**Comment by DarkMemeGod411** [comment]
white. no question I like the white one

**Comment by cs6413110** [comment]
Add the texture on the green to the white one

**Comment by CelestialKnight7** [comment]
@@cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 cs6413110@cs6413110  @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110@cs6413110 @cs6413110 @@cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110@cs6413110 @cs6413110 @cs6413110 @cs6413110@cs6413110 @cs6413110 @cs6413110 @cs6413110 @@cs6413110 @cs6413110 @@@cs6413110 @cs6413110 @@@cs6413110 @cs6413110 @@@cs6413110 @@cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110@cs6413110 @cs6413110 @cs6413110 @cs6413110 @@cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 @cs6413110 cs6413110  vcs6413110 cs6413110 cs6413110 cs6413110 cs6413110 cs6413110 cs6413110 cs6413110   cs6413110

**Comment by LostKing73** [comment]
white cuz portal

**Comment by DarkMemeGod411** [comment]
one or the other, DMG : 👍

**Comment by cs6413110** [comment]
gray

**Comment by LostKing73** [comment]
gray yea actually

**Comment by BreadSpammer** [comment]
whigte

**Comment by CelestialKnight7** [comment]
gross
![Uploading pixil-frame-0 - 2024-10-22T121809.269.png…]()

**Comment by LostKing73** [comment]
make greyer
