### ISSUE TITLE
Alts

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#94]
why do they exist.

pls, use this issue to figure out a solution, bcuz no punishment matters when tony34 spams greek symbols that mean the n word

**Comment by BreadSpammer** [comment]
solution: make accounts cost money to make unless an admin veto's an account name using a new command /veto <name> that makes it so making an account with that name is free

**Comment by BreadSpammer** [comment]
or like die idk

**Comment by LostKing73** [comment]
> solution: make accounts cost money to make unless an admin veto's an account name using a new command /veto that makes it so making an account with that name is free

huh????

**Comment by cs6413110** [comment]
scam

**Comment by CelestialKnight7** [comment]
a exists cuz im lazy and cant be bothered to type more characters

**Comment by LostKing73** [comment]
no no a is fine since its like a communal testing acc

**Comment by 3foe** [comment]
require an admin/vip to authenticate an account before it can chat

**Comment by LostKing73** [comment]
and how would we judge whether its a alt or just someone new

**Comment by 3foe** [comment]
idk, but if we get an alt we can jsut ban it and not authenticate anymore.

also the link is hard to get so basically a new player has to join with an old player and copy the link from them, they can vouch for them

**Comment by LostKing73** [comment]
@cs6413110 this one actually is imprtant tho.
