### ISSUE TITLE
so like

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#96]
admin abuse is obv a problem

the gpa's constantly complain abt me doing it, and 3foenation and 3foe both also do it, not to mention the occasional super turip from celestial.

the solution? 

get better players

jk, no. other than simply NOT abusing admin(which is what I'm doing now) we would do this

### Specialized Players

so like, "special players" is just admins, and like sullivan or smth. 

### the basics

pretty much each player will get their own command or smth to activate a special ability for them, for example, for 3foe it would be like increased hp and lifesteal. note, ur hp will be at the top like a boss hp bar.

### why add this

gives a way to not rly admin abuse but still be op, and gives other players smth to fight

### vote

👍 =ye
👎 =ne(comment y)

**Comment by LostKing73** [comment]
idk bruh im eepy

**Comment by 3foenation** [comment]
what are we talking about getting rid of admin or getting new buffs for admin.

**Comment by LostKing73** [comment]
k like disregard coltin ig

**Comment by 3foenation** [comment]
im asking if this will be in place of admin or will give the admin buffs

**Comment by BreadSpammer** [comment]
1: too much effort for no reason
2: don't abuse admin (foreign concept)

**Comment by 3foe** [comment]
I do like the idea of custom commands tho, it would be funny and would make the game more interseting

**Comment by 3foe** [comment]
like bradley jsut idk becomes a piece of bread, LostKing idk, Evn becomes a DRg, I become like life steal tonk, smt like that

**Comment by LostKing73** [comment]
![USE AAAAA](https://github.com/user-attachments/assets/e6f5811a-5a6e-46dc-99f3-c829f9202aee)
i use this for cosmets, is this what u mean?

**Comment by LostKing73** [comment]
but i wanna be coooooooool why downvote :(

**Comment by 3foe** [comment]
upvoted :D

**Comment by 3foe** [comment]
> ![USE AAAAA](https://private-user-images.githubusercontent.com/175903140/379329129-e6f5811a-5a6e-46dc-99f3-c829f9202aee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU5OTksIm5iZiI6MTcyOTY5NTY5OSwicGF0aCI6Ii8xNzU5MDMxNDAvMzc5MzI5MTI5LWU2ZjU4MTFhLTVhNmUtNDZkYy05OWYzLWM4MjlmOTIwMmFlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNTAxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDA1YTdlYjMyMjgwOWMzODg4ZTg4Nzc1OTZlYzcxMDc4NWUzNjcxN2IyYjkwZDQ2N2Q3YjFhN2Q5Y2EyNjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qwzekX1Bv71dW-kD4nq4cl8yraTgnNsqpeDrC6szmWU) i use this for cosmets, is this what u mean?

yes, and also the tank treads

**Comment by BreadSpammer** [comment]
bruh this is just coating admin abuse in a new format. no

**Comment by LostKing73** [comment]
ok i didnt rly care anyways
