### ISSUE TITLE
lil guy

### ISSUE THREAD

**Issue by CelestialKnight7** [cs6413110/Pixel-Tanks#98]
![pixil-gif-drawing (63)](https://github.com/user-attachments/assets/2582a087-0198-457b-bf37-9ef0c056e615)

praise him or die

![pixil-gif-drawing (62)](https://github.com/user-attachments/assets/19f93d4a-bba9-4dcc-94d4-fa843de671a1)

**Comment by cs6413110** [comment]
YSE

**Comment by LostKing73** [comment]
is that a bullet with drone fans on it?

**Comment by CelestialKnight7** [comment]
nah just a drone

**Comment by CelestialKnight7** [comment]
its for invnetory thing

**Comment by CelestialKnight7** [comment]
![pixil-gif-drawing (64)](https://github.com/user-attachments/assets/bb73503e-6e73-4426-860d-509728ef93ea)

**Comment by LostKing73** [comment]
im still confused what it is

**Comment by LostKing73** [comment]
is it like a flying projector?

**Comment by LostKing73** [comment]
@cs6413110 FIX

**Comment by CelestialKnight7** [comment]
ever played subnatica?

**Comment by BreadSpammer** [comment]
idk Aaron broke game while trying to optimize so wait 3-5 business days and it might get fixed

**Comment by CelestialKnight7** [comment]
![image](https://github.com/user-attachments/assets/d889f010-58ab-495c-886a-03e076565f9b)
![image](https://github.com/user-attachments/assets/2c9f078e-783f-4d9e-b0e0-4ef2b7f2b933)

**Comment by LostKing73** [comment]
O.O YES

**Comment by LostKing73** [comment]
COOOL

**Comment by CelestialKnight7** [comment]
lil drone guy crafts ur tonk

**Comment by cs6413110** [comment]
Me looking at the new tanks drone lore drop with more excitement than any minecraft update drop

**Comment by CelestialKnight7** [comment]
hole
![pixil-gif-drawing (66)](https://github.com/user-attachments/assets/4436b789-a7a1-407f-a603-337235fb21ba)
![pixil-gif-drawing (65)](https://github.com/user-attachments/assets/6adfa3cd-b9df-46d7-82e8-ffadc4b639f4)

**Comment by CelestialKnight7** [comment]
agony

**Comment by BreadSpammer** [comment]
@CelestialKnight7 add ur inventory image thingy to tonks

step 1: go to https://github.com/cs6413110/Pixel-Tanks/tree/master/public/images/menus
step 2: rename ur inventory menu thong to "inventory_"
step 3: delete the old inventory_ and replace it with urs
step 4: make menus for cruts and stuff

**Comment by CelestialKnight7** [comment]
ill do step 4

**Comment by LostKing73** [comment]
pls so we can actually get an inventory

**Comment by cs6413110** [comment]
ye, soon

**Comment by LostKing73** [comment]
its fixed, but like we need the entire thing coded and images made for it so like figs

**Comment by LostKing73** [comment]
aint no way

**Comment by LostKing73** [comment]
where????

**Comment by BreadSpammer** [comment]
nUH uH

**Comment by CelestialKnight7** [comment]
xifed the facist bread spam

**Comment by BreadSpammer** [comment]
NOonOononooOOoado9uadio >:(((

**Comment by BreadSpammer** [comment]
COMUNISM WILL LIVE ON- *BreadSpammer was banned by Celestial for the punishable offense "not democracy"*

**Comment by CelestialKnight7** [comment]
@cs6413110 can/will you redo the text in the inventory so it doesnt auto select the color box?

**Comment by CelestialKnight7** [comment]
so first go on invnetory
then invnetory open aniamtion plays
then drone out animation plays
then drones fly around while u stay in the inventory
when u leave the drones fly back to their starting corners
then the drone in animation plays
then the invnentory open animation plays in reverse
the end

**Comment by BreadSpammer** [comment]
![Screenshot 2024-10-24 1 16 42 PM](https://github.com/user-attachments/assets/ac04084b-e841-44fc-b82e-806067e5aa2c)

**Comment by LostKing73** [comment]
gnats

**Comment by CelestialKnight7** [comment]
i was not lying when i said **lil** guy

**Comment by LostKing73** [comment]
bro why are they there? how do they spawn? why are they a separate entity?

**Comment by CelestialKnight7** [comment]
press m idk how they work aaron made them for testing

**Comment by LostKing73** [comment]
lol i didnt reload so literal gnats
![image](https://github.com/user-attachments/assets/6e08327a-c69e-4e6f-8fe4-8396fa807b48)

**Comment by CelestialKnight7** [comment]
@cs6413110 ok i need saving from the tiny. double thier size ill animate it or something later... or not idk

**Comment by cs6413110** [comment]
?

**Comment by CelestialKnight7** [comment]
just double their size plz

**Comment by LostKing73** [comment]
i reloaded but they are still black dots, I think its cuz of my texture pack, @cs6413110 can u fix at lunch pls?

**Comment by CelestialKnight7** [comment]
![Screenshot 2024-10-25 11 41 30 AM](https://github.com/user-attachments/assets/b862016e-4990-4801-8a64-552817b8de0e)
![Screenshot 2024-10-25 11 41 26 AM](https://github.com/user-attachments/assets/43f0d74c-6b1f-402b-ac18-6b79f1e1103d)
![Screenshot 2024-10-25 11 41 17 AM](https://github.com/user-attachments/assets/f644d0bf-1b14-4a43-8d99-7e808b25919e)
![Screenshot 2024-10-25 11 39 05 AM](https://github.com/user-attachments/assets/f939b6aa-aade-48fb-b948-6b81df27b3ed)

**Comment by LostKing73** [comment]
ez

**Comment by BreadSpammer** [comment]
ye its on #107. basically were gonna htmlify the thing so u can type e in, and e to leave

**Comment by LostKing73** [comment]
lol i forgot u can still press m to summon him
