### ISSUE TITLE
New Perk/Item: Electric Bullets

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#99]
so like kinda ricochet but also not

### The Basics

normal shooting becomes a slow, sluggish firing speed(like half shotgun)but bullets will stun(stop movement for like .5 seconds) enemies and then shoot electricity to players within 3 blocks(unless a block is in the way) which will then continue 2 blocks away(cant hit same person more that once, unless u want it to?) and then 1 block away, and will keep chaining until no one is in the radius. On contact(bullet form) it will deal the normal amount of damage, then on each electricity bounce it will do 25 damage. Note that the electricity that bounces also stuns(we can change to not stun if u want)

### Why add this?

firstly, its rly cool, but secondly, remember this morning when me and cs where chased by  everyone else like a swarm of bees? well this would be able to shoot into the crowd and deal a good amount of damage, while it also stops the crowd from getting you surrounded.

### Voting

👍 = yes
👎 = no (comment y)

**Comment by LostKing73** [comment]
this could technically be an item too, where it shoots out like dyna

**Comment by 3foe** [comment]
I think perks shouldent give a debuff because the name means buff, but I think without the nerf, it's too broken. So I think we should go item instead of perk, give it a 5-10 sec cooldown, decrease the stun time to .25, and keep the stun of the chain. maybe call it electric shot, electric net, electro web.

**Comment by LostKing73** [comment]
wait W i thought this would be shut down but 3 upvotes so far?

**Comment by LostKing73** [comment]
> I think perks shouldent give a debuff because the name means buff, but I think without the nerf, it's too broken. So I think we should go item instead of perk, give it a 5-10 sec cooldown, decrease the stun time to .25, and keep the stun of the chain. maybe call it electric shot, electric net, electro web.

so, the issue with a .25 second stun is that its way to short. trust me, .5 is perfect

**Comment by 3foe** [comment]
k

**Comment by 3foe** [comment]
I do have a concern. we need to have the item look cool because it can easily look very bad

**Comment by LostKing73** [comment]
> I do have a concern. we need to have the item look cool because it can easily look very bad

that's not hard, me and evan are both great at designing that kind of stuff

**Comment by LostKing73** [comment]
@BreadSpammer why downvote?

**Comment by BreadSpammer** [comment]
literally it's dmg and 3foe again invalid opinions laff. this thing looks either terrible in almost any situation bc u basically don't have normal shooting with less damage, and u get cheesed with normal shooting until ur drained to death, or ur in Tdm and the entire enemy team doesn't have a brain cell and then it might be usable

**Comment by BreadSpammer** [comment]
also #85

**Comment by LostKing73** [comment]
shotgun,gripple, and boost still exist. also, a new perk doesn't have to be something that you have to use like shield. it seems plenty balanced to me, and is an original idea, which was cs' problem

**Comment by CelestialKnight7** [comment]
i am simple man, i see movement restriction - i downvote.

more seriously tho u said it 'stops the crowd' which is a good thing... in pve. imagine being the crown and the person ur chasing just shoots a couple of bullets which stun all of u keeping you from chasing them.
now that i think about it this circles back perfectly to flat behavior of just running and shooting behind you.

its a good idea in concept but i imagine in practice it would be agony for the people getting stunned and annoying for the person using it as you said it takes your damage.. which is a good sacrifice but then all you would end up doing is stunlocking them while doing no damage, essentially putting both of you in a stalemate until the person getting stunned just insta's you.

**Comment by LostKing73** [comment]
it is only half a second, its more like it stops boosts

**Comment by CelestialKnight7** [comment]
yeah but its per bullet is half a second, which can hit u multiple times

**Comment by LostKing73** [comment]
it cant. it can only hit once

**Comment by CelestialKnight7** [comment]
then whats the point, just make a stun bomb or something as an item and actually balance it so it explodes after a delay instead of being an instant impact item like a bullet that you cant dodge easily or play around

**Comment by CelestialKnight7** [comment]
this idea has no future as a perk ill just say that, it seems more like an item anyways.

**Comment by 3foe** [comment]
yup

**Comment by BreadSpammer** [comment]
E.M.P

**Comment by LostKing73** [comment]
> then whats the point, just make a stun bomb or something as an item and actually balance it so it explodes after a delay instead of being an instant impact item like a bullet that you cant dodge easily or play around

fine. what if it could infently arc between players and hit more than once, but it can only stun once. big damage, and the stun is helpful

**Comment by CelestialKnight7** [comment]
problem with this as an item
- stun
- no space
- infinite damage potential

**Comment by LostKing73** [comment]
infitete IF there are 2 people AND if they are within 1 block of each other, so hard to get that much, the stun works fine and is more of a boost interrupt, ig we can lower time if u want, and wdym no space?

**Comment by CelestialKnight7** [comment]
would turrets count? how long between the arc between entities?

**Comment by CelestialKnight7** [comment]
> infitete IF there are 2 people AND if they are within 1 block of each other, so hard to get that much, the stun works fine and is more of a boost interrupt, ig we can lower time if u want, and wdym no space?

we have 12 items

**Comment by LostKing73** [comment]
remove usb, its not good and just, if u hit it u get to do 2 more damage

**Comment by LostKing73** [comment]
> would turrets count? how long between the arc between entities?

turrents count, and it hits, bounces up to 3, then up to 2, then up to 1 block away for the rest of the bounces

**Comment by CelestialKnight7** [comment]
make a limit of 5 times it can bounce, and how much damage does each hit do

**Comment by LostKing73** [comment]
25 damage, so itll do like 80 damage if it bounces between 2.

**Comment by cs6413110** [comment]
just don't add?

**Comment by LostKing73** [comment]
why not tho. like it doesnt have to be good OR bad, which means its perfect rn?

**Comment by BreadSpammer** [comment]
ye so like no. check #100 new idea

**Comment by LostKing73** [comment]
bruh, give it a chance

**Comment by LostKing73** [comment]
it literally works perfectly, and can be an item if u don't want it as a perk?

**Comment by cs6413110** [comment]
Give it a chance first in the idea field, because it's a waste of time for me to code something just to remove it because it was unbalanced two seconds later.

**Comment by LostKing73** [comment]
i mean i dont see how its unbalanced rn. it should work? only thing is is it gonna be a perk or item

**Comment by BreadSpammer** [comment]
Also would do #707 but like know

**Comment by CelestialKnight7** [comment]
> then whats the point, just make a stun bomb or something as an item and actually balance it so it explodes after a delay instead of being an instant impact item like a bullet that you cant dodge easily or play around

^

**Comment by LostKing73** [comment]
> the point of the item is an anti-team item. as the most targeted player in the game I want this item. plus its an alternative to the current meta which is dynamite or reflect. this is different from damage items or healing, it's a stun item.

lol

**Comment by CelestialKnight7** [comment]
but stun is worrying cuz it restricts movement which is a very important part of the game. If you ever stop moving for 1 whole second during a fight, you are gone.

this still doesnt address the problem of theres no room for the item on the roster

a deviation from the meta is a good point tho

side note: have you considered not being the most targeted person in the game. I wonder what actions you did that could have landed you in that position.

**Comment by 3foe** [comment]
1 good thing ur not gong to be stunned for a whole second

2 remove smoke bomb whnes the last time you saw someone use it

3 yay

side note I am the best player so I'm targeted its just because yall skill + issue

**Comment by LostKing73** [comment]
> side note I am the best player so I'm targeted its just because yall skill + issue

HAAAAAAAAAAAAHAHAHAHAHAHHAHAHAHAHAAAAAAHAHAHAHAHA OMG IM DYING HAHAHAHAHAHA

**Comment by LostKing73** [comment]
but like he's right with smoke. it was good on paper but like seizure warning in game

**Comment by CelestialKnight7** [comment]
> but like he's right with smoke. it was good on paper but like seizure warning in game

bruh literaly already said how to xif in balancing, just make the smoke a static frame and then play the rest of the animation when it dies. u could also make it electric if u want it to do damage

**Comment by BreadSpammer** [comment]
ye I might make smoke bomb do damage (not that much, imagine dreadnaught death DMG, something to worry about, but like not that bad)

**Comment by CelestialKnight7** [comment]
can u xif animation first :(

**Comment by LostKing73** [comment]
first, not only would that look bad, but it would be big spike that can hit anywhere on the map(in ur view)

**Comment by BreadSpammer** [comment]
that does 2 damage

**Comment by BreadSpammer** [comment]
and thats a waste of an item

**Comment by LostKing73** [comment]
> and thats a waste of an item

another reason why electric bullet is better

**Comment by CelestialKnight7** [comment]
whaatever lets just vote cuz im tired of checking this issue

@cs6413110 @BreadSpammer @LostKing73 @CelestialKnight7 @DarkMemeGod411 VOTE

keep electric something (bullet/bomb idk) (we'll worry about what to swap it out with after it gets votes) = 👍 
how bout no = 👎

**Comment by LostKing73** [comment]
bro, the smoke is so dum, why arent yall wanting it gone??????

**Comment by BreadSpammer** [comment]
bc its already coded and #707

**Comment by CelestialKnight7** [comment]
yay outvoted and aaron would vote no anyways so yeet

**Comment by CelestialKnight7** [comment]
democracy saves the day again

**Comment by LostKing73** [comment]
like, what? smoke is literally useless unless ur oppenet has epelepsy and u want them to die irl. and ur "fix" just makes it uglier and a big spike that can be placed anywhere and doesn't even do any damage to matter. this LITERALLY has no downsides(like as in negatives if we add it). so like, literally whats the prblem

**Comment by CelestialKnight7** [comment]
> like, what? smoke is literally useless unless ur oppenet has epelepsy and u want them to die irl. and ur "fix" just makes it uglier and a big spike that can be placed anywhere and doesn't even do any damage to matter. this LITERALLY has no downsides(like as in negatives if we add it). so like, literally whats the prblem

dont like

**Comment by CelestialKnight7** [comment]
the vote has been called, and the decision has been made. Court is adjourned

**Comment by CelestialKnight7** [comment]
you may appeal it to the higher authority if you wish

**Comment by LostKing73** [comment]
who other than you likes smoke??? in this form or when "fixed"???

**Comment by CelestialKnight7** [comment]
you may adress you concerns when appealed with the higher authorities

**Comment by 3foe** [comment]
not everyone has voted

**Comment by CelestialKnight7** [comment]
everyone important has, except aaron

**Comment by LostKing73** [comment]
bruh like idc, but my point of smoke cloud is bad and ur "fix" is also bad

**Comment by BreadSpammer** [comment]
then replace smoke bomb with emp ezzzzzz

**Comment by 3foe** [comment]
FIXGS

**Comment by 3foe** [comment]
plz i nee this i get teamed on too much

**Comment by LostKing73** [comment]
no.
